### PR TITLE
Stabilize tests

### PR DESCRIPTION
**Pull request by michalbiesek**
- provide a size that doesn't fill into the tcache
>

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/456)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/456#-:-MQvLMYl6xmkjjaxlnhm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/456)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[test/memkind_highcapacity_tests.cpp, line 74 at r2](https://reviewable.io/reviews/memkind/memkind/456#-MQvXN0q6yEfP_4OawBA:-MQvXN0q6yEfP_4OawBB:b-k8yv0o) ([raw file](https://github.com/memkind/memkind/blob/561272eb62840c982ef13663d80c058798b64d3d/test/memkind_highcapacity_tests.cpp#L74)):*
> ```cpp
>         high_capacity_nodes.size() != 1) {
>         GTEST_SKIP() <<
>                      "This test requires only 1 highest capacity NUMA Node in the OS ";
> ```

exactly 1
___
*[test/memkind_highcapacity_tests.cpp, line 119 at r2](https://reviewable.io/reviews/memkind/memkind/456#-MQvXqrYBIh9v7t4s8IQ:-MQvXqrYBIh9v7t4s8IR:b-k8yv0o) ([raw file](https://github.com/memkind/memkind/blob/561272eb62840c982ef13663d80c058798b64d3d/test/memkind_highcapacity_tests.cpp#L119)):*
> ```cpp
>         high_capacity_nodes.size() != 1) {
>         GTEST_SKIP() <<
>                      "This test requires only 1 highest capacity NUMA Node in the OS ";
> ```

exactly 1

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/456)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[test/memkind_highcapacity_tests.cpp, line 74 at r2](https://reviewable.io/reviews/memkind/memkind/456#-MQvXN0q6yEfP_4OawBA:-MQvaiOG7m4e-jgr4eaF:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/561272eb62840c982ef13663d80c058798b64d3d/test/memkind_highcapacity_tests.cpp#L74)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

exactly 1
</blockquote></details>

Done.
___
*[test/memkind_highcapacity_tests.cpp, line 119 at r2](https://reviewable.io/reviews/memkind/memkind/456#-MQvXqrYBIh9v7t4s8IQ:-MQvaijt8813Lqt3c8B1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/561272eb62840c982ef13663d80c058798b64d3d/test/memkind_highcapacity_tests.cpp#L119)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

exactly 1
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/456#-:-MQw0azZ0pVr0AFuq1j2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
