### PR TITLE
fix allocations to MEMKIND_HIGHEST_CAPACITY kind

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [x] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/423)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/423)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/memkind_hmat.c, line 22 at r1](https://reviewable.io/reviews/memkind/memkind/423#-MOBe-7LCecWvuBEEQQ8:-MOBe-7M-L03elg8-rV-:bp9j62e) ([raw file](https://github.com/memkind/memkind/blob/48fde292a4edea7401a0dcd0061c6a4e80f10525/src/memkind_hmat.c#L22)):*
> ```
> numa_num_possible_nodes()
> ```
You sure you need here the maximum number of nodes that the kernel can handle?
I believe you only need the maximum NUMA Node-id, which is **currently** available in the OS, and adjust your logic to it

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/423)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[src/memkind_hmat.c, line 22 at r1](https://reviewable.io/reviews/memkind/memkind/423#-MOBe-7LCecWvuBEEQQ8:-MOBnSDp-Dp2Br836Gh2:b-de4bl0) ([raw file](https://github.com/memkind/memkind/blob/48fde292a4edea7401a0dcd0061c6a4e80f10525/src/memkind_hmat.c#L22)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> numa_num_possible_nodes()
> ```
You sure you need here the maximum number of nodes that the kernel can handle?
I believe you only need the maximum NUMA Node-id, which is **currently** available in the OS, and adjust your logic to it
</blockquote></details>

Will numa_max_node() + 1 be ok? This way I'll have a bitmask with minimum needed size while still keep my implementation simple.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/423)* status: 0 of 2 files reviewed, all discussions resolved

___
*[src/memkind_hmat.c, line 22 at r1](https://reviewable.io/reviews/memkind/memkind/423#-MOBe-7LCecWvuBEEQQ8:-MOBqzPd6xHoZywDod8P:b2nign6) ([raw file](https://github.com/memkind/memkind/blob/48fde292a4edea7401a0dcd0061c6a4e80f10525/src/memkind_hmat.c#L22)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Will numa_max_node() + 1 be ok? This way I'll have a bitmask with minimum needed size while still keep my implementation simple.
</blockquote></details>

yes

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/423)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

___
*[src/memkind_hmat.c, line 22 at r2](https://reviewable.io/reviews/memkind/memkind/423#-MOBs69O7IVzjH9jtw0W:-MOBs69O7IVzjH9jtw0X:b-9omy85) ([raw file](https://github.com/memkind/memkind/blob/2e73d581d17f351edaf686988a06c7459bfa2a85/src/memkind_hmat.c#L22)):*
> ```
> numa_max_node() + 1
> ```
rename it to
int max_node_id = numa_max_node()
And in loop give condition <=
___
*[test/memkind_highcapacity_tests.cpp, line 51 at r2](https://reviewable.io/reviews/memkind/memkind/423#-MOBsJKa9AoAzPjNwsKF:-MOBsJKa9AoAzPjNwsKG:bpesgit) ([raw file](https://github.com/memkind/memkind/blob/2e73d581d17f351edaf686988a06c7459bfa2a85/test/memkind_highcapacity_tests.cpp#L51)):*
> ```
> numa_num_possible_nodes()
> ```
A similar situation applies here you could check the situation in OS not the maximum number of nodes 
___
*[test/memkind_highcapacity_tests.cpp, line 73 at r2](https://reviewable.io/reviews/memkind/memkind/423#-MOBsZ_S5AaMA6a-GjEE:-MOBsZ_S5AaMA6a-GjEF:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/2e73d581d17f351edaf686988a06c7459bfa2a85/test/memkind_highcapacity_tests.cpp#L73)):*
> ```cpp
> 
>     // get highest NUMA node capacity in the system
>     int num_nodes = numa_num_possible_nodes();
> ```

.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/423)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/memkind_hmat.c, line 20 at r3](https://reviewable.io/reviews/memkind/memkind/423#-MOBx7CmDIXT7ao_sA-T:-MOBx7CmDIXT7ao_sA-U:bbvhpz1) ([raw file](https://github.com/memkind/memkind/blob/5fca56171e75da38eba11fdbff1f7155ad7052c8/src/memkind_hmat.c#L20)):*
> ```C
> 
> static void memkind_hi_cap_numanodes_init(void)
> {
> ```

Please unify the author and the committer of these changes

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/423)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[src/memkind_hmat.c, line 20 at r3](https://reviewable.io/reviews/memkind/memkind/423#-MOBx7CmDIXT7ao_sA-T:-MOCC-rU1u4njfkigpcP:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5fca56171e75da38eba11fdbff1f7155ad7052c8/src/memkind_hmat.c#L20)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please unify the author and the committer of these changes 
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
:lgtm: I merge this but I leave the #421 since we should have an architecture in QEMU to cover this case.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/423#-:-MOCD8uiDeMMsikgX2tf:b-hjrw9u)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
