### PR TITLE
Substitute mutex with queue

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/763)

### CODE REVIEW

**Review by bratpiorka — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/763)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/763)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[test/memkind_memtier_data_movement_test.cpp, line 1151 at r1](https://reviewable.io/reviews/memkind/memkind/763#-Mx0a-B8B0uRxecRfbOK-r1-1151:-Mx4DVJR5YTDDspyal68:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e8d49fa08ce824f36398f80f8924f1053811798d/test/memkind_memtier_data_movement_test.cpp#L1151)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Condition already satisfied if two previous conditions are true.
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 7 of 7 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/763)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 7 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/763)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[test/memkind_memtier_data_movement_test.cpp, line 1193 at r3](https://reviewable.io/reviews/memkind/memkind/763#-Mx4Gh9AEBt6kmZxRUCI:-Mx4Gh9AEBt6kmZxRUCJ:b-9wcq8t) ([raw file](https://github.com/memkind/memkind/blob/f74d59e5a3c39822d8082a08732ba49fc3de3630/test/memkind_memtier_data_movement_test.cpp#L1193)):*
> ```cpp
>     ASSERT_EQ(queue.head, nullptr);
>     ASSERT_EQ(queue.tail, nullptr);
>     ASSERT_EQ(queue.tail, queue.head);
> ```

nit: Already satisfied condition.

**Pull request merged**
