### PR TITLE
Add generic template for parametrized test

### PR DESCRIPTION
**Pull request by michalbiesek**
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/464)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/464)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[test/common.h, line 77 at r1](https://reviewable.io/reviews/memkind/memkind/464#-MR57_ewE770UNqOZKaD:-MR57_ey6Z9kfVZqTKR8:bq4cyaf) ([raw file](https://github.com/memkind/memkind/blob/2fb8a2848bd13d91d94873900b5a67bc4fe6144d/test/common.h#L77)):*
> ```objc
>     void TearDown()
>     {
>         fprintf(stderr, "Finish Testing: %s\n", kind_name(memory_kind));
> ```

Finished
___
*[test/memkind_dax_kmem_test.cpp, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/464#-MR5BTgV8UeeiLEC545x:-MR5BTgV8UeeiLEC545y:b-a4e2bs) ([raw file](https://github.com/memkind/memkind/blob/2fb8a2848bd13d91d94873900b5a67bc4fe6144d/test/memkind_dax_kmem_test.cpp#L37)):*
> ```cpp
>     void SetUp()
>     {
>         memory_kind = GetParam();
> ```

Remove this and SetUp() here.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/464)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[test/common.h, line 77 at r1](https://reviewable.io/reviews/memkind/memkind/464#-MR57_ewE770UNqOZKaD:-MR5ZcxS0zqVmP8rV5vP:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2fb8a2848bd13d91d94873900b5a67bc4fe6144d/test/common.h#L77)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Finished
</blockquote></details>

Done.
___
*[test/memkind_dax_kmem_test.cpp, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/464#-MR5BTgV8UeeiLEC545x:-MR5Ztog60IFoiwoMhe7:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2fb8a2848bd13d91d94873900b5a67bc4fe6144d/test/memkind_dax_kmem_test.cpp#L37)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove this and SetUp() here. 
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/464)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[test/memkind_dax_kmem_test.cpp, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/464#-MR5BTgV8UeeiLEC545x:-MRJ9xG928qQ2jT371UH:b4tx5kn) ([raw file](https://github.com/memkind/memkind/blob/2fb8a2848bd13d91d94873900b5a67bc4fe6144d/test/memkind_dax_kmem_test.cpp#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I mean, invoke the SetUp() from the upper class here.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/464)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[test/memkind_dax_kmem_test.cpp, line 37 at r1](https://reviewable.io/reviews/memkind/memkind/464#-MR5BTgV8UeeiLEC545x:-MRLF9sw87UBLZSA_36m:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2fb8a2848bd13d91d94873900b5a67bc4fe6144d/test/memkind_dax_kmem_test.cpp#L37)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I mean, invoke the SetUp() from the upper class here.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/464#-:-MROe2w9AQdjgzMhm0PR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/464)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/464#-:-MROlAtQ5q5mvtiH2jL9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
