### PR TITLE
Add Centos 7 image to docker files

### PR DESCRIPTION
**Pull request by TomekIdczak97**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [x] Other

### Checklist

- [x] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [x] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/397)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/397)* status: all files reviewed, 5 unresolved discussions (waiting on @TomekIdczak97)

___
*[utils/docker/Dockerfile.centos-7, line 9 at r1](https://reviewable.io/reviews/memkind/memkind/397#-MKF2CKr7Tx21nwvMBMW:-MKF2CKr7Tx21nwvMBMX:bgas7r8) ([raw file](https://github.com/memkind/memkind/blob/4f6ee235f40ff2366aa01951fdb4c36e34310392/utils/docker/Dockerfile.centos-7#L9)):*
> ```
> dnf
> ```
yum
___
*[utils/docker/Dockerfile.centos-7, line 43 at r1](https://reviewable.io/reviews/memkind/memkind/397#-MKF2bXR4DqwlQZ7MRfW:-MKF2bXS8fbUAL_b76Ue:b-637e15) ([raw file](https://github.com/memkind/memkind/blob/4f6ee235f40ff2366aa01951fdb4c36e34310392/utils/docker/Dockerfile.centos-7#L43)):*
> ```
> ·
> ```
remove space after '2' please validate this PR against whitespaces: git diff --check HEAD~1
___
*[utils/docker/Dockerfile.centos-7, line 48 at r1](https://reviewable.io/reviews/memkind/memkind/397#-MKF2wca0fDsc7FA6BhX:-MKF2wca0fDsc7FA6BhY:b-igxnlp) ([raw file](https://github.com/memkind/memkind/blob/4f6ee235f40ff2366aa01951fdb4c36e34310392/utils/docker/Dockerfile.centos-7#L48)):*
> ```
> RUN useradd -m $USER
> ```
RUN useradd -m $USER -p `mkpasswd $USERPASS` ?
___
*[utils/docker/docker_run_build.sh, line 39 at r1](https://reviewable.io/reviews/memkind/memkind/397#-MKF2HxTDakqfS-Rs9tI:-MKF2HxTDakqfS-Rs9tJ:blibnwu) ([raw file](https://github.com/memkind/memkind/blob/4f6ee235f40ff2366aa01951fdb4c36e34310392/utils/docker/docker_run_build.sh#L39)):*
> ```Shell
> # if TBB library version is specified install library and use it
> # as MEMKIND_HEAP_MANAGER
> if [ -n "$TBB_LIBRARY_VERSION" ]; then
> ```

Please also update this:
https://github.com/memkind/memkind/blob/9b399ebf08745cc4448422681e5a843df21a66bf/utils/docker/docker_run_build.sh#L29
We talk about this offline - you could do this with this commit
___
*[utils/docker/README.md, line 5 at r1](https://reviewable.io/reviews/memkind/memkind/397#-MKF35Dy2vDak_xM5BJv:-MKF35Dy2vDak_xM5BJw:bk6lblv) ([raw file](https://github.com/memkind/memkind/blob/4f6ee235f40ff2366aa01951fdb4c36e34310392/utils/docker/README.md#L5)):*
> ```
> Centos
> ```
CentOS

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/397)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @michalbiesek and @TomekIdczak97)

___
*[utils/docker/Dockerfile.centos-7, line 9 at r1](https://reviewable.io/reviews/memkind/memkind/397#-MKF2CKr7Tx21nwvMBMW:-MMKZdeuEo6wLlyt-eKl:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/4f6ee235f40ff2366aa01951fdb4c36e34310392/utils/docker/Dockerfile.centos-7#L9)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> dnf
> ```
yum
</blockquote></details>

Done.
___
*[utils/docker/Dockerfile.centos-7, line 43 at r1](https://reviewable.io/reviews/memkind/memkind/397#-MKF2bXR4DqwlQZ7MRfW:-MMKZcEe0MUi9RmEoN9x:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/4f6ee235f40ff2366aa01951fdb4c36e34310392/utils/docker/Dockerfile.centos-7#L43)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ·
> ```
remove space after '2' please validate this PR against whitespaces: git diff --check HEAD~1
</blockquote></details>

Done.
___
*[utils/docker/Dockerfile.centos-7, line 48 at r1](https://reviewable.io/reviews/memkind/memkind/397#-MKF2wca0fDsc7FA6BhX:-MMKZOrN5134nIKviSF1:b-2gn15v) ([raw file](https://github.com/memkind/memkind/blob/4f6ee235f40ff2366aa01951fdb4c36e34310392/utils/docker/Dockerfile.centos-7#L48)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> RUN useradd -m $USER
> ```
RUN useradd -m $USER -p `mkpasswd $USERPASS` ?
</blockquote></details>

Done. mkpasswd is not working this way on this OS.
___
*[utils/docker/README.md, line 5 at r1](https://reviewable.io/reviews/memkind/memkind/397#-MKF35Dy2vDak_xM5BJv:-MMKZMRr9iTYdYqM_LWW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/4f6ee235f40ff2366aa01951fdb4c36e34310392/utils/docker/README.md#L5)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Centos
> ```
CentOS
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/397)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @michalbiesek and @TomekIdczak97)

___
*[utils/docker/Dockerfile.centos-7, line 19 at r2](https://reviewable.io/reviews/memkind/memkind/397#-MMKf97U9ewdQp1kKHs8:-MMKf97U9ewdQp1kKHs9:bxtub52) ([raw file](https://github.com/memkind/memkind/blob/2bc8bca6714a7c2a5b35b0699aeda6a2fcfabfaa/utils/docker/Dockerfile.centos-7#L19)):*
> ```
>     gcc-c++ \
>     git \
>     glibc \
> ```

Is it needed?

**Review by PatKamin — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/397)* status: all files reviewed, 7 unresolved discussions (waiting on @michalbiesek and @TomekIdczak97)

___
*[utils/docker/docker_install_ndctl.sh, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/397#-MMKg99q1CQp6NlhEyFK:-MMKg99q1CQp6NlhEyFL:bxkkmo8) ([raw file](https://github.com/memkind/memkind/blob/2bc8bca6714a7c2a5b35b0699aeda6a2fcfabfaa/utils/docker/docker_install_ndctl.sh#L16)):*
> ```Shell
> if [[ $(cat /etc/os-release) = *"fedora"* ]]; then
> 
>   #reverting ldconfig_scriplets changes for centos 7
> ```

scriptlets

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/397)* status: all files reviewed, 4 unresolved discussions (waiting on @TomekIdczak97)

___
*[utils/docker/docker_install_ndctl.sh, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/397#-MMKj7ef37vxiKhH9sAR:-MMKj7ef37vxiKhH9sAS:bxexa6n) ([raw file](https://github.com/memkind/memkind/blob/2bc8bca6714a7c2a5b35b0699aeda6a2fcfabfaa/utils/docker/docker_install_ndctl.sh#L16)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   #reverting ldconfig_scriplets changes for centos 7
>   git config user.name "someone"
>   git config user.email "someone@someplace.com"
>   git revert 27e8d272b88bf03b1e931202f58094771c27ebef --no-edit
> ```
</details>

Does this change mean that in the case of Centos 7 after downloading the package from the Github repository or cloning for example v70.1 user must revert some commit otherwise the rpm-build is failing?
___
*[utils/docker/docker_install_ndctl.sh, line 30 at r2](https://reviewable.io/reviews/memkind/memkind/397#-MMKiWiD6SvrkwhyttY1:-MMKiWiD6SvrkwhyttY2:bbj31ml) ([raw file](https://github.com/memkind/memkind/blob/2bc8bca6714a7c2a5b35b0699aeda6a2fcfabfaa/utils/docker/docker_install_ndctl.sh#L30)):*
> ```
> -disable-docs --disable-asciidoctor
> ```
I like this change but I prefer to be done as a separate commit, see that:
https://github.com/memkind/memkind/blob/14ba5be23ebf36c5edbf30f111c338ad72931d1f/utils/docker/Dockerfile.fedora-32#L11
is obsolete.  The same parameter could be passed in the case of Ubuntu so basically this is a separate change that I would like to see as a separate commit.

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/397)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[utils/docker/Dockerfile.centos-7, line 19 at r2](https://reviewable.io/reviews/memkind/memkind/397#-MMKf97U9ewdQp1kKHs8:-MMPk6BDCXQgLO7FwuAC:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2bc8bca6714a7c2a5b35b0699aeda6a2fcfabfaa/utils/docker/Dockerfile.centos-7#L19)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

Done.
___
*[utils/docker/docker_install_ndctl.sh, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/397#-MMKj7ef37vxiKhH9sAR:-MMPizuS0k_sdNyPDGgM:b-9lh7b4) ([raw file](https://github.com/memkind/memkind/blob/2bc8bca6714a7c2a5b35b0699aeda6a2fcfabfaa/utils/docker/docker_install_ndctl.sh#L16)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>   #reverting ldconfig_scriplets changes for centos 7
>   git config user.name "someone"
>   git config user.email "someone@someplace.com"
>   git revert 27e8d272b88bf03b1e931202f58094771c27ebef --no-edit
> ```
Does this change mean that in the case of Centos 7 after downloading the package from the Github repository or cloning for example v70.1 user must revert some commit otherwise the rpm-build is failing?
</blockquote></details>

Exactly. Ask Adam if you need more details.
___
*[utils/docker/docker_install_ndctl.sh, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/397#-MMKg99q1CQp6NlhEyFK:-MMPk8Y8AanbGfSVmqpH:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2bc8bca6714a7c2a5b35b0699aeda6a2fcfabfaa/utils/docker/docker_install_ndctl.sh#L16)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

scriptlets
</blockquote></details>

Done.
___
*[utils/docker/docker_install_ndctl.sh, line 30 at r2](https://reviewable.io/reviews/memkind/memkind/397#-MMKiWiD6SvrkwhyttY1:-MMPgzs9EfkAJcMCL3a_:b-otqi76) ([raw file](https://github.com/memkind/memkind/blob/2bc8bca6714a7c2a5b35b0699aeda6a2fcfabfaa/utils/docker/docker_install_ndctl.sh#L30)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> -disable-docs --disable-asciidoctor
> ```
I like this change but I prefer to be done as a separate commit, see that:
https://github.com/memkind/memkind/blob/14ba5be23ebf36c5edbf30f111c338ad72931d1f/utils/docker/Dockerfile.fedora-32#L11
is obsolete.  The same parameter could be passed in the case of Ubuntu so basically this is a separate change that I would like to see as a separate commit.
</blockquote></details>

I need to remove this change. It was used to test installation of ndctl on centos 8 (there is no asciidoctor package and asciidoc is not working) and it fails, because asciidoctor is also needed while building rpm and I don't know how to prevent rpmbuild from using this package.

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/397)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[utils/docker/docker_install_ndctl.sh, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/397#-MMKj7ef37vxiKhH9sAR:-MMQ1K182_Ze4jhFMXQQ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2bc8bca6714a7c2a5b35b0699aeda6a2fcfabfaa/utils/docker/docker_install_ndctl.sh#L16)):*
<details><summary><i>Previously, TomekIdczak97 (tomekidczak) wrote…</i></summary><blockquote>

Exactly. Ask Adam if you need more details.
</blockquote></details>

Done.
___
*[utils/docker/docker_install_ndctl.sh, line 30 at r2](https://reviewable.io/reviews/memkind/memkind/397#-MMKiWiD6SvrkwhyttY1:-MMQ1LAT1iZhPo9yDYRV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2bc8bca6714a7c2a5b35b0699aeda6a2fcfabfaa/utils/docker/docker_install_ndctl.sh#L30)):*
<details><summary><i>Previously, TomekIdczak97 (tomekidczak) wrote…</i></summary><blockquote>

I need to remove this change. It was used to test installation of ndctl on centos 8 (there is no asciidoctor package and asciidoc is not working) and it fails, because asciidoctor is also needed while building rpm and I don't know how to prevent rpmbuild from using this package.
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/397)* status: all files reviewed, 7 unresolved discussions (waiting on @TomekIdczak97)

___
*[utils/docker/docker_install_ndctl.sh, line 17 at r4](https://reviewable.io/reviews/memkind/memkind/397#-MMQ2wSg530-p1AAgqhM:-MMQ2wSg530-p1AAgqhN:bckz33x) ([raw file](https://github.com/memkind/memkind/blob/802b0c2ed89c20b99320c4fcac9bd5da4520ecb5/utils/docker/docker_install_ndctl.sh#L17)):*
> ```
> someone
> ```
memkinduser
___
*[utils/docker/docker_install_ndctl.sh, line 18 at r4](https://reviewable.io/reviews/memkind/memkind/397#-MMQ3nd_28dqBrqMOt50:-MMQ3nd_28dqBrqMOt51:b3oyyis) ([raw file](https://github.com/memkind/memkind/blob/802b0c2ed89c20b99320c4fcac9bd5da4520ecb5/utils/docker/docker_install_ndctl.sh#L18)):*
> ```
> someone@someplace
> ```
memkinduser@memkinduser
___
*[utils/docker/docker_install_ndctl.sh, line 32 at r4](https://reviewable.io/reviews/memkind/memkind/397#-MMQ3jeU8me8G5om6bMY:-MMQ3_zV8U5CZz1p0fBp:b-e8xajq) ([raw file](https://github.com/memkind/memkind/blob/802b0c2ed89c20b99320c4fcac9bd5da4520ecb5/utils/docker/docker_install_ndctl.sh#L32)):*
> memkinduser
nit: please remove this newline
___
*[utils/docker/docker_install_ndctl.sh, line 34 at r4](https://reviewable.io/reviews/memkind/memkind/397#-MMQ3jHgAOTXTyPBtmas:-MMQ3jHgAOTXTyPBtmat:b-rjxlym) ([raw file](https://github.com/memkind/memkind/blob/802b0c2ed89c20b99320c4fcac9bd5da4520ecb5/utils/docker/docker_install_ndctl.sh#L34)):*
> ```Shell
> 
>   ./rpmbuild.sh
> ```

nit: please remove this newline
___
*[utils/docker/docker_install_ndctl.sh, line 39 at r4](https://reviewable.io/reviews/memkind/memkind/397#-MMQ3bmC17U_oPZI3RMN:-MMQ3bmC17U_oPZI3RMO:b-rjxlym) ([raw file](https://github.com/memkind/memkind/blob/802b0c2ed89c20b99320c4fcac9bd5da4520ecb5/utils/docker/docker_install_ndctl.sh#L39)):*
> ```Shell
> 
> else
> ```

nit: please remove this newline
___
*[utils/docker/docker_install_ndctl.sh, line 43 at r4](https://reviewable.io/reviews/memkind/memkind/397#-MMQ3eqL4y_IgGJZVuUM:-MMQ3dSM4y7kzr7vyFUC:b-rjxlym) ([raw file](https://github.com/memkind/memkind/blob/802b0c2ed89c20b99320c4fcac9bd5da4520ecb5/utils/docker/docker_install_ndctl.sh#L43)):*
> ```Shell
>   ./configure --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib --disable-docs
>   make -j "$(nproc)"
> ```

nit: please remove this newline
___
*[utils/docker/docker_install_ndctl.sh, line 45 at r4](https://reviewable.io/reviews/memkind/memkind/397#-MMQ3hYbAgPo1XhQdl9d:-MMQ3hYbAgPo1XhQdl9e:b-rjxlym) ([raw file](https://github.com/memkind/memkind/blob/802b0c2ed89c20b99320c4fcac9bd5da4520ecb5/utils/docker/docker_install_ndctl.sh#L45)):*
> ```Shell
> 
>   sudo make -j "$(nproc)" install
> ```

nit: please remove this newline

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/397)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[utils/docker/docker_install_ndctl.sh, line 17 at r4](https://reviewable.io/reviews/memkind/memkind/397#-MMQ2wSg530-p1AAgqhM:-MMQ7gc-1nXt4A4Vx8Cn:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/802b0c2ed89c20b99320c4fcac9bd5da4520ecb5/utils/docker/docker_install_ndctl.sh#L17)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> someone
> ```
memkinduser
</blockquote></details>

Done.
___
*[utils/docker/docker_install_ndctl.sh, line 18 at r4](https://reviewable.io/reviews/memkind/memkind/397#-MMQ3nd_28dqBrqMOt50:-MMQ7gxTC9xEzicO_v8J:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/802b0c2ed89c20b99320c4fcac9bd5da4520ecb5/utils/docker/docker_install_ndctl.sh#L18)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> someone@someplace
> ```
memkinduser@memkinduser
</blockquote></details>

Done.

**Comment by michalbiesek** [comment]
@pmem-bot-ae
test this please

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/397)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

**Review by michalbiesek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/397#-:-MMQTHkH5sL5f5UIGq3t:bnfp4nl)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

**Pull request merged**
