### PR TITLE
Remove unorder map structure from hmat test

### PR DESCRIPTION
**Pull request by michalbiesek**
- create factory in memory_topology

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/491)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/491)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @michalbiesek)

___
*[test/memkind_hmat_tests.cpp, line 12 at r1](https://reviewable.io/reviews/memkind/memkind/491#-MRxf4Wb7leLpoz1TSRP:-MRxf4Wb7leLpoz1TSRQ:bfcm7qw) ([raw file](https://github.com/memkind/memkind/blob/56988dcd83ec7c58b694681fa27300beacfa8dac/test/memkind_hmat_tests.cpp#L12)):*
> ```cpp
> #include "TestPrereq.hpp"
> #include "common.h"
> #include "memory_topology.h"
> ```

not needed?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/491)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[test/memkind_hmat_tests.cpp, line 12 at r1](https://reviewable.io/reviews/memkind/memkind/491#-MRxf4Wb7leLpoz1TSRP:-MRxghf265_DYpOD54AZ:b-n1h9ze) ([raw file](https://github.com/memkind/memkind/blob/56988dcd83ec7c58b694681fa27300beacfa8dac/test/memkind_hmat_tests.cpp#L12)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

I need this :) 
TopologyFactory is defined in memory_topology.h
Memkind_Param_Test in common.h
TestPrereq tp in "TestPrereq.hpp"

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/491#-:-MRxhLGSAbM5wrODpJf1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/491#-:-MRxjdXD8UJKTzF8Jo0J:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
