### PR TITLE
Add shellcheck to Github Actions

### PR DESCRIPTION
**Pull request by jacekgrzybek**
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/749)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac and @PatKamin)

**Review by PatKamin — COMMENTED** [review]
Definitely silently ignoring pre-existing issues is not the way to go. We want to have a coherent style applied across the scripts in the whole repo. With a list of existing issues you could figure out the best options to run the shellcheck with.

As to the permissions I think it's just for posting issues as a code review comment. It's better to have these issues printed in shellcheck github action log with a failed status instead. Please, verify what are these permissions needed for.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749#-:-Mw0SLjE8mLLtfoxzl-x:bpu8su7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jacekgrzybek)

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: all files reviewed, 1 unresolved discussion (waiting on @jacekgrzybek)

___
*[.github/workflows/gha.yml, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/749#-Mw6nSYc-shqm2F7PlTN:-Mw6nSYc-shqm2F7PlTO:bftzrpd) ([raw file](https://github.com/memkind/memkind/blob/5d7cf25a4abc5e407f78d050af858a4d9989a303/.github/workflows/gha.yml#L16)):*
> ```YAML
>     - uses: ludeeus/action-shellcheck@master
>       with:
>         ignore: jemalloc
> ```

shouldn't this be "ignore_paths" ? see readme at https://github.com/ludeeus/action-shellcheck

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r5, 16 of 16 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: all files reviewed, 4 unresolved discussions (waiting on @jacekgrzybek)

___
*[-- commits, line 5 at r6](https://reviewable.io/reviews/memkind/memkind/749#-MwWebJgEfvqGuRqdmzB):*
"Apply shellcheck fixes to bash scripts"
___
*[build.sh, line 14 at r6](https://reviewable.io/reviews/memkind/memkind/749#-MwWiMkgEgTAIHIBszLL:-MwWiMkgEgTAIHIBszLM:b-t3recf) ([raw file](https://github.com/memkind/memkind/blob/08fef00178881cf9b19ea481f9053515096f4e29/build.sh#L14)):*
> ```Shell
> 
> #use V=1 for full cmdlines of build
> make all -j$(nproc)
> ```

nit: Add an extra space between `j` and `$`.
___
*[.github/workflows/gha.yml, line 18 at r5](https://reviewable.io/reviews/memkind/memkind/749#-MwWeDeRC91ym9mO7ji8:-MwWeDeRC91ym9mO7ji9:boha1k2) ([raw file](https://github.com/memkind/memkind/blob/6ba04a1c359e216c1e794f21d093809868d39bc7/.github/workflows/gha.yml#L18)):*
> ```YAML
>         ignore: jemalloc
>         ignore_paths: ./jemalloc
>         ignore_names: ltmain.sh
> ```

This file is not included in source files. As this github action doesn't need to build memkind I don't see a reason why this ignore should be added. Please, verify that it's not needed.

**Review by PatKamin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: all files reviewed, 5 unresolved discussions (waiting on @jacekgrzybek)

___
*[utils/docker/run_local.sh, line 18 at r7](https://reviewable.io/reviews/memkind/memkind/749#-MwWpKgL42hBmrFIo1Gl:-MwWr5fb6MALdcEg-ZsQ:buk77xv) ([raw file](https://github.com/memkind/memkind/blob/b9bdba59bc804ea31c61484a9316c27cc6c7c9e4/utils/docker/run_local.sh#L18)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Try to use single quotes for variable.
</blockquote></details>

On a second thought, removing all inner double quotes would do the job (most probably).

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r8, 1 of 2 files at r9, 13 of 13 files at r10, 12 of 12 files at r11.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: 6 of 19 files reviewed, 8 unresolved discussions (waiting on @jacekgrzybek and @PatKamin)

___
*[test/test.sh, line 325 at r8](https://reviewable.io/reviews/memkind/memkind/749#-MwaPVSD1v6Ci_NXmIDn:-MwaPVSE7PjsCOY5dJEc:bh7ck5s) ([raw file](https://github.com/memkind/memkind/blob/a241889d136320491f71f11c897adf210e56ba5e/test/test.sh#L325)):*
> ```Shell
>             exit 0;
>             ;;
>         *)
> ```

Print usage and exit.
___
*[test/test_dax_kmem.sh, line 225 at r8](https://reviewable.io/reviews/memkind/memkind/749#-MwaQ0DBBdf1AxHlmLL5:-MwaQ0DBBdf1AxHlmLL6:bh7ck5s) ([raw file](https://github.com/memkind/memkind/blob/a241889d136320491f71f11c897adf210e56ba5e/test/test_dax_kmem.sh#L225)):*
> ```Shell
>             exit 0;
>             ;;
>         *)
> ```

Print usage and exit.
___
*[utils/docker/run_local.sh, line 35 at r11](https://reviewable.io/reviews/memkind/memkind/749#-MwaUIoR9p-pv2tjP40l:-MwaUIoR9p-pv2tjP40m:b-c1pz91) ([raw file](https://github.com/memkind/memkind/blob/9d30434c9aedff626b9267f1a5523564b4e2d5e0/utils/docker/run_local.sh#L35)):*
> ```Shell
> docker build --tag memkind_cont \
>              --file "$DOCKER_IMAGE_NAME" \
>              --build-arg http_proxy="${http_proxy:?}" \
> ```

http_proxy doesn't have to be set. Remove the checking for a var part.

**Review by jacekgrzybek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: 6 of 20 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[build.sh, line 14 at r6](https://reviewable.io/reviews/memkind/memkind/749#-MwWiMkgEgTAIHIBszLL:-MwkLyE54pzD-L3T-blh:bb7f2mf) ([raw file](https://github.com/memkind/memkind/blob/08fef00178881cf9b19ea481f9053515096f4e29/build.sh#L14)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Add an extra space between `j` and `$`.
</blockquote></details>

done
___
*[.github/workflows/gha.yml, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/749#-Mw6nSYc-shqm2F7PlTN:-MwkLzuU1N4qYqm0GAvE:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5d7cf25a4abc5e407f78d050af858a4d9989a303/.github/workflows/gha.yml#L16)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

shouldn't this be "ignore_paths" ? see readme at https://github.com/ludeeus/action-shellcheck
</blockquote></details>

Done.
___
*[test/test_dax_kmem.sh, line 225 at r8](https://reviewable.io/reviews/memkind/memkind/749#-MwaQ0DBBdf1AxHlmLL5:-MwkOcFG3rJCI64cTt1B:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a241889d136320491f71f11c897adf210e56ba5e/test/test_dax_kmem.sh#L225)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Print usage and exit.
</blockquote></details>

Done.
___
*[utils/docker/run_local.sh, line 35 at r11](https://reviewable.io/reviews/memkind/memkind/749#-MwaUIoR9p-pv2tjP40l:-MwkOeKUAsVJsA-oUNvh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9d30434c9aedff626b9267f1a5523564b4e2d5e0/utils/docker/run_local.sh#L35)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

http_proxy doesn't have to be set. Remove the checking for a var part.
</blockquote></details>

Done.

**Review by jacekgrzybek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: 6 of 20 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @jacekgrzybek, and @PatKamin)

___
*[test/test.sh, line 325 at r8](https://reviewable.io/reviews/memkind/memkind/749#-MwaPVSD1v6Ci_NXmIDn:-MwkQI_eBW4unGBFReGj:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a241889d136320491f71f11c897adf210e56ba5e/test/test.sh#L325)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Print usage and exit.
</blockquote></details>

Done.

**Review by jacekgrzybek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: 6 of 20 files reviewed, 7 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[-- commits, line 5 at r6](https://reviewable.io/reviews/memkind/memkind/749#-MwWebJgEfvqGuRqdmzB):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

"Apply shellcheck fixes to bash scripts"
</blockquote></details>

Done.
___
*[.github/workflows/gha.yml, line 18 at r5](https://reviewable.io/reviews/memkind/memkind/749#-MwWeDeRC91ym9mO7ji8:-MwkQOi32N2CU1IWl79n:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6ba04a1c359e216c1e794f21d093809868d39bc7/.github/workflows/gha.yml#L18)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This file is not included in source files. As this github action doesn't need to build memkind I don't see a reason why this ignore should be added. Please, verify that it's not needed.
</blockquote></details>

Done.
___
*[utils/docker/run_local.sh, line 18 at r7](https://reviewable.io/reviews/memkind/memkind/749#-MwWpKgL42hBmrFIo1Gl:-MwkTlCE9MNnNzuePElf:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b9bdba59bc804ea31c61484a9316c27cc6c7c9e4/utils/docker/run_local.sh#L18)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

On a second thought, removing all inner double quotes would do the job (most probably).
</blockquote></details>

Done.

**Review by jacekgrzybek — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749#-:-MwkV4sGCOtWxeRbEVl9:bb7f2mf)* status: 6 of 20 files reviewed, 7 unresolved discussions (waiting on @bratpiorka and @PatKamin)

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 15 of 15 files at r4, 14 of 14 files at r15, 12 of 13 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: all files reviewed, 6 unresolved discussions (waiting on @PatKamin)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: all files reviewed, 6 unresolved discussions (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 6 of 16 files at r6, 1 of 14 files at r15, 11 of 13 files at r16, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 14 files at r15, 11 of 13 files at r16, 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jacekgrzybek)

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
I'll confirm (soon-ish) if tests are run properly, and they succeed - right now, Jenkins CI is failing for some reason, beside that it looks ok

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/749#-:-NJtZkJwCF_f6cE7Ia7z:b5u9zzf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jacekgrzybek)

**Comment by lukaszstolarczuk** [comment]
Closing for now, to be continued if the times come (low priority as of today).

Ref: https://github.com/memkind/memkind/issues/870

**Pull request closed without merging**
