### PR TITLE
Fix print syntax errors in pytests

### PR DESCRIPTION
**Pull request by TomekIdczak97**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [x] Other

### Checklist

- [x] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/380)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Review by kasiawasiuta — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/380)* status: all files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)

___
*[test/autohbw_test.py, line 28 at r1](https://reviewable.io/reviews/memkind/memkind/380#-MIdJIoG2RCKCQW7Lyrp:-MIdJIoHEdsMaGF6ON9u:b-wg5la6) ([raw file](https://github.com/memkind/memkind/blob/a21b1dad84c37ecf6202988fa35c456a30279457/test/autohbw_test.py#L28)):*
> ```Python
>         """ This test executes ./autohbw_test_helper with LD_PRELOAD that is overriding malloc() and free() to equivalent autohbw functions"""
>         command = self.test_prefix + self.cmd_helper.get_command_path(self.binary) + " malloc"
>         print("Executing command: {0}".format(command))
> ```

consider following syntax: print(f"Executing command: {command}")

**Comment by michalbiesek** [comment]
> > Reviewed 2 of 2 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/memkind/memkind/380)_ status: all files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)
> 
> _[test/autohbw_test.py, line 28 at r1](https://reviewable.io/reviews/memkind/memkind/380#-MIdJIoG2RCKCQW7Lyrp:-MIdJIoHEdsMaGF6ON9u:b-wg5la6) ([raw file](https://github.com/memkind/memkind/blob/a21b1dad84c37ecf6202988fa35c456a30279457/test/autohbw_test.py#L28)):_
> 
> > ```python
> >         """ This test executes ./autohbw_test_helper with LD_PRELOAD that is overriding malloc() and free() to equivalent autohbw functions"""
> >         command = self.test_prefix + self.cmd_helper.get_command_path(self.binary) + " malloc"
> >         print("Executing command: {0}".format(command))
> > ```
> 
> consider following syntax: print(f"Executing command: {command}")

If you go with the solution with f string please ensure that every Dockerfile got a python in at least version 3.6.  - personally, I pay no attention if this solution here is using f string or not. I care only that all tests pass regarding switch python from 2 to 3.

**Comment by michalbiesek** [comment]
@pmem-bot-ae
test this please

**Comment by michalbiesek** [comment]
LGTM - if you want to do f string change - ensure that every Dockerfile got a python in at least version 3.6 and feel free to update it everywhere

**Pull request merged**
