### PR TITLE
Change clock type used in MTT bg thread to CLOCK_REALTIME

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/800)

### CODE REVIEW

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/800)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[src/mtt_allocator.c, line 160 at r1](https://reviewable.io/reviews/memkind/memkind/800#-N-ZCC5e0m7wScmg57r8:-N-ZCC5e0m7wScmg57r9:b-cn9elj) ([raw file](https://github.com/memkind/memkind/blob/0b5a84f69c856183fa255c4314e76da9cc3ee7ef/src/mtt_allocator.c#L160)):*
> ```C
>     // TODO: we use CLOCK_REALTIME here only because pthread_cond_timedwait
>     // waits using this clock. CLOCK_MONOTONIC would be better here, but not
>     // all Linux distro implements pthread_cond_clockwait that could wait on
> ```

nit: distributions (or distros)

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/800)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka)

___
*[src/mtt_allocator.c, line 160 at r1](https://reviewable.io/reviews/memkind/memkind/800#-N-apy5CEEQIhmrmutZ_:-N-apy5D09gNqwQv5Z3a:b-456kis) ([raw file](https://github.com/memkind/memkind/blob/0b5a84f69c856183fa255c4314e76da9cc3ee7ef/src/mtt_allocator.c#L160)):*
> ```C
>     // TODO: we use CLOCK_REALTIME here only because pthread_cond_timedwait
>     // waits using this clock. CLOCK_MONOTONIC would be better here, but not
>     // all Linux distro implements pthread_cond_clockwait that could wait on
> ```

What are these distros that don't support CLOCK_MONOTONIC in pthread_cond_clockwait? Are they even supported by memkind? If it's about the availability of the CLOCK_MONOTONIC macro then it's much better to create an `#ifdef` for using one clock or another.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/800)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[src/mtt_allocator.c, line 160 at r1](https://reviewable.io/reviews/memkind/memkind/800#-N-apy5CEEQIhmrmutZ_:-N-b5oh4ANq60GkE7GEb:b-bf4bxk) ([raw file](https://github.com/memkind/memkind/blob/0b5a84f69c856183fa255c4314e76da9cc3ee7ef/src/mtt_allocator.c#L160)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

What are these distros that don't support CLOCK_MONOTONIC in pthread_cond_clockwait? Are they even supported by memkind? If it's about the availability of the CLOCK_MONOTONIC macro then it's much better to create an `#ifdef` for using one clock or another.
</blockquote></details>

It is not about support from CLOCK_MONOTONIC - it is about support for pthread_cond_clockwait which could take it as a parameter. I checked that this function is not available in Ubuntu used in our QEMU HMAT tests.

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/800)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
