### PR TITLE
Feat sync with wip

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/601)

### CODE REVIEW

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 2 of 3 files at r6, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, 3 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by michalbiesek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/601#-:-MWhv4Bk5yG84hkZwjKa:bnfp4nl)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @michalbiesek and @PatKamin)

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, 2 of 3 files at r6, 1 of 1 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, 2 of 3 files at r14, 3 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — APPROVED** [review]

**Comment by michalbiesek** [comment]
Please verify diff:
git diff origin/feat-sync_with_wip upstream/wip-memory-tiering
After this merge feat-memory-tiering should be inline with wip-memory-tiering

**Review by bratpiorka — COMMENTED** [review]
ok since code on "feat" branch is IMHO better, I made a PR that merges them to "wip" (see PR #603)

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/601#-:-MWiGdZp07ER7mq_yQ3L:b-5hbl4c)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
