### PR TITLE
Add note to manual regarding DRAM usage for FS_DAX and KMEM_DAX

### PR DESCRIPTION
**Pull request by michalbiesek**
Required:

- [x] #630

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/637)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/637)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[man/memtier.7, line 77 at r2](https://reviewable.io/reviews/memkind/memkind/637#-M_K6ev-8oQoCp8WO9a7:-M_K6ev-8oQoCp8WO9a8:bn4fzjz) ([raw file](https://github.com/memkind/memkind/blob/8f7df61a7dd1cc0bf063a196140670d15dd262d0/man/memtier.7#L77)):*
> ```Roff
> tier memory allocation request, with usage of
> .I DAX_KMEM
> tier, allocation will fall back to PMEM memory, wherein with the usage of
> ```

I'm not sure but "wherein" -> "while" wouldn't be better?

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/637)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/637)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[man/memtier.7, line 77 at r3](https://reviewable.io/reviews/memkind/memkind/637#-M_WJB003U5wGTMz5GD8:-M_WJB003U5wGTMz5GD9:ba2iki2) ([raw file](https://github.com/memkind/memkind/blob/26c307f0fe59f9b4308342718369a721b7dfeaf3/man/memtier.7#L77)):*
> ```Roff
> tier memory allocation request, with usage of
> .I KMEM_DAX
> tier, allocation will fall back to PMEM memory, while with the usage of
> ```

Too long and complcated sentence. Split it into two separate ones. One for the kmem dax description and second for the fs dax description.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/637)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[man/memtier.7, line 77 at r2](https://reviewable.io/reviews/memkind/memkind/637#-M_K6ev-8oQoCp8WO9a7:-M__4AffEJWy1Q-db7aN:b9gu2er) ([raw file](https://github.com/memkind/memkind/blob/8f7df61a7dd1cc0bf063a196140670d15dd262d0/man/memtier.7#L77)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I'm not sure but "wherein" -> "while" wouldn't be better?
</blockquote></details>

Rephrased
___
*[man/memtier.7, line 77 at r3](https://reviewable.io/reviews/memkind/memkind/637#-M_WJB003U5wGTMz5GD8:-M__4BY45X-OAk0cOKLQ:b9gu2er) ([raw file](https://github.com/memkind/memkind/blob/26c307f0fe59f9b4308342718369a721b7dfeaf3/man/memtier.7#L77)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Too long and complcated sentence. Split it into two separate ones. One for the kmem dax description and second for the fs dax description.
</blockquote></details>

Rephrased

**Review by PatKamin — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/637)* status: all files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[man/memtier.7, line 85 at r4](https://reviewable.io/reviews/memkind/memkind/637#-M__lQ83CFHWPF9i-5Cy:-M__lQ83CFHWPF9i-5Cz:b3t8xdl) ([raw file](https://github.com/memkind/memkind/blob/0c89112be6f7806324662ac9a9e9e5231a6dad6c/man/memtier.7#L85)):*
> ```Roff
> .TP
> VAL (optional) - initial value of threshold between two adjacent N and N+1 tiers. For every allocation,
> if it's size is greater or equal than VAL, it will go to tier >= 1. It has to be greater or equal to MIN value
> ```

it will go to N+1 tier
___
*[man/memtier.7, line 86 at r4](https://reviewable.io/reviews/memkind/memkind/637#-M__lXaC9NY5XApTRNPx:-M__lXaC9NY5XApTRNPy:b-e8jx12) ([raw file](https://github.com/memkind/memkind/blob/0c89112be6f7806324662ac9a9e9e5231a6dad6c/man/memtier.7#L86)):*
> ```Roff
> VAL (optional) - initial value of threshold between two adjacent N and N+1 tiers. For every allocation,
> if it's size is greater or equal than VAL, it will go to tier >= 1. It has to be greater or equal to MIN value
> and less or equal than MAX value. Note that in DYNAMIC_THRESHOLD policy this value could change in time
> ```

could --> can
___
*[man/memtier.7, line 87 at r4](https://reviewable.io/reviews/memkind/memkind/637#-M__lnAp1QF7-mxwK61K:-M__lnAp1QF7-mxwK61L:blzfws6) ([raw file](https://github.com/memkind/memkind/blob/0c89112be6f7806324662ac9a9e9e5231a6dad6c/man/memtier.7#L87)):*
> ```Roff
> if it's size is greater or equal than VAL, it will go to tier >= 1. It has to be greater or equal to MIN value
> and less or equal than MAX value. Note that in DYNAMIC_THRESHOLD policy this value could change in time
> to keep desired ratios between tiers.
> ```

ratios --> ratio
___
*[man/memtier.7, line 89 at r4](https://reviewable.io/reviews/memkind/memkind/637#-M__mND70QqiN3cw90uj:-M__mND70QqiN3cw90uk:b-e8jx12) ([raw file](https://github.com/memkind/memkind/blob/0c89112be6f7806324662ac9a9e9e5231a6dad6c/man/memtier.7#L89)):*
> ```Roff
> to keep desired ratios between tiers.
> .TP
> MIN (optional) - minimum value of threshold. In DYNAMIC_THRESHOLD policy, threshold value could change in time
> ```

could --> can
___
*[man/memtier.7, line 112 at r4](https://reviewable.io/reviews/memkind/memkind/637#-M__myku8pPGU-jkiwKu:-M__myku8pPGU-jkiwKv:b-3fnx69) ([raw file](https://github.com/memkind/memkind/blob/0c89112be6f7806324662ac9a9e9e5231a6dad6c/man/memtier.7#L112)):*
> ```Roff
> 
> .SH "DRAM FALLBACK POLICY"
> .DRAM FALL
> ```

Remove this line.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/637)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @PatKamin)

___
*[man/memtier.7, line 85 at r4](https://reviewable.io/reviews/memkind/memkind/637#-M__lQ83CFHWPF9i-5Cy:-M__rsAt76HqGWIWWl0z:bkntgvm) ([raw file](https://github.com/memkind/memkind/blob/0c89112be6f7806324662ac9a9e9e5231a6dad6c/man/memtier.7#L85)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

it will go to N+1 tier
</blockquote></details>

Not part of my changes, but Done
___
*[man/memtier.7, line 86 at r4](https://reviewable.io/reviews/memkind/memkind/637#-M__lXaC9NY5XApTRNPx:-M__rrqi5XxtHaV2E2ro:bkntgvm) ([raw file](https://github.com/memkind/memkind/blob/0c89112be6f7806324662ac9a9e9e5231a6dad6c/man/memtier.7#L86)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

could --> can
</blockquote></details>

Not part of my changes, but Done
___
*[man/memtier.7, line 87 at r4](https://reviewable.io/reviews/memkind/memkind/637#-M__lnAp1QF7-mxwK61K:-M__rr7J-jHU0kcnWw3V:bkntgvm) ([raw file](https://github.com/memkind/memkind/blob/0c89112be6f7806324662ac9a9e9e5231a6dad6c/man/memtier.7#L87)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

ratios --> ratio
</blockquote></details>

Not part of my changes, but Done
___
*[man/memtier.7, line 89 at r4](https://reviewable.io/reviews/memkind/memkind/637#-M__mND70QqiN3cw90uj:-M__roFr-FcdxoMsDeVS:bkntgvm) ([raw file](https://github.com/memkind/memkind/blob/0c89112be6f7806324662ac9a9e9e5231a6dad6c/man/memtier.7#L89)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

could --> can
</blockquote></details>

Not part of my changes, but Done
___
*[man/memtier.7, line 112 at r4](https://reviewable.io/reviews/memkind/memkind/637#-M__myku8pPGU-jkiwKu:-M__rmB45K1latHnGsx_:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0c89112be6f7806324662ac9a9e9e5231a6dad6c/man/memtier.7#L112)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove this line.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/637#-:-M_a3hXwAa4yscZRGDeO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
