### PR TITLE
Redesign usage of config env vars

### PR DESCRIPTION
**Pull request by bratpiorka**
- rename env var to MEMKIND_MEM_TIERS
- all configuration parameters are passed in form PARAM_NAME:VALUE
- parameters are separated by ','
- added new env tests

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/629)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/629)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[man/memtier.7, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSjVfX5vNooQL5J38F:-MZSjVfYBFDV49VnbGCQ:bjw6ch4) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/man/memtier.7#L16)):*
> ```
> Sets the memkind tiering functionality. Passed as a semicolon separated list
> of tier configurations ended with a policy parameter. Each configuration consists of
> comma separated list of parameters in following format:
> ```
Passed as a semicolon-separated list of tier configurations ended with a policy parameter. Each tier configuration consists of
a comma-separated list of tier parameters in the following format:
.IP
"param_name:value,(...)"
, where the param_name is the name of the parameter. For more details about aram_namesee the PARAMETER NAME section below

Something like that 
I am aware that this is not related to your changes but this man should be updated.
___
*[man/memtier.7, line 25 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSrkOdBobKSyAqEPRx:-MZSrkOdBobKSyAqEPRy:b78ke7o) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/man/memtier.7#L25)):*
> ```
> kind
> ```
not sure but I think in this man the "tier" name is more convenient - the "kind" abstraction should be hidden here
___
*[man/memtier.7, line 32 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSkKRlEj5AV0ROz99i:-MZSkKRlEj5AV0ROz99j:bo9u5k5) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/man/memtier.7#L32)):*
> ```
> MAX_SIZE
> ```
not related to this PR but is this field mandatory? I mean this is basically a "user defined size limitation for fs-dax" so this could be renamed as MAX_SIZE_LIMIT or PMEM_SIZE_LIMIT to avoid disambiguation with other tiers. The renaming part could be done now.
___
*[man/memtier.7, line 57 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSjro1BMzrghxxz2AF:-MZSjro1BMzrghxxz2AG:brexlhq) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/man/memtier.7#L57)):*
> ```
> POLICY_DYNAMIC_THRESHOLD
> ```
not related with this PR but this could DYNAMIC_THRESHOLD, e.g in the end will be POLICY=DYNAMIC_THRESHOLD instead of POLICY=POLICY_DYNAMIC_THRESHOLD
___
*[test/tiering_tests.py, line 335 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSl06C298DG2yTlbqJ:-MZSl06C298DG2yTlbqK:b-iokxsm) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/test/tiering_tests.py#L335)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     def test_FSDAX_no_max_size(self):
>         self.get_ld_preload_cmd_output(
>             "KIND:FS_DAX,PATH:/tmp/,RATIO:1;" +
>             self.default_policy,
>             negative_test=True)
> ```
</details>

see my comment regarding the limitation of size
___
*[test/tiering_tests.py, line 365 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSmENA0t3S8-PfsWR5:-MZSmENA0t3S8-PfsWR6:b-83x9zg) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/test/tiering_tests.py#L365)):*
> ```Python
>             "KIND:DRAM,RATIO:1;POLICY:" + policy_str,
>             negative_test=True)
> ```

Is there are tests for negative configuration in the form where you define the path and/or MAX_SIZE for DRAM kind?

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/629)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[man/memtier.7, line 16 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSjVfX5vNooQL5J38F:-MZWp2xNA5zb6l0L5tUs:bcb9gpb) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/man/memtier.7#L16)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Sets the memkind tiering functionality. Passed as a semicolon separated list
> of tier configurations ended with a policy parameter. Each configuration consists of
> comma separated list of parameters in following format:
> ```
Passed as a semicolon-separated list of tier configurations ended with a policy parameter. Each tier configuration consists of
a comma-separated list of tier parameters in the following format:
.IP
"param_name:value,(...)"
, where the param_name is the name of the parameter. For more details about aram_namesee the PARAMETER NAME section below

Something like that 
I am aware that this is not related to your changes but this man should be updated.
</blockquote></details>

I updated this but agree that it requires further work
___
*[man/memtier.7, line 25 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSrkOdBobKSyAqEPRx:-MZWhPdDDVaQ3AvWUTew:b-itewwa) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/man/memtier.7#L25)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> kind
> ```
not sure but I think in this man the "tier" name is more convenient - the "kind" abstraction should be hidden here
</blockquote></details>

You build tiered memory using tiers, and each tier is based on some kind of memory. I slightly modified this description but I think we can safely use "kind" word here
___
*[man/memtier.7, line 32 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSkKRlEj5AV0ROz99i:-MZWgLnz2gpi_K8ECkE8:b-bb3h5s) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/man/memtier.7#L32)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> MAX_SIZE
> ```
not related to this PR but is this field mandatory? I mean this is basically a "user defined size limitation for fs-dax" so this could be renamed as MAX_SIZE_LIMIT or PMEM_SIZE_LIMIT to avoid disambiguation with other tiers. The renaming part could be done now.
</blockquote></details>

Done, renamed and it is not mandatory anymore.
___
*[man/memtier.7, line 57 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSjro1BMzrghxxz2AF:-MZWeCQCChk7OZPfgPpb:b14blm0) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/man/memtier.7#L57)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> POLICY_DYNAMIC_THRESHOLD
> ```
not related with this PR but this could DYNAMIC_THRESHOLD, e.g in the end will be POLICY=DYNAMIC_THRESHOLD instead of POLICY=POLICY_DYNAMIC_THRESHOLD
</blockquote></details>

yes, this looks better
___
*[test/tiering_tests.py, line 335 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSl06C298DG2yTlbqJ:-MZWp2Bf7QdECEjLC5wt:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/test/tiering_tests.py#L335)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     def test_FSDAX_no_max_size(self):
>         self.get_ld_preload_cmd_output(
>             "KIND:FS_DAX,PATH:/tmp/,RATIO:1;" +
>             self.default_policy,
>             negative_test=True)
> ```
see my comment regarding the limitation of size
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 365 at r2](https://reviewable.io/reviews/memkind/memkind/629#-MZSmENA0t3S8-PfsWR5:-MZWd6nF2pjc6MV7oGbL:b-hs4p71) ([raw file](https://github.com/memkind/memkind/blob/6de131ba7abde47be32e48ddd1ffb34fcd69b962/test/tiering_tests.py#L365)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Is there are tests for negative configuration in the form where you define the path and/or MAX_SIZE for DRAM kind?
</blockquote></details>

Yes, I missed this. I added "test_unsupported_param" and a code that logs error in this case.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/629)* status: 3 of 4 files reviewed, 9 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[test/tiering_tests.py, line 60 at r3](https://reviewable.io/reviews/memkind/memkind/629#-MZWnXPi-T1qAZjE5QNS:-MZWnXPjBjwno8D3sB3i:b2bvpmj) ([raw file](https://github.com/memkind/memkind/blob/fca15f985fed3eee73a2dd05b70442566ec2a089/test/tiering_tests.py#L60)):*
> ```Python
>         log_level_env = self.log_prefix + "LOG_LEVEL=" + log_level \
>             if log_level else ""
>         config_env = self.mem_tiers_env_var + "=\"" + config + "\""
> ```

Use single quotes: `'="'`, it's easier to read.
___
*[test/tiering_tests.py, line 345 at r3](https://reviewable.io/reviews/memkind/memkind/629#-MZWoz3u-M9l2tcIvF96:-MZWoz3u-M9l2tcIvF97:bdzkrka) ([raw file](https://github.com/memkind/memkind/blob/fca15f985fed3eee73a2dd05b70442566ec2a089/test/tiering_tests.py#L345)):*
> ```Python
>             negative_test=True)
> 
>     def test_FSDAX_no_max_size(self):
> ```

I think you can remove test test_FSDAX_no_size now.
___
*[tiering/ctl.c, line 193 at r3](https://reviewable.io/reviews/memkind/memkind/629#-MZWq7b73zlo3rbpnJAG:-MZWq7b73zlo3rbpnJAH:bwln5h8) ([raw file](https://github.com/memkind/memkind/blob/fca15f985fed3eee73a2dd05b70442566ec2a089/tiering/ctl.c#L193)):*
> ```C
>     int ret = -1;
> 
>     int is_pmem = 0;
> ```

`is_fsdax` would be better. See that other tiers for pmem like DAX_MEM will be added.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/629)* status: all files reviewed, 9 unresolved discussions (waiting on @bratpiorka)

___
*[man/memtier.7, line 33 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZWwe_wCIbilmQSvx8E:-MZWwe_wCIbilmQSvx8F:ba0nrcx) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/man/memtier.7#L33)):*
> ```
> the size of pmem file
> ```
the limitation size of pmem file
___
*[man/memtier.7, line 34 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZWwqb44lTd0a0Bpn2H:-MZWwqb44lTd0a0Bpn2I:btu39hz) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/man/memtier.7#L34)):*
> ```
> PMEM_SIZE_LIMIT (optional) - the size of pmem file, it's the maximum size of total allocations to PMEM. Pass this option
> only with FS_DAX kind. The accepted formats are: 1, 1K, 1M, 1G. See
> ```
.. the size limitation of pmem file, it's the maximum size of total allocations to PMEM. The option is valid only with FS_DAX kind. By default no limit is introduced 

Something like that.
___
*[test/tiering_tests.py, line 233 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZWv7CN8hVqHB3t7vBW:-MZWv7CO3s7pDkNUYBjb:b-5irki) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/test/tiering_tests.py#L233)):*
> ```
> /tmt/
> ```
/tmp/

I believe you want to check the behavior DRAM case with the correct values of PMEM params
___
*[tiering/ctl.c, line 212 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZX09IqAQKZulAcxXRK:-MZX09IqAQKZulAcxXRL:btca70t) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/tiering/ctl.c#L212)):*
> ```
>         } else if (!strcmp(param_str, "PATH")) {
>             pmem_path = strtok_r(NULL, CTL_PARAM_SEPARATOR, &sptr);
> ```
I think you could avoid later validation if you do something like:
if is_pmem
   pmem_path = strtok_r(NULL, CTL_PARAM_SEPARATOR, &sptr);
else
    log_err("PATH param can be defined only for FS_DAX kind");
    return -1;
___
*[tiering/ctl.c, line 213 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZX0Ktn4Oo8jd1i2M_b:-MZX0KtoCl8bT2agtlbs:bklrvlh) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/tiering/ctl.c#L213)):*
> ```
> PMEM_SIZE_LIMIT
> ```
similar situation as in PATH case
___
*[tiering/ctl.c, line 259 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZWvVES2_HI-8BkvGDE:-MZWvVES2_HI-8BkvGDF:b-3qwrld) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/tiering/ctl.c#L259)):*
> ```
> MAX_SIZE
> ```
PMEM_SIZE_LIMIT ?

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/629)* status: all files reviewed, 9 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[man/memtier.7, line 33 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZWwe_wCIbilmQSvx8E:-MZX255U97yUaVsL4rrj:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/man/memtier.7#L33)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> the size of pmem file
> ```
the limitation size of pmem file
</blockquote></details>

Done.
___
*[man/memtier.7, line 34 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZWwqb44lTd0a0Bpn2H:-MZX2byTAX7GCiwf-1jx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/man/memtier.7#L34)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> PMEM_SIZE_LIMIT (optional) - the size of pmem file, it's the maximum size of total allocations to PMEM. Pass this option
> only with FS_DAX kind. The accepted formats are: 1, 1K, 1M, 1G. See
> ```
.. the size limitation of pmem file, it's the maximum size of total allocations to PMEM. The option is valid only with FS_DAX kind. By default no limit is introduced 

Something like that.
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 60 at r3](https://reviewable.io/reviews/memkind/memkind/629#-MZWnXPi-T1qAZjE5QNS:-MZX0O7wD0gcPa6GT499:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/fca15f985fed3eee73a2dd05b70442566ec2a089/test/tiering_tests.py#L60)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Use single quotes: `'="'`, it's easier to read.
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 345 at r3](https://reviewable.io/reviews/memkind/memkind/629#-MZWoz3u-M9l2tcIvF96:-MZX0SJdERK-Gkh7i8OI:bd33s6k) ([raw file](https://github.com/memkind/memkind/blob/fca15f985fed3eee73a2dd05b70442566ec2a089/test/tiering_tests.py#L345)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I think you can remove test test_FSDAX_no_size now.
</blockquote></details>

Currently this is the only test that checks what happens if there will be no PMEM_MAX_SIZE parameter set. So I think it should not be removed.
___
*[test/tiering_tests.py, line 233 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZWv7CN8hVqHB3t7vBW:-MZX2skeAKnuahfe_6o-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/test/tiering_tests.py#L233)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> /tmt/
> ```
/tmp/

I believe you want to check the behavior DRAM case with the correct values of PMEM params
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 193 at r3](https://reviewable.io/reviews/memkind/memkind/629#-MZWq7b73zlo3rbpnJAG:-MZX1Ph1COTqrDm4A5eH:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/fca15f985fed3eee73a2dd05b70442566ec2a089/tiering/ctl.c#L193)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`is_fsdax` would be better. See that other tiers for pmem like DAX_MEM will be added.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 212 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZX09IqAQKZulAcxXRK:-MZX1dXQ-v69HbMEqxlb:b-w3jar7) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/tiering/ctl.c#L212)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         } else if (!strcmp(param_str, "PATH")) {
>             pmem_path = strtok_r(NULL, CTL_PARAM_SEPARATOR, &sptr);
> ```
I think you could avoid later validation if you do something like:
if is_pmem
   pmem_path = strtok_r(NULL, CTL_PARAM_SEPARATOR, &sptr);
else
    log_err("PATH param can be defined only for FS_DAX kind");
    return -1;

</blockquote></details>

I can't do it here because we don't have a strict order of parameters, so user can first define PATH and then KIND. This is why the validation part is done after parsing all parameters.
___
*[tiering/ctl.c, line 213 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZX0Ktn4Oo8jd1i2M_b:-MZX1r8bDzqxEg4ghvAe:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/tiering/ctl.c#L213)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> PMEM_SIZE_LIMIT
> ```
similar situation as in PATH case
</blockquote></details>

.
___
*[tiering/ctl.c, line 259 at r4](https://reviewable.io/reviews/memkind/memkind/629#-MZWvVES2_HI-8BkvGDE:-MZX1yDA1rBKfg5LsKwM:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c6c399272fe59fec844e2a8c265d9716b42233e3/tiering/ctl.c#L259)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> MAX_SIZE
> ```
PMEM_SIZE_LIMIT ?
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/629)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[tiering/ctl.c, line 335 at r5](https://reviewable.io/reviews/memkind/memkind/629#-MZX9fNPEYe66YnnmMPg:-MZX9fNPEYe66YnnmMPh:b1in9sh) ([raw file](https://github.com/memkind/memkind/blob/b5b3936c2cebbda7e1597f0638a51d2a1e0823d3/tiering/ctl.c#L335)):*
> ```
> Failed to parse
> ```
Missing POLICY parameter in the query

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/629)* status: all files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[tiering/ctl.c, line 335 at r5](https://reviewable.io/reviews/memkind/memkind/629#-MZX9fNPEYe66YnnmMPg:-MZXEjFdAhqY_diYLekI:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b5b3936c2cebbda7e1597f0638a51d2a1e0823d3/tiering/ctl.c#L335)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Failed to parse
> ```
Missing POLICY parameter in the query
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/629)* status: all files reviewed, 3 unresolved discussions (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/629#-:-MZYCk--AR-Amcb0I9wP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/629)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
