### PR TITLE
Extend main.py with disabling hwloc build

### PR DESCRIPTION
**Pull request by michalbiesek**
- add option to test memkind with disable hwloc

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/487)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/487)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek and @PatKamin)

___
*[test/TestPrereq.hpp, line 186 at r1](https://reviewable.io/reviews/memkind/memkind/487#-MRslRhI2bzYSTArp2Jc:-MRslRhJ2i0OfSGVHbwN:by3ljw4) ([raw file](https://github.com/memkind/memkind/blob/77f5175e90e5bc03b1e9b678d1c679690bf76ed7/test/TestPrereq.hpp#L186)):*
> ```cpp
>     }
> 
>     bool is_KNL_supported() const
> ```

shouldn't this func be called "is_KN_family_supported" or similar?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/487)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[test/TestPrereq.hpp, line 186 at r1](https://reviewable.io/reviews/memkind/memkind/487#-MRslRhI2bzYSTArp2Jc:-MRso3ob14e9h-cVCgoc:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/77f5175e90e5bc03b1e9b678d1c679690bf76ed7/test/TestPrereq.hpp#L186)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

shouldn't this func be called "is_KN_family_supported" or similar?
</blockquote></details>

Done.

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/487#-:-MRso_kFBvUFa9E8lazN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/487)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[test/TestPrereq.hpp, line 132 at r1](https://reviewable.io/reviews/memkind/memkind/487#-MRssI-GBMgSPbwoFvb1:-MRssI-H1-5EdMlnW29m:b-9fplyi) ([raw file](https://github.com/memkind/memkind/blob/77f5175e90e5bc03b1e9b678d1c679690bf76ed7/test/TestPrereq.hpp#L132)):*
> ```cpp
>             case PMEM: {
>                 cpu_model_data_t cpu = get_cpu_model_data();
>                 return cpu.family == CPU_FAMILY_INTEL && (cpu.model == CPU_MODEL_CLX);
> ```

nit: Could be a separate method, like `is_KNL_supported()`

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/487)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[test/TestPrereq.hpp, line 132 at r1](https://reviewable.io/reviews/memkind/memkind/487#-MRssI-GBMgSPbwoFvb1:-MRt-VtKDs2FIHWATCi1:b-huk2wn) ([raw file](https://github.com/memkind/memkind/blob/77f5175e90e5bc03b1e9b678d1c679690bf76ed7/test/TestPrereq.hpp#L132)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Could be a separate method, like `is_KNL_supported()`
</blockquote></details>

Currently, there is no need to expose this as a method. See that in the case of is_KN_family_supported we are interested to check this CPU support in the test itself. I don't see know any purpose to check CLX explicitly in any of tests so I would prefer to leave it as it is.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/487#-:-MRt51-w4U8u_ReBo1R5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
