### PR TITLE
Add memkind-memory-matrix

### PR DESCRIPTION
**Pull request by michalbiesek**
Ref #440

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/447)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/447)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

___
*[utils/memkind_matrix/memory_matrix.c, line 10 at r1](https://reviewable.io/reviews/memkind/memkind/447#-MPhv5km3ZAiBnmgYSRm:-MPhv5kn1v8CwRniGd32:bhbw0t2) ([raw file](https://github.com/memkind/memkind/blob/438dbdd14815a144f33fef7c066bcdd3ff6bc6ae/utils/memkind_matrix/memory_matrix.c#L10)):*
> ```C
> #include "numa.h"
> 
> static void print_array(int *array_to_print,struct bitmask *node_mask,
> ```

nit: Add whitespace after the comma.
___
*[utils/memkind_matrix/memory_matrix.c, line 57 at r1](https://reviewable.io/reviews/memkind/memkind/447#-MPi9nCI51HQInf3sDgu:-MPi9nCJDROG-xQMlGqU:bgn31et) ([raw file](https://github.com/memkind/memkind/blob/438dbdd14815a144f33fef7c066bcdd3ff6bc6ae/utils/memkind_matrix/memory_matrix.c#L57)):*
> ```C
>     err = hwloc_topology_init(&topology);
>     if (err) {
>         printf("hwloc initialize failed");
> ```

initialization
___
*[utils/memkind_matrix/memory_matrix.c, line 92 at r1](https://reviewable.io/reviews/memkind/memkind/447#-MPiCvuF1xux64PYBH2P:-MPiCvuF1xux64PYBH2Q:bxj9vut) ([raw file](https://github.com/memkind/memkind/blob/438dbdd14815a144f33fef7c066bcdd3ff6bc6ae/utils/memkind_matrix/memory_matrix.c#L92)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>             err = hwloc_memattr_get_value(topology, HWLOC_MEMATTR_ID_BANDWIDTH, target_node,
>                                           &initiator, 0, &mem_attr);
>             if (err) {
>                 *(bandwidth_array + i*num_nodes + j) = -1;
>             } else {
>                 *(bandwidth_array + i*num_nodes + j) = mem_attr;
>             }
> ```
</details>

This  block of code could be in a separate function instead of repeating it twice.
___
*[utils/memkind_matrix/memory_matrix.c, line 128 at r1](https://reviewable.io/reviews/memkind/memkind/447#-MPhudvT7WYXowOex5vS:-MPhudvT7WYXowOex5vT:bboxkt0) ([raw file](https://github.com/memkind/memkind/blob/438dbdd14815a144f33fef7c066bcdd3ff6bc6ae/utils/memkind_matrix/memory_matrix.c#L128)):*
> ```C
> static int print_all(void)
> {
>     printf("Libhwloc is not supported");
> ```

Add \n at the end of the line. Same with other messages preceding `return` statements.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/447)* status: all files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

**Comment by michalbiesek** [comment]
@bratpiorka @PatKamin is ready to review (I update the dates since the last review) - please review. Let me know via comment ("LGTM") if I could merge this.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/447#-:-MQH8xe37TGEDfNt3QjT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[utils/memkind_matrix/memory_matrix.c, line 1 at r3](https://reviewable.io/reviews/memkind/memkind/447#-MQH5y0916SyG_FNkbX6:-MQH5y0916SyG_FNkbX7:bgzjp0o) ([raw file](https://github.com/memkind/memkind/blob/244bcefc4bc80b1597b1f02726e27ba71b52bf14/utils/memkind_matrix/memory_matrix.c#L1)):*
> ```C
> // SPDX-License-Identifier: BSD-2-Clause
> ```

Nit: Change directory name to memory_matrix.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/447)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @bratpiorka and @PatKamin)

___
*[utils/memkind_matrix/memory_matrix.c, line 10 at r1](https://reviewable.io/reviews/memkind/memkind/447#-MPhv5km3ZAiBnmgYSRm:-MQHHL8z0CgpNErQW3Sw:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/438dbdd14815a144f33fef7c066bcdd3ff6bc6ae/utils/memkind_matrix/memory_matrix.c#L10)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Add whitespace after the comma.
</blockquote></details>

Done.
___
*[utils/memkind_matrix/memory_matrix.c, line 57 at r1](https://reviewable.io/reviews/memkind/memkind/447#-MPi9nCI51HQInf3sDgu:-MQHHJmL2Zu2EtKHCKQt:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/438dbdd14815a144f33fef7c066bcdd3ff6bc6ae/utils/memkind_matrix/memory_matrix.c#L57)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

initialization
</blockquote></details>

Done.
___
*[utils/memkind_matrix/memory_matrix.c, line 92 at r1](https://reviewable.io/reviews/memkind/memkind/447#-MPiCvuF1xux64PYBH2P:-MQHHMGY8dCHvSf3ITV8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/438dbdd14815a144f33fef7c066bcdd3ff6bc6ae/utils/memkind_matrix/memory_matrix.c#L92)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

> ```
>             err = hwloc_memattr_get_value(topology, HWLOC_MEMATTR_ID_BANDWIDTH, target_node,
>                                           &initiator, 0, &mem_attr);
>             if (err) {
>                 *(bandwidth_array + i*num_nodes + j) = -1;
>             } else {
>                 *(bandwidth_array + i*num_nodes + j) = mem_attr;
>             }
> ```
This  block of code could be in a separate function instead of repeating it twice.
</blockquote></details>

Done.
___
*[utils/memkind_matrix/memory_matrix.c, line 128 at r1](https://reviewable.io/reviews/memkind/memkind/447#-MPhudvT7WYXowOex5vS:-MQHHMhR6iRdlUNYBnuK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/438dbdd14815a144f33fef7c066bcdd3ff6bc6ae/utils/memkind_matrix/memory_matrix.c#L128)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add \n at the end of the line. Same with other messages preceding `return` statements.
</blockquote></details>

Done.
___
*[utils/memkind_matrix/memory_matrix.c, line 1 at r3](https://reviewable.io/reviews/memkind/memkind/447#-MQH5y0916SyG_FNkbX6:-MQHHDo131-i0FzEJS5a:b-vvxlx4) ([raw file](https://github.com/memkind/memkind/blob/244bcefc4bc80b1597b1f02726e27ba71b52bf14/utils/memkind_matrix/memory_matrix.c#L1)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Nit: Change directory name to memory_matrix.
</blockquote></details>

Done - unified everywhere.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/447)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by PatKamin — APPROVED** [review]

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/447#-:-MQHMdox5JCkfRodgSfO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
