### PR TITLE
Skip huge pages tests when condition not met

### PR DESCRIPTION
**Pull request by PatKamin**
When running `make check` or test/test.sh directly, skip all tests which
require huge pages enabled in the system in case there are no huge pages
available.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

- - -
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/848)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/848)* status: all files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[`test/test.sh` line 258 at r1](https://reviewable.io/reviews/memkind/memkind/848#-N96MUbp8BJ-RNYFEYrq:-N96MUbp8BJ-RNYFEYrr:b-5f2i6h) ([raw file](https://github.com/memkind/memkind/blob/05d76cd46a6c0ad82138e22675271cddd3fd6d44/test/test.sh#L258)):*
> ```Shell
>         SKIPPED_GTESTS=":-*test_TC_MEMKIND_2MBPages_*:*GBPages*:*PAGE_SIZE_2MB*:*HUGETLB*:*GBTLB*"
>     else
>         SKIPPED_GTESTS=$SKIPPED_GTESTS":*test_TC_MEMKIND_2MBPages_*:*GBPages*:*PAGE_SIZE_2MB*:*HUGETLB*:*GBTLB*"
> ```

you could simplify this func and always execute "else" path
___
*[`test/test.sh` line 263 at r1](https://reviewable.io/reviews/memkind/memkind/848#-N96MeAl73BvY6Jlw6S1:-N96MeAl73BvY6Jlw6S2:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/05d76cd46a6c0ad82138e22675271cddd3fd6d44/test/test.sh#L263)):*
> ```Shell
>         SKIPPED_PYTESTS=" and not test_TC_MEMKIND_2MBPages_"
>     else
>         SKIPPED_PYTESTS=$SKIPPED_PYTESTS" and not test_TC_MEMKIND_2MBPages_"
> ```

.
___
*[`test/test.sh` line 282 at r1](https://reviewable.io/reviews/memkind/memkind/848#-N96M8YhBPubxcQ55Ywk:-N96M8YhBPubxcQ55Ywl:b-tc7f3t) ([raw file](https://github.com/memkind/memkind/blob/05d76cd46a6c0ad82138e22675271cddd3fd6d44/test/test.sh#L282)):*
> ```Shell
> check_hbw_nodes
> check_auto_dax_kmem_nodes
> check_hugepages
> ```

What if skip_hugepages_tests was called 2 times? here and in case of m) option?

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/848)* status: all files reviewed, 3 unresolved discussions (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/848)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[`test/test.sh` line 258 at r1](https://reviewable.io/reviews/memkind/memkind/848#-N96MUbp8BJ-RNYFEYrq:-N96aBXC4emKR1aVChLy:b-sihbm6) ([raw file](https://github.com/memkind/memkind/blob/05d76cd46a6c0ad82138e22675271cddd3fd6d44/test/test.sh#L258)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

you could simplify this func and always execute "else" path
</blockquote></details>

Can't, the `-` sign at the beginning is essential.
___
*[`test/test.sh` line 263 at r1](https://reviewable.io/reviews/memkind/memkind/848#-N96MeAl73BvY6Jlw6S1:-N96aBLC9zHo5uFsMJAA:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/05d76cd46a6c0ad82138e22675271cddd3fd6d44/test/test.sh#L263)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/848)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[`test/test.sh` line 258 at r1](https://reviewable.io/reviews/memkind/memkind/848#-N96MUbp8BJ-RNYFEYrq:-N9AdlXa4_Kx5O36qbU1:bow9e1m) ([raw file](https://github.com/memkind/memkind/blob/05d76cd46a6c0ad82138e22675271cddd3fd6d44/test/test.sh#L258)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Can't, the `-` sign at the beginning is essential.
</blockquote></details>

sorry, I missed this, but aren't all tests NOT skipped by default?

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/848)* status: all files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[`test/test.sh` line 258 at r1](https://reviewable.io/reviews/memkind/memkind/848#-N96MUbp8BJ-RNYFEYrq:-N9B9bcj3tCFkKEzFw4q:bksmb38) ([raw file](https://github.com/memkind/memkind/blob/05d76cd46a6c0ad82138e22675271cddd3fd6d44/test/test.sh#L258)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

sorry, I missed this, but aren't all tests NOT skipped by default? 
</blockquote></details>

ok I got explanation online
___
*[`test/test.sh` line 3 at r3](https://reviewable.io/reviews/memkind/memkind/848#-N9B8p3TAGTNR8k5ZIw_:-N9B8p3TAGTNR8k5ZIwa:blw9wj7) ([raw file](https://github.com/memkind/memkind/blob/ba886e20901e9c4eab8cdf1cf66c12787decd87a/test/test.sh#L3)):*
> ```Shell
> #!/bin/bash
> # SPDX-License-Identifier: BSD-2-Clause
> # Copyright (C) 2014 - 2021 Intel Corporation.
> ```

bump date
___
*[`test/test.sh` line 47 at r3](https://reviewable.io/reviews/memkind/memkind/848#-N9BA7El3FSCoe8C7r80:-N9BA7El3FSCoe8C7r81:b-450i7j) ([raw file](https://github.com/memkind/memkind/blob/ba886e20901e9c4eab8cdf1cf66c12787decd87a/test/test.sh#L47)):*
> ```Shell
>     -d,
>         skip high bandwidth memory nodes detection tests
>     -m,
> ```

this is done by default - you could remove this option



_Code quote:_
```Shell
    -m,
        skip tests that require huge pages configured on the machine
```

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/848)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

___
*[`test/test.sh` line 282 at r1](https://reviewable.io/reviews/memkind/memkind/848#-N96M8YhBPubxcQ55Ywk:-N9BQzEIBxfnmW-4A4M5:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/05d76cd46a6c0ad82138e22675271cddd3fd6d44/test/test.sh#L282)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

What if skip_hugepages_tests was called 2 times? here and in case of m) option?
</blockquote></details>

Done.
___
*[`test/test.sh` line 3 at r3](https://reviewable.io/reviews/memkind/memkind/848#-N9B8p3TAGTNR8k5ZIw_:-N9BO5Vx4_3-oa8GKzUg:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ba886e20901e9c4eab8cdf1cf66c12787decd87a/test/test.sh#L3)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

bump date
</blockquote></details>

Done.
___
*[`test/test.sh` line 47 at r3](https://reviewable.io/reviews/memkind/memkind/848#-N9BA7El3FSCoe8C7r80:-N9BQwooCwBYVgf5zFIV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ba886e20901e9c4eab8cdf1cf66c12787decd87a/test/test.sh#L47)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this is done by default - you could remove this option
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/848)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
