### PR TITLE
Remove initialized variable

### PR DESCRIPTION
**Pull request by michalbiesek**
- use current_kind to determine if  the library was initialized
- adjust likely/unlikely for the pointer

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/588)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/588)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[tiering/memtier.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/588#-MWTTE6SEvWe4FxDW4aO:-MWTTE6SEvWe4FxDW4aP:bgu5mhq) ([raw file](https://github.com/memkind/memkind/blob/0502de2a115fa1d6569cc8061a852cc936b402c8/tiering/memtier.c#L26)):*
> ```C
> 
> // TODO create structure to keep kind + multiple tiers
> static struct memtier_kind *current_kind;
> ```

initialize to NULL?

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/588#-:-MWTTgl8D0HsP91j03nU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/588#-:-MWTU5bBDz7lKJySzfiQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/588)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

___
*[tiering/memtier.c, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/588#-MWTTE6SEvWe4FxDW4aO:-MWTV1-400q3i4Aewqc5:bjylahz) ([raw file](https://github.com/memkind/memkind/blob/0502de2a115fa1d6569cc8061a852cc936b402c8/tiering/memtier.c#L26)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

initialize to NULL?
</blockquote></details>

Not needed - 6.7.8.10, ref: http://www.open-std.org/JTC1/sc22/wg14/www/docs/n1256.pdf

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/588)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
