### PR TITLE
Modify internal memtier API

### PR DESCRIPTION
**Pull request by michalbiesek**
- ~~Remove policy param from builder use operation abstracttion~~ #633 
- Add handling ctl in the static policy case

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/632)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/632)* status: all files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[src/memkind_memtier.c, line 504 at r1](https://reviewable.io/reviews/memkind/memkind/632#-M_K11Oa-IiETvw9VvUj:-M_K11Oa-IiETvw9VvUk:bkfptsn) ([raw file](https://github.com/memkind/memkind/blob/7e3321e1bc72bdb1ceb5a0177db05548da45c25c/src/memkind_memtier.c#L504)):*
> ```C
>             case MEMTIER_POLICY_STATIC_THRESHOLD:
>                 b->create_mem = builder_static_create_memory;
>                 b->thres = NULL;
> ```

you don't have to zero "thres" member
___
*[src/memkind_memtier.c, line 276 at r2](https://reviewable.io/reviews/memkind/memkind/632#-M_K2Le2AZ1-KfQ2c9R4:-M_K2Le2AZ1-KfQ2c9R5:btu16wk) ([raw file](https://github.com/memkind/memkind/blob/d8ce060af156bc01a96397be583650468db05964/src/memkind_memtier.c#L276)):*
> ```
> threshold_var
> ```

where do you call this function with "threshold_var" set to true?
___
*[src/memkind_memtier.c, line 547 at r2](https://reviewable.io/reviews/memkind/memkind/632#-M_K2oqY9yekiTTcLWva:-M_K2oqZARyOuhqVN7qE:bgvnne5) ([raw file](https://github.com/memkind/memkind/blob/d8ce060af156bc01a96397be583650468db05964/src/memkind_memtier.c#L547)):*
> ```
> _dynamic_th
> ```

IMHO we could copy contents of memtier_policy_dynamic_threshold_construct_memtier_memory here since this is the only place where it is called and both of them are necessary

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/632)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

___
*[src/memkind_memtier.c, line 504 at r1](https://reviewable.io/reviews/memkind/memkind/632#-M_K11Oa-IiETvw9VvUj:-M_K53OBBkSCXeqJAJO5:bioukda) ([raw file](https://github.com/memkind/memkind/blob/7e3321e1bc72bdb1ceb5a0177db05548da45c25c/src/memkind_memtier.c#L504)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

you don't have to zero "thres" member
</blockquote></details>

I split this PR into two parts (I address this in #633)
FYI I prefer to have an implementation which confirms standard:
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf -> 7.22.3.2 (footnote)
___
*[src/memkind_memtier.c, line 276 at r2](https://reviewable.io/reviews/memkind/memkind/632#-M_K2Le2AZ1-KfQ2c9R4:-M_K7ZNs6S8dqMwvT8sk:bhtah1k) ([raw file](https://github.com/memkind/memkind/blob/d8ce060af156bc01a96397be583650468db05964/src/memkind_memtier.c#L276)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> ```
> threshold_var
> ```

where do you call this function with "threshold_var" set to true?
</blockquote></details>

I split this PR into two parts (I address this in #633)
___
*[src/memkind_memtier.c, line 547 at r2](https://reviewable.io/reviews/memkind/memkind/632#-M_K2oqY9yekiTTcLWva:-M_K7r6h1OO_Smc6fAG0:bhtah1k) ([raw file](https://github.com/memkind/memkind/blob/d8ce060af156bc01a96397be583650468db05964/src/memkind_memtier.c#L547)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> ```
> _dynamic_th
> ```

IMHO we could copy contents of memtier_policy_dynamic_threshold_construct_memtier_memory here since this is the only place where it is called and both of them are necessary 
</blockquote></details>

I split this PR into two parts (I address this in #633)

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/632)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @bratpiorka)

___
*[src/memkind_memtier.c, line 504 at r1](https://reviewable.io/reviews/memkind/memkind/632#-M_K11Oa-IiETvw9VvUj:-M_L4pV80lm1A0669bZG:b-3rvo7a) ([raw file](https://github.com/memkind/memkind/blob/7e3321e1bc72bdb1ceb5a0177db05548da45c25c/src/memkind_memtier.c#L504)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

I split this PR into two parts (I address this in #633)
FYI I prefer to have an implementation which confirms standard:
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf -> 7.22.3.2 (footnote)

</blockquote></details>

interesting, thanks for the link

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/632#-:-M_L5HmV9kXPqSZ9mZk-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/632)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/632#-:-M_PynT95COvOlpX6XKw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
