### PR TITLE
Add py.test instalation to QEMU image configuration

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/498)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/498)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

___
*[utils/qemu/ubuntu-packer.json, line 64 at r1](https://reviewable.io/reviews/memkind/memkind/498#-MS3U919AZkqpWFm_N4n:-MS3U919AZkqpWFm_N4o:b-1hm956) ([raw file](https://github.com/memkind/memkind/blob/22d9b9fefb92adfcbd6d44c209edb430d599e027/utils/qemu/ubuntu-packer.json#L64)):*
> ```
> pkg-config uuid-dev
> ```
pkg-config python3-pip uuid-dev
___
*[utils/qemu/ubuntu-packer.json, line 65 at r1](https://reviewable.io/reviews/memkind/memkind/498#-MS3U-7p4kNkCu35jZDp:-MS3U-7p4kNkCu35jZDq:b-3spb0b) ([raw file](https://github.com/memkind/memkind/blob/22d9b9fefb92adfcbd6d44c209edb430d599e027/utils/qemu/ubuntu-packer.json#L65)):*
> ```
> pip
> ```
you don't have pip installed in this OS by default.
___
*[utils/qemu/ubuntu-packer.json, line 65 at r1](https://reviewable.io/reviews/memkind/memkind/498#-MS3UJzq8nK7Fd-wKHM7:-MS3UJzq8nK7Fd-wKHM8:bj45wgw) ([raw file](https://github.com/memkind/memkind/blob/22d9b9fefb92adfcbd6d44c209edb430d599e027/utils/qemu/ubuntu-packer.json#L65)):*
> ```
> sudo pip install --upgrade pip && sudo pip install wheel && sudo pip install pytest==3.9.2
> ```
sudo pip3 install pytest==3.9.2

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/498)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[utils/qemu/ubuntu-packer.json, line 64 at r1](https://reviewable.io/reviews/memkind/memkind/498#-MS3U919AZkqpWFm_N4n:-MS3hkLp-QoafcwOp76l:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/22d9b9fefb92adfcbd6d44c209edb430d599e027/utils/qemu/ubuntu-packer.json#L64)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> pkg-config uuid-dev
> ```
pkg-config python3-pip uuid-dev
</blockquote></details>

Done.
___
*[utils/qemu/ubuntu-packer.json, line 65 at r1](https://reviewable.io/reviews/memkind/memkind/498#-MS3U-7p4kNkCu35jZDp:-MS3hmW7-yCiMCn3R3Kn:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/22d9b9fefb92adfcbd6d44c209edb430d599e027/utils/qemu/ubuntu-packer.json#L65)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> pip
> ```
you don't have pip installed in this OS by default.
</blockquote></details>

Done.
___
*[utils/qemu/ubuntu-packer.json, line 65 at r1](https://reviewable.io/reviews/memkind/memkind/498#-MS3UJzq8nK7Fd-wKHM7:-MS3hngx3KeoNZQxUmRQ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/22d9b9fefb92adfcbd6d44c209edb430d599e027/utils/qemu/ubuntu-packer.json#L65)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> sudo pip install --upgrade pip && sudo pip install wheel && sudo pip install pytest==3.9.2
> ```
sudo pip3 install pytest==3.9.2
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/498)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[utils/qemu/ubuntu-packer.json, line 64 at r1](https://reviewable.io/reviews/memkind/memkind/498#-MS3U919AZkqpWFm_N4n:-MS6rMdp0S7fJc-m9XBm:buvl8ae) ([raw file](https://github.com/memkind/memkind/blob/22d9b9fefb92adfcbd6d44c209edb430d599e027/utils/qemu/ubuntu-packer.json#L64)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope.
I think you push force 2 times - the second time restores the first revision.
" force-pushed the bratpiorka:hmat-devel_hmat_pytest branch from 976e4ca to 22d9b9f "
Commit 976e4ca looks like the one with expected changes.

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/498)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[utils/qemu/ubuntu-packer.json, line 64 at r1](https://reviewable.io/reviews/memkind/memkind/498#-MS3U919AZkqpWFm_N4n:-MS71lpC04z3K_El6HBC:b-p15ve0) ([raw file](https://github.com/memkind/memkind/blob/22d9b9fefb92adfcbd6d44c209edb430d599e027/utils/qemu/ubuntu-packer.json#L64)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Nope.
I think you push force 2 times - the second time restores the first revision.
" force-pushed the bratpiorka:hmat-devel_hmat_pytest branch from 976e4ca to 22d9b9f "
Commit 976e4ca looks like the one with expected changes.
</blockquote></details>

You are right. Now I pushed correct version

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
