### PR TITLE
Feat static ratio tests

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/606)

### CODE REVIEW

**Comment by bratpiorka** [comment]
requires #605

**Comment by michalbiesek** [comment]
Rebase and please uncomment test which required #604

**Review by bratpiorka — COMMENTED** [review]
@michalbiesek which test? There are no commented tests in tiering_tests.py or memkind_memtier_test.cpp

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/606#-:-MX69vleCWMvxiVPiYKt:b8bd06m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek and @PatKamin)

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/606)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[test/memkind_memtier_test.cpp, line 808 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX6oOT_-r9QUsQJ8a94:-MX6oOT_-r9QUsQJ8a95:b42dxs) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/test/memkind_memtier_test.cpp#L808)):*
> ```cpp
>     ASSERT_EQ(0ULL, allocs.size());
> }
> ```

Can you tell me what is behavior/provide to test to cover this:
- 3 tiers 3:1:5
- allocate only on tier_2  - using memtier_tier_malloc
- after finish allocation on tier_2:
- change allocation for memtier_kind_malloc

Will the allocation go with a switching pattern between tier_1 and tier_3 or will fulfill last one?

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/606)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/606)* status: all files reviewed, 6 unresolved discussions (waiting on @bratpiorka)

___
*[src/memkind_memtier.c, line 198 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7FVS_7hEAI0Fzpu7-:-MX7FVS_7hEAI0Fzpu70:brseshh) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/src/memkind_memtier.c#L198)):*
> ```C
>     }
> 
>     // perform deep copy but store normalized (to tier[0] ratio instead of
> ```

Revert this change with the closing bracket.
___
*[test/memkind_memtier_test.cpp, line 67 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7FoP_D0Aa5QKgPuY7:-MX7FoP_D0Aa5QKgPuY8:bo37s0t) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/test/memkind_memtier_test.cpp#L67)):*
> ```cpp
> };
> 
> class MemkindMemtier3KindAdvancedTest: public ::testing::Test
> ```

Word "advanced" is unnecessary.
___
*[test/memkind_memtier_test.cpp, line 67 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7Ft2W9L0pT3uos8fI:-MX7Ft2W9L0pT3uos8fJ:bjm9po1) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/test/memkind_memtier_test.cpp#L67)):*
> ```cpp
> };
> 
> class MemkindMemtier3KindAdvancedTest: public ::testing::Test
> ```

3Kinds
___
*[test/memkind_memtier_test.cpp, line 811 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7JWfD6u8Wclkd8Qew:-MX7JWfD6u8Wclkd8Qex:b-7qjbm1) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/test/memkind_memtier_test.cpp#L811)):*
> ```cpp
> TEST_F(MemkindMemtier3KindAdvancedTest, test_ratio_malloc_only)
> {
>     const int tier_regular_normalized_ratio =
> ```

float
___
*[test/memkind_memtier_test.cpp, line 817 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7KTmX6zLUsQNks4n_:-MX7KTmX6zLUsQNks4na:b-t5rrox) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/test/memkind_memtier_test.cpp#L817)):*
> ```cpp
>     const int sizes_num = 10;
>     const size_t sizes[sizes_num] = {16, 32, 16, 64, 16, 128, 32, 256, 64, 128};
>     size_t num_allocs = 200;
> ```

nit: unsigned
___
*[test/memkind_memtier_test.cpp, line 819 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7KYJJ8ueURnTWKlmg:-MX7KHUZ3KsMNX-Y8r-s:b-t5rrox) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/test/memkind_memtier_test.cpp#L819)):*
> ```cpp
>     size_t num_allocs = 200;
>     std::vector<void *> allocs;
>     size_t i;
> ```

nit: unsigned

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/606)* status: all files reviewed, 7 unresolved discussions (waiting on @bratpiorka)

___
*[test/memkind_memtier_test.cpp, line 842 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7RCLJAXmi2bHps3Sj:-MX7RCLK2mN-6L3_tglx:b-3vg1ry) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/test/memkind_memtier_test.cpp#L842)):*
> ```cpp
>         if (tier_regular_actual_ratio < tier_regular_normalized_ratio) {
>             ASSERT_GE(memtier_tier_allocated_size(m_tier_regular),
>                       hi_cap_alloc_size);
> ```

My bad, ignore my last comment. There should be check `ASSERT_GT (memtier_tier_allocated_size(m_tier_regular), regular_alloc_size);`, though.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/606)* status: all files reviewed, 5 unresolved discussions (waiting on @PatKamin)

___
*[src/memkind_memtier.c, line 198 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7FVS_7hEAI0Fzpu7-:-MX7XkIn7hpsLdPsIcYV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/src/memkind_memtier.c#L198)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Revert this change with the closing bracket.
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 67 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7FoP_D0Aa5QKgPuY7:-MX7YbEg5pfGIFkQrAdR:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/test/memkind_memtier_test.cpp#L67)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Word "advanced" is unnecessary.
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 67 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7Ft2W9L0pT3uos8fI:-MX7YbUF6o8zhCyMlN3F:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/test/memkind_memtier_test.cpp#L67)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

3Kinds
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 811 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7JWfD6u8Wclkd8Qew:-MX7Xi4eAq6fq7L4qeXY:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/test/memkind_memtier_test.cpp#L811)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

float
</blockquote></details>

Done.
___
*[test/memkind_memtier_test.cpp, line 842 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7RCLJAXmi2bHps3Sj:-MX7Xj1yBIJ8R8GyKd7Q:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/test/memkind_memtier_test.cpp#L842)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

My bad, ignore my last comment. There should be check `ASSERT_GT (memtier_tier_allocated_size(m_tier_regular), regular_alloc_size);`, though.
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/606)* status: all files reviewed, 5 unresolved discussions (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/606#-:-MX7g1ab9FgiDHotXskx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/memkind_memtier.c, line 198 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7FVS_7hEAI0Fzpu7-:-MX7ewAdAxzS4SwGXK0C:bd2ohwc) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/src/memkind_memtier.c#L198)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: I don't see any change.

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/606)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[src/memkind_memtier.c, line 198 at r5](https://reviewable.io/reviews/memkind/memkind/606#-MX7FVS_7hEAI0Fzpu7-:-MX7h1u53mXKPg3pWbBI:bfe4vx0) ([raw file](https://github.com/memkind/memkind/blob/c2e69cc781841e3a583bac319218a681b3eed629/src/memkind_memtier.c#L198)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: I don't see any change.
</blockquote></details>

Done. I reverted all changes in this file

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/606)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
