### PR TITLE
Migrate to GH actions

### PR DESCRIPTION
**Pull request by michalbiesek**
- remove Travis configuration

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/455)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/455)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[.github/workflows/gha.yml, line 12 at r1](https://reviewable.io/reviews/memkind/memkind/455#-MR4b8G82vY48hk6wfEJ:-MR4b8G82vY48hk6wfEK:b-cfo84n) ([raw file](https://github.com/memkind/memkind/blob/a96a004d81ea2e32df780c8bebd733fa169c28d1/.github/workflows/gha.yml#L12)):*
> ```YAML
>       uses: actions/checkout@v2
>       with:
>         fetch-depth: 0
> ```

nit: Why not fetching only the latest commit?
___
*[.github/workflows/gha.yml, line 14 at r1](https://reviewable.io/reviews/memkind/memkind/455#-MR4ZIZZ0KmYDXIZNfe6:-MR4ZIZ_3JpEy8Zg2J19:b-v14iyu) ([raw file](https://github.com/memkind/memkind/blob/a96a004d81ea2e32df780c8bebd733fa169c28d1/.github/workflows/gha.yml#L14)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>       uses: actions/checkout@v2
>       with:
>         fetch-depth: 0
>           packages:
>             - astyle
> ```
</details>

nit: add whitespaces to align this with `name:`

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/455)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[.github/workflows/gha.yml, line 12 at r1](https://reviewable.io/reviews/memkind/memkind/455#-MR4b8G82vY48hk6wfEJ:-MS8BNZy9v7P4Gr3V0_y:b-njhc95) ([raw file](https://github.com/memkind/memkind/blob/a96a004d81ea2e32df780c8bebd733fa169c28d1/.github/workflows/gha.yml#L12)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Why not fetching only the latest commit?
</blockquote></details>

I need to fetch all tags for build.sh
___
*[.github/workflows/gha.yml, line 43 at r2](https://reviewable.io/reviews/memkind/memkind/455#-MS8BSZX8pzu0j7EDM4k:-MS8BSZX8pzu0j7EDM4l:b-ds2lv) ([raw file](https://github.com/memkind/memkind/blob/6f8da1e9d80363de7473c43f8841f4b31cbc3741/.github/workflows/gha.yml#L43)):*
> ```YAML
> 
>     - name: Install basic dependencies
>       run: sudo apt install autoconf libnuma-dev
> ```

The status is available on my fork:
https://github.com/michalbiesek/memkind/actions/runs/518074029

**Review by PatKamin — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/455)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[.github/workflows/gha.yml, line 7 at r2](https://reviewable.io/reviews/memkind/memkind/455#-MS8Kb-K01ufuv2332gq:-MS8Kb-K01ufuv2332gr:b-glbsvn) ([raw file](https://github.com/memkind/memkind/blob/6f8da1e9d80363de7473c43f8841f4b31cbc3741/.github/workflows/gha.yml#L7)):*
> ```YAML
> 
>   linting:
>     runs-on: ubuntu-18.04
> ```

You're using ubuntu-20.04 image for building. Why not using it here? 
___
*[.github/workflows/gha.yml, line 50 at r2](https://reviewable.io/reviews/memkind/memkind/455#-MS8MK1o8YiNKV4chq2w:-MS8MK1pDPfuMI0G6HSU:b-oxiu34) ([raw file](https://github.com/memkind/memkind/blob/6f8da1e9d80363de7473c43f8841f4b31cbc3741/.github/workflows/gha.yml#L50)):*
> ```YAML
>               sudo apt install libdaxctl-dev
>           else
>             echo "Skipped install daxtl phase"
> ```

Skipping daxctl installation

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/455)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[.github/workflows/gha.yml, line 7 at r2](https://reviewable.io/reviews/memkind/memkind/455#-MS8Kb-K01ufuv2332gq:-MS8SXhF-pskMjfo6tWf:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6f8da1e9d80363de7473c43f8841f4b31cbc3741/.github/workflows/gha.yml#L7)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

You're using ubuntu-20.04 image for building. Why not using it here? 
</blockquote></details>

Done.
___
*[.github/workflows/gha.yml, line 50 at r2](https://reviewable.io/reviews/memkind/memkind/455#-MS8MK1o8YiNKV4chq2w:-MS8S_i69TerEkOyuUER:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6f8da1e9d80363de7473c43f8841f4b31cbc3741/.github/workflows/gha.yml#L50)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Skipping daxctl installation
</blockquote></details>

Done.

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/455#-:-MS8Syr5CDAprNFLS9oZ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[.github/workflows/gha.yml, line 43 at r2](https://reviewable.io/reviews/memkind/memkind/455#-MS8BSZX8pzu0j7EDM4k:-MS8SusXAf87laO2ILdb:b32w0x) ([raw file](https://github.com/memkind/memkind/blob/6f8da1e9d80363de7473c43f8841f4b31cbc3741/.github/workflows/gha.yml#L43)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

The status is available on my fork:
https://github.com/michalbiesek/memkind/actions/runs/518074029
</blockquote></details>

OK

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/455#-:-MS8cZAF7q7DCV74Xe9D:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Pull request merged**
