### PR TITLE
Feat hmat xml

### PR DESCRIPTION
**Pull request by michalbiesek**
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/466)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/466)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[test/memkind_hmat_tests.cpp, line 39 at r1](https://reviewable.io/reviews/memkind/memkind/466#-MRK_Q7S-HPRxvroop2S:-MRK_Q7S-HPRxvroop2T:b-zesutf) ([raw file](https://github.com/memkind/memkind/blob/1ed423bff7ef18e60c84de96f3e61d7e8c38faf2/test/memkind_hmat_tests.cpp#L39)):*
> ```cpp
>         if (TopologyMap.size() == 0) {
>             //TODO find better way to lookup for number of classes
>             TopologyMap.reserve(11);
> ```

Do we really need reserving space for topologies? If not, IMHO we could remove this
___
*[utils/qemu/topology/clx_2_var1_hmat.xml, line 40 at r1](https://reviewable.io/reviews/memkind/memkind/466#-MRKbo1bDYDm5cJpIt2L:-MRKbo1bDYDm5cJpIt2M:b-sljgcm) ([raw file](https://github.com/memkind/memkind/blob/1ed423bff7ef18e60c84de96f3e61d7e8c38faf2/utils/qemu/topology/clx_2_var1_hmat.xml#L40)):*
> ```XML
>         <latency initiator='0' target='2' type='access' value='176'/>
>         <latency initiator='1' target='1' type='access' value='72'/>
>         <latency initiator='1' target='2' type='access' value='240'/>
> ```

using bandwidth data from MLC:

        <latency initiator='0' target='0' type='access' value='72'/>
        <bandwidth initiator='0' target='0' type='access' value='111395' unit='MiB'/>
        <latency initiator='0' target='1' type='access' value='133'/>
        <bandwidth initiator='0' target='1' type='access' value='33778' unit='MiB'/>
        <latency initiator='0' target='2' type='access' value='176'/>
        <bandwidth initiator='0' target='2' type='access' value='25607' unit='MiB'/>
        <latency initiator='1' target='1' type='access' value='72'/>
        <bandwidth initiator='1' target='1' type='access' value='33773' unit='MiB'/>
        <latency initiator='1' target='2' type='access' value='240'/>
        <bandwidth initiator='1' target='2' type='access' value='840' unit='MiB'/>

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/466)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @bratpiorka)

___
*[test/memkind_hmat_tests.cpp, line 39 at r1](https://reviewable.io/reviews/memkind/memkind/466#-MRK_Q7S-HPRxvroop2S:-MRKuoucC39bSu18zfZO:bho3u3h) ([raw file](https://github.com/memkind/memkind/blob/1ed423bff7ef18e60c84de96f3e61d7e8c38faf2/test/memkind_hmat_tests.cpp#L39)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Do we really need reserving space for topologies? If not, IMHO we could remove this
</blockquote></details>

I prefer to keep this reserve method
___
*[utils/qemu/topology/clx_2_var1_hmat.xml, line 40 at r1](https://reviewable.io/reviews/memkind/memkind/466#-MRKbo1bDYDm5cJpIt2L:-MRLC3kz872LVHGtASvu:b2jwvez) ([raw file](https://github.com/memkind/memkind/blob/1ed423bff7ef18e60c84de96f3e61d7e8c38faf2/utils/qemu/topology/clx_2_var1_hmat.xml#L40)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

using bandwidth data from MLC:

        <latency initiator='0' target='0' type='access' value='72'/>
        <bandwidth initiator='0' target='0' type='access' value='111395' unit='MiB'/>
        <latency initiator='0' target='1' type='access' value='133'/>
        <bandwidth initiator='0' target='1' type='access' value='33778' unit='MiB'/>
        <latency initiator='0' target='2' type='access' value='176'/>
        <bandwidth initiator='0' target='2' type='access' value='25607' unit='MiB'/>
        <latency initiator='1' target='1' type='access' value='72'/>
        <bandwidth initiator='1' target='1' type='access' value='33773' unit='MiB'/>
        <latency initiator='1' target='2' type='access' value='240'/>
        <bandwidth initiator='1' target='2' type='access' value='840' unit='MiB'/>
</blockquote></details>

Done I approximate a little bit but done.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/466)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 8 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/466#-:-MRP5XLv0JJwt2PVk8oN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
