### PR TITLE
Remove non-functional code for 1GB pages.

### PR DESCRIPTION
**Pull request by kilobyte**
The code and tests have been deprecated in 2016, removed in early 2017, leaving just stubs that checked alignment but did nothing useful.

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/776)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: all files reviewed, 1 unresolved discussion (waiting on @kilobyte)

___
*[include/memkind_deprecated.h, line 46 at r1](https://reviewable.io/reviews/memkind/memkind/776#-MylQl1666HnekSWPIds:-MylQl1666HnekSWPIdt:b5xcupc) ([raw file](https://github.com/memkind/memkind/blob/844ab4a5fd3b6b6d7e71043858acb57c78ccb9a2/include/memkind_deprecated.h#L46)):*
> ```objc
>     MEMKIND_PARTITION_HBW_PREFERRED_HUGETLB = 4,
>     MEMKIND_PARTITION_HUGETLB = 5,
>     MEMKIND_PARTITION_HBW_INTERLEAVE = 9,
> ```

if we don't re-enumarate these items, we should comment-out old values and add a comment?

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: 30 of 31 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[include/memkind_deprecated.h, line 46 at r1](https://reviewable.io/reviews/memkind/memkind/776#-MylQl1666HnekSWPIds:-Mz5Uste-x1LKdU8CUTr:bq60le6) ([raw file](https://github.com/memkind/memkind/blob/844ab4a5fd3b6b6d7e71043858acb57c78ccb9a2/include/memkind_deprecated.h#L46)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

if we don't re-enumarate these items, we should comment-out old values and add a comment?
</blockquote></details>

They can be reused without much issue, thus I've only added a comment.

Also, no one is supposed to even use these enums, it's long-deprecated code that should be removed.  Alas, the TBB wrapper is a bit entangled with it, that's why this pull request doesn't remove these enums yet.

**Review by maciekpac — COMMENTED** [review]
> Reviewed 30 of 31 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: 29 of 35 files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[-- commits, line 8 at r3](https://reviewable.io/reviews/memkind/memkind/776#-MzJqMnXCs29uEzaq_69):*
This sentence sounds strange and I'm not sure if the meaning is correct.
___
*[include/memkind/internal/memkind_private.h, line 115 at r3](https://reviewable.io/reviews/memkind/memkind/776#-MzJqvjjDMYcDYz_sOze:-MzJqvjjDMYcDYz_sOzf:b-grsqp7) ([raw file](https://github.com/memkind/memkind/blob/b953b50a31ceb4ab2e23841ec7b001096c50e346/include/memkind/internal/memkind_private.h#L115)):*
> ```objc
> char *memkind_get_env(const char *name);
> 
> struct memkind *memkind_kind_by_priv(void *ptr);
> ```

maybe some comment/annotation about what the void *ptr should be ? E.g. "@ptr is equal to the ```priv``` field of the returned memkind_registry_g.partition_map[i]" or "@ptr pointer to the ```priv``` field of the returned memkind_registry_g.partition_map[i]" or, shortly,  "@ptr pointer to the ```priv``` field"
___
*[src/tbb_wrapper.c, line 176 at r3](https://reviewable.io/reviews/memkind/memkind/776#-MzJsOkwCqiR5nCjfhM6:-MzJsOkx76OMuYypGYY0:blvyolg) ([raw file](https://github.com/memkind/memkind/blob/b953b50a31ceb4ab2e23841ec7b001096c50e346/src/tbb_wrapper.c#L176)):*
> ```C
> struct memkind *tbb_detect_kind(void *ptr)
> {
>     if (!ptr) {
> ```

I think this check is redundant (```memkind_kind_by_priv``` should handle NULL values well), but it can stay here - might work slightly quicker in some scenarios with this check. Was that the purpose of leaving it here ?
___
*[test/trial_generator.cpp, line 169 at r2](https://reviewable.io/reviews/memkind/memkind/776#-MzJpY530WvQcficFF7g:-MzJpY530WvQcficFF7h:bcd9ena) ([raw file](https://github.com/memkind/memkind/blob/54a835cd095033a6eff157c3532002f8ca9f41f9/test/trial_generator.cpp#L169)):*
> ```cpp
>                     psize = HBW_PAGESIZE_4KB;
>                 else if (trial_vec[i].page_size == 2097152)
>                     psize = HBW_PAGESIZE_2MB;
> ```

are 2 MB pagesizes removed ? or just the related testcase ?

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, 2 of 2 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: all files reviewed, 6 unresolved discussions (waiting on @kilobyte and @PatKamin)

___
*[include/memkind/internal/memkind_private.h, line 50 at r5](https://reviewable.io/reviews/memkind/memkind/776#-MzPA8e4E4_arsJc4yiW:-MzPA8e4E4_arsJc4yiX:b-eaz8pb) ([raw file](https://github.com/memkind/memkind/blob/b0afb50528834df2e9d058c1b08583d9c911f4d1/include/memkind/internal/memkind_private.h#L50)):*
> ```objc
> 
> // Number of static kinds.
> #define MEMKIND_NUM_BASE_KIND 23
> ```

Do we need to define it? If so, could be do this close to definition of kinds list? Maybe we could generate this value?
___
*[src/memkind.c, line 269 at r5](https://reviewable.io/reviews/memkind/memkind/776#-MzPApiv0hfNyRj91t2D:-MzPApiv0hfNyRj91t2E:bu5mbxp) ([raw file](https://github.com/memkind/memkind/blob/b0afb50528834df2e9d058c1b08583d9c911f4d1/src/memkind.c#L269)):*
> ```C
>         &MEMKIND_HIGHEST_BANDWIDTH_LOCAL_PREFERRED_STATIC,
>     },
>     MEMKIND_NUM_BASE_KIND,
> ```

can't we use sizeof partition map instead of this magic number?

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: all files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @maciekpac, @PatKamin, and @ptr)

___
*[-- commits, line 8 at r3](https://reviewable.io/reviews/memkind/memkind/776#-MzJqMnXCs29uEzaq_69):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

This sentence sounds strange and I'm not sure if the meaning is correct.
</blockquote></details>

Not sure what do you mean.  I believe my use is correct (see eg. [wiktionary](https://en.wiktionary.org/wiki/wean)) and it's a medium-popularity tech idiom, guessable even if you haven't heard it before.
___
*[include/memkind/internal/memkind_private.h, line 115 at r3](https://reviewable.io/reviews/memkind/memkind/776#-MzJqvjjDMYcDYz_sOze:-MzQZuE85u79RtUhe-Os:b-1ia9wl) ([raw file](https://github.com/memkind/memkind/blob/b953b50a31ceb4ab2e23841ec7b001096c50e346/include/memkind/internal/memkind_private.h#L115)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

maybe some comment/annotation about what the void *ptr should be ? E.g. "@ptr is equal to the ```priv``` field of the returned memkind_registry_g.partition_map[i]" or "@ptr pointer to the ```priv``` field of the returned memkind_registry_g.partition_map[i]" or, shortly,  "@ptr pointer to the ```priv``` field"
</blockquote></details>

I  gave it a more descriptive name, despite `tbb_detect_kind()` still using `ptr` internally.
___
*[include/memkind/internal/memkind_private.h, line 50 at r5](https://reviewable.io/reviews/memkind/memkind/776#-MzPA8e4E4_arsJc4yiW:-MzQXXgmAsEfgEcn3lBE:b993sj4) ([raw file](https://github.com/memkind/memkind/blob/b0afb50528834df2e9d058c1b08583d9c911f4d1/include/memkind/internal/memkind_private.h#L50)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Do we need to define it? If so, could be do this close to definition of kinds list? Maybe we could generate this value?
</blockquote></details>

Alas, with no centralized list, there's no place to generate it as easy anymore.  Maybe at runtime?
___
*[src/memkind.c, line 269 at r5](https://reviewable.io/reviews/memkind/memkind/776#-MzPApiv0hfNyRj91t2D:-MzQXwbH0kythdmpJJKz:b-tgkfvb) ([raw file](https://github.com/memkind/memkind/blob/b0afb50528834df2e9d058c1b08583d9c911f4d1/src/memkind.c#L269)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

can't we use sizeof partition map instead of this magic number?
</blockquote></details>

sizeof partition_map leaves space for dynamic kinds.
___
*[src/tbb_wrapper.c, line 176 at r3](https://reviewable.io/reviews/memkind/memkind/776#-MzJsOkwCqiR5nCjfhM6:-MzQZF5f3IhJg1SF1F3H:b-7trbgl) ([raw file](https://github.com/memkind/memkind/blob/b953b50a31ceb4ab2e23841ec7b001096c50e346/src/tbb_wrapper.c#L176)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think this check is redundant (```memkind_kind_by_priv``` should handle NULL values well), but it can stay here - might work slightly quicker in some scenarios with this check. Was that the purpose of leaving it here ?
</blockquote></details>

`memkind_kind_by_priv` would return some unrelated kind that doesn't use the `priv` pointer.
___
*[test/trial_generator.cpp, line 169 at r2](https://reviewable.io/reviews/memkind/memkind/776#-MzJpY530WvQcficFF7g:-MzQYn4h699V-3Thpa7c:b-yq0ymx) ([raw file](https://github.com/memkind/memkind/blob/54a835cd095033a6eff157c3532002f8ca9f41f9/test/trial_generator.cpp#L169)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

are 2 MB pagesizes removed ? or just the related testcase ?
</blockquote></details>

It's just the if that's removed — if the page size is not 4KB, it is assumed to be 2MB, just like the old code assumed 1GB_STRICT.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 7 of 7 files at r6, 2 of 2 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: all files reviewed, 6 unresolved discussions (waiting on @bratpiorka, @maciekpac, @PatKamin, and @ptr)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[test/trial_generator.cpp, line 169 at r2](https://reviewable.io/reviews/memkind/memkind/776#-MzJpY530WvQcficFF7g:-MzVqxyPCKx_EM0YXXv1:b-hmv3s5) ([raw file](https://github.com/memkind/memkind/blob/54a835cd095033a6eff157c3532002f8ca9f41f9/test/trial_generator.cpp#L169)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

It's just the if that's removed — if the page size is not 4KB, it is assumed to be 2MB, just like the old code assumed 1GB_STRICT.
</blockquote></details>

I think an explicit check would be more readable, but ok.

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[test/trial_generator.cpp, line 169 at r2](https://reviewable.io/reviews/memkind/memkind/776#-MzJpY530WvQcficFF7g:-MzVuB-ICYvLtXPsEyxW:b-scf4qt) ([raw file](https://github.com/memkind/memkind/blob/54a835cd095033a6eff157c3532002f8ca9f41f9/test/trial_generator.cpp#L169)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think an explicit check would be more readable, but ok.
</blockquote></details>

Kind of hard to find something to do when the check fails.

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r9, 4 of 4 files at r10, 2 of 2 files at r11, 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: all files reviewed, 1 unresolved discussion (waiting on @kilobyte and @PatKamin)

___
*[`include/memkind/internal/memkind_private.h` line 50 at r12](https://reviewable.io/reviews/memkind/memkind/776#-N1cLVu40tsBT9FT7GVl:-N1cLVu40tsBT9FT7GVm:bwnudre) ([raw file](https://github.com/memkind/memkind/blob/5472fae332f7bb888538fadf99cf8a2741f29cad/include/memkind/internal/memkind_private.h#L50)):*
> ```objc
> 
> // Number of static kinds.
> #define MEMKIND_NUM_BASE_KIND 23
> ```

could you rename this to "MEMKIND_NUM_STATIC_KINDS" and move it close to static kinds definition?

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: 33 of 36 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[`include/memkind/internal/memkind_private.h` line 50 at r12](https://reviewable.io/reviews/memkind/memkind/776#-N1cLVu40tsBT9FT7GVl:-N1gxe-35OHvux1sSGal:bvkecrf) ([raw file](https://github.com/memkind/memkind/blob/5472fae332f7bb888538fadf99cf8a2741f29cad/include/memkind/internal/memkind_private.h#L50)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

could you rename this to "MEMKIND_NUM_STATIC_KINDS" and move it close to static kinds definition?
</blockquote></details>

Renamed.

Alas, can't move the define as it's used from different .c files, and it's the only related thing in the .h

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 31 files at r1, 2 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: 35 of 36 files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @kilobyte)

___
*[`man/hbwmalloc.3` line 222 at r12](https://reviewable.io/reviews/memkind/memkind/776#-N1gvlHE8WcFlvk6Bs30:-N1gvlHE8WcFlvk6Bs31:b-y73pcn) ([raw file](https://github.com/memkind/memkind/blob/5472fae332f7bb888538fadf99cf8a2741f29cad/man/hbwmalloc.3#L222)):*
> ```Roff
> .TP
> .BR Note:
> .BR HBW_PAGESIZE_2MB
> ```

Combine this note with the previous one in a common section `Notes:`
___
*[`src/hbwmalloc.c` line 244 at r12](https://reviewable.io/reviews/memkind/memkind/776#-N1gwK0i9RnL1ob4Wmsj:-N1gwK0j2m4mA7FGGMCB:btggzes) ([raw file](https://github.com/memkind/memkind/blob/5472fae332f7bb888538fadf99cf8a2741f29cad/src/hbwmalloc.c#L244)):*
> ```C
>         hbw_get_policy() == HBW_POLICY_INTERLEAVE) {
> 
>         log_err("HBW_POLICY_INTERLEAVE is unsupported with used page size!");
> ```

with 2MB page size
___
*[`test/test.sh` line 13 at r13](https://reviewable.io/reviews/memkind/memkind/776#-N1gyLBa4RMsLlz6h37j:-N1gyLBb66_agImSoOSK:b-450ueo) ([raw file](https://github.com/memkind/memkind/blob/1e2023398b39703c379851d784fa81e41fc88260/test/test.sh#L13)):*
> ```Shell
> # Gtest binaries executed by Berta
> # TODO add allocator_perf_tool_tests binary to independent sh script
> GTEST_BINARIES=(all_tests decorator_test \
> ```

nit: Rebalance these two lines for better readability.

**Review by PatKamin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: 35 of 36 files reviewed, 5 unresolved discussions (waiting on @bratpiorka and @kilobyte)

___
*[`src/memkind.c` line 269 at r14](https://reviewable.io/reviews/memkind/memkind/776#-N1hkhxyDbmi_XYYjWaP:-N1hkhxyDbmi_XYYjWaQ:b-60ahs4) ([raw file](https://github.com/memkind/memkind/blob/330013f83d496f99025b9ba15907edc3066b5819/src/memkind.c#L269)):*
> ```C
>         &MEMKIND_HIGHEST_BANDWIDTH_LOCAL_PREFERRED_STATIC,
>     },
>     MEMKIND_NUM_STATIC_KINDS,
> ```

Perhaps you could move this struct to the memkind.h or memkind_private.h header and remove introduced `#define` for this const in the memkind_private header? This way you could avoid situations where someone forgets to update this constant when adding new kind.

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: 26 of 36 files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[`man/hbwmalloc.3` line 222 at r12](https://reviewable.io/reviews/memkind/memkind/776#-N1gvlHE8WcFlvk6Bs30:-N2GNt-F8vkk_6CjSejo:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5472fae332f7bb888538fadf99cf8a2741f29cad/man/hbwmalloc.3#L222)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Combine this note with the previous one in a common section `Notes:`
</blockquote></details>

Done.
___
*[`src/hbwmalloc.c` line 244 at r12](https://reviewable.io/reviews/memkind/memkind/776#-N1gwK0i9RnL1ob4Wmsj:-N2GOJIxDhgTVM8K5LQg:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5472fae332f7bb888538fadf99cf8a2741f29cad/src/hbwmalloc.c#L244)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

with 2MB page size
</blockquote></details>

Done.
___
*[`src/memkind.c` line 269 at r14](https://reviewable.io/reviews/memkind/memkind/776#-N1hkhxyDbmi_XYYjWaP:-N2GOL985HnFzK85fQY7:bqrsp0u) ([raw file](https://github.com/memkind/memkind/blob/330013f83d496f99025b9ba15907edc3066b5819/src/memkind.c#L269)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Perhaps you could move this struct to the memkind.h or memkind_private.h header and remove introduced `#define` for this const in the memkind_private header? This way you could avoid situations where someone forgets to update this constant when adding new kind.
</blockquote></details>

Can't be reasonably done; I've added another comment to at least make it easier to update.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 31 files at r1, 9 of 9 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Review by kilobyte — COMMENTED** [review]
Rebased to solve new conflicts.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776#-:-N6XwEo49f2sF8DcAgXT:b-79gf82)* status: 22 of 37 files reviewed, all discussions resolved (waiting on @bratpiorka, @maciekpac, and @PatKamin)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 14 of 14 files at r18, 4 of 4 files at r19, 2 of 2 files at r20, 8 of 8 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 20 of 31 files at r1, 14 of 14 files at r18, 4 of 4 files at r19, 2 of 2 files at r20, 8 of 8 files at r21.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Review by PatKamin — COMMENTED** [review]
Tests still fail, they just didn't trigger. See current test status. One of the failing tests uses this function: https://github.com/memkind/memkind/blob/master/src/memkind_memtier.c#L839
Please, search for all places where .partition is used and make an update.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776#-:-NCZqCPL43nv8G-3CC-A:b-8g943)* status: 23 of 40 files reviewed, all discussions resolved (waiting on @bratpiorka, @maciekpac, and @PatKamin)

**Comment by kilobyte** [comment]
Seems to work now.

**Review by PatKamin — COMMENTED** [review]
nit: Remove redundant filters here: https://github.com/memkind/memkind/blob/master/test/test.sh#L259.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776#-:-ND374og-CJQ6bk5vL_O:bty2wja)* status: 25 of 40 files reviewed, all discussions resolved (waiting on @bratpiorka, @maciekpac, and @PatKamin)

**Review by PatKamin — APPROVED** [review]
> Reviewed 7 of 15 files at r22, 8 of 8 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Comment by kilobyte** [comment]
Denitted.

**Pull request merged**
