### PR TITLE
Feat utils qemu

### PR DESCRIPTION
**Pull request by PatKamin**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/410)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/410)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @PatKamin)

___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/410#-MNYhc4A-STAjO3PbJKe:-MNYhc4A-STAjO3PbJKf:b2lgu2q) ([raw file](https://github.com/memkind/memkind/blob/5fa71c5f8ab5cc4cda30b918fcafd639281316c7/utils/qemu/packer-scripts/ubuntu-packer.json#L2)):*
> ```JSON
> {
>   "builders": [
> ```

Please add license (if possible) and update MANIFEST files and Makefile.am for file refrerences.
___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 6 at r1](https://reviewable.io/reviews/memkind/memkind/410#-MNYhxw9EYBDmGZvlimk:-MNYhxw9EYBDmGZvliml:b-wzmspv) ([raw file](https://github.com/memkind/memkind/blob/5fa71c5f8ab5cc4cda30b918fcafd639281316c7/utils/qemu/packer-scripts/ubuntu-packer.json#L6)):*
> ```JSON
>       "type": "qemu",
> 
>       "memory": 2048,
> ```

Any chance to short Readme with instruction what you need to run this script and how to run it? 
___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 25 at r1](https://reviewable.io/reviews/memkind/memkind/410#-MNYibZ47nC5NMRem-m7:-MNYibZ47nC5NMRem-m8:blhacof) ([raw file](https://github.com/memkind/memkind/blob/5fa71c5f8ab5cc4cda30b918fcafd639281316c7/utils/qemu/packer-scripts/ubuntu-packer.json#L25)):*
> ```JSON
>         "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
>         "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
>         "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
> ```

- setup GRUB parameters  in guest to no-graphics mode etc/default/GRUB: GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0"
- setup GRUB parameters in guest to speed up boot etc/default/GRUB: GRUB_HIDDEN_TIMEOUT=0 GRUB_HIDDEN_TIMEOUT_QUIET=true
 let me know if it is feasible to do it here?
___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 73 at r1](https://reviewable.io/reviews/memkind/memkind/410#-MNYjDRBEI2lnyubvAvY:-MNYjDRBEI2lnyubvAvZ:b-1gawmu) ([raw file](https://github.com/memkind/memkind/blob/5fa71c5f8ab5cc4cda30b918fcafd639281316c7/utils/qemu/packer-scripts/ubuntu-packer.json#L73)):*
> ```JSON
>     "locale": "en_US",
>     "hostname": "memkind",
>     "ssh_fullname": "memkinduser",
> ```

Not sure if all steps from https://github.com/memkind/memkind/blob/2db4d733ef5239f97212ca4433b2ca3231375d91/utils/qemu/README.md#ssh-key-exchange-host-guest are feasible but Edit guest ssh configuration should be
___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 75 at r1](https://reviewable.io/reviews/memkind/memkind/410#-MNYiuXB8QPd7SLY9hh9:-MNYiuXB8QPd7SLY9hhA:bdw4sqo) ([raw file](https://github.com/memkind/memkind/blob/5fa71c5f8ab5cc4cda30b918fcafd639281316c7/utils/qemu/packer-scripts/ubuntu-packer.json#L75)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     "hostname": "memkind",
>     "ssh_fullname": "memkinduser",
>     "ssh_password": "memkind",
>     "ssh_username": "memkinduser",
> ```
</details>

Can we keep convention with password and user as in:
https://github.com/memkind/memkind/blob/8e9936d7938197ada5dee798d2dd046917c63a50/utils/docker/Dockerfile.ubuntu-20.04#L39-L40

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/410)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @PatKamin)

___
*[utils/qemu/README.md, line 5 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNZ-poq62nNVOFcED13:-MNZ-poq62nNVOFcED14:bhb775h) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/README.md#L5)):*
> ```
> Ubuntu OS
> ```
nit: maybe refer in the whole readme to Ubuntu OS image as Ubuntu 18.04 version
___
*[utils/qemu/README.md, line 6 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNZ-5tX3ATe8UGtWmJB:-MNZ-5tX3ATe8UGtWmJC:b-2wg1v2) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/README.md#L6)):*
> ```Markdown
> 
> Scripts in this directory let you run the installation of the Ubuntu OS image in QEMU environment.
> ```

Please refer to https://learn.hashicorp.com/tutorials/packer/getting-started-install since the trouble with packer from clean the apt version we talk about offline
___
*[utils/qemu/README.md, line 9 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNZ-j9B8gqxguOmGdcY:-MNZ-j9B8gqxguOmGdcZ:b-pet5sa) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/README.md#L9)):*
> ```
> ··
> ```
nit: remove whitespaces
___
*[utils/qemu/README.md, line 14 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNZ-47NAohGnGG97sFd:-MNZ-47NAohGnGG97sFe:b-pet5sa) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/README.md#L14)):*
> ```
> ··
> ```
nit: remove whitespaces
___
*[utils/qemu/README.md, line 15 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNZ-1BACw78BbR0Cucz:-MNZ-1BACw78BbR0Cud-:b-960xxq) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/README.md#L15)):*
> ```Markdown
> 
> In order to run the OS installation run the following command from the packer-scripts directory:  
> ```$ sudo PACKER_LOG=1 packer build ubuntu-packer.json```
> ```

nit add enter here to get rid of this newline warning

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/410)* status: 0 of 3 files reviewed, 11 unresolved discussions (waiting on @PatKamin)

___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 63 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNbS1zcEb5-PIHZCCvY:-MNbS1zcEb5-PIHZCCvZ:b-8sad9b) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/packer-scripts/ubuntu-packer.json#L63)):*
> ```
> libdaxctl-dev
> ```
remove this, since you install ndctl by yourself
Could you add numactl in these packages - it is useful in the development part

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/410)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @michalbiesek)

___
*[utils/qemu/README.md, line 5 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNZ-poq62nNVOFcED13:-MNbnMsJ1C0JEvenUORf:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/README.md#L5)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Ubuntu OS
> ```
nit: maybe refer in the whole readme to Ubuntu OS image as Ubuntu 18.04 version
</blockquote></details>

Done
___
*[utils/qemu/README.md, line 6 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNZ-5tX3ATe8UGtWmJB:-MNbpX6m4zHmxJ0TO4H6:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/README.md#L6)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please refer to https://learn.hashicorp.com/tutorials/packer/getting-started-install since the trouble with packer from clean the apt version we talk about offline
</blockquote></details>

Done
___
*[utils/qemu/README.md, line 9 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNZ-j9B8gqxguOmGdcY:-MNbqsp-6j84XNih0ISz:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/README.md#L9)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ··
> ```
nit: remove whitespaces
</blockquote></details>

Done
___
*[utils/qemu/README.md, line 14 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNZ-47NAohGnGG97sFd:-MNbr52l3tAkM5IfiE4b:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/README.md#L14)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ··
> ```
nit: remove whitespaces
</blockquote></details>

Done
___
*[utils/qemu/README.md, line 15 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNZ-1BACw78BbR0Cucz:-MNbr84k5QdTiPkfNC68:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/README.md#L15)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

nit add enter here to get rid of this newline warning
</blockquote></details>

Done
___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/410#-MNYhc4A-STAjO3PbJKe:-MNbrKp8B7IEB0ERF-IK:bu72nf7) ([raw file](https://github.com/memkind/memkind/blob/5fa71c5f8ab5cc4cda30b918fcafd639281316c7/utils/qemu/packer-scripts/ubuntu-packer.json#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please add license (if possible) and update MANIFEST files and Makefile.am for file refrerences.
</blockquote></details>

There is no comments in json files. MANIFEST and Makefile.am updated.
___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 6 at r1](https://reviewable.io/reviews/memkind/memkind/410#-MNYhxw9EYBDmGZvlimk:-MNbtEiZ-T4csswyIctB:b-ghcdit) ([raw file](https://github.com/memkind/memkind/blob/5fa71c5f8ab5cc4cda30b918fcafd639281316c7/utils/qemu/packer-scripts/ubuntu-packer.json#L6)):*
> Any chance to short Readme with instruction what you need to run this script and how to run it?
Done
___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 25 at r1](https://reviewable.io/reviews/memkind/memkind/410#-MNYibZ47nC5NMRem-m7:-MNbzyxH-pHdUJRFUMAs:b-7qukv0) ([raw file](https://github.com/memkind/memkind/blob/5fa71c5f8ab5cc4cda30b918fcafd639281316c7/utils/qemu/packer-scripts/ubuntu-packer.json#L25)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

- setup GRUB parameters  in guest to no-graphics mode etc/default/GRUB: GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0"
- setup GRUB parameters in guest to speed up boot etc/default/GRUB: GRUB_HIDDEN_TIMEOUT=0 GRUB_HIDDEN_TIMEOUT_QUIET=true
 let me know if it is feasible to do it here?
</blockquote></details>

Done, not tested with the python script from #408 yet
___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 73 at r1](https://reviewable.io/reviews/memkind/memkind/410#-MNYjDRBEI2lnyubvAvY:-MNc4F1qEPmZjYBEJgBL:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/5fa71c5f8ab5cc4cda30b918fcafd639281316c7/utils/qemu/packer-scripts/ubuntu-packer.json#L73)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Not sure if all steps from https://github.com/memkind/memkind/blob/2db4d733ef5239f97212ca4433b2ca3231375d91/utils/qemu/README.md#ssh-key-exchange-host-guest are feasible but Edit guest ssh configuration should be
</blockquote></details>

Done
___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 75 at r1](https://reviewable.io/reviews/memkind/memkind/410#-MNYiuXB8QPd7SLY9hh9:-MNc6q6e4xZMiTQTPq_4:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/5fa71c5f8ab5cc4cda30b918fcafd639281316c7/utils/qemu/packer-scripts/ubuntu-packer.json#L75)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     "hostname": "memkind",
>     "ssh_fullname": "memkinduser",
>     "ssh_password": "memkind",
>     "ssh_username": "memkinduser",
> ```
Can we keep convention with password and user as in:
https://github.com/memkind/memkind/blob/8e9936d7938197ada5dee798d2dd046917c63a50/utils/docker/Dockerfile.ubuntu-20.04#L39-L40
</blockquote></details>

Done
___
*[utils/qemu/packer-scripts/ubuntu-packer.json, line 63 at r2](https://reviewable.io/reviews/memkind/memkind/410#-MNbS1zcEb5-PIHZCCvY:-MNc0D2C6RgfAR96M-_w:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/93bbfee65370147722ad8c684fe80a9e38c3537b/utils/qemu/packer-scripts/ubuntu-packer.json#L63)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> libdaxctl-dev
> ```
remove this, since you install ndctl by yourself
Could you add numactl in these packages - it is useful in the development part
</blockquote></details>

Done

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/410)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[MANIFEST, line 559 at r3](https://reviewable.io/reviews/memkind/memkind/410#-MNcXtAE8Y7KGsprt4Et:-MNcXtAE8Y7KGsprt4Eu:bxftkn4) ([raw file](https://github.com/memkind/memkind/blob/3b586140c5af2316367ad18c95328d950ef169ae/MANIFEST#L559)):*
> ```
> utils/qemu/http/preseed.cfg
> utils/qemu/README.md
> utils/qemu/ubuntu-packer.json
> ```
nit: alphabetical order please
README
http/preseed.cfg
ubuntu-packer.json
___
*[Makefile.am, line 399 at r3](https://reviewable.io/reviews/memkind/memkind/410#-MNcY-wO29WJKGsw-ZBS:-MNcY-wO29WJKGsw-ZBT:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/3b586140c5af2316367ad18c95328d950ef169ae/Makefile.am#L399)):*
> ```Makefile
>              utils/docker/set_host_configuration.sh \
>              utils/qemu/http/preseed.cfg
>              utils/qemu/README.md
> ```

.
___
*[copying_headers/MANIFEST.freeBSD, line 199 at r3](https://reviewable.io/reviews/memkind/memkind/410#-MNcfcMl7_xK18sWmcBi:-MNcfcMl7_xK18sWmcBj:b-1trf3q) ([raw file](https://github.com/memkind/memkind/blob/3b586140c5af2316367ad18c95328d950ef169ae/copying_headers/MANIFEST.freeBSD#L199)):*
> ```
> utils/qemu/http/preseed.cfg
> utils/qemu/README.md
> utils/qemu/ubuntu-packer.json
> ```
Move this to Manifest.EXEMPT since files listed there have no license.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/410)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @PatKamin)

___
*[utils/qemu/README.md, line 17 at r3](https://reviewable.io/reviews/memkind/memkind/410#-MNcgTDn3j7dpjwGcRFC:-MNcgTDn3j7dpjwGcRFD:b2bjugf) ([raw file](https://github.com/memkind/memkind/blob/3b586140c5af2316367ad18c95328d950ef169ae/utils/qemu/README.md#L17)):*
> ```
> In order to run the OS installation run the following command from the packer-scripts directory:
> ```
Now you don't need to be in the packer-scripts directory anymore :)

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/410)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @PatKamin)

___
*[utils/qemu/ubuntu-packer.json, line 69 at r4](https://reviewable.io/reviews/memkind/memkind/410#-MNcn7Kl1YmqeTucWigH:-MNcn7Kl1YmqeTucWigI:bwol7cx) ([raw file](https://github.com/memkind/memkind/blob/5207f8db12e27e4e56611df8164362bfdc3225dc/utils/qemu/ubuntu-packer.json#L69)):*
> ```
> reboot
> ```
shutdown now?
The use case could be possibly like that:
./prepare image by the packer
./run python to run the test or run python to start dev.
After reboot, qemu process will be active and I must kill it

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/410)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @PatKamin)

___
*[utils/qemu/ubuntu-packer.json, line 69 at r4](https://reviewable.io/reviews/memkind/memkind/410#-MNcn7Kl1YmqeTucWigH:-MNcuyG33EJSeLK96lLM:bb5xxit) ([raw file](https://github.com/memkind/memkind/blob/5207f8db12e27e4e56611df8164362bfdc3225dc/utils/qemu/ubuntu-packer.json#L69)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> reboot
> ```
shutdown now?
The use case could be possibly like that:
./prepare image by the packer
./run python to run the test or run python to start dev.
After reboot, qemu process will be active and I must kill it
</blockquote></details>

remove this "reboot" line would also do the job

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/410)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @PatKamin)

___
*[Makefile.am, line 400 at r4](https://reviewable.io/reviews/memkind/memkind/410#-MNgU-uQDD--RFcLjKFn:-MNgU-uQDD--RFcLjKFo:bfdw7tj) ([raw file](https://github.com/memkind/memkind/blob/5207f8db12e27e4e56611df8164362bfdc3225dc/Makefile.am#L400)):*
> ```
>              utils/qemu/http/preseed.cfg
>              utils/qemu/README.md
>              utils/qemu/ubuntu-packer.json
> ```
you miss '\\'

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/410)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

___
*[MANIFEST, line 559 at r3](https://reviewable.io/reviews/memkind/memkind/410#-MNcXtAE8Y7KGsprt4Et:-MNglBma8QsjYgYALTsg:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/3b586140c5af2316367ad18c95328d950ef169ae/MANIFEST#L559)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> utils/qemu/http/preseed.cfg
> utils/qemu/README.md
> utils/qemu/ubuntu-packer.json
> ```
nit: alphabetical order please
README
http/preseed.cfg
ubuntu-packer.json
</blockquote></details>

Done
___
*[Makefile.am, line 399 at r3](https://reviewable.io/reviews/memkind/memkind/410#-MNcY-wO29WJKGsw-ZBS:-MNglQ2zD0PHvguz1fV7:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/3b586140c5af2316367ad18c95328d950ef169ae/Makefile.am#L399)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

.
</blockquote></details>

Done
___
*[Makefile.am, line 400 at r4](https://reviewable.io/reviews/memkind/memkind/410#-MNgU-uQDD--RFcLjKFn:-MNglZwNDikdPYCWcv3A:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/5207f8db12e27e4e56611df8164362bfdc3225dc/Makefile.am#L400)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>              utils/qemu/http/preseed.cfg
>              utils/qemu/README.md
>              utils/qemu/ubuntu-packer.json
> ```
you miss '\\'
</blockquote></details>

Done
___
*[copying_headers/MANIFEST.freeBSD, line 199 at r3](https://reviewable.io/reviews/memkind/memkind/410#-MNcfcMl7_xK18sWmcBi:-MNgllX5BC088-5WWC2C:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/3b586140c5af2316367ad18c95328d950ef169ae/copying_headers/MANIFEST.freeBSD#L199)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> utils/qemu/http/preseed.cfg
> utils/qemu/README.md
> utils/qemu/ubuntu-packer.json
> ```
Move this to Manifest.EXEMPT since files listed there have no license.
</blockquote></details>

Done
___
*[utils/qemu/README.md, line 17 at r3](https://reviewable.io/reviews/memkind/memkind/410#-MNcgTDn3j7dpjwGcRFC:-MNgmBI0-5Wbi8c8RUZH:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/3b586140c5af2316367ad18c95328d950ef169ae/utils/qemu/README.md#L17)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> In order to run the OS installation run the following command from the packer-scripts directory:
> ```
Now you don't need to be in the packer-scripts directory anymore :)
</blockquote></details>

Done
___
*[utils/qemu/ubuntu-packer.json, line 69 at r4](https://reviewable.io/reviews/memkind/memkind/410#-MNcn7Kl1YmqeTucWigH:-MNgms8k818J9syfy621:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/5207f8db12e27e4e56611df8164362bfdc3225dc/utils/qemu/ubuntu-packer.json#L69)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

remove this "reboot" line would also do the job
</blockquote></details>

Done

**Review by michalbiesek — APPROVED** [review]
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/410)* status: 5 of 6 files reviewed, all discussions resolved

**Pull request merged**
