### PR TITLE
Adding CI for PPC64LE

### PR DESCRIPTION
**Pull request by ezeeyahoo**
### Description
Job matrix added for PPC64LE with minimized redundancy without compromising reaability.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

No regression to existing code.
Just added continuous integration for PPC64LE platform, request you to please review.

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/390)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Comment by ezeeyahoo** [comment]
https://travis-ci.com/github/ezeeyahoo/memkind/builds/191351445

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/390)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ezeeyahoo)

___
*[.travis.yml, line 21 at r1](https://reviewable.io/reviews/memkind/memkind/390#-MK8vWxu9MVrLrLOOZer:-MK8vWxu9MVrLrLOOZes:b-mhc4he) ([raw file](https://github.com/memkind/memkind/blob/6edb01f3345b1ad25d00cb57dc60fa1cf5ccc16d/.travis.yml#L21)):*
> ```
>     - <<: *Astyle_
>       name: "Astyle PPC"
>       arch: ppc64le
> ```
Thanks for the patch, Astyle job for ppc64le is not needed - x86-64 is sufficient, please remove the change related to Astyle job.
___
*[.travis.yml, line 82 at r1](https://reviewable.io/reviews/memkind/memkind/390#-MK8vTMa7gbGSHr5hNjQ:-MK8vTMa7gbGSHr5hNjR:bcr98zt) ([raw file](https://github.com/memkind/memkind/blob/6edb01f3345b1ad25d00cb57dc60fa1cf5ccc16d/.travis.yml#L82)):*
> ```
> ··
> ```
please remove this change

**Comment by ezeeyahoo** [comment]
Done

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/390)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
