### PR TITLE
Extend manual information about hwloc

### PR DESCRIPTION
**Pull request by michalbiesek**
- clarify information about locality and memory characteristics
  requirements
Ref: https://github.com/memkind/memkind/pull/500#pullrequestreview-579285994

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/507)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/507)* status: all files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[man/memkind.3, line 1151 at r1](https://reviewable.io/reviews/memkind/memkind/507#-MSSR_ZX8-K3NKllsvMI:-MSSR_ZX8-K3NKllsvMJ:bf5tttv) ([raw file](https://github.com/memkind/memkind/blob/84e4df605be4166ded3d1dd0fa371f7365477fd2/man/memkind.3#L1151)):*
> ```Roff
> .I libhwloc
> dependency.
> Functionality based on locality required that memkind library needs to be configured and built with the support of
> ```

maybe better will be: " .. requires that memkind library is configured ... "
___
*[man/memkind.3, line 1160 at r1](https://reviewable.io/reviews/memkind/memkind/507#-MSSRp2z9T1fO5qEz2ym:-MSSRp2z9T1fO5qEz2yn:bahfyvo) ([raw file](https://github.com/memkind/memkind/blob/84e4df605be4166ded3d1dd0fa371f7365477fd2/man/memkind.3#L1160)):*
> ```Roff
> .UR https://uefi.org/sites/default/files/resources/ACPI_6_3_final_Jan30.pdf
> .UE
> Functionality based on memory performance characteristics required that platform configuration
> ```

maybe better: " ... requires that platform configuration fully supports HMAT and memkind library is configured ..."
___
*[man/memkindallocator.3, line 246 at r1](https://reviewable.io/reviews/memkind/memkind/507#-MSSSEkKEkH6svi7rF28:-MSSSEkKEkH6svi7rF29:b-2zxdb2) ([raw file](https://github.com/memkind/memkind/blob/84e4df605be4166ded3d1dd0fa371f7365477fd2/man/memkindallocator.3#L246)):*
> ```Roff
> .I libhwloc
> dependency.
> Functionality based on locality information required that memkind library needs to be configured and built with the support of
> ```

requires.. see comment above

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/507)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

___
*[man/memkind.3, line 1151 at r1](https://reviewable.io/reviews/memkind/memkind/507#-MSSR_ZX8-K3NKllsvMI:-MSST6Kw4QWiV8tMd7by:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/84e4df605be4166ded3d1dd0fa371f7365477fd2/man/memkind.3#L1151)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

maybe better will be: " .. requires that memkind library is configured ... "
</blockquote></details>

Done.
___
*[man/memkind.3, line 1160 at r1](https://reviewable.io/reviews/memkind/memkind/507#-MSSRp2z9T1fO5qEz2ym:-MSSTEnM092hJedMJJhA:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/84e4df605be4166ded3d1dd0fa371f7365477fd2/man/memkind.3#L1160)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

maybe better: " ... requires that platform configuration fully supports HMAT and memkind library is configured ..."
</blockquote></details>

Done.
___
*[man/memkindallocator.3, line 246 at r1](https://reviewable.io/reviews/memkind/memkind/507#-MSSSEkKEkH6svi7rF28:-MSSTFDb656J_viOMQ6M:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/84e4df605be4166ded3d1dd0fa371f7365477fd2/man/memkindallocator.3#L246)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

requires.. see comment above
</blockquote></details>

Done.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/507)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/507#-:-MSSUzjXC_kiHAZIyx3k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/507#-:-MSSqQUf3f3fhMzCkW5Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/507#-:-MSSrToO8MkSGztipcIE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by mjsmolarek — APPROVED** [review]

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/507#-:-MSWvIFA0wCdBlMj_1Zc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
