### PR TITLE
[Documentation] Extend manual by HMAT clarification

### PR DESCRIPTION
**Pull request by michalbiesek**
- access class 0 provide information about relationship
  between target node and only highest performing initiator(s) Node(s)
- ref: https://www.kernel.org/doc/html/latest/admin-guide/mm/numaperf.html

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/519)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/519#-:-MT15_GG4QKN7d_mvkDw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/519#-:-MT4UvB75eG9v8nwOSKY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Comment by michalbiesek** [comment]
@PatKamin 
I update the version to be more readable

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/519)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[man/memkind.3, line 1168 at r2](https://reviewable.io/reviews/memkind/memkind/519#-MT5F8D47g8VP77ey9wc:-MT5F8D47g8VP77ey9wd:b9x17c0) ([raw file](https://github.com/memkind/memkind/blob/11d33b3147729dd5290d6530a1ef7aeaca6e6ccb/man/memkind.3#L1168)):*
> ```
> which can initiate the allocation
> ```
(which can initiate the allocation) --> replace these two commas with round brackets OR just remove these two commas

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/519)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[man/memkind.3, line 1168 at r2](https://reviewable.io/reviews/memkind/memkind/519#-MT5F8D47g8VP77ey9wc:-MT6R7_f7In0xkKCMuh1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/11d33b3147729dd5290d6530a1ef7aeaca6e6ccb/man/memkind.3#L1168)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

> ```
> which can initiate the allocation
> ```
(which can initiate the allocation) --> replace these two commas with round brackets OR just remove these two commas
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/519#-:-MT6Rkl03jXiBbVUwJzS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/519#-:-MT6SbZq5KQKZeB-pq-I:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/519)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[man/memkind.3, line 1166 at r3](https://reviewable.io/reviews/memkind/memkind/519#-MTKcPP19Ds19Y_hN2Wy:-MTKcPP19Ds19Y_hN2Wz:b-fa1yk4) ([raw file](https://github.com/memkind/memkind/blob/909aee48329049cdd95f0ba7c52762c3b684ea9b/man/memkind.3#L1166)):*
> ```Roff
> .PP
> .BR Note:
> Operating system limits exposed information about memory performance characteristics.
> ```

you should use active voice in the vast majority of any writing.

For a given target NUMA node, the OS exposes only the performance characteristics of the best performing NIMA node.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/519)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @PatKamin and @pbalcer)

___
*[man/memkind.3, line 1166 at r3](https://reviewable.io/reviews/memkind/memkind/519#-MTKcPP19Ds19Y_hN2Wy:-MTL2rzqCMYD2wbfMTYs:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/909aee48329049cdd95f0ba7c52762c3b684ea9b/man/memkind.3#L1166)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

you should use active voice in the vast majority of any writing.

For a given target NUMA node, the OS exposes only the performance characteristics of the best performing NIMA node.

</blockquote></details>

Done.

**Pull request merged**
