### PR TITLE
Parse DRAM kind name from ENV var and use it when creating tiered kind

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/591)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/591)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/591)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[tiering/memtier.c, line 143 at r1](https://reviewable.io/reviews/memkind/memkind/591#-MWUMXXk2Rxe91RqDh92:-MWUMXXk2Rxe91RqDh93:b-xqjsut) ([raw file](https://github.com/memkind/memkind/blob/6d243143c47f859945556d53521a85440f740b3f/tiering/memtier.c#L143)):*
> ```C
>     log_debug("ratio_value: %u", ratio_value);
> 
>     current_tier = memtier_tier_new(kind);
> ```

modify commit message to fill into the limit of 80 characters in first line.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/591)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[tiering/memtier.c, line 114 at r1](https://reviewable.io/reviews/memkind/memkind/591#-MWUOm-J4fQ9oLUFjJ4U:-MWUOm-J4fQ9oLUFjJ4V:bducy8u) ([raw file](https://github.com/memkind/memkind/blob/6d243143c47f859945556d53521a85440f740b3f/tiering/memtier.c#L114)):*
> ```C
>     }
> 
>     log_debug("kind_name: %s", kind->name);
> ```

Uncomment the tests. See how this function could look like in https://github.com/memkind/memkind/pull/589/files
___
*[tiering/memtier.c, line 143 at r1](https://reviewable.io/reviews/memkind/memkind/591#-MWUMXXk2Rxe91RqDh92:-MWUP44gEkoH9gvq3TKe:b32v57) ([raw file](https://github.com/memkind/memkind/blob/6d243143c47f859945556d53521a85440f740b3f/tiering/memtier.c#L143)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

modify commit message to fill into the limit of 80 characters in first line.
</blockquote></details>

+1

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/591#-:-MWYNFWtCC4WBKckhCci:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Pull request merged**
