### PR TITLE
Make RankingPerfTest more accurate - take into account metadata & ove…

### PR DESCRIPTION
**Pull request by maciekpac**
…rhead when setting limits

### Types of changes

- [x] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [x] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/802)

### CODE REVIEW

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/802)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/802)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/802#-N-fiMel241Y1DGxCK9C):*
Too long commit msg header. Please, move the second part of the commit msg below the commit message header.

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/802)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @PatKamin)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/802#-N-fiMel241Y1DGxCK9C):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Too long commit msg header. Please, move the second part of the commit msg below the commit message header.
</blockquote></details>

Done.

**Review by PatKamin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/802)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
