### PR TITLE
Add MEMKIND_BACKGROUND_THREAD_LIMIT env var test

### PR DESCRIPTION
**Pull request by PatKamin**
- [x] Requires #478 
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [x] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/501)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/501)* status: 0 of 20 files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[test/environ_max_bg_threads_test.cpp, line 8 at r1](https://reviewable.io/reviews/memkind/memkind/501#-MS7o7fuDb5ujHAh1Jfh:-MS7o7fuDb5ujHAh1Jfi:bv21p0r) ([raw file](https://github.com/memkind/memkind/blob/bb8fe9cfbbf97358560f454d7fec719db6ceb443/test/environ_max_bg_threads_test.cpp#L8)):*
> ```
> #include "common.h"
> ```
not needed I believe to see that this file doesn't use gtest
___
*[test/environ_max_bg_threads_test.cpp, line 22 at r1](https://reviewable.io/reviews/memkind/memkind/501#-MS7oFDWCM5kmC_tqEWD:-MS7oFDWCM5kmC_tqEWE:bkh37r1) ([raw file](https://github.com/memkind/memkind/blob/bb8fe9cfbbf97358560f454d7fec719db6ceb443/test/environ_max_bg_threads_test.cpp#L22)):*
> ```
> if (memkind_set_bg_threads(false) & memkind_set_bg_threads(true)) {
> ```
can you split this into steps and check result for each function sepeartely
___
*[test/max_bg_threads_env_var_test.py, line 29 at r1](https://reviewable.io/reviews/memkind/memkind/501#-MS7oRJV1sa3--3HISIr:-MS7oRJV1sa3--3HISIs:bu81gr5) ([raw file](https://github.com/memkind/memkind/blob/bb8fe9cfbbf97358560f454d7fec719db6ceb443/test/max_bg_threads_env_var_test.py#L29)):*
<details><summary><i alt="summary">Quoted 19 lines of code…</i></summary>

> ```
> def test_TC_MEMKIND_max_bg_threads_env_var_min(self):
>         """This test checks whether MEMKIND_BACKGROUND_THREAD_LIMIT environment variable limits the number of
>            background threads spawned correctly."""
>         threads_count_test_path = "../environ_max_bg_threads_test"
>         threads_limit = 1
>         command = f"MEMKIND_BACKGROUND_THREAD_LIMIT={threads_limit} " \
>                   f"{self.cmd_helper.get_command_path(threads_count_test_path)}"
>         _, retcode = self.cmd_helper.execute_cmd(command)
>         assert retcode != -1, self.fail_msg.format(f"\nError: Execution of \'{command}\' returns {retcode}")
>         min_threads = self.base_threads_count + threads_limit
>         assert retcode == min_threads, self.fail_msg.format(f"Error: There should be {min_threads} threads running. " \
>                                                             f"Counted threads: {retcode}")
>         threads_limit = 10
>         command = f"MEMKIND_BACKGROUND_THREAD_LIMIT={threads_limit} " \
>                   f"{self.cmd_helper.get_command_path(threads_count_test_path)}"
>         _, retcode = self.cmd_helper.execute_cmd(command)
>         assert retcode != -1, self.fail_msg.format(f"\nError: Execution of \'{command}\' returns {retcode}")
>         assert retcode > min_threads, self.fail_msg.format(f"Error: There should be more than {min_threads} threads " \
>                                                            f"running. Counted threads: {retcode}")
> ```
</details>

Could you split this by test cases or parametrized this?

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/501)* status: 0 of 20 files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[test/environ_max_bg_threads_test.cpp, line 8 at r1](https://reviewable.io/reviews/memkind/memkind/501#-MS7o7fuDb5ujHAh1Jfh:-MS7upVB18HwRTm8D0hF:b6cbgi4) ([raw file](https://github.com/memkind/memkind/blob/bb8fe9cfbbf97358560f454d7fec719db6ceb443/test/environ_max_bg_threads_test.cpp#L8)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include "common.h"
> ```
not needed I believe to see that this file doesn't use gtest
</blockquote></details>

I've used the definition of "MB" from there. Replaced include with define.
___
*[test/environ_max_bg_threads_test.cpp, line 22 at r1](https://reviewable.io/reviews/memkind/memkind/501#-MS7oFDWCM5kmC_tqEWD:-MS7v4CVE7DtcELf8Dob:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/bb8fe9cfbbf97358560f454d7fec719db6ceb443/test/environ_max_bg_threads_test.cpp#L22)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if (memkind_set_bg_threads(false) & memkind_set_bg_threads(true)) {
> ```
can you split this into steps and check result for each function sepeartely
</blockquote></details>

Done.
___
*[test/max_bg_threads_env_var_test.py, line 29 at r1](https://reviewable.io/reviews/memkind/memkind/501#-MS7oRJV1sa3--3HISIr:-MS88EZ7DURbvWDWx10s:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/bb8fe9cfbbf97358560f454d7fec719db6ceb443/test/max_bg_threads_env_var_test.py#L29)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> def test_TC_MEMKIND_max_bg_threads_env_var_min(self):
>         """This test checks whether MEMKIND_BACKGROUND_THREAD_LIMIT environment variable limits the number of
>            background threads spawned correctly."""
>         threads_count_test_path = "../environ_max_bg_threads_test"
>         threads_limit = 1
>         command = f"MEMKIND_BACKGROUND_THREAD_LIMIT={threads_limit} " \
>                   f"{self.cmd_helper.get_command_path(threads_count_test_path)}"
>         _, retcode = self.cmd_helper.execute_cmd(command)
>         assert retcode != -1, self.fail_msg.format(f"\nError: Execution of \'{command}\' returns {retcode}")
>         min_threads = self.base_threads_count + threads_limit
>         assert retcode == min_threads, self.fail_msg.format(f"Error: There should be {min_threads} threads running. " \
>                                                             f"Counted threads: {retcode}")
>         threads_limit = 10
>         command = f"MEMKIND_BACKGROUND_THREAD_LIMIT={threads_limit} " \
>                   f"{self.cmd_helper.get_command_path(threads_count_test_path)}"
>         _, retcode = self.cmd_helper.execute_cmd(command)
>         assert retcode != -1, self.fail_msg.format(f"\nError: Execution of \'{command}\' returns {retcode}")
>         assert retcode > min_threads, self.fail_msg.format(f"Error: There should be more than {min_threads} threads " \
>                                                            f"running. Counted threads: {retcode}")
> ```
Could you split this by test cases or parametrized this?
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 3 of 20 files at r1, 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/501)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @PatKamin)

___
*[test/environ_max_bg_threads_test.cpp, line 22 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDTLG_1vPCs67c3lHm:-MSDTLG_1vPCs67c3lHn:b-sxfd3g) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/environ_max_bg_threads_test.cpp#L22)):*
> ```
> if (memkind_set_bg_threads(false)) {
> ```
What's the point of this? don't you just need to enable threads?
___
*[test/max_bg_threads_env_var_test.py, line 17 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDU1a5A0iUzi_ZVgmr:-MSDU1a5A0iUzi_ZVgms:bahfctf) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/max_bg_threads_env_var_test.py#L17)):*
> ```
> self.base_threads_count
> ```
maybe rename this as a constant like MAIN_THREAD or something like that
___
*[test/max_bg_threads_env_var_test.py, line 22 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDRRxF7mgxNtKXBEmP:-MSDRRxF7mgxNtKXBEmQ:b-ls2pdf) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/max_bg_threads_env_var_test.py#L22)):*
> ```
> self.cmd_helper.get_command_path(self.threads_count_test_path)
> ```
Can this be called directly? I mean there is no point for store the path you just need the executable -in other words
threads_count_test_path -> test_exec  or something like that
test_exec = self.cmd_helper.get_command_path(self.threads_count_test_path)
___
*[test/max_bg_threads_env_var_test.py, line 24 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDUj0SDwClbzNoK5S9:-MSDUj0SDwClbzNoK5SA:b-tpst8) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/max_bg_threads_env_var_test.py#L24)):*
> ```
> get_threads_count
> ```
could be merged with command and rename to something which tells that you execute here binary run_test_exec or something like that
___
*[test/max_bg_threads_env_var_test.py, line 26 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDTBSfBH2i4UngzaV1:-MSDTBSfBH2i4UngzaV2:b-3fx3n8) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/max_bg_threads_env_var_test.py#L26)):*
> ```
> command
> ```
command or self.command?
___
*[test/max_bg_threads_env_var_test.py, line 38 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDUwfQ1zkUYsSAp9td:-MSDUwfQ1zkUYsSAp9te:b-yry86i) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/max_bg_threads_env_var_test.py#L38)):*
> ```
> -1
> ```
I am not sure if we should abort the application in this case - need to think about it

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/501)* status: all files reviewed, 6 unresolved discussions (waiting on @PatKamin)

___
*[test/environ_max_bg_threads_test.cpp, line 8 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDYdTe1PEAYWHtKmRS:-MSDYdTe1PEAYWHtKmRT:bypb08l) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/environ_max_bg_threads_test.cpp#L8)):*
> ```cpp
> #include <unistd.h>
> 
> #define MB 1048576ULL
> ```

could you define this as 1024 * 1024?

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/501)* status: all files reviewed, 6 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[test/environ_max_bg_threads_test.cpp, line 22 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDTLG_1vPCs67c3lHm:-MSDW3vOCPWFcVpjIdrW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/environ_max_bg_threads_test.cpp#L22)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if (memkind_set_bg_threads(false)) {
> ```
What's the point of this? don't you just need to enable threads?
</blockquote></details>

Done.
___
*[test/max_bg_threads_env_var_test.py, line 17 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDU1a5A0iUzi_ZVgmr:-MSDWK8E4xpipqZeWlUl:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/max_bg_threads_env_var_test.py#L17)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> self.base_threads_count
> ```
maybe rename this as a constant like MAIN_THREAD or something like that
</blockquote></details>

Done.
___
*[test/max_bg_threads_env_var_test.py, line 22 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDRRxF7mgxNtKXBEmP:-MSDWp6w48cNHFkBKtYq:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/max_bg_threads_env_var_test.py#L22)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> self.cmd_helper.get_command_path(self.threads_count_test_path)
> ```
Can this be called directly? I mean there is no point for store the path you just need the executable -in other words
threads_count_test_path -> test_exec  or something like that
test_exec = self.cmd_helper.get_command_path(self.threads_count_test_path)

</blockquote></details>

Done.
___
*[test/max_bg_threads_env_var_test.py, line 24 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDUj0SDwClbzNoK5S9:-MSDXKJkAmrg9Bp3uwkm:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/max_bg_threads_env_var_test.py#L24)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> get_threads_count
> ```
could be merged with command and rename to something which tells that you execute here binary run_test_exec or something like that
</blockquote></details>

Done.
___
*[test/max_bg_threads_env_var_test.py, line 26 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDTBSfBH2i4UngzaV1:-MSDXRpwBqH0bqbE4Spv:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/max_bg_threads_env_var_test.py#L26)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> command
> ```
command or self.command?
</blockquote></details>

Done.
___
*[test/max_bg_threads_env_var_test.py, line 38 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDUwfQ1zkUYsSAp9td:-MSDXTZo-EO5vnWj9Xm5:b-iow8j3) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/max_bg_threads_env_var_test.py#L38)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> -1
> ```
I am not sure if we should abort the application in this case - need to think about it
</blockquote></details>

Moved to a separate test.

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/501)* status: 6 of 9 files reviewed, 6 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[test/environ_max_bg_threads_test.cpp, line 8 at r2](https://reviewable.io/reviews/memkind/memkind/501#-MSDYdTe1PEAYWHtKmRS:-MSDczrF6FL9eOaC9TNb:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c72f049092e7d652e39af45b364835036d867d85/test/environ_max_bg_threads_test.cpp#L8)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

could you define this as 1024 * 1024?
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/501)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind.c, line 595 at r3](https://reviewable.io/reviews/memkind/memkind/501#-MSDkEio5_6kjeLVNd4k:-MSDkEip9ly5kMpa4XGw:b-5ojjmw) ([raw file](https://github.com/memkind/memkind/blob/856c79f7c5bf75dadfab2cf36bfd2f063a87f8eb/src/memkind.c#L595)):*
> ```
>                 log_err("Error on parsing value MEMKIND_BACKGROUND_THREAD_LIMIT");
>                 exit(-1);
> ```
log_fatal
abort()
___
*[test/max_bg_threads_env_var_test.py, line 47 at r3](https://reviewable.io/reviews/memkind/memkind/501#-MSDkMjx-QqTzZW9dJvp:-MSDkMjx-QqTzZW9dJvq:btom9zi) ([raw file](https://github.com/memkind/memkind/blob/856c79f7c5bf75dadfab2cf36bfd2f063a87f8eb/test/max_bg_threads_env_var_test.py#L47)):*
> ```
>         assert threads_count == 255, \
>                self.fail_msg.format(f"Error: Negative value of MEMKIND_BACKGROUND_THREAD_LIMIT should not be handled. " \
>                                     f"Counted threads: {threads_count}. Output: {output}")
> ```
You should check output status here

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/501)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[src/memkind.c, line 595 at r3](https://reviewable.io/reviews/memkind/memkind/501#-MSDkEio5_6kjeLVNd4k:-MSDlHvODQPrGfTnad6D:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/856c79f7c5bf75dadfab2cf36bfd2f063a87f8eb/src/memkind.c#L595)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>                 log_err("Error on parsing value MEMKIND_BACKGROUND_THREAD_LIMIT");
>                 exit(-1);
> ```
log_fatal
abort()
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/501)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind.c, line 595 at r4](https://reviewable.io/reviews/memkind/memkind/501#-MSDlu-MBE77rxKbkkj-:-MSDlu-MBE77rxKbkkj0:b4jd1h9) ([raw file](https://github.com/memkind/memkind/blob/6f28589ad865f218db5cd6ba482111446e167ecc/src/memkind.c#L595)):*
> ```
> log_fatal("Error: Wrong value of MEMKIND_BACKGROUND_THREAD_LIMIT=%ld", thread_limit);
> ```
Just print the env with %s no need to change the type from size_t to signed

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/501)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[src/memkind.c, line 595 at r4](https://reviewable.io/reviews/memkind/memkind/501#-MSDlu-MBE77rxKbkkj-:-MSRXEt09Mv2P2HLgziQ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6f28589ad865f218db5cd6ba482111446e167ecc/src/memkind.c#L595)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> log_fatal("Error: Wrong value of MEMKIND_BACKGROUND_THREAD_LIMIT=%ld", thread_limit);
> ```
Just print the env with %s no need to change the type from size_t to signed

</blockquote></details>

Done.
___
*[test/max_bg_threads_env_var_test.py, line 47 at r3](https://reviewable.io/reviews/memkind/memkind/501#-MSDkMjx-QqTzZW9dJvp:-MSRXJEc3lqnX1W3QZay:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/856c79f7c5bf75dadfab2cf36bfd2f063a87f8eb/test/max_bg_threads_env_var_test.py#L47)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         assert threads_count == 255, \
>                self.fail_msg.format(f"Error: Negative value of MEMKIND_BACKGROUND_THREAD_LIMIT should not be handled. " \
>                                     f"Counted threads: {threads_count}. Output: {output}")
> ```
You should check output status here
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/501)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @michalbiesek)

**Pull request merged**
