### PR TITLE
Add munmap implementation

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [x] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/821)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 18 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/821)* status: 18 of 20 files reviewed, 3 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[`include/memkind/internal/mmap_tracing_queue.h` line 22 at r1](https://reviewable.io/reviews/memkind/memkind/821#-N301YmU4jvMjJwURlt8:-N301YmU4jvMjJwURlt9:b-at1pkr) ([raw file](https://github.com/memkind/memkind/blob/61fb63b8e0f752d0d10f60e31cf825542b9a70b7/include/memkind/internal/mmap_tracing_queue.h#L22)):*
> ```objc
>     // remove pages, regardless of DRAM/PMEM localization
>     MMAP_TRACING_EVENT_MUNMAP,
>     // remove pages, regardless of DRAM/PMEM localization
> ```

MUNMAP and RE_MMAP have the same comments?
___
*[`src/bigary.c` line 104 at r1](https://reviewable.io/reviews/memkind/memkind/821#-N301xryCaENJIOkQ9hk:-N301xryCaENJIOkQ9hl:b-54vpbh) ([raw file](https://github.com/memkind/memkind/blob/61fb63b8e0f752d0d10f60e31cf825542b9a70b7/src/bigary.c#L104)):*
> ```C
> void bigary_destroy(bigary *restrict m_bigary)
> {
>     // TODO unmap the area!
> ```

as I see you're unmapping bigary->area bellow, so what this comment is about?
___
*[`src/bigary.c` line 113 at r1](https://reviewable.io/reviews/memkind/memkind/821#-N3027B8A1ir0wLO_T52:-N3027B8A1ir0wLO_T53:b-7ropln) ([raw file](https://github.com/memkind/memkind/blob/61fb63b8e0f752d0d10f60e31cf825542b9a70b7/src/bigary.c#L113)):*
> ```C
> void bigary_destroy_mmap(bigary *restrict m_bigary, const MmapCallback *m_mmap)
> {
>     // TODO unmap the area!
> ```

ditto

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/821)* status: all files reviewed, 4 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[`test/memkind_memtier_data_movement_test.cpp` line 1573 at r1](https://reviewable.io/reviews/memkind/memkind/821#-N305MwHCpYkaksakHrk:-N305MwHCpYkaksakHrl:b-mi3rwq) ([raw file](https://github.com/memkind/memkind/blob/61fb63b8e0f752d0d10f60e31cf825542b9a70b7/test/memkind_memtier_data_movement_test.cpp#L1573)):*
> ```cpp
>     ASSERT_EQ(start_addr, 0xABCDul);
>     ASSERT_EQ(nof_pages, 1ul);
>     ASSERT_EQ(event, MMAP_TRACING_EVENT_MMAP);
> ```

the event changes?

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/821)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[`include/memkind/internal/mmap_tracing_queue.h` line 22 at r1](https://reviewable.io/reviews/memkind/memkind/821#-N301YmU4jvMjJwURlt8:-N31hi4IBIU-dKxeN2-5:b-bu91xm) ([raw file](https://github.com/memkind/memkind/blob/61fb63b8e0f752d0d10f60e31cf825542b9a70b7/include/memkind/internal/mmap_tracing_queue.h#L22)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

MUNMAP and RE_MMAP have the same comments?
</blockquote></details>

Updated
___
*[`src/bigary.c` line 104 at r1](https://reviewable.io/reviews/memkind/memkind/821#-N301xryCaENJIOkQ9hk:-N31iE4D6vbyZ7fpvBO3:b-erje7z) ([raw file](https://github.com/memkind/memkind/blob/61fb63b8e0f752d0d10f60e31cf825542b9a70b7/src/bigary.c#L104)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

as I see you're unmapping bigary->area bellow, so what this comment is about?
</blockquote></details>

I think this comment is old/irrelevant, removed
___
*[`src/bigary.c` line 113 at r1](https://reviewable.io/reviews/memkind/memkind/821#-N3027B8A1ir0wLO_T52:-N31i_Ir0Bz_tKHMGWB4:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/61fb63b8e0f752d0d10f60e31cf825542b9a70b7/src/bigary.c#L113)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`test/memkind_memtier_data_movement_test.cpp` line 1573 at r1](https://reviewable.io/reviews/memkind/memkind/821#-N305MwHCpYkaksakHrk:-N31igPn4vEKyGvhYB7B:bgy4365) ([raw file](https://github.com/memkind/memkind/blob/61fb63b8e0f752d0d10f60e31cf825542b9a70b7/test/memkind_memtier_data_movement_test.cpp#L1573)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

the event changes?
</blockquote></details>

It should correspond to the one that was taken from the queue in mmap_tracing_queue_process_one. I initialized the variable to a different value to make sure that the value was really updated.

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 18 of 20 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/821)* status: all files reviewed, 5 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[`src/mtt_internals.c` line 285 at r2](https://reviewable.io/reviews/memkind/memkind/821#-N33gJMO2Z_T2VPxv8IS:-N33gJMO2Z_T2VPxv8IT:b5x8hx6) ([raw file](https://github.com/memkind/memkind/blob/022ed8a23c6be5ff228d7e8473094953446c568a/src/mtt_internals.c#L285)):*
> ```C
> {
>     // update dram ranking
>     ssize_t additional_dram_used = mtt_internals_process_queued(internals);
> ```

diff_in_dram_used maybe?

**Review by bratpiorka — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/821)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/821)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[`src/mtt_internals.c` line 285 at r2](https://reviewable.io/reviews/memkind/memkind/821#-N33gJMO2Z_T2VPxv8IS:-N33ueb1Cnbt7Cbu88Dx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/022ed8a23c6be5ff228d7e8473094953446c568a/src/mtt_internals.c#L285)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

diff_in_dram_used maybe?
</blockquote></details>

Done.

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/821)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
