### PR TITLE
Update clang-format configuration and disable the format for struct

### PR DESCRIPTION
**Pull request by michalbiesek**
Ref: https://github.com/memkind/memkind/pull/516#pullrequestreview-596114979
The intention of this PR is to avoid breaking the line in sections like e.g.: struct

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/546)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/546#-:-MUgzvQF5clfWf4mDMvt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/546)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[src/memkind_regular.c, line 86 at r1](https://reviewable.io/reviews/memkind/memkind/546#-MUh3Oug7vKkn5PmSdmh:-MUh3Oug7vKkn5PmSdmi:bcufzlx) ([raw file](https://github.com/memkind/memkind/blob/d6df04c052878829c2e3c788bc5943f559a462b8/src/memkind_regular.c#L86)):*
> ```C
>     .finalize = memkind_regular_finalize,
>     .get_stat = memkind_arena_get_kind_stat,
>     .defrag_reallocate = memkind_arena_defrag_reallocate
> ```

nit: introduce a comma after the last element instead of switching clang-format off/on

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/546#-:-MUh3p1x3qNxbUPD9Awl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/546)* status: 1 of 14 files reviewed, all discussions resolved (waiting on @bratpiorka)

___
*[src/memkind_regular.c, line 86 at r1](https://reviewable.io/reviews/memkind/memkind/546#-MUh3Oug7vKkn5PmSdmh:-MUhRZ6UCwhOnEg9dWjT:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d6df04c052878829c2e3c788bc5943f559a462b8/src/memkind_regular.c#L86)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: introduce a comma after the last element instead of switching clang-format off/on
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/546#-:-MUhWMqG-0E6jHibKTV-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/546)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/memkind_local.c, line 266 at r4](https://reviewable.io/reviews/memkind/memkind/546#-MUhSLlB5ALOAQ59pvc3:-MUhWoP65Uqvqg425T-I:b-eunnih) ([raw file](https://github.com/memkind/memkind/blob/ab57935a39343355724f9938e32acc46e5e5d272/src/memkind_local.c#L266)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this should be not needed now when you added commas at the end of structs?
</blockquote></details>

memkind_ops MEMKIND_HIGHEST_CAPACITY_LOCAL_PREFERRED_OPS
MEMKIND_HIGHEST_BANDWIDTH_LOCAL_PREFERRED_OPS
lines would be break without it

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/546#-:-MUhXIwpDxYxAc05Q0i4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

**Pull request merged**
