### PR TITLE
Feat cleanup ctl memtier

### PR DESCRIPTION
**Pull request by michalbiesek**
Required:

- [x]  #588 

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/590)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/590)* status: all files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

___
*[tiering/ctl.c, line 20 at r2](https://reviewable.io/reviews/memkind/memkind/590#-MWTgzhF6_jT8KUhca4v:-MWTgzhF6_jT8KUhca4w:bvafjza) ([raw file](https://github.com/memkind/memkind/blob/27c5db2e27425aca9435630d4075665e1a97a8b2/tiering/ctl.c#L20)):*
> ```C
> #define CTL_STRING_QUERY_SEPARATOR ","
> 
> static struct memtier_tier *current_tier;
> ```

so we'll keep current_kind in memtier.c and list of tiers that builds this kind here?
___
*[tiering/ctl.c, line 250 at r2](https://reviewable.io/reviews/memkind/memkind/590#-MWThIOSBO5ow78B-F6o:-MWThIOSBO5ow78B-F6p:b-6eyiii) ([raw file](https://github.com/memkind/memkind/blob/27c5db2e27425aca9435630d4075665e1a97a8b2/tiering/ctl.c#L250)):*
> ```C
> }
> 
> static memkind_t get_kind(const char *str, const char *pmem_path,
> ```

please add clt_ prefix as all functions in this file have it
___
*[tiering/ctl.c, line 267 at r2](https://reviewable.io/reviews/memkind/memkind/590#-MWTgfno2bpS1eloJ2cv:-MWTgfno2bpS1eloJ2cw:bt95yj2) ([raw file](https://github.com/memkind/memkind/blob/27c5db2e27425aca9435630d4075665e1a97a8b2/tiering/ctl.c#L267)):*
> ```C
> }
> 
> // TODO - move this code during refactoring after implementing support for
> ```

this TODO is not needed now?
___
*[tiering/ctl.c, line 269 at r2](https://reviewable.io/reviews/memkind/memkind/590#-MWThKp67hXXzr-Q7RmU:-MWThKp67hXXzr-Q7RmV:b-viwj2i) ([raw file](https://github.com/memkind/memkind/blob/27c5db2e27425aca9435630d4075665e1a97a8b2/tiering/ctl.c#L269)):*
> ```C
> // TODO - move this code during refactoring after implementing support for
> // multiple kinds
> static const char *policy_to_str(memtier_policy_t policy)
> ```

add ctl_ prefix

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/590)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @bratpiorka)

___
*[tiering/ctl.c, line 20 at r2](https://reviewable.io/reviews/memkind/memkind/590#-MWTgzhF6_jT8KUhca4v:-MWTkKaV5-ZkayI4noIJ:b-tp7ql2) ([raw file](https://github.com/memkind/memkind/blob/27c5db2e27425aca9435630d4075665e1a97a8b2/tiering/ctl.c#L20)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

so we'll keep current_kind in memtier.c and list of tiers that builds this kind here?
</blockquote></details>

There is no reason to keep tier structure on memtier layer
___
*[tiering/ctl.c, line 250 at r2](https://reviewable.io/reviews/memkind/memkind/590#-MWThIOSBO5ow78B-F6o:-MWTkAru7aEFCHrhD0ms:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/27c5db2e27425aca9435630d4075665e1a97a8b2/tiering/ctl.c#L250)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please add clt_ prefix as all functions in this file have it
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 267 at r2](https://reviewable.io/reviews/memkind/memkind/590#-MWTgfno2bpS1eloJ2cv:-MWTkFYR3mZIO8D1yINs:ba3dfob) ([raw file](https://github.com/memkind/memkind/blob/27c5db2e27425aca9435630d4075665e1a97a8b2/tiering/ctl.c#L267)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this TODO is not needed now?
</blockquote></details>

Removed
___
*[tiering/ctl.c, line 269 at r2](https://reviewable.io/reviews/memkind/memkind/590#-MWThKp67hXXzr-Q7RmU:-MWTkGTA6SgacnawOCQh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/27c5db2e27425aca9435630d4075665e1a97a8b2/tiering/ctl.c#L269)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

add ctl_ prefix 
</blockquote></details>

Done.

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/590#-:-MWTlWJ16_im141uQl9k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/590#-:-MWUDiGVDGH4r9Xx3HdR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
