### PR TITLE
Add new test cases for HMAT attributes.

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [x] Other (tests)

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [x] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/474)

### CODE REVIEW

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 4 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: 4 of 19 files reviewed, 12 unresolved discussions (waiting on @bratpiorka)

___
*[MANIFEST, line 579 at r2](https://reviewable.io/reviews/memkind/memkind/474#-MRPTjJf6yHvu5w41las:-MRPTjJg93zd0Y_NVuwC:b-lp2lvd) ([raw file](https://github.com/memkind/memkind/blob/4cf3e4fc39530382c92f0009cfce6a5870076fde/MANIFEST#L579)):*
> ```
> utils/qemu/topology/clx_2_var1_hmat.xml
> ```
Add: utils/qemu/topology/clx_2_var1_emul_hbw.xml
___
*[MANIFEST, line 581 at r2](https://reviewable.io/reviews/memkind/memkind/474#-MRPToVrDrWAGHQzRVS7:-MRPToVrDrWAGHQzRVS8:bjllmdj) ([raw file](https://github.com/memkind/memkind/blob/4cf3e4fc39530382c92f0009cfce6a5870076fde/MANIFEST#L581)):*
> ```
> utils/qemu/topology/clx_2_var2_hmat.xml
> utils/qemu/topology/clx_2_var2_emul_hbw.xml
> ```
nit: alphabetical order please: emul before hmat 
___
*[Makefile.am, line 413 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPTy0jDfsJ4NchVv_L:-MRPTy0jDfsJ4NchVv_M:b-dmfu4b) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/Makefile.am#L413)):*
> ```
>              utils/qemu/topology/clx_2_var1_hmat.xml \
>              utils/qemu/topology/clx_2_var1_emul_hbw.xml \
> ```
nit: alphabetical order please: emul before hmat 
___
*[copying_headers/MANIFEST.freeBSD, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPU2zH2ePE9uEGf7pr:-MRPU2zIBdLZBEFun4Xd:b-82u4ar) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/copying_headers/MANIFEST.freeBSD#L1)):*
> ```
> 
> ```

Please restore
___
*[copying_headers/MANIFEST.freeBSD, line 232 at r2](https://reviewable.io/reviews/memkind/memkind/474#-MRPU9yMB4Gu96GAJRF3:-MRPU9yMB4Gu96GAJRF4:b-bvfdh5) ([raw file](https://github.com/memkind/memkind/blob/4cf3e4fc39530382c92f0009cfce6a5870076fde/copying_headers/MANIFEST.freeBSD#L232)):*
> ```
> utils/qemu/topology/clx_4_var4_hmat.xml
> utils/qemu/topology/clx_4_var4_emul_hbw.xml
> ```
nit: alphabetical order please: emul before hmat 
___
*[utils/qemu/topology/clx_2_var1_emul_hbw.xml, line 5 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPUfjyB9AfpPym_w7y:-MRPUfjyB9AfpPym_w7z:b9e19h3) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/clx_2_var1_emul_hbw.xml#L5)):*
> ```
> CascadeLake2Var1HMAT
> ```
CascadeLake2Var1HBW - check name in every xml please
___
*[utils/qemu/topology/README.md, line 14 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPV0VWErlAA_GIYWAf:-MRPV0VWErlAA_GIYWAg:b-bch0ph) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L14)):*
> ```
> memory DRAM 
> ```
memory DRAM +HBM
___
*[utils/qemu/topology/README.md, line 17 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPV3z9BDCKjWrROES4:-MRPV3z9BDCKjWrROES5:blbu8fz) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L17)):*
> ```
> memory DRAM
> ```
memory DRAM +HBM
___
*[utils/qemu/topology/README.md, line 20 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPV6DT2jcdpqAvqHSP:-MRPV6DT2jcdpqAvqHSQ:blbu8fz) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L20)):*
> ```
> memory DRAM
> ```
memory DRAM +HBM
___
*[utils/qemu/topology/README.md, line 23 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPV9hNDw53gTiAppwm:-MRPV9hNDw53gTiAppwn:blbu8fz) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L23)):*
> ```
> memory DRAM
> ```
memory DRAM +HBM
___
*[utils/qemu/topology/README.md, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPVCRI17KO6cFiSetS:-MRPVCRI17KO6cFiSetT:blbu8fz) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L26)):*
> ```
> memory DRAM
> ```
memory DRAM +HBM
___
*[utils/qemu/topology/README.md, line 29 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPVDrz1et-OFg2Crgs:-MRPVDrz1et-OFg2Crgt:blbu8fz) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L29)):*
> ```
> memory DRAM
> ```
memory DRAM +HBM

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @michalbiesek)

___
*[MANIFEST, line 579 at r2](https://reviewable.io/reviews/memkind/memkind/474#-MRPTjJf6yHvu5w41las:-MRPbgiq8FRuhv-D3c-H:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/4cf3e4fc39530382c92f0009cfce6a5870076fde/MANIFEST#L579)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> utils/qemu/topology/clx_2_var1_hmat.xml
> ```
Add: utils/qemu/topology/clx_2_var1_emul_hbw.xml
</blockquote></details>

Done.
___
*[copying_headers/MANIFEST.freeBSD, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPU2zH2ePE9uEGf7pr:-MRPWoo0DjLBljiTImAH:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/copying_headers/MANIFEST.freeBSD#L1)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please restore
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 14 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPV0VWErlAA_GIYWAf:-MRPeLemDl05zt0iqIa_:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L14)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memory DRAM 
> ```
memory DRAM +HBM
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 17 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPV3z9BDCKjWrROES4:-MRPeLtA37IQne1xPxr9:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L17)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memory DRAM
> ```
memory DRAM +HBM
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 20 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPV6DT2jcdpqAvqHSP:-MRPeMN63IHCUT2e6TtZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L20)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memory DRAM
> ```
memory DRAM +HBM
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 23 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPV9hNDw53gTiAppwm:-MRPeMnU7ZOjazhtCNkw:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L23)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memory DRAM
> ```
memory DRAM +HBM
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPVCRI17KO6cFiSetS:-MRPeNCs-QKytoxdgdug:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L26)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memory DRAM
> ```
memory DRAM +HBM
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 29 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPVDrz1et-OFg2Crgs:-MRPeNWc5YS-tyMlxJYU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/README.md#L29)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memory DRAM
> ```
memory DRAM +HBM
</blockquote></details>

Done.
___
*[utils/qemu/topology/clx_2_var1_emul_hbw.xml, line 5 at r1](https://reviewable.io/reviews/memkind/memkind/474#-MRPUfjyB9AfpPym_w7y:-MRPe3OqEgBBktMIsA5x:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6d335fdf4ce88b830d2755ec9a0ab10088d743ff/utils/qemu/topology/clx_2_var1_emul_hbw.xml#L5)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> CascadeLake2Var1HMAT
> ```
CascadeLake2Var1HBW - check name in every xml please
</blockquote></details>

Done.

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 8 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: 8 of 20 files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

___
*[utils/qemu/topology/clx_2_var1_emul_hmat.xml, line 3 at r3](https://reviewable.io/reviews/memkind/memkind/474#-MRPeYq-DapUt6JpqFIZ:-MRPeYq-DapUt6JpqFI_:b-n1r2fe) ([raw file](https://github.com/memkind/memkind/blob/8bcc0140a3dab0fb90dc45379f3ee7effbecf4dc/utils/qemu/topology/clx_2_var1_emul_hmat.xml#L3)):*
> ```XML
> 
> ```

restore the original name please
___
*[utils/qemu/topology/clx_2_var1_hbw.xml, line 23 at r3](https://reviewable.io/reviews/memkind/memkind/474#-MRPgDwKEgGFxkNpOOl7:-MRPgDwKEgGFxkNpOOl8:b2nh3b8) ([raw file](https://github.com/memkind/memkind/blob/8bcc0140a3dab0fb90dc45379f3ee7effbecf4dc/utils/qemu/topology/clx_2_var1_hbw.xml#L23)):*
> ```XML
>       <cell id='1' cpus='8-15' memory='512' unit='MiB'>
>         <distances>
>           <sibling id='0' value='20'/>
> ```

clx_2_var1_emul_hbw.xml? - shouldn't this be name of this file.
___
*[utils/qemu/topology/clx_2_var1_hbw.xml, line 40 at r3](https://reviewable.io/reviews/memkind/memkind/474#-MRPf33m1B53KZ7oO2eg:-MRPf33m1B53KZ7oO2eh:b-k2v08h) ([raw file](https://github.com/memkind/memkind/blob/8bcc0140a3dab0fb90dc45379f3ee7effbecf4dc/utils/qemu/topology/clx_2_var1_hbw.xml#L40)):*
> ```
> value='200'/>
> ```
Regarding Node 2, I know this is the only emulation, but I think this should consider memory properties like that:
HBW Node will probably have less capacity than PMEM Node (even less then DRAM Node).
HBW Node will probably have lower latency than PMEM Node (HBW Node will probably got slightly bigger latency than DRAM Node)
Simillar note consider all the _emul_hbw architectures.

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: 6 of 19 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[utils/qemu/topology/clx_2_var1_emul_hmat.xml, line 3 at r3](https://reviewable.io/reviews/memkind/memkind/474#-MRPeYq-DapUt6JpqFIZ:-MRPuEWc92g2sfV-1KgA:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8bcc0140a3dab0fb90dc45379f3ee7effbecf4dc/utils/qemu/topology/clx_2_var1_emul_hmat.xml#L3)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

restore the original name please
</blockquote></details>

Done.
___
*[utils/qemu/topology/clx_2_var1_hbw.xml, line 23 at r3](https://reviewable.io/reviews/memkind/memkind/474#-MRPgDwKEgGFxkNpOOl7:-MRPsQ63Dv4JoGbfk9zb:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8bcc0140a3dab0fb90dc45379f3ee7effbecf4dc/utils/qemu/topology/clx_2_var1_hbw.xml#L23)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

clx_2_var1_emul_hbw.xml? - shouldn't this be name of this file.
</blockquote></details>

Done.
___
*[utils/qemu/topology/clx_2_var1_hbw.xml, line 40 at r3](https://reviewable.io/reviews/memkind/memkind/474#-MRPf33m1B53KZ7oO2eg:-MRPu82PCPPb1mU8UWkf:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8bcc0140a3dab0fb90dc45379f3ee7effbecf4dc/utils/qemu/topology/clx_2_var1_hbw.xml#L40)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> value='200'/>
> ```
Regarding Node 2, I know this is the only emulation, but I think this should consider memory properties like that:
HBW Node will probably have less capacity than PMEM Node (even less then DRAM Node).
HBW Node will probably have lower latency than PMEM Node (HBW Node will probably got slightly bigger latency than DRAM Node)
Simillar note consider all the _emul_hbw architectures.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 11 of 20 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[utils/qemu/topology/README.md, line 11 at r4](https://reviewable.io/reviews/memkind/memkind/474#-MRPzahjBUgGl0TMGXuh:-MRPzahjBUgGl0TMGXui:b-3s5d5u) ([raw file](https://github.com/memkind/memkind/blob/ce87c678ee776c8e8daf86e8e8ed497d0839e60d/utils/qemu/topology/README.md#L11)):*
> ```Markdown
> - knm_snc4.xml - Knights Mill, cluster mode: SNC-4 - memory: DRAM+MCDRAM
> - clx_2_var1.xml - Cascade Lake, 2 sockets - memory DRAM+PMEM - PMEM on socket 0
> - clx_2_var1_emul_hbw.xml - emulated Cascade Lake, 2 sockets - memory DRAM+HBM - HBM on socket 1 (HMAT support)
> ```

on socket 0 ?

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 3 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka)

___
*[utils/qemu/topology/clx_2_var2_emul_hbw.xml, line 41 at r4](https://reviewable.io/reviews/memkind/memkind/474#-MRPz_aj2tXudIZ9HXNv:-MRPz_aj2tXudIZ9HXNw:b-yb9mij) ([raw file](https://github.com/memkind/memkind/blob/ce87c678ee776c8e8daf86e8e8ed497d0839e60d/utils/qemu/topology/clx_2_var2_emul_hbw.xml#L41)):*
> ```
> 8000
> ```
80000 ? I compare this scenario with clx2_var1_emul_hbw.xml

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 3 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: 10 of 19 files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @michalbiesek, and @PatKamin)

___
*[utils/qemu/topology/clx_2_var2_emul_hbw.xml, line 43 at r5](https://reviewable.io/reviews/memkind/memkind/474#-MRUfzmr5cfzFQxyX2hn:-MRUfzms5Q9lumsoeZvd:bssqolh) ([raw file](https://github.com/memkind/memkind/blob/d92ccb06ca3aba4d963a2738b43bffbbec8d6bcf/utils/qemu/topology/clx_2_var2_emul_hbw.xml#L43)):*
> ```
>  <bandwidth initiator='1' target='1' type='access' value='33770' unit='MiB'/>
> ```
.
___
*[utils/qemu/topology/clx_2_var2_hmat.xml, line 43 at r5](https://reviewable.io/reviews/memkind/memkind/474#-MRUhUUCCWwbhCShrKxy:-MRUhUUCCWwbhCShrKxz:b-u4rl4k) ([raw file](https://github.com/memkind/memkind/blob/d92ccb06ca3aba4d963a2738b43bffbbec8d6bcf/utils/qemu/topology/clx_2_var2_hmat.xml#L43)):*
> ```
>  <bandwidth initiator='1' target='1' type='access' value='33770' unit='MiB'/>
> ```
. I think this concern all the xml's. To generalize Same CPU_NUMA_NODE -> Same CPU_NUMA_NODE should have similar bandwidth/latency as Node0 -> Node0
___
*[utils/qemu/topology/README.md, line 6 at r5](https://reviewable.io/reviews/memkind/memkind/474#-MRUf0S7DovD1eznPP8L:-MRUf0S7DovD1eznPP8M:b-x5pm5p) ([raw file](https://github.com/memkind/memkind/blob/d92ccb06ca3aba4d963a2738b43bffbbec8d6bcf/utils/qemu/topology/README.md#L6)):*
> ```Markdown
> 
> XML files in this directory simulates different memory architectures.
> Note that systems marked with (*) are "emulated" and not based on real products.
> ```

+1 for the table
___
*[utils/qemu/topology/clx_2_var1_emul_hbw.xml, line 43 at r5](https://reviewable.io/reviews/memkind/memkind/474#-MRUfYpNAqpjrwLsGrrW:-MRUfYpNAqpjrwLsGrrX:b-1qxvr5) ([raw file](https://github.com/memkind/memkind/blob/d92ccb06ca3aba4d963a2738b43bffbbec8d6bcf/utils/qemu/topology/clx_2_var1_emul_hbw.xml#L43)):*
> ```
> <bandwidth initiator='1' target='1' type='access' value='33770' unit='MiB'/>
> ```
Node 1 is the same as Node 0 right (not regarding the capacity of course)?  so relation bandwidth 1->1 should be similar to 0->0

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: 9 of 20 files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[utils/qemu/topology/clx_2_var2_emul_hbw.xml, line 41 at r4](https://reviewable.io/reviews/memkind/memkind/474#-MRPz_aj2tXudIZ9HXNv:-MRUCQNK9W7ychImVJ0e:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ce87c678ee776c8e8daf86e8e8ed497d0839e60d/utils/qemu/topology/clx_2_var2_emul_hbw.xml#L41)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 8000
> ```
80000 ? I compare this scenario with clx2_var1_emul_hbw.xml
</blockquote></details>

Done.
___
*[utils/qemu/topology/clx_2_var2_emul_hbw.xml, line 43 at r5](https://reviewable.io/reviews/memkind/memkind/474#-MRUfzmr5cfzFQxyX2hn:-MRUyrmoETr4kY20rcy3:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d92ccb06ca3aba4d963a2738b43bffbbec8d6bcf/utils/qemu/topology/clx_2_var2_emul_hbw.xml#L43)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  <bandwidth initiator='1' target='1' type='access' value='33770' unit='MiB'/>
> ```
.
</blockquote></details>

Done.
___
*[utils/qemu/topology/clx_2_var2_hmat.xml, line 43 at r5](https://reviewable.io/reviews/memkind/memkind/474#-MRUhUUCCWwbhCShrKxy:-MRUyu3_8aQ-L2eOw15t:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d92ccb06ca3aba4d963a2738b43bffbbec8d6bcf/utils/qemu/topology/clx_2_var2_hmat.xml#L43)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  <bandwidth initiator='1' target='1' type='access' value='33770' unit='MiB'/>
> ```
. I think this concern all the xml's. To generalize Same CPU_NUMA_NODE -> Same CPU_NUMA_NODE should have similar bandwidth/latency as Node0 -> Node0
</blockquote></details>

Done.
___
*[utils/qemu/topology/README.md, line 11 at r4](https://reviewable.io/reviews/memkind/memkind/474#-MRPzahjBUgGl0TMGXuh:-MRUCSS45rkTRpRAh4Pu:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ce87c678ee776c8e8daf86e8e8ed497d0839e60d/utils/qemu/topology/README.md#L11)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

on socket 0 ?
</blockquote></details>

Done.
___
*[utils/qemu/topology/clx_2_var1_emul_hbw.xml, line 43 at r5](https://reviewable.io/reviews/memkind/memkind/474#-MRUfYpNAqpjrwLsGrrW:-MRUpKhD4QnL6k9IlEmA:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d92ccb06ca3aba4d963a2738b43bffbbec8d6bcf/utils/qemu/topology/clx_2_var1_emul_hbw.xml#L43)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> <bandwidth initiator='1' target='1' type='access' value='33770' unit='MiB'/>
> ```
Node 1 is the same as Node 0 right (not regarding the capacity of course)?  so relation bandwidth 1->1 should be similar to 0->0
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 20 files at r3, 3 of 12 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[utils/qemu/topology/clx_4_var2_emul_hbw.xml, line 69 at r6](https://reviewable.io/reviews/memkind/memkind/474#-MRV791T1560WvuyCO-x:-MRV791T1560WvuyCO-y:b-g2w6tu) ([raw file](https://github.com/memkind/memkind/blob/afee22df6f590dcfafb598d424d41dcb0e7c8f2d/utils/qemu/topology/clx_4_var2_emul_hbw.xml#L69)):*
> ```
> <bandwidth initiator='0' target='4' type='access' value='130000' unit='MiB'/>
> ```
correct me if I am wrong but I think Node 1 and Node 4 are on the same socket  and this not correspond to latency values I mean:
 Node0->Node4 got lower latency then Node1->Node4
 Node0->Node4 got higher bandwidth then Node1->Node4

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[utils/qemu/topology/clx_4_var2_emul_hbw.xml, line 69 at r6](https://reviewable.io/reviews/memkind/memkind/474#-MRV791T1560WvuyCO-x:-MRV7ycjEvkTKvsyeO30:b-z27bln) ([raw file](https://github.com/memkind/memkind/blob/afee22df6f590dcfafb598d424d41dcb0e7c8f2d/utils/qemu/topology/clx_4_var2_emul_hbw.xml#L69)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> <bandwidth initiator='0' target='4' type='access' value='130000' unit='MiB'/>
> ```
correct me if I am wrong but I think Node 1 and Node 4 are on the same socket  and this not correspond to latency values I mean:
 Node0->Node4 got lower latency then Node1->Node4
 Node0->Node4 got higher bandwidth then Node1->Node4
</blockquote></details>

And should be opposite

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 2 of 20 files at r3, 2 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474#-:-MRVEPKFEIwEpwIp4upv:bnfp4nl)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @michalbiesek and @PatKamin)

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/474)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @michalbiesek and @PatKamin)

___
*[utils/qemu/topology/clx_4_var2_emul_hbw.xml, line 69 at r6](https://reviewable.io/reviews/memkind/memkind/474#-MRV791T1560WvuyCO-x:-MRVDVuG8UzPV_qZ52Ne:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/afee22df6f590dcfafb598d424d41dcb0e7c8f2d/utils/qemu/topology/clx_4_var2_emul_hbw.xml#L69)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

And should be opposite
</blockquote></details>

Done.

**Pull request merged**
