### PR TITLE
PMEM parametrized tests

### PR DESCRIPTION
**Pull request by abonisl**
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/69)

### CODE REVIEW

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 564 at r1](https://reviewable.io/reviews/memkind/memkind/69#-LLdybh07ERn-FpD2hpN:-LLdybh07ERn-FpD2hpO:buorpzc) ([raw file](https://github.com/memkind/memkind/blob/4e66e962d6500ef37cfd8d94d8a1f3dab7a788f8/test/memkind_pmem_tests.cpp#L564)):*
> ```cpp
> }
> 
> TEST_F(MemkindPmemTests, test_TC_MEMKIND_PmemKinds)
> ```

this test could be removed:
test_TC_MEMKIND_PmemCreateDestroyKindLoopWithMallocSmallSize perform simillar functionality

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 321 at r2](https://reviewable.io/reviews/memkind/memkind/69#-LLhz_Al9JNIY6ibWo1w:-LLhz_Al9JNIY6ibWo1x:b-1d0keq) ([raw file](https://github.com/memkind/memkind/blob/245a2331ef47f567b923756cef5f3d0d6c8653d9/test/memkind_pmem_tests.cpp#L321)):*
> ```
> test_TC_MEMKIND_PmemReallocValue
> ```
rename to test_TC_MEMKIND_PmemReallocIncreaseSize

**Comment by michalbiesek** [comment]
___
*[test/alloc_performance_tests.cpp, line 1958 at r2](https://reviewable.io/reviews/memkind/memkind/69#-LLmjNe2CAwnWB2ykbJD:-LLmjNe2CAwnWB2ykbJE:bjepopj) ([raw file](https://github.com/memkind/memkind/blob/245a2331ef47f567b923756cef5f3d0d6c8653d9/test/alloc_performance_tests.cpp#L1958)):*
> ```
> test_TC_MEMKIND_PMEM_ALLOCATOR_malloc_1_thread_100_bytes
> ```
test_TC_MEMKIND_PMEM_malloc_1_thread_100_bytes

**Comment by michalbiesek** [comment]
___
*[test/alloc_performance_tests.cpp, line 2178 at r2](https://reviewable.io/reviews/memkind/memkind/69#-LLmjUw67r5Oy9JPIs8M:-LLmjUw67r5Oy9JPIs8N:bhj6dna) ([raw file](https://github.com/memkind/memkind/blob/245a2331ef47f567b923756cef5f3d0d6c8653d9/test/alloc_performance_tests.cpp#L2178)):*
> ```
> AllocPerformanceTest
> ```
Please do it AllocPerformanceTest as seperate PR - it will be easier on our side to update Jenkins configuration

**Comment by michalbiesek** [comment]
___
*[test/allocator_perf_tool/AllocatorFactory.hpp, line 91 at r2](https://reviewable.io/reviews/memkind/memkind/69#-LLmkcfGBK4mcxHAoJYK:-LLmkcfGBK4mcxHAoJYL:b3kqx) ([raw file](https://github.com/memkind/memkind/blob/245a2331ef47f567b923756cef5f3d0d6c8653d9/test/allocator_perf_tool/AllocatorFactory.hpp#L91)):*
> ```cpp
>                                       AllocatorTypes::MEMKIND_HBW_PREFERRED_GBTLB);
>         memkind_allocators[AllocatorTypes::MEMKIND_PMEM] =
> 		    MemkindAllocatorWithTimer(MEMKIND_PMEM, AllocatorTypes::MEMKIND_PMEM);
> ```

.

**Comment by michalbiesek** [comment]
___
*[test/allocator_perf_tool/AllocatorFactory.hpp, line 59 at r2](https://reviewable.io/reviews/memkind/memkind/69#-LLmkePa-5jmLR-FrGDD:-LLmkePa-5jmLR-FrGDE:bcktvlk) ([raw file](https://github.com/memkind/memkind/blob/245a2331ef47f567b923756cef5f3d0d6c8653d9/test/allocator_perf_tool/AllocatorFactory.hpp#L59)):*
> ```cpp
>     AllocatorFactory()
>     {
>         memkind_create_pmem(PMEM_DIR, PMEM_PART_SIZE, &MEMKIND_PMEM);
> ```

I'm not sure is this You want to achieve it here. Execute AllocPerformanceTest.test_TC_MEMKIND_PMEM_realloc_72_thread_100_bytes and see what happened. You create kind for every thread. Check status of this operation, consider moving creating operation somewhere else but as I mention before do it in seperate PR.

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 337 at r2](https://reviewable.io/reviews/memkind/memkind/69#-LLmlB5mBJ5mB85rBePD:-LLmlB5mBJ5mB85rBePE:b-o0up3a) ([raw file](https://github.com/memkind/memkind/blob/245a2331ef47f567b923756cef5f3d0d6c8653d9/test/memkind_pmem_tests.cpp#L337)):*
> ```cpp
>     ASSERT_EQ(*test1, *test2);
> 
>     memkind_free(pmem_kind, test1);
> ```

This is Undefined Behaviour.

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 420 at r2](https://reviewable.io/reviews/memkind/memkind/69#-LLmlXvm-LT_IVkFFlNV:-LLmlXvm-LT_IVkFFlNW:b-5rck0z) ([raw file](https://github.com/memkind/memkind/blob/245a2331ef47f567b923756cef5f3d0d6c8653d9/test/memkind_pmem_tests.cpp#L420)):*
> ```cpp
>     timer.start();
>     do {
>         size = rand() % (std::get<0>(GetParam()) + 1 - std::get<1>(GetParam())) + std::get<1>(GetParam());
> ```

don't use rand - my intention is to have test which are repeatable.

**Comment by michalbiesek** [comment]
Please extend test for memkind_posix_memalign:
-with calling wrong alignment parameter which will not be power of 2 and less than sizeof(void*)  check error return code (EINVAL) and see that memory wasn't allocated.
-with calling wrong alignment parameter which will be power of 2 but less than sizeof(void*) check error return code (EINVAL) and see that memory wasn't allocated.
-with calling wrong alignment parameter which will not be power of 2 and greater than sizeof(void*)  check error return code (EINVAL) and see that memory wasn't allocated.
-with calling wrong alignment parameter which will be power of 2 and equal sizeof(void*) check status for success and see that memory was allocated.
-with calling wiht very large value of size ( maybe SIZE_MAX) to see that error return code ENOMEM is returned

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 127 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM6rkCm4fCuI33R_pNb:-LM6rkCnDt9KbAKRCUDJ:b-va1in5) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L127)):*
> ```
> size0
> ```
pass value directly without size0 variable - just like in test_TC_MEMKIND_PmemMallocSizeMax

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 178 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM6uAi5EdIveva-BlGi:-LM6uAi5EdIveva-BlGj:b-km461k) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L178)):*
> ```
> -1
> ```
Don't use negative values - use SIZE_MAX instead of

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 318 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM6up3g-NRUEXFeM6tl:-LM6up3g-NRUEXFeM6tm:b-oa3lu) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L318)):*
> ```
> size
> ```
pass 0 directly like in test_TC_MEMKIND_PmemReallocSizeMax

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 330 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM6yQgs0tNKg93Si1Wb:-LM6yQgtEK8hE5IEkwvP:bnlym0y) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L330)):*
> ```
> test = memkind_realloc(pmem_kind, test, SIZE_MAX);
> ```
Don't use same variable in realloc as parameter and as return variable - instead of use new variable.

Let's imagine scenario when You pass valid pointer as argument:
int size = 100;
void * ptr = malloc(100);
 ptr = realloc(ptr, MAGIC_VALUE);

Be aware that, when realloc fails, it doesn't free the memory block pointed to by argument ptr.

In code above You have dangling pointer, because You overwrite ptr with NULL value and lose the adress of memory which should be free.

Form the code in test, in other way with new variable, add code:

void *new_test =nullptr;
new_test = memkind_realloc(pmem_kind, test, SIZE_MAX);
ASSERT_TRUE(new_test == nullptr);

This apply to other realloc tests.

Don't forget add here memkind_free.

I will add information in manual about realloc, that when size is zero memory is free and realloc returns null pointer.

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 369 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM72HKj3gJJfxadgKus:-LM72HKj3gJJfxadgKut:b-cl03x6) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L369)):*
> ```cpp
>     test2 = (char*)memkind_realloc(pmem_kind, test1, size);
>     ASSERT_TRUE(test2 != nullptr);
>     ASSERT_EQ(*val, *test2);
> ```

I think You could replace this with memcmp.

status = memcmp ( test1, test2, sizeof(val));

and assert status against 0.

Therefore You will be sure that whole string was correctly reallocated.

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 359 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM72kcc3aBzpFbCKtZ1:-LM72kcc3aBzpFbCKtZ2:b-9salvz) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L359)):*
> ```
> test_TC_MEMKIND_PmemReallocValue
> ```
test_TC_MEMKIND_PmemReallocIncreaseSize

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 359 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM72mHp8e7MltGzIvYY:-LM72mHp8e7MltGzIvYZ:b-qu3ij5) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L359)):*
> ```
> char val[]
> ```
could be const

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 460 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM75Ugm4rq5L4pyia6O:-LM75Ugm4rq5L4pyia6P:b-phjvjz) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L460)):*
> ```
> 1*5
> ```
.

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 329 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM7BDPm-2Tqis6Ao9rS:-LM7BDPm-2Tqis6Ao9rT:bhbgjxg) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L329)):*
> ```
> memkind_realloc(pmem_kind, test, SIZE_MAX);
> ```
please change line above to:
errno = 0;
test = memkind_realloc(pmem_kind, test, SIZE_MAX);
ASSERT_TRUE(errno == ENOMEM);

I will add information in manual about setting errno variable, in case of failure of realloc operation.

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 526 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM7DTYHBJY1obyaVHr-:-LM7DTYI3YbTcqvlZ4KY:b-r4sh7v) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L526)):*
> ```
> 4
> ```
sizeof(void*) /2

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 546 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM7ELkmEOWbR6UmC1HA:-LM7ELkmEOWbR6UmC1HB:b-hz1klm) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L546)):*
> ```cpp
> }
> 
> TEST_F(MemkindPmemTests, test_TC_MEMKIND_PmemPosixMemalignLowestAlignment)
> ```

Could You please extend memkind_posix_memalign test with cover the following requirement?
If size is 0, then memkind_posix_memalign() returns NULL.

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 460 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM7UmhADC2iEXFgV1fL:-LM7UmhADC2iEXFgV1fM:b-9o3spm) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L460)):*
> ```
> 1*5
> ```
Don't use Magic number.
Please use some  variable, like 
const double test_malloc_time = 5;

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 662 at r3](https://reviewable.io/reviews/memkind/memkind/69#-LM7WDSVDQ2HyhLjbSn7:-LM7WDSVDQ2HyhLjbSn8:b-wn7me2) ([raw file](https://github.com/memkind/memkind/blob/3f347c1a03241c81bd6b8fd2bf2bb9778200b120/test/memkind_pmem_tests.cpp#L662)):*
> ```
> memkind_create_pmem
> ```
What about memkind_destroy_kind ?

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 133 at r4](https://reviewable.io/reviews/memkind/memkind/69#-LM7lrccCOxXoPG4z_MQ:-LM7lrccCOxXoPG4z_MR:b-dkscj7) ([raw file](https://github.com/memkind/memkind/blob/77697686ae0612557b4c6ac4c2225e885ad2dbce/test/memkind_pmem_tests.cpp#L133)):*
> ```cpp
> {
>     void *test1 = nullptr;
> ```

errno = 0;

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 170 at r4](https://reviewable.io/reviews/memkind/memkind/69#-LM7luwQ5a4QXUJXxihm:-LM7luwQ5a4QXUJXxihn:b-dkscj7) ([raw file](https://github.com/memkind/memkind/blob/77697686ae0612557b4c6ac4c2225e885ad2dbce/test/memkind_pmem_tests.cpp#L170)):*
> ```cpp
>     size_t size = std::get<0>(GetParam());
>     size_t num = std::get<1>(GetParam());
> ```

errno = 0;

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 328 at r5](https://reviewable.io/reviews/memkind/memkind/69#-LM7w8sFBWcW3eum6nJz:-LM7w8sGBnBP5Ar4ZZa3:b-fveigu) ([raw file](https://github.com/memkind/memkind/blob/ecd5436e6417a269421fa068413b1d6483a3438b/test/memkind_pmem_tests.cpp#L328)):*
> ```
> test
> ```
new_test

**Comment by abonisl** [comment]
Ok done. Also added new tests PmemFreeNullptr and PmemReallocDecreaseSize.
and removed test_TC_MEMKIND_PmemAlignment (will be back in the next pr)

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 167 at r7](https://reviewable.io/reviews/memkind/memkind/69#-LMLiCri0Nd3QEwr-Ta-:-LMaIMpVATcfuOZa6DCq:br0owj3) ([raw file](https://github.com/memkind/memkind/blob/d96131492198164ca89bb0c4fe7811caa5b0d36b/test/memkind_pmem_tests.cpp#L167)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

> ```
>   if(size == SIZE_MAX || num == SIZE_MAX) {
> ```
@michalbiesek you were against this logic, there is solution as adding the errno as third parameter and checking for all the cases. Pls give some feedback to the idea.
</blockquote></details>

2 of 5 case check these line - that's why I were against the logic of this test. This could be achieved in other way, see for example TC_MEMKIND_PmemReallocSizeMax,test_TC_MEMKIND_PmemMallocSizeMax, - the check errno value against ENOMEM.

My idea in this case would be extract these two pair values ({SIZE_MAX,1},{10,SIZE_MAX}) to separate test like:

test_TC_MEMKIND_PmemCallocSizeMax with size = SIZE_MAX and num =1
test_TC_MEMKIND_PmemCallocNumMax with size = 10 and num =SIZE_MAX

Rest of the values would check scenario with zero value as size or num - therefore I would rename it test_TC_MEMKIND_PmemCallocSize to test_TC_MEMKIND_PmemCallocZero

**Comment by michalbiesek** [comment]
___
*[test/memkind_pmem_tests.cpp, line 671 at r9](https://reviewable.io/reviews/memkind/memkind/69#-LMh06El1ncnlr2MLBfP:-LMkos-781JcGCsUXXS_:bjh0w6y) ([raw file](https://github.com/memkind/memkind/blob/672de7dc94385305f352d19fc7ec97e6b02b72a1/test/memkind_pmem_tests.cpp#L671)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ASSERT_TRUE(i > 0);
> ```
Test fails because of this assert
</blockquote></details>

It is the issue with memkind_posix_memalign and free it. This is already covered by separate PR86. I don't want that this will block whole PR.
You could end this test if there is no memory. Add Comment with TODO to point that this is issue with posix_mem_align and test should be updated after resolving this - You could refer in comment to PR#86

**Pull request merged**
