### PR TITLE
Feat hwloc rpm build

### PR DESCRIPTION
**Pull request by michalbiesek**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/446)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/446)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[utils/docker/README.md, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/446#-MQCBB_MEyKTP_dad8xe:-MQCBB_MEyKTP_dad8xf:btcx89c) ([raw file](https://github.com/memkind/memkind/blob/0b72a509afd25349da43c936b43ba69f31ee68e2/utils/docker/README.md#L26)):*
> ```Markdown
> * **HWLOC_LIBRARY_VERSION** - hwloc library version.
> For fully testing MEMKIND_HIGHEST_CAPACITY_LOCALITY, MEMKIND_HIGHEST_BANDWIDTH, MEMKIND_LOWEST_LATENCY, hwloc library version tag must be passed as parameter,
> see https://github.com/open-mpi/hwloc/tags.
> ```

Not quite. If I used tag `hwloc-2.4.0` then I would get `HWLOC_FILTER_VERSION=wloc-2.4.0` in docker_install_hwloc.sh, right?. It's better to place here an example how exactly this variable should look like.

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 10 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/446#-:-MQpXF1N3RfwEISggaeW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 10 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/446)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[utils/docker/README.md, line 24 at r2](https://reviewable.io/reviews/memkind/memkind/446#-MQp_fjGAH_JhVk9NVn4:-MQp_fjGAH_JhVk9NVn5:b-vgleeh) ([raw file](https://github.com/memkind/memkind/blob/e165c996a1e3529fc1d1b63d900451c5eca0801a/utils/docker/README.md#L24)):*
> ```Markdown
> see https://github.com/pmem/ndctl/tags.
> 
> * **ENABLE_HWLOC** - controls install hwloc library.
> ```

installation of? or simply: install hwloc library
___
*[utils/docker/README.md, line 25 at r2](https://reviewable.io/reviews/memkind/memkind/446#-MQpa2E2EmtN2aQYF9ti:-MQpa2E2EmtN2aQYF9tj:bs5ldhl) ([raw file](https://github.com/memkind/memkind/blob/e165c996a1e3529fc1d1b63d900451c5eca0801a/utils/docker/README.md#L25)):*
> ```Markdown
> 
> * **ENABLE_HWLOC** - controls install hwloc library.
> For fully testing MEMKIND_HBW*, MEMKIND_HIGHEST_BANDWIDTH, MEMKIND_LOWEST_LATENCY, MEMKIND_*LOCAL hwloc library version must be installed as Setting **ENABLE_HWLOC** to 1 causes install hwloc library
> ```

(...) must be installed. Setting (...) to 1 runs the installation of hwloc library.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/446)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[utils/docker/README.md, line 24 at r2](https://reviewable.io/reviews/memkind/memkind/446#-MQp_fjGAH_JhVk9NVn4:-MQpcRL13KwQyrS5WJ04:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e165c996a1e3529fc1d1b63d900451c5eca0801a/utils/docker/README.md#L24)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

installation of? or simply: install hwloc library
</blockquote></details>

Done.
___
*[utils/docker/README.md, line 25 at r2](https://reviewable.io/reviews/memkind/memkind/446#-MQpa2E2EmtN2aQYF9ti:-MQpcRnI6xWrgUX4BM9q:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e165c996a1e3529fc1d1b63d900451c5eca0801a/utils/docker/README.md#L25)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

(...) must be installed. Setting (...) to 1 runs the installation of hwloc library.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/446#-:-MQplOAM-bN8N1dhao6q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
