### PR TITLE
Fix in coverage script to prevent timeout

### PR DESCRIPTION
**Pull request by kasiawasiuta**
### Types of changes

- [x] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/368)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/368)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kasiawasiuta, @michalbiesek, and @PatKamin)

___
*[utils/docker/docker_run_coverage.sh, line 18 at r1](https://reviewable.io/reviews/memkind/memkind/368#-MG3xi1x-sEUj2poQLWa:-MG3xi1x-sEUj2poQLWb:b-8i6lpq) ([raw file](https://github.com/memkind/memkind/blob/02a31e7327b4f93e7342d9b65e72b04345fa79b0/utils/docker/docker_run_coverage.sh#L18)):*
> ```
> ROOT_DIR
> ```
nit: maybe CODECOV_DIR or CODECOV_LOCAL_DIR ?
___
*[utils/docker/docker_run_coverage.sh, line 20 at r1](https://reviewable.io/reviews/memkind/memkind/368#-MG3xqFR1rD5gC_rtpNk:-MG3xqFR1rD5gC_rtpNl:blyyt1y) ([raw file](https://github.com/memkind/memkind/blob/02a31e7327b4f93e7342d9b65e72b04345fa79b0/utils/docker/docker_run_coverage.sh#L20)):*
> ```
> $ROOT_DIR
> ```
can we add  "" around the variable name (same in curl command below) - just like in e.g. "$MEMKIND_REPO_PATH" below ?

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/368)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @kasiawasiuta, @michalbiesek, and @PatKamin)

___
*[utils/docker/docker_run_coverage.sh, line 8 at r1](https://reviewable.io/reviews/memkind/memkind/368#-MG40R3JDB3KdGsd7P1s:-MG40R3K2_CH0DvbJv0B:b-j6mlm8) ([raw file](https://github.com/memkind/memkind/blob/02a31e7327b4f93e7342d9b65e72b04345fa79b0/utils/docker/docker_run_coverage.sh#L8)):*
> ```Shell
> # calculates coverage and creates online report using codecov provided script
> # The script is taken from a3be2bd tag, to prevent from using later version
> # with hardcoded strict curl timeout
> ```

maybe you could refer here https://github.com/codecov/codecov-bash/pull/338

**Review by kasiawasiuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/368)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[utils/docker/docker_run_coverage.sh, line 8 at r1](https://reviewable.io/reviews/memkind/memkind/368#-MG40R3JDB3KdGsd7P1s:-MG7bk81CCjgXREl_R5C:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/02a31e7327b4f93e7342d9b65e72b04345fa79b0/utils/docker/docker_run_coverage.sh#L8)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

maybe you could refer here https://github.com/codecov/codecov-bash/pull/338
</blockquote></details>

Done.
___
*[utils/docker/docker_run_coverage.sh, line 20 at r1](https://reviewable.io/reviews/memkind/memkind/368#-MG3xqFR1rD5gC_rtpNk:-MG7fAzd-k47E3IIKfHq:b-5h0lsh) ([raw file](https://github.com/memkind/memkind/blob/02a31e7327b4f93e7342d9b65e72b04345fa79b0/utils/docker/docker_run_coverage.sh#L20)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> $ROOT_DIR
> ```
can we add  "" around the variable name (same in curl command below) - just like in e.g. "$MEMKIND_REPO_PATH" below ?
</blockquote></details>

Better be safe than sorry ;)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/368)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @kasiawasiuta, @michalbiesek, and @PatKamin)

___
*[utils/docker/docker_run_coverage.sh, line 6 at r2](https://reviewable.io/reviews/memkind/memkind/368#-MG7vBCY53X8-hJ1Uc-s:-MG7vBCY53X8-hJ1Uc-t:bhg39mv) ([raw file](https://github.com/memkind/memkind/blob/f2044361f83f070d1a09a42d739c176a5de802db/utils/docker/docker_run_coverage.sh#L6)):*
> ```Shell
> 
> # docker_run_coverage.sh - is called inside a Docker container;
> # calculates coverage and creates online report using codecov provided script
> ```

Missing dot at the end of this sentence.
___
*[utils/docker/docker_run_coverage.sh, line 7 at r2](https://reviewable.io/reviews/memkind/memkind/368#-MG7vd4fDOLm-Qw0J4SH:-MG7vd4fDOLm-Qw0J4SI:b-deuk0i) ([raw file](https://github.com/memkind/memkind/blob/f2044361f83f070d1a09a42d739c176a5de802db/utils/docker/docker_run_coverage.sh#L7)):*
> ```Shell
> # docker_run_coverage.sh - is called inside a Docker container;
> # calculates coverage and creates online report using codecov provided script
> # The script is taken from a3be2bd tag, to prevent from using later version
> ```

`to prevent usage of` or `to prevent (who? what?) from using`
https://www.ef.com/wwen/english-resources/english-grammar/using-prevent/

**Review by kasiawasiuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/368)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[utils/docker/docker_run_coverage.sh, line 6 at r2](https://reviewable.io/reviews/memkind/memkind/368#-MG7vBCY53X8-hJ1Uc-s:-MG8JLP26gNCKCRNnRd2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f2044361f83f070d1a09a42d739c176a5de802db/utils/docker/docker_run_coverage.sh#L6)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Missing dot at the end of this sentence.
</blockquote></details>

Done.
___
*[utils/docker/docker_run_coverage.sh, line 7 at r2](https://reviewable.io/reviews/memkind/memkind/368#-MG7vd4fDOLm-Qw0J4SH:-MG8Iv991-Uf4sub2MTy:b-8y69w3) ([raw file](https://github.com/memkind/memkind/blob/f2044361f83f070d1a09a42d739c176a5de802db/utils/docker/docker_run_coverage.sh#L7)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`to prevent usage of` or `to prevent (who? what?) from using`
https://www.ef.com/wwen/english-resources/english-grammar/using-prevent/
</blockquote></details>

I removed "from", it matches one of the examples from the site you provided

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/368#-:-MG8KRbHC4X6I-f23Yzc:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/368#-:-MG8Kh3o53q499zdXYVX:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
