### PR TITLE
Fix python tests to work with python3

### PR DESCRIPTION
**Pull request by TomekIdczak97**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [x] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/377)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Comment by michalbiesek** [comment]
@pmem-bot-ae
test this please

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/377)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @TomekIdczak97)

___
*[test/dax_kmem_env_var_test.py, line 29 at r1](https://reviewable.io/reviews/memkind/memkind/377#-MHzORmk2VEyXHHJ3ABE:-MHzORmk2VEyXHHJ3ABF:b-dxcg2g) ([raw file](https://github.com/memkind/memkind/blob/a947709f796c5971418b3d6e6a7b5a59aa562c4c/test/dax_kmem_env_var_test.py#L29)):*
> ```Python
>     def test_TC_MEMKIND_dax_kmem_env_var_compare_nodemask_default_and_env_variable(self):
>         """ This test checks whether dax_kmem_nodemask_default and dax_kmem_nodemask_env_variable have the same value """
>         dax_kmem_nodemask_default = self.get_dax_kmem_nodes().decode("utf-8")
> ```

Let me know if python also need to be updated related to this change
___
*[test/dax_kmem_env_var_test.py, line 39 at r1](https://reviewable.io/reviews/memkind/memkind/377#-MHzOP6Z3tFDHyj-auiu:-MHzOP6Z3tFDHyj-auiv:b5iyrz0) ([raw file](https://github.com/memkind/memkind/blob/a947709f796c5971418b3d6e6a7b5a59aa562c4c/test/dax_kmem_env_var_test.py#L39)):*
> ```Python
>         output, retcode = self.cmd_helper.execute_cmd(command)
>         assert retcode != 0, self.fail_msg.format("\nError: Execution of: \'{0}\' returns: {1} \noutput: {2}".format(command, retcode, output))
>         assert self.expected_libnuma_warning == output.decode("utf-8"), self.fail_msg.format("Error: expected libnuma warning ({0}) " \
> ```

https://github.com/memkind/memkind/blob/70de7eb44cdd58ca46655943a8955e8348166f98/test/hbw_detection_test.py#L28 I believe this file should be also updated.

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/377)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @michalbiesek and @TomekIdczak97)

___
*[test/dax_kmem_env_var_test.py, line 29 at r1](https://reviewable.io/reviews/memkind/memkind/377#-MHzORmk2VEyXHHJ3ABE:-MHzXYXCEfAfra4TyUyn:b-i3r2t9) ([raw file](https://github.com/memkind/memkind/blob/a947709f796c5971418b3d6e6a7b5a59aa562c4c/test/dax_kmem_env_var_test.py#L29)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Let me know if python also need to be updated related to this change
</blockquote></details>

It works with both python 2 and 3.

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/377)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @TomekIdczak97)

___
*[test/dax_kmem_env_var_test.py, line 25 at r1](https://reviewable.io/reviews/memkind/memkind/377#-MHzgd0P2LAGswz_-CBT:-MHzgd0P2LAGswz_-CBU:b3flcj4) ([raw file](https://github.com/memkind/memkind/blob/a947709f796c5971418b3d6e6a7b5a59aa562c4c/test/dax_kmem_env_var_test.py#L25)):*
> ```Python
>         assert retcode == 0, self.fail_msg.format("\nError: Execution of \'{0}\' returns {1}, \noutput: {2}".format(command, retcode, output))
>         print("\nExecution of {} returns output {}".format(command, output))
>         return output
> ```

Decode byte string here instead of doing this in every place where this method is used.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/377)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @TomekIdczak97)

___
*[test/dax_kmem_env_var_test.py, line 23 at r2](https://reviewable.io/reviews/memkind/memkind/377#-MITL4uK6nEiHfLByi7U:-MITL4uK6nEiHfLByi7V:b-7avxp) ([raw file](https://github.com/memkind/memkind/blob/a6e31e39a5e1d44e90e70149643a5430605105f3/test/dax_kmem_env_var_test.py#L23)):*
> ```Python
>             command = "MEMKIND_DAX_KMEM_NODES={}".format(nodemask) + command
>         output, retcode = self.cmd_helper.execute_cmd(command)
>         assert retcode == 0, self.fail_msg.format("\nError: Execution of \'{0}\' returns {1}, \noutput: {2}".format(command, retcode, output))
> ```

I think that every print statement in these two files should have `output` decoded. Otherwise you will get sth like:  b'output string' in console. Please, verify.

**Review by TomekIdczak97 — COMMENTED** [review]
Trigger tests, please.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/377#-:-MITsroBEXcX1mpH20Iw:b5i7kv0)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[test/dax_kmem_env_var_test.py, line 25 at r1](https://reviewable.io/reviews/memkind/memkind/377#-MHzgd0P2LAGswz_-CBT:-MITsGQMAulMSxKUkF72:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a947709f796c5971418b3d6e6a7b5a59aa562c4c/test/dax_kmem_env_var_test.py#L25)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Decode byte string here instead of doing this in every place where this method is used.
</blockquote></details>

Done.
___
*[test/dax_kmem_env_var_test.py, line 29 at r1](https://reviewable.io/reviews/memkind/memkind/377#-MHzORmk2VEyXHHJ3ABE:-MITsI-x7VcNSPI55dOk:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a947709f796c5971418b3d6e6a7b5a59aa562c4c/test/dax_kmem_env_var_test.py#L29)):*
<details><summary><i>Previously, TomekIdczak97 (tomekidczak) wrote…</i></summary><blockquote>

It works with both python 2 and 3.
</blockquote></details>

Done.
___
*[test/dax_kmem_env_var_test.py, line 39 at r1](https://reviewable.io/reviews/memkind/memkind/377#-MHzOP6Z3tFDHyj-auiu:-MITsIpy6H0DwEy3UIF7:bm47nm0) ([raw file](https://github.com/memkind/memkind/blob/a947709f796c5971418b3d6e6a7b5a59aa562c4c/test/dax_kmem_env_var_test.py#L39)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

https://github.com/memkind/memkind/blob/70de7eb44cdd58ca46655943a8955e8348166f98/test/hbw_detection_test.py#L28 I believe this file should be also updated.
</blockquote></details>

With newest changes it is not needed in any of pytest .py files, it is fixed in cmd_helper's method.
___
*[test/dax_kmem_env_var_test.py, line 23 at r2](https://reviewable.io/reviews/memkind/memkind/377#-MITL4uK6nEiHfLByi7U:-MITsDiKAHL2plg3cFS8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a6e31e39a5e1d44e90e70149643a5430605105f3/test/dax_kmem_env_var_test.py#L23)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I think that every print statement in these two files should have `output` decoded. Otherwise you will get sth like:  b'output string' in console. Please, verify.
</blockquote></details>

Done.

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/377)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[test/dax_kmem_env_var_test.py, line 39 at r1](https://reviewable.io/reviews/memkind/memkind/377#-MHzOP6Z3tFDHyj-auiu:-MITt1Fi8E2JFh_-pci8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a947709f796c5971418b3d6e6a7b5a59aa562c4c/test/dax_kmem_env_var_test.py#L39)):*
<details><summary><i>Previously, TomekIdczak97 (tomekidczak) wrote…</i></summary><blockquote>

With newest changes it is not needed in any of pytest .py files, it is fixed in cmd_helper's method.
</blockquote></details>

Done.

**Comment by michalbiesek** [comment]
@pmem-bot-ae
test this please

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/377#-:-MIU4TJwCdC_Gx4J759_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/377)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
