### PR TITLE
Parse policy name passed in ENV var and use it when creating tiered kind

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/575)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/575)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[include/memkind_memtier.h, line 31 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW-yqkd8KOhYsUCQ2L3:-MW-yqkd8KOhYsUCQ2L4:b18io01) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/include/memkind_memtier.h#L31)):*
> ```objc
>      */
>     MEMTIER_POLICY_CIRCULAR = 0,
>     MEMTIER_POLICY_MAX_VALUE
> ```

please use the comment form as in https://github.com/memkind/memkind/blob/5576ea811ca812d717cb8e16e19ea7fd67a5d7fd/include/memkind.h#L81-L84

I will provide a proper update to memkind_stat_type in separate PR.
___
*[tiering/ctl.c, line 146 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW03Arg6YlrNR_wVlw3:-MW03Arg6YlrNR_wVlw4:b-90mgm5) ([raw file](https://github.com/memkind/memkind/blob/2f3859431e610c917eb5b5df6d01c5b71adb7e4d/tiering/ctl.c#L146)):*
> ```
> // TODO: Allow multiple kinds to be created
> ```
I would rather remove this comment when the multiple kinds creation would be performed here.
___
*[tiering/ctl.c, line 172 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW03-zM6DS-0Zkfwi7I:-MW03-zM6DS-0Zkfwi7J:b-nr30lg) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/ctl.c#L172)):*
> ```
> = -1;
> ```
this could be even without an assignment to -1
___
*[tiering/ctl.c, line 174 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW035Z54Ni4yHGQDgPo:-MW035Z54Ni4yHGQDgPp:b-pi13g8) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/ctl.c#L174)):*
> ```
> *policy = MEMTIER_POLICY_MAX_VALUE;
> ```
.
___
*[tiering/ctl.c, line 197 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW02gxKDji_D5TnJfc7:-MW02gxKDji_D5TnJfc8:b-6jc3tc) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/ctl.c#L197)):*
> ```
>         if (ret < 0) {
>             break;
>         }
> ```
why break, can't you leave the logic as it was?
> ```
>        if (ret != 0) {
>           log_err("Failed to parse query: %s", qbuf);
>         return -1;
> ```
___
*[tiering/ctl.c, line 204 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW01_Rs4IpO4o_r8sIt:-MW01_Rt72DkvZ3wf15a:b5kazps) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/ctl.c#L204)):*
> ```
> ret < 0
> ```
why you change the form with checking ret status?
___
*[tiering/memtier.c, line 142 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW-xPDs59gN5OTQJUpb:-MW-xPDs59gN5OTQJUpc:b-a4uafn) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/memtier.c#L142)):*
> ```
> ctl_policy_to_str(
> ```
This temporary translation to string should be currently done on this layer. 
See that with every additional change on this layer there will be more to clean up related to this TODO above.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/575)* status: all files reviewed, 11 unresolved discussions (waiting on @bratpiorka)

___
*[test/tiering_tests.py, line 305 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW05hZG4jVM-0Dg4QZ4:-MW05hZG4jVM-0Dg4QZ5:b-9jpqs3) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/test/tiering_tests.py#L305)):*
> ```Python
>     def test_negative_unsupported_policy(self):
>         output = self.get_ld_preload_cmd_output(
>             "MEMKIND_MEM_TIERING_CONFIG=DRAM:1,ABC", validate_retcode=False)
> ```

Add test case with numbers and mix of alphanumeric values.
___
*[test/tiering_tests.py, line 315 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW05HmZ3U4eWRuBS5M4:-MW05Hm_Dryi9fjyDyFU:b-dxwun5) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/test/tiering_tests.py#L315)):*
> ```Python
>             "," + self.default_policy, validate_retcode=False)
> 
>         # NOTE: only last query is threated as a policy, so first from two
> ```

nit: treated
___
*[test/tiering_tests.py, line 316 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW05MeP5fQOa39r8IvU:-MW05MeP5fQOa39r8IvV:bp6bloj) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/test/tiering_tests.py#L316)):*
> ```Python
> 
>         # NOTE: only last query is threated as a policy, so first from two
>         # polices will be threated as kind
> ```

nit: policies treated
___
*[tiering/ctl.c, line 188 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW08J2p35BOy7kaKkg1:-MW08J2qC3rw1vGFBysN:b-b4gtwl) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/ctl.c#L188)):*
> ```C
>     }
> 
>     while (qbuf != NULL) {
> ```

nit: Now that you know exactly how many queries are in the qbuf, this can be a `for` loop.

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/575)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[include/memkind_memtier.h, line 31 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW-yqkd8KOhYsUCQ2L3:-MW3PkxyBdsXU5EhxJKL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/include/memkind_memtier.h#L31)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

please use the comment form as in https://github.com/memkind/memkind/blob/5576ea811ca812d717cb8e16e19ea7fd67a5d7fd/include/memkind.h#L81-L84

I will provide a proper update to memkind_stat_type in separate PR.
</blockquote></details>

Done.
___
*[test/tiering_tests.py, line 305 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW05hZG4jVM-0Dg4QZ4:-MW3Pmb26uRI-55rbmLE:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/test/tiering_tests.py#L305)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add test case with numbers and mix of alphanumeric values.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 146 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW03Arg6YlrNR_wVlw3:-MW3Qa0sDXvtS7kyExmz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2f3859431e610c917eb5b5df6d01c5b71adb7e4d/tiering/ctl.c#L146)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> // TODO: Allow multiple kinds to be created
> ```
I would rather remove this comment when the multiple kinds creation would be performed here.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 172 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW03-zM6DS-0Zkfwi7I:-MW3Q1fkAVqvLpLp7_o1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/ctl.c#L172)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> = -1;
> ```
this could be even without an assignment to -1
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 174 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW035Z54Ni4yHGQDgPo:-MW3Q34s71XvaocwUwEK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/ctl.c#L174)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> *policy = MEMTIER_POLICY_MAX_VALUE;
> ```
.
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 188 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW08J2p35BOy7kaKkg1:-MW3Q6UX3XDIoXbOR6MI:b3zqxxl) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/ctl.c#L188)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Now that you know exactly how many queries are in the qbuf, this can be a `for` loop.
</blockquote></details>

I prefer while(query_count) because we don't need additional counter
___
*[tiering/ctl.c, line 197 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW02gxKDji_D5TnJfc7:-MW3QFQ7DMyUyjACVr6b:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/ctl.c#L197)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         if (ret < 0) {
>             break;
>         }
> ```
why break, can't you leave the logic as it was?
> ```
>        if (ret != 0) {
>           log_err("Failed to parse query: %s", qbuf);
>         return -1;
> ```
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 204 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW01_Rs4IpO4o_r8sIt:-MW3QGaEDS3iJQ1n8a-M:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/ctl.c#L204)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ret < 0
> ```
why you change the form with checking ret status?
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 142 at r1](https://reviewable.io/reviews/memkind/memkind/575#-MW-xPDs59gN5OTQJUpb:-MW3QZPHBfVDbYD_WeIq:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cfe2d6bd1224dba26cec4c766bc0356dc597feb4/tiering/memtier.c#L142)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ctl_policy_to_str(
> ```
This temporary translation to string should be currently done on this layer. 
See that with every additional change on this layer there will be more to clean up related to this TODO above.
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/575)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[tiering/memtier.c, line 123 at r2](https://reviewable.io/reviews/memkind/memkind/575#-MW3VhTG91qcMuQGXguH:-MW3VhTG91qcMuQGXguI:b-on0zf2) ([raw file](https://github.com/memkind/memkind/blob/7f517f2fe566945207b50d7f095323b10245f862/tiering/memtier.c#L123)):*
> ```
> char 
> ```
const char
___
*[tiering/memtier.c, line 131 at r2](https://reviewable.io/reviews/memkind/memkind/575#-MW3VjBLBePx51itueHB:-MW3VjBLBePx51itueHC:b-72d2lc) ([raw file](https://github.com/memkind/memkind/blob/7f517f2fe566945207b50d7f095323b10245f862/tiering/memtier.c#L131)):*
> ```
> char
> ```
const char

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/575)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[tiering/memtier.c, line 123 at r2](https://reviewable.io/reviews/memkind/memkind/575#-MW3VhTG91qcMuQGXguH:-MW3aCId1p2GvzDOv23-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7f517f2fe566945207b50d7f095323b10245f862/tiering/memtier.c#L123)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> char 
> ```
const char
</blockquote></details>

Done.
___
*[tiering/memtier.c, line 131 at r2](https://reviewable.io/reviews/memkind/memkind/575#-MW3VjBLBePx51itueHB:-MW3aCfZEK6xVv0ZD0az:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7f517f2fe566945207b50d7f095323b10245f862/tiering/memtier.c#L131)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> char
> ```
const char
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/575)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/575)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[tiering/memtier.c, line 123 at r3](https://reviewable.io/reviews/memkind/memkind/575#-MW3dirQ8wG9iachAfrN:-MW3dirQ8wG9iachAfrO:bl0oofo) ([raw file](https://github.com/memkind/memkind/blob/469c0529ddead0c8c93640fdb3f13c912eccbfd9/tiering/memtier.c#L123)):*
> ```C
> // TODO - move this code during refactoring after implementing support for
> // multiple kinds
> const char *policy_to_str(memtier_policy_t policy)
> ```

nit:static

**Review by PatKamin — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/575)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[tiering/ctl.c, line 180 at r4](https://reviewable.io/reviews/memkind/memkind/575#-MW4UicPDoYyJj0Rhog7:-MW4UicPDoYyJj0Rhog8:b-9b9c45) ([raw file](https://github.com/memkind/memkind/blob/de1c9e5fd4b34e54a17f70ed64a926f0b13ea8ec/tiering/ctl.c#L180)):*
> ```C
>                                   ratio_value);
>         } else {
>             ret = ctl_parse_policy(qbuf, policy);
> ```

I think that there should be a check whether we have at least two queries, one for a kind and one for a policy. In case of not satisfying these requirements, should return -1 and abort.

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/575)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @michalbiesek and @PatKamin)

___
*[tiering/ctl.c, line 180 at r4](https://reviewable.io/reviews/memkind/memkind/575#-MW4UicPDoYyJj0Rhog7:-MW4Z5RGBxT2D99T6B-a:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/de1c9e5fd4b34e54a17f70ed64a926f0b13ea8ec/tiering/ctl.c#L180)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I think that there should be a check whether we have at least two queries, one for a kind and one for a policy. In case of not satisfying these requirements, should return -1 and abort.
</blockquote></details>

Done.

**Comment by michalbiesek** [comment]
Please rebase

**Pull request merged**
