### PR TITLE
Add Cascade Lake topology

### PR DESCRIPTION
**Pull request by michalbiesek**
- provide handling Cascade Lake in python engine
- add two example topologies

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/435)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/435)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @michalbiesek)

___
*[utils/qemu/topology/csl_4_var1.xml, line 69 at r1](https://reviewable.io/reviews/memkind/memkind/435#-MOlAnGQ4tYD2-Jt5kkw:-MOlAnGQ4tYD2-Jt5kkx:b-rgvgsx) ([raw file](https://github.com/memkind/memkind/blob/7e8eedb0064dac47b58723d60187a2df6a038136/utils/qemu/topology/csl_4_var1.xml#L69)):*
> ```XML
>         </distances>
>       </cell>
>       <cell id='5'  memory='1536' unit='MiB'>
> ```

Is it possible to omit `id=5` so the numbering would be the same as on the bare metal? PMEM would be on 4, 6 and 7 numa nodes.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/435)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[utils/qemu/topology/csl_4_var1.xml, line 69 at r1](https://reviewable.io/reviews/memkind/memkind/435#-MOlAnGQ4tYD2-Jt5kkw:-MOlQrhw1qZ3gTHWZk_F:bj081dm) ([raw file](https://github.com/memkind/memkind/blob/7e8eedb0064dac47b58723d60187a2df6a038136/utils/qemu/topology/csl_4_var1.xml#L69)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Is it possible to omit `id=5` so the numbering would be the same as on the bare metal? PMEM would be on 4, 6 and 7 numa nodes.
</blockquote></details>

I change it to 4 sockets variant as we discuss offline.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/435)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @michalbiesek)

___
*[utils/qemu/topology/csl_4_var1.xml, line 18 at r2](https://reviewable.io/reviews/memkind/memkind/435#-MOpeOXu2jOE6b0m3Cu3:-MOpeOXv0TczvzA-89VT:bpsv8ix) ([raw file](https://github.com/memkind/memkind/blob/78f35929ce222112ebb0ce05b7ed69962b0271f2/utils/qemu/topology/csl_4_var1.xml#L18)):*
> ```XML
>           <sibling id='0' value='10'/>
>           <sibling id='1' value='21'/>
>           <sibling id='2' value='31'/>
> ```

Rename these files from csl... to clx...

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/435)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[utils/qemu/topology/csl_4_var1.xml, line 18 at r2](https://reviewable.io/reviews/memkind/memkind/435#-MOpeOXu2jOE6b0m3Cu3:-MOpjS5F3zOoZHGTysSQ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/78f35929ce222112ebb0ce05b7ed69962b0271f2/utils/qemu/topology/csl_4_var1.xml#L18)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Rename these files from csl... to clx...
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/435#-:-MOpjn9l541JJvB3Nhfh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
