### PR TITLE
[RFC] Executable to measure counter impact

### PR DESCRIPTION
**Pull request by michalbiesek**
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/626)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/626)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @michalbiesek and @PatKamin)

___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 134 at r1](https://reviewable.io/reviews/memkind/memkind/626#-MZCsPb80da_U2FUu0vU:-MZCsPb80da_U2FUu0vV:b1g951o) ([raw file](https://github.com/memkind/memkind/blob/741995f45b79b04a2f245542fd063be9bcbd1cd5/utils/memtier_counter_bench/memtier_counter_bench.cpp#L134)):*
> ```cpp
>         memtier_builder_add_tier(m_tier_builder, MEMKIND_REGULAR, 1);
>         memtier_builder_set_policy(m_tier_builder,
>                                    MEMTIER_POLICY_STATIC_THRESHOLD);
> ```

Could you add a class for dynamic threshold as well? Even with default parameters (no CTL API used)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/626#-:-MZD3fHW6mvO39dwx8GY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/626)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @bratpiorka and @PatKamin)

___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 134 at r1](https://reviewable.io/reviews/memkind/memkind/626#-MZCsPb80da_U2FUu0vU:-MZD3ie1BwtvIOCQsdzZ:bv0nhla) ([raw file](https://github.com/memkind/memkind/blob/741995f45b79b04a2f245542fd063be9bcbd1cd5/utils/memtier_counter_bench/memtier_counter_bench.cpp#L134)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Could you add a class for dynamic threshold as well? Even with default parameters (no CTL API used)
</blockquote></details>

Done. -s static threshold, -d dynamic threshold ratio is 1:1 for both.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/626)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/626)* status: all files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 7 at r3](https://reviewable.io/reviews/memkind/memkind/626#-MZDJMSu8EY9Jce_v_nH:-MZDJMSu8EY9Jce_v_nI:b-74axmj) ([raw file](https://github.com/memkind/memkind/blob/585cd1abe8601907cea447809fab08ff081b8a76/utils/memtier_counter_bench/memtier_counter_bench.cpp#L7)):*
> ```cpp
> 
> #include <argp.h>
> ```

nit: Remove empty line.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 13 at r3](https://reviewable.io/reviews/memkind/memkind/626#-MZDJUJx5ZlszocXRheh:-MZDJUJx5ZlszocXRhei:b-74axmj) ([raw file](https://github.com/memkind/memkind/blob/585cd1abe8601907cea447809fab08ff081b8a76/utils/memtier_counter_bench/memtier_counter_bench.cpp#L13)):*
> ```cpp
> #include <stdint.h>
> #include <thread>
> ```

nit: Remove empty line.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 16 at r3](https://reviewable.io/reviews/memkind/memkind/626#-MZDMl3bA2FYOKDezxZc:-MZDMl3bA2FYOKDezxZd:bcqrz3d) ([raw file](https://github.com/memkind/memkind/blob/585cd1abe8601907cea447809fab08ff081b8a76/utils/memtier_counter_bench/memtier_counter_bench.cpp#L16)):*
> ```cpp
> #include <vector>
> 
> #define ITERATION 10000000
> ```

Move this global to the main() function as there is only one case you use this variable.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 37 at r3](https://reviewable.io/reviews/memkind/memkind/626#-MZDNcBv8tOBylxwwtv7:-MZDNcBv8tOBylxwwtv8:b-hqeim3) ([raw file](https://github.com/memkind/memkind/blob/585cd1abe8601907cea447809fab08ff081b8a76/utils/memtier_counter_bench/memtier_counter_bench.cpp#L37)):*
> ```cpp
>             for (size_t k = 0; k < nworks; ++k) {
>                 vthread[k] = std::thread([&]() {
>                     std::vector<void *> v;
> ```

Move repetitive code to a new function to highlight that you do here the same thing.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/626)* status: all files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/626)* status: all files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 24 at r3](https://reviewable.io/reviews/memkind/memkind/626#-MZDaR_q5AhL0Z9tQdbz:-MZDaR_q5AhL0Z9tQdc-:b-ysy52v) ([raw file](https://github.com/memkind/memkind/blob/585cd1abe8601907cea447809fab08ff081b8a76/utils/memtier_counter_bench/memtier_counter_bench.cpp#L24)):*
> ```cpp
>     {
>         if (nworks == 1) {
>             std::vector<void *> v;
> ```

This binary has a potential of being a benchmark itself. I mean, you can drop the dependence on the `perf` tool and count the time here with `std::chrono` or sth like that. Then you could count the number of operations per second performed by each object and print it to the stdout. You could even make this in a loop of five and calculate the mean result which will be printed out.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/626)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 7 at r3](https://reviewable.io/reviews/memkind/memkind/626#-MZDJMSu8EY9Jce_v_nH:-MZHza149nQaegx4H9V1:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/585cd1abe8601907cea447809fab08ff081b8a76/utils/memtier_counter_bench/memtier_counter_bench.cpp#L7)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Remove empty line.
</blockquote></details>

Done
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 13 at r3](https://reviewable.io/reviews/memkind/memkind/626#-MZDJUJx5ZlszocXRheh:-MZHzfaS1wdxNCxKGmjA:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/585cd1abe8601907cea447809fab08ff081b8a76/utils/memtier_counter_bench/memtier_counter_bench.cpp#L13)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Remove empty line.
</blockquote></details>

Done
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 16 at r3](https://reviewable.io/reviews/memkind/memkind/626#-MZDMl3bA2FYOKDezxZc:-MZHzwz82zOcIXq61ygt:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/585cd1abe8601907cea447809fab08ff081b8a76/utils/memtier_counter_bench/memtier_counter_bench.cpp#L16)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Move this global to the main() function as there is only one case you use this variable.
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 24 at r3](https://reviewable.io/reviews/memkind/memkind/626#-MZDaR_q5AhL0Z9tQdbz:-MZI2TlhBZvjHhoqA20c:b-2427uh) ([raw file](https://github.com/memkind/memkind/blob/585cd1abe8601907cea447809fab08ff081b8a76/utils/memtier_counter_bench/memtier_counter_bench.cpp#L24)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This binary has a potential of being a benchmark itself. I mean, you can drop the dependence on the `perf` tool and count the time here with `std::chrono` or sth like that. Then you could count the number of operations per second performed by each object and print it to the stdout. You could even make this in a loop of five and calculate the mean result which will be printed out. 
</blockquote></details>

Just FYI: With the current approach I start each process again - see that if I do this in the loop by the second run for example I don't call jemalloc to create arena (the situation in case of second run is different) - Nevertheless done
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 37 at r3](https://reviewable.io/reviews/memkind/memkind/626#-MZDNcBv8tOBylxwwtv7:-MZI-pAz-rGOTMt1m5XZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/585cd1abe8601907cea447809fab08ff081b8a76/utils/memtier_counter_bench/memtier_counter_bench.cpp#L37)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Move repetitive code to a new function to highlight that you do here the same thing.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/626)* status: all files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 22 at r4](https://reviewable.io/reviews/memkind/memkind/626#-MZIr32s0yKguznzw0e6:-MZIr32s0yKguznzw0e7:b-12dt7j) ([raw file](https://github.com/memkind/memkind/blob/cd8cf1b0dab3a582d8ddb68e2adc7cd024f696b2/utils/memtier_counter_bench/memtier_counter_bench.cpp#L22)):*
> ```cpp
>     {
>         std::chrono::time_point<std::chrono::system_clock> start, end;
>         start = std::chrono::system_clock::now();
> ```

auto start = ...
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 39 at r4](https://reviewable.io/reviews/memkind/memkind/626#-MZIr8Qy4MExXfihTBmy:-MZIr8Qy4MExXfihTBmz:b-3r5206) ([raw file](https://github.com/memkind/memkind/blob/cd8cf1b0dab3a582d8ddb68e2adc7cd024f696b2/utils/memtier_counter_bench/memtier_counter_bench.cpp#L39)):*
> ```cpp
>             }
>         }
>         end = std::chrono::system_clock::now();
> ```

auto end = ...
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 41 at r4](https://reviewable.io/reviews/memkind/memkind/626#-MZIuPfC5yTC4Z9JxrFE:-MZIuPfD48uyOZXzJX09:b-2pr687) ([raw file](https://github.com/memkind/memkind/blob/cd8cf1b0dab3a582d8ddb68e2adc7cd024f696b2/utils/memtier_counter_bench/memtier_counter_bench.cpp#L41)):*
> ```cpp
>         end = std::chrono::system_clock::now();
>         auto time_per_op =
>             static_cast<double>((end - start).count()) / m_iteration;
> ```

I might be wrong, but I think that you should divide it further by nthreads, because every thread will make m_iterations.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/626)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 22 at r4](https://reviewable.io/reviews/memkind/memkind/626#-MZIr32s0yKguznzw0e6:-MZM9A7T2VY8X8gYl5EC:b-o8hh6c) ([raw file](https://github.com/memkind/memkind/blob/cd8cf1b0dab3a582d8ddb68e2adc7cd024f696b2/utils/memtier_counter_bench/memtier_counter_bench.cpp#L22)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

auto start = ...
</blockquote></details>

not possible :)
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 39 at r4](https://reviewable.io/reviews/memkind/memkind/626#-MZIr8Qy4MExXfihTBmy:-MZM9C62CCr-dPpt5WDd:b-o8hh6c) ([raw file](https://github.com/memkind/memkind/blob/cd8cf1b0dab3a582d8ddb68e2adc7cd024f696b2/utils/memtier_counter_bench/memtier_counter_bench.cpp#L39)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

auto end = ...
</blockquote></details>

not possible :)
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 41 at r4](https://reviewable.io/reviews/memkind/memkind/626#-MZIuPfC5yTC4Z9JxrFE:-MZMFWAe1jnlo7yzrPMx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cd8cf1b0dab3a582d8ddb68e2adc7cd024f696b2/utils/memtier_counter_bench/memtier_counter_bench.cpp#L41)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I might be wrong, but I think that you should divide it further by nthreads, because every thread will make m_iterations.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/626#-:-MZMGevW5rbzGtp6YMPb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
