### PR TITLE
updates to AUTHORS

### PR DESCRIPTION
**Pull request by kilobyte**
I'm not convinced there's much point in keeping this file, but if we do, let's update it.

But maybe we should delete it instead?

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/782)

### CODE REVIEW

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/782)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/782)* status: all files reviewed, 2 unresolved discussions (waiting on @kilobyte)

___
*[AUTHORS, line 8 at r3](https://reviewable.io/reviews/memkind/memkind/782#-MzG5NOb1fJVVvsFiW9_:-MzG5NOb1fJVVvsFiW9a:b-1j3od0) ([raw file](https://github.com/memkind/memkind/blob/b73ae1935771c96a75274912b9c9baa0c7cc105b/AUTHORS#L8)):*
> ```
> Hector Barajas Villalobos <hector.a.barajas.villalobos@intel.com>
> Ruchira Sasanka <ruchira.sasanka@intel.com>
> Krzysztof Kulakowski <krzysztof.kulakowski@intel.com>
> ```

kułakowski
___
*[AUTHORS, line 13 at r3](https://reviewable.io/reviews/memkind/memkind/782#-MzG5T1FAaJGRAuAw_B1:-MzG5T1FAaJGRAuAw_B2:b-qxvmsw) ([raw file](https://github.com/memkind/memkind/blob/b73ae1935771c96a75274912b9c9baa0c7cc105b/AUTHORS#L13)):*
> ```
> Grzegorz Ozanski <grzegorz.ozanski@intel.com>
> Artur Koziej <artur.koziej@intel.com>
> Jakub Dlugolecki <jakub.dlugolecki@intel.com>
> ```

Długołęcki

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/782)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @bratpiorka)

___
*[AUTHORS, line 8 at r3](https://reviewable.io/reviews/memkind/memkind/782#-MzG5NOb1fJVVvsFiW9_:-MzH1PZX0nB6o2a-GYuZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b73ae1935771c96a75274912b9c9baa0c7cc105b/AUTHORS#L8)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

kułakowski
</blockquote></details>

Done.
___
*[AUTHORS, line 13 at r3](https://reviewable.io/reviews/memkind/memkind/782#-MzG5T1FAaJGRAuAw_B1:-MzH1PxXCVC3KLwrLQGM:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b73ae1935771c96a75274912b9c9baa0c7cc105b/AUTHORS#L13)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Długołęcki
</blockquote></details>

Done.

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/782)* status: all files reviewed, 2 unresolved discussions (waiting on @kilobyte)

___
*[AUTHORS, line 13 at r3](https://reviewable.io/reviews/memkind/memkind/782#-MzG5T1FAaJGRAuAw_B1:-MzJg23354-Q5cDKibRV:b3kxg) ([raw file](https://github.com/memkind/memkind/blob/b73ae1935771c96a75274912b9c9baa0c7cc105b/AUTHORS#L13)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ę
___
*[AUTHORS, line 11 at r4](https://reviewable.io/reviews/memkind/memkind/782#-MzJg7eNAnsRNiG5R64F:-MzJg7eNAnsRNiG5R64G:b-o9jwqx) ([raw file](https://github.com/memkind/memkind/blob/bc5c76b59ee36d806b6c58931435fd15a2428807/AUTHORS#L11)):*
> ```
> Rafael Aquini <aquini@redhat.com>
> Alexandr Konovalov <alexandr.konovalov@intel.com>
> Grzegorz Ozanski <grzegorz.ozanski@intel.com>
> ```

Ozański ? Ożański? nie jestem pewien

**Review by bratpiorka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/782)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac and @PatKamin)

**Pull request merged**
