### PR TITLE
Remove slab metadata

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/764)

### CODE REVIEW

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, 7 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/764)* status: 13 of 18 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[MANIFEST, line 444 at r3](https://reviewable.io/reviews/memkind/memkind/764#-MxDkMIi6PNAeGdkZOGg:-MxDkMIjCX57UHUfKmw2:bu8255y) ([raw file](https://github.com/memkind/memkind/blob/84da0db621d45b0a7fe627fbe502eac8e3cb4fb3/MANIFEST#L444)):*
> ```
> src/memkind_regular.c
> src/mmap_tracing_queue.c
> src/slab_tracker.cpp
> ```

Add to this file the rest of new files.
___
*[src/fast_pool_allocator.c, line 37 at r3](https://reviewable.io/reviews/memkind/memkind/764#-MxDpliD7rJX4YuxcLKh:-MxDpliEAgPJoLTbKgsu:bqf30mb) ([raw file](https://github.com/memkind/memkind/blob/84da0db621d45b0a7fe627fbe502eac8e3cb4fb3/src/fast_pool_allocator.c#L37)):*
> ```C
>     if (size == 0)
>         return NULL;
>     size_t size_rank = size_to_size_rank(size);
> ```

size_rank -> rank_size for better readability (in other places too, like the names of functions, ie. size_to_rank_size)
___
*[src/fast_slab_allocator.c, line 7 at r1](https://reviewable.io/reviews/memkind/memkind/764#-MxDg0oa9Nb32hplkNBv:-MxDg0obDeqKCPAeFmq2:btnw3lh) ([raw file](https://github.com/memkind/memkind/blob/73f10b1a17fb3e0c2bf25bc7b5e2940f9919522b/src/fast_slab_allocator.c#L7)):*
> ```C
> 
> // SPDX-License-Identifier: BSD-2-Clause
> /* Copyright (C) 2021-2022 Intel Corporation. */
> ```

Leave one license.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 11 of 11 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/764)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/764)* status: 12 of 18 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[MANIFEST, line 444 at r3](https://reviewable.io/reviews/memkind/memkind/764#-MxDkMIi6PNAeGdkZOGg:-MxF4z2LBdrmrTORYrHz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/84da0db621d45b0a7fe627fbe502eac8e3cb4fb3/MANIFEST#L444)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add to this file the rest of new files.
</blockquote></details>

Done.
___
*[src/fast_pool_allocator.c, line 37 at r3](https://reviewable.io/reviews/memkind/memkind/764#-MxDpliD7rJX4YuxcLKh:-MxF6b-OExX4Cy1X18-q:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/84da0db621d45b0a7fe627fbe502eac8e3cb4fb3/src/fast_pool_allocator.c#L37)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

size_rank -> rank_size for better readability (in other places too, like the names of functions, ie. size_to_rank_size)
</blockquote></details>

Done.
___
*[src/fast_slab_allocator.c, line 7 at r1](https://reviewable.io/reviews/memkind/memkind/764#-MxDg0oa9Nb32hplkNBv:-MxF5Fkv6wLZQ75vq1Up:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/73f10b1a17fb3e0c2bf25bc7b5e2940f9919522b/src/fast_slab_allocator.c#L7)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Leave one license.
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/764)* status: all files reviewed, 3 unresolved discussions (waiting on @PatKamin)

**Review by PatKamin — APPROVED** [review]
> Reviewed 3 of 11 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/764)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
