### PR TITLE
Bandwidth kinds

### PR DESCRIPTION
**Pull request by michalbiesek**
Based on #471 - only last commit is valid

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/475)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/475)* status: all files reviewed, 5 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[man/memkind.3, line 733 at r1](https://reviewable.io/reviews/memkind/memkind/475#-MRZtmqmCgxuDg4_EqqV:-MRZtj9R05nBozoqNkxj:bsc1e90) ([raw file](https://github.com/memkind/memkind/blob/cfb93d3fae8a05e99cf1f4cceb9dc3f39ac19c54/man/memkind.3#L733)):*
> ```
> om a NUMA nod
> ```
already described above
___
*[src/memkind.c, line 292 at r1](https://reviewable.io/reviews/memkind/memkind/475#-MRZtwDzCUnAAneabw-x:-MRZtwDzCUnAAneabw-y:bo0h1e4) ([raw file](https://github.com/memkind/memkind/blob/cfb93d3fae8a05e99cf1f4cceb9dc3f39ac19c54/src/memkind.c#L292)):*
> ```C
>         &MEMKIND_LOWEST_LATENCY_LOCAL_PREFERRED_STATIC;
> MEMKIND_EXPORT struct memkind *MEMKIND_HIGHEST_BANDWIDTH_LOCAL =
>         &MEMKIND_HIGHEST_BANDWIDTH_LOCAL_STATIC;
> ```

bandwidth
___
*[src/memkind.c, line 294 at r1](https://reviewable.io/reviews/memkind/memkind/475#-MRZtxuR4B8QVobVc0CA:-MRZtxuR4B8QVobVc0CB:bo0h1e4) ([raw file](https://github.com/memkind/memkind/blob/cfb93d3fae8a05e99cf1f4cceb9dc3f39ac19c54/src/memkind.c#L294)):*
> ```C
>         &MEMKIND_HIGHEST_BANDWIDTH_LOCAL_STATIC;
> MEMKIND_EXPORT struct memkind *MEMKIND_HIGHEST_BANDWIDTH_LOCAL_PREFERRED =
>         &MEMKIND_HIGHEST_BANDWIDTH_LOCAL_PREFERRED_STATIC;
> ```

bandwidth
___
*[src/memkind.c, line 328 at r1](https://reviewable.io/reviews/memkind/memkind/475#-MRZtyx-Dzp9sje4qWIv:-MRZtyx-Dzp9sje4qWIw:bo0h1e4) ([raw file](https://github.com/memkind/memkind/blob/cfb93d3fae8a05e99cf1f4cceb9dc3f39ac19c54/src/memkind.c#L328)):*
> ```C
>         [MEMKIND_PARTITION_LOWEST_LATENCY_LOCAL] = &MEMKIND_LOWEST_LATENCY_LOCAL_STATIC,
>         [MEMKIND_PARTITION_LOWEST_LATENCY_LOCAL_PREFERRED] = &MEMKIND_LOWEST_LATENCY_LOCAL_PREFERRED_STATIC,
>         [MEMKIND_PARTITION_HIGHEST_BANDWIDTH_LOCAL] = &MEMKIND_HIGHEST_BANDWIDTH_LOCAL_STATIC,
> ```

bandwidth
___
*[src/memkind.c, line 329 at r1](https://reviewable.io/reviews/memkind/memkind/475#-MRZtzNk3JOhMI9Fu9fG:-MRZtzNk3JOhMI9Fu9fH:bo0h1e4) ([raw file](https://github.com/memkind/memkind/blob/cfb93d3fae8a05e99cf1f4cceb9dc3f39ac19c54/src/memkind.c#L329)):*
> ```C
>         [MEMKIND_PARTITION_LOWEST_LATENCY_LOCAL_PREFERRED] = &MEMKIND_LOWEST_LATENCY_LOCAL_PREFERRED_STATIC,
>         [MEMKIND_PARTITION_HIGHEST_BANDWIDTH_LOCAL] = &MEMKIND_HIGHEST_BANDWIDTH_LOCAL_STATIC,
>         [MEMKIND_PARTITION_HIGHEST_BANDWIDTH_LOCAL_PREFERRED] = &MEMKIND_HIGHEST_BANDWIDTH_LOCAL_PREFERRED_STATIC,
> ```

bandwidth

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/475)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[man/memkind.3, line 733 at r1](https://reviewable.io/reviews/memkind/memkind/475#-MRZtmqmCgxuDg4_EqqV:-MR_4hor3FHVVLxOT84u:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cfb93d3fae8a05e99cf1f4cceb9dc3f39ac19c54/man/memkind.3#L733)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> ```
> om a NUMA nod
> ```
already described above
</blockquote></details>

Done.
___
*[man/memkind.3, line 733 at r1](https://reviewable.io/reviews/memkind/memkind/475#-MRPPdJpmvjwUHkAtzsa-r1-733:-MR_4i6H8gDnC-PB9p0U:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/cfb93d3fae8a05e99cf1f4cceb9dc3f39ac19c54/man/memkind.3#L733)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This should not be part of this commit.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/475)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/475#-:-MR_7C-uEahAWIiFwG8S:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/475#-:-MR_86s51xJuXiXZhR1M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
