### PR TITLE
Refactor allocator lookup in fast_pool_allocator

### PR DESCRIPTION
**Pull request by maciekpac**
### Description
Refactoring done for code clarity and performance

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [x] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/805)

### CODE REVIEW

**Review by bratpiorka — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/805)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte and @PatKamin)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/805)* status: 0 of 18 files reviewed, 11 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[include/memkind/internal/critnib.h, line 5 at r2](https://reviewable.io/reviews/memkind/memkind/805#-N0-hva6CJNrPjCngsmT:-N00HSR8458pM1S4kK6r:b-l9fwry) ([raw file](https://github.com/memkind/memkind/blob/e3d78ff7f4b3773e5f7b894cf76bdf0c4d43a259/include/memkind/internal/critnib.h#L5)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

What is the purpose of this define?
</blockquote></details>

I think it was a header guard. Changed to ```#pragma once```
___
*[src/critnib.c, line 385 at r1](https://reviewable.io/reviews/memkind/memkind/805#-N0-dWduEFYElpvcxM6k:-N00Qwn03hW2Yez0Roz2:b-2zy9qq) ([raw file](https://github.com/memkind/memkind/blob/ef248c04745adb7dcaeb8d42299bffc3406e9ad2/src/critnib.c#L385)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Should we care about 32-bit platforms in mtt_allocator implementation?
</blockquote></details>

Removed support and added compile-time check
___
*[src/critnib.c, line 514 at r1](https://reviewable.io/reviews/memkind/memkind/805#-N0-g71U0v4aGHjsejAA:-N00TcBbCG9yvpu3LNUZ:b-o663ic) ([raw file](https://github.com/memkind/memkind/blob/ef248c04745adb7dcaeb8d42299bffc3406e9ad2/src/critnib.c#L514)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Some formatting issue?
</blockquote></details>

It looks like it's present in the original code: https://github.com/kilobyte/critnib/blob/master/critnib.c

The comment and formatting issue goes all the way down to initial commit: "Initial import from PMDK.":

https://github.com/kilobyte/critnib/blob/8935927b2a7b4eb8b691d41f7f1a424c3063f9ab/critnib.c#L531

I contacted the author (Adam) and he said it corresponded to backspace - corrections applied
___
*[src/critnib.c, line 134 at r2](https://reviewable.io/reviews/memkind/memkind/805#-N0-lFyx6vOA4Icu3EJn:-N00PuXO5FQwf3JJqOZ-:bixine3) ([raw file](https://github.com/memkind/memkind/blob/e3d78ff7f4b3773e5f7b894cf76bdf0c4d43a259/src/critnib.c#L134)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Do we have a guarantee that c is not NULL?
</blockquote></details>

added assert
___
*[src/slab_tracker.cpp, line 14 at r1](https://reviewable.io/reviews/memkind/memkind/805#-N0-gYZm1yZPAr_8tqGc:-N00qUav64lua1y9LLU1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ef248c04745adb7dcaeb8d42299bffc3406e9ad2/src/slab_tracker.cpp#L14)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove the commented out code.
</blockquote></details>

Done.
___
*[src/slab_tracker.cpp, line 42 at r1](https://reviewable.io/reviews/memkind/memkind/805#-N0-hEeSDVWiWtdgHKOt:-N00qaEr8Ql2YH6UttkY:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ef248c04745adb7dcaeb8d42299bffc3406e9ad2/src/slab_tracker.cpp#L42)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This question should be rephrased to a statement. AS I see there is no other option for a return value from the `critnib_insert`.
</blockquote></details>

Done.
___
*[include/memkind/internal/pmdk-compat.h, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/805#-N0-Mu_q8I_KN9nx6IW2:-N00HvkUDXaK4vmaZLaG:bklylkg) ([raw file](https://github.com/memkind/memkind/blob/ef248c04745adb7dcaeb8d42299bffc3406e9ad2/include/memkind/internal/pmdk-compat.h#L1)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add license header.
</blockquote></details>

Removed the file
___
*[include/memkind/internal/pmdk-compat.h, line 32 at r1](https://reviewable.io/reviews/memkind/memkind/805#-N0-NX2c8s8XO12w8V5o:-N00Peep52gnXXhuP63w:ba3dfob) ([raw file](https://github.com/memkind/memkind/blob/ef248c04745adb7dcaeb8d42299bffc3406e9ad2/include/memkind/internal/pmdk-compat.h#L32)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Either add a TODO here if you plan sth for these dummy functions, or remove them.
</blockquote></details>

Removed
___
*[include/memkind/internal/pmdk-compat.h, line 10 at r2](https://reviewable.io/reviews/memkind/memkind/805#-N0-jcPEEBCUV9ou2fUy:-N00PYjj6sgBa-_zr90_:ba3dfob) ([raw file](https://github.com/memkind/memkind/blob/e3d78ff7f4b3773e5f7b894cf76bdf0c4d43a259/include/memkind/internal/pmdk-compat.h#L10)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Removed
___
*[include/memkind/internal/pmdk-compat.h, line 12 at r2](https://reviewable.io/reviews/memkind/memkind/805#-N0-jdfnD5SX8GVBCWnS:-N00P_Au0eKHxrVB-870:ba3dfob) ([raw file](https://github.com/memkind/memkind/blob/e3d78ff7f4b3773e5f7b894cf76bdf0c4d43a259/include/memkind/internal/pmdk-compat.h#L12)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Removed
___
*[include/memkind/internal/pmdk-compat.h, line 13 at r2](https://reviewable.io/reviews/memkind/memkind/805#-N0-jOTG2xiLr6WP6a97:-N00PbMh21z5dkaxujjY:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/e3d78ff7f4b3773e5f7b894cf76bdf0c4d43a259/include/memkind/internal/pmdk-compat.h#L13)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

These defines can be moved to the critnib.c file. Moreover, I don't think that the code is clearer by replacing the pthred prefix with a util prefix for some of these functions if they were moved. This file could be removed.
</blockquote></details>

Done.

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r5, 5 of 7 files at r6, 12 of 12 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/805)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @kilobyte, @maciekpac, and @PatKamin)

___
*[include/memkind/internal/critnib.h, line 2 at r8](https://reviewable.io/reviews/memkind/memkind/805#-N00rjo413Il63RBDlqa:-N00rjo50aRt-zC6GoV9:bno6txo) ([raw file](https://github.com/memkind/memkind/blob/a704f7ed4ac64ca066419c4f2f70e9bca9692404/include/memkind/internal/critnib.h#L2)):*
> ```objc
> /* SPDX-License-Identifier: BSD-3-Clause */
> /* Copyright 2018, Intel Corporation */
> ```

nit: 2018-2022
___
*[src/critnib.c, line 58 at r8](https://reviewable.io/reviews/memkind/memkind/805#-N00tHZ-6oVRc2yuLb7N:-N00tHZ-6oVRc2yuLb7O:b-tqtvlh) ([raw file](https://github.com/memkind/memkind/blob/a704f7ed4ac64ca066419c4f2f70e9bca9692404/src/critnib.c#L58)):*
> ```C
> #include "memkind/internal/critnib.h"
> 
> #define util_lssb_index64(x) ((unsigned char)__builtin_ctzll(x))
> ```

This is not used.

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/805)* status: 5 of 18 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[src/critnib.c, line 58 at r8](https://reviewable.io/reviews/memkind/memkind/805#-N00tHZ-6oVRc2yuLb7N:-N00yfIT1PTkReMQkF6z:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/a704f7ed4ac64ca066419c4f2f70e9bca9692404/src/critnib.c#L58)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This is not used.
</blockquote></details>

Done.

**Review by PatKamin — APPROVED** [review]
> Reviewed 3 of 20 files at r9, 7 of 7 files at r11, 11 of 11 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/805)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Review by PatKamin — APPROVED** [review]
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/805)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Pull request merged**
