### PR TITLE
Handle failure scenarios in memtier_init

### PR DESCRIPTION
**Pull request by michalbiesek**
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/574)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/574#-:-MVzfHqV2oFaQDIPKTTG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/574#-:-MW-As0aEa9mZWJlSDuB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[test/tiering_tests.py, line 186 at r1](https://reviewable.io/reviews/memkind/memkind/574#-MW-AYEs3-Cph36aC_wu:-MW-AYEs3-Cph36aC_wv:b-s4suwp) ([raw file](https://github.com/memkind/memkind/blob/d7156357963008d62dd33e423f0c8a1033b746b1/test/tiering_tests.py#L186)):*
> ```Python
>             "Wrong message"
> 
>     def test_empty_confg(self):
> ```

config

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/574)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[test/tiering_tests.py, line 186 at r1](https://reviewable.io/reviews/memkind/memkind/574#-MW-AYEs3-Cph36aC_wu:-MW-DNdpACqJC0uzXCDc:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d7156357963008d62dd33e423f0c8a1033b746b1/test/tiering_tests.py#L186)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

config
</blockquote></details>

Done.

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/574#-:-MW-E3N-1IdyApxAjilS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/574)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Pull request merged**
