### PR TITLE
Add pool allocator

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/734)

### CODE REVIEW

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/734)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[test/memkind_memtier_data_movement_test.cpp, line 309 at r1](https://reviewable.io/reviews/memkind/memkind/734#-Mv2nPamBZxQRazuEgC9:-Mv2nPamBZxQRazuEgCA:b-spo8o6) ([raw file](https://github.com/memkind/memkind/blob/cb19327ad8afbc754aa84a65ddebe213800fcfe6/test/memkind_memtier_data_movement_test.cpp#L309)):*
> ```cpp
> }
> 
> TEST(PoolAlloc, Basic)
> ```

Please, create a class for this test. This file will grow bigger pretty fast. There is no need for plenty of other tests to have access to this function.

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/734)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[test/memkind_memtier_data_movement_test.cpp, line 309 at r1](https://reviewable.io/reviews/memkind/memkind/734#-Mv2nPamBZxQRazuEgC9:-Mv3VBEJ06abtnEx5VFK:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/cb19327ad8afbc754aa84a65ddebe213800fcfe6/test/memkind_memtier_data_movement_test.cpp#L309)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, create a class for this test. This file will grow bigger pretty fast. There is no need for plenty of other tests to have access to this function.
</blockquote></details>

Done

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/734)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/734)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac)

___
*[src/pool_allocator.c, line 25 at r2](https://reviewable.io/reviews/memkind/memkind/734#-Mv3btEJDblKiDgF5hJZ:-Mv3btEJDblKiDgF5hJ_:brruha2) ([raw file](https://github.com/memkind/memkind/blob/c9eed2ba3b68bb4679cbfd3d0a91b6562ae056b4/src/pool_allocator.c#L25)):*
> ```C
> 
> #ifndef MEMKIND_EXPORT
> #define MEMKIND_EXPORT __attribute__((visibility("default")))
> ```

this is already defined in "memkind_private.h"
___
*[src/pool_allocator.c, line 34 at r2](https://reviewable.io/reviews/memkind/memkind/734#-Mv3cSFj0vmcBXRLdgVF:-Mv3cSFk1HO3SbixF2Na:burz3ix) ([raw file](https://github.com/memkind/memkind/blob/c9eed2ba3b68bb4679cbfd3d0a91b6562ae056b4/src/pool_allocator.c#L34)):*
> ```C
> {
>     uint64_t idx;
>     asm("\tbsr %1, %0\n" : "=r"(idx) : "r"(n));
> ```

do you need \t and \n here?
___
*[src/pool_allocator.c, line 99 at r2](https://reviewable.io/reviews/memkind/memkind/734#-Mv3dG1e5Hxbp85e8Lx-:-Mv3dG1e5Hxbp85e8Lx0:bv7bm5c) ([raw file](https://github.com/memkind/memkind/blob/c9eed2ba3b68bb4679cbfd3d0a91b6562ae056b4/src/pool_allocator.c#L99)):*
> ```C
> // -------- public functions --------------------------------------------------
> 
> MEMKIND_EXPORT void *pool_allocator_malloc(PoolAllocator *pool, size_t size)
> ```

rename to pool_alloc_malloc to be consistent with slab_alloc_malloc

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/734)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/pool_allocator.c, line 25 at r2](https://reviewable.io/reviews/memkind/memkind/734#-Mv3btEJDblKiDgF5hJZ:-Mv5LAufCIPEWsMJsnxl:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c9eed2ba3b68bb4679cbfd3d0a91b6562ae056b4/src/pool_allocator.c#L25)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this is already defined in "memkind_private.h"
</blockquote></details>

Done.
___
*[src/pool_allocator.c, line 34 at r2](https://reviewable.io/reviews/memkind/memkind/734#-Mv3cSFj0vmcBXRLdgVF:-Mv5MrZCDfkOfl-YqIpB:b-5mrezb) ([raw file](https://github.com/memkind/memkind/blob/c9eed2ba3b68bb4679cbfd3d0a91b6562ae056b4/src/pool_allocator.c#L34)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

do you need \t and \n here?
</blockquote></details>

Actually, it looks like the code works without it. Removed.
___
*[src/pool_allocator.c, line 99 at r2](https://reviewable.io/reviews/memkind/memkind/734#-Mv3dG1e5Hxbp85e8Lx-:-Mv5LT62DmxkFek6BHZH:bi6ia82) ([raw file](https://github.com/memkind/memkind/blob/c9eed2ba3b68bb4679cbfd3d0a91b6562ae056b4/src/pool_allocator.c#L99)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

rename to pool_alloc_malloc to be consistent with slab_alloc_malloc
</blockquote></details>

pool_alloc_(create|destroy|malloc|free) doesn't really look good, it might suggest we are creating an allocation from a pool, not creating an allocator...

Also, we have MTTAllocator, not MTTAlloc...

slab_alloc was the odd one, not pool_allocator

What do you think now? Maybe I should modify slab's name instead?

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/734)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[src/pool_allocator.c, line 99 at r2](https://reviewable.io/reviews/memkind/memkind/734#-Mv3dG1e5Hxbp85e8Lx-:-MvIP2yY46ZNYmzG99sc:b-5g0t9g) ([raw file](https://github.com/memkind/memkind/blob/c9eed2ba3b68bb4679cbfd3d0a91b6562ae056b4/src/pool_allocator.c#L99)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

pool_alloc_(create|destroy|malloc|free) doesn't really look good, it might suggest we are creating an allocation from a pool, not creating an allocator...

Also, we have MTTAllocator, not MTTAlloc...

slab_alloc was the odd one, not pool_allocator

What do you think now? Maybe I should modify slab's name instead?
</blockquote></details>

yes, please rename slab

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/734)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/pool_allocator.c, line 99 at r2](https://reviewable.io/reviews/memkind/memkind/734#-Mv3dG1e5Hxbp85e8Lx-:-MvJYEOL6cJ1lBc7ncmb:bjxkj9a) ([raw file](https://github.com/memkind/memkind/blob/c9eed2ba3b68bb4679cbfd3d0a91b6562ae056b4/src/pool_allocator.c#L99)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

yes, please rename slab
</blockquote></details>

maybe in separate PR?

**Review by bratpiorka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/734)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

___
*[src/pool_allocator.c, line 99 at r2](https://reviewable.io/reviews/memkind/memkind/734#-Mv3dG1e5Hxbp85e8Lx-:-MvJescu9VuN39BYmxDH:b32wtd) ([raw file](https://github.com/memkind/memkind/blob/c9eed2ba3b68bb4679cbfd3d0a91b6562ae056b4/src/pool_allocator.c#L99)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

maybe in separate PR?
</blockquote></details>

ok

**Pull request merged**
