### PR TITLE
Check for return code in tiering python tests

### PR DESCRIPTION
**Pull request by PatKamin**
Replace check for a specific log message with a check of application's
return code.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/614)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/614)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[test/tiering_tests.py, line 62 at r1](https://reviewable.io/reviews/memkind/memkind/614#-MXbN_G98kpRw2Lah6RX:-MXbN_G98kpRw2Lah6RY:b-hgnpm0) ([raw file](https://github.com/memkind/memkind/blob/d14b7af209740cf6ef531cd64a6b7d2495d8e58c/test/tiering_tests.py#L62)):*
> ```
>         fail_msg = "Test failed with error: \nExecution of: '" + command + \
>             "' returns: " + str(retcode) + "\noutput: " + output
> ```
IMHO, In the case of negative tests, this message could be confusing.
___
*[test/tiering_tests.py, line 63 at r1](https://reviewable.io/reviews/memkind/memkind/614#-MXbLke-7v6h1eeRaVIY:-MXbLke04wljqlkeFg0r:b-vvuixf) ([raw file](https://github.com/memkind/memkind/blob/d14b7af209740cf6ef531cd64a6b7d2495d8e58c/test/tiering_tests.py#L63)):*
> ```
> if not negative_test:
> ```
reverse logic -> if negative_test

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/614)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[test/tiering_tests.py, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/614#-MXbOKG_9IAPpI2m_9GW:-MXbOKG_9IAPpI2m_9GX:b-sdnpu8) ([raw file](https://github.com/memkind/memkind/blob/d14b7af209740cf6ef531cd64a6b7d2495d8e58c/test/tiering_tests.py#L58)):*
> ```Python
>         log_level_env = self.log_prefix + "LOG_LEVEL=" + log_level \
>             if log_level else ""
>         command = " ".join([self.ld_preload_env, log_level_env,
> ```

https://github.com/memkind/memkind/blob/d87326ddd7346bfb3eabaddc07b31eb68db35891/tiering/ctl.c#L221 somehow related with your changes?

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/614)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[test/tiering_tests.py, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/614#-MXbOKG_9IAPpI2m_9GW:-MXfEbpl7NJ6CWBZ9JR_:b-o99vu1) ([raw file](https://github.com/memkind/memkind/blob/d14b7af209740cf6ef531cd64a6b7d2495d8e58c/test/tiering_tests.py#L58)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

https://github.com/memkind/memkind/blob/d87326ddd7346bfb3eabaddc07b31eb68db35891/tiering/ctl.c#L221 somehow related with your changes?
</blockquote></details>

Yes, I decided to remove these as well.
___
*[test/tiering_tests.py, line 62 at r1](https://reviewable.io/reviews/memkind/memkind/614#-MXbN_G98kpRw2Lah6RX:-MXfHFwnBXEMtIvwBeir:b-f6f073) ([raw file](https://github.com/memkind/memkind/blob/d14b7af209740cf6ef531cd64a6b7d2495d8e58c/test/tiering_tests.py#L62)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         fail_msg = "Test failed with error: \nExecution of: '" + command + \
>             "' returns: " + str(retcode) + "\noutput: " + output
> ```
IMHO, In the case of negative tests, this message could be confusing.
</blockquote></details>

Good point. I've shortened the message.
___
*[test/tiering_tests.py, line 63 at r1](https://reviewable.io/reviews/memkind/memkind/614#-MXbLke-7v6h1eeRaVIY:-MXfI6CX7LrJVh0-qJSz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d14b7af209740cf6ef531cd64a6b7d2495d8e58c/test/tiering_tests.py#L63)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if not negative_test:
> ```
reverse logic -> if negative_test
</blockquote></details>

Done.

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/614#-:-MXfctDT2VAPgE_Vg5gt:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/614#-:-MXfeqZ3EjNVWxa63uFT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
