### PR TITLE
Update README with changes in jemalloc

### PR DESCRIPTION
**Pull request by PatKamin**
Changes introduced with commit c3fb4e4ca65f174edff36249c3ff79b82b4112ab

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/720)

### CODE REVIEW

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte and @maciekpac)

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/720)* status: all files reviewed, 1 unresolved discussion (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[README, line 135 at r1](https://reviewable.io/reviews/memkind/memkind/720#-MrX2Rn43iAFzsjpf0pm:-MrX2Rn53TBGzcQsxuhf:b-yoxkpg) ([raw file](https://github.com/memkind/memkind/blob/57d6dc346d0bc0f5945a92678793c7b6b94f7eea/README#L135)):*
> ```
> - handling of custom hooks for metadata allocations
> - optimization for searching commands in mallctl
> - the build system has been lightly modified.
> ```

could you also update "lightly" to "slightly"?

**Review by maciekpac — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/720)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @kilobyte)

___
*[README, line 135 at r1](https://reviewable.io/reviews/memkind/memkind/720#-MrX2Rn43iAFzsjpf0pm:-MrX5KWk1gh3tHiu8p3L:b-pabohu) ([raw file](https://github.com/memkind/memkind/blob/57d6dc346d0bc0f5945a92678793c7b6b94f7eea/README#L135)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

could you also update "lightly" to "slightly"?
</blockquote></details>

Good point, but it looks like this is not a part of this commit. I think it would  be good to update, but I think I can already give "approve".

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/720)* status: all files reviewed, 1 unresolved discussion (waiting on @kilobyte and @maciekpac)

___
*[README, line 135 at r1](https://reviewable.io/reviews/memkind/memkind/720#-MrX2Rn43iAFzsjpf0pm:-MrX62XFDUe0LVhsxnbo:b-ercjch) ([raw file](https://github.com/memkind/memkind/blob/57d6dc346d0bc0f5945a92678793c7b6b94f7eea/README#L135)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Good point, but it looks like this is not a part of this commit. I think it would  be good to update, but I think I can already give "approve".
</blockquote></details>

I think that commit message could be updated with "+ fix typo" or sth similar

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/720)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @kilobyte)

___
*[README, line 135 at r1](https://reviewable.io/reviews/memkind/memkind/720#-MrX2Rn43iAFzsjpf0pm:-MrX6eQb04toff6MhFjm:b-orumjy) ([raw file](https://github.com/memkind/memkind/blob/57d6dc346d0bc0f5945a92678793c7b6b94f7eea/README#L135)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I think that commit message could be updated with "+ fix typo" or sth similar
</blockquote></details>

Good point

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/720)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/memkind/memkind/720#-MrX7YLHBsRZZoV21L8W):*
nit:
Changes introduced with commit ....
->
Changed introduced by the commit ....

I think it collocates better, but maybe someone else would like to comment, I'm not a linguist,

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/720)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/memkind/memkind/720#-MrX7YLHBsRZZoV21L8W):*
> Changed introduced by the commit ....
Change**s** introduced by the commit ....

Sorry, my last comment included a typo

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/720)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @maciekpac)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/memkind/memkind/720#-MrX7YLHBsRZZoV21L8W):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

> Changed introduced by the commit ....
Change**s** introduced by the commit ....

Sorry, my last comment included a typo
</blockquote></details>

I think this is auto-generated part of commit message

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/720)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @bratpiorka, @kilobyte, and @maciekpac)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/memkind/memkind/720#-MrX7YLHBsRZZoV21L8W):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I think this is auto-generated part of commit message
</blockquote></details>

Done.
___
*[README, line 135 at r1](https://reviewable.io/reviews/memkind/memkind/720#-MrX2Rn43iAFzsjpf0pm:-MrX96o78XKZ8KdAg3Wu:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/57d6dc346d0bc0f5945a92678793c7b6b94f7eea/README#L135)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Good point
</blockquote></details>

Done.

**Review by maciekpac — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Pull request merged**
