### PR TITLE
Update memtier memory manual

### PR DESCRIPTION
**Pull request by PatKamin**
Update the memory tiering manual after comments in #658 

TODO:
[x] Create a separate section about policies and how they are implemented

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/681)

### CODE REVIEW

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[man/memtier.7, line 192 at r1](https://reviewable.io/reviews/memkind/memkind/681#-McsypmY8uK7IbGRSYzb:-McsypmY8uK7IbGRSYzc:bf488hl) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L192)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> If there is not enough memory to satisfy the
> .I FS_DAX
> or
> .I KMEM_DAX
> tier mmeory allocation request, the application will fail.
> ```
</details>

I am not sure about this. The application will fail or allocation will fail?
___
*[man/memtier.7, line 196 at r1](https://reviewable.io/reviews/memkind/memkind/681#-McsyQs1AqzTa6Udj5YP:-McsyQs1AqzTa6Udj5YQ:b-vo0fzh) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L196)):*
> ```
> mmeory
> ```
memory
___
*[man/memtier.7, line 208 at r1](https://reviewable.io/reviews/memkind/memkind/681#-Mcsy8Nk2sWdm9TWWzjW:-Mcsy8Nk2sWdm9TWWzjX:bov7bj) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L208)):*
> ```
> .B LD_PRELOAD=libmemtier.so
> .B MEMKIND_MEM_TIERS="KIND:FS_DAX,PATH:/mnt/pmem0,PMEM_SIZE_LIMIT:10G,RATIO:1;KIND:DRAM,RATIO:4;POLICY:STATIC_RATIO"
> ```
same line ?
LD_PRELOAD MEMKIND_MEM_TIERS.. ?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @PatKamin)

___
*[man/memtier.7, line 222 at r1](https://reviewable.io/reviews/memkind/memkind/681#-McszjS92YjQsIOcRiuC:-McszjSADUvK2F9wE7tT:bb1d3q4) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L222)):*
> ```
> environment variable where all allocations will come from PMEM memory with filesystem created on top of it and default PMEM
> file size:
> ```
PMEM file size in one line

But I would rather say here that PMEM memory is limited only by the file system specified in the /mnt/pmem0 path something like this - IMHO it gives you more information than default PMEM file size
___
*[man/memtier.7, line 232 at r1](https://reviewable.io/reviews/memkind/memkind/681#-Mct-KMVDsCK5khigM7j:-Mct-KMWDaRvuyl_WZWX:b-tdo0pl) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L232)):*
> ```
> KMEM_DAX nodes
> ```
Persistent Memory Numa Node(s) ? not sure about this
___
*[man/memtier.7, line 236 at r1](https://reviewable.io/reviews/memkind/memkind/681#-Mct-agVAnyKH6WFYyVb:-Mct-agVAnyKH6WFYyVc:bvdvw6d) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L236)):*
> ```
> this threshold value
> ```
"this" is needed here?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @PatKamin)

___
*[man/memtier.7, line 199 at r2](https://reviewable.io/reviews/memkind/memkind/681#-MctL8KfA93VD2jqHEOr:-MctL8KfA93VD2jqHEOs:b-apaz71) ([raw file](https://github.com/memkind/memkind/blob/6432315e2bf2dce50582babe40bc6c86fcb6afde/man/memtier.7#L199)):*
> ```
> The following
> ```
following example ?
___
*[man/memtier.7, line 209 at r2](https://reviewable.io/reviews/memkind/memkind/681#-MctLSv5DyiKExhmC-2s:-MctLSv5DyiKExhmC-2t:baeakca) ([raw file](https://github.com/memkind/memkind/blob/6432315e2bf2dce50582babe40bc6c86fcb6afde/man/memtier.7#L209)):*
> ```
> .B MEMKIND_MEM_TIERS="KIND:FS_DAX,PATH:/mnt/pmem0,PMEM_SIZE_LIMIT:10G,RATIO:1;KIND:DRAM,RATIO:4;POLICY:STATIC_RATIO"
> ```
What is first here the LD_PRELOAD or the description:
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> The example value of
> .BR MEMKIND_MEM_TIERS
> environment variable where 20% of the allocated memory will come from PMEM memory and 80% will come from DRAM (
> .I FS_DAX:DRAM
> ratio is 1:4):
> ```
</details>

___
*[man/memtier.7, line 222 at r2](https://reviewable.io/reviews/memkind/memkind/681#-MctLwvA91uuLDPTaw4-:-MctLwvA91uuLDPTaw40:b-pky1b0) ([raw file](https://github.com/memkind/memkind/blob/6432315e2bf2dce50582babe40bc6c86fcb6afde/man/memtier.7#L222)):*
> ```
> come from
> ```
come only from ?

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @michalbiesek)

___
*[man/memtier.7, line 192 at r1](https://reviewable.io/reviews/memkind/memkind/681#-McsypmY8uK7IbGRSYzb:-McxHN_t6RXU9KoJZMNz:b3udrcu) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L192)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> If there is not enough memory to satisfy the
> .I FS_DAX
> or
> .I KMEM_DAX
> tier mmeory allocation request, the application will fail.
> ```
I am not sure about this. The application will fail or allocation will fail?
</blockquote></details>

allocation - done.
___
*[man/memtier.7, line 196 at r1](https://reviewable.io/reviews/memkind/memkind/681#-McsyQs1AqzTa6Udj5YP:-McxHpj16Pm9KHj2OIXr:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L196)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> mmeory
> ```
memory
</blockquote></details>

Done.
___
*[man/memtier.7, line 208 at r1](https://reviewable.io/reviews/memkind/memkind/681#-Mcsy8Nk2sWdm9TWWzjW:-McxIedv1dXxblBWwFPQ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L208)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> .B LD_PRELOAD=libmemtier.so
> .B MEMKIND_MEM_TIERS="KIND:FS_DAX,PATH:/mnt/pmem0,PMEM_SIZE_LIMIT:10G,RATIO:1;KIND:DRAM,RATIO:4;POLICY:STATIC_RATIO"
> ```
same line ?
LD_PRELOAD MEMKIND_MEM_TIERS.. ?
</blockquote></details>

Done.
___
*[man/memtier.7, line 222 at r1](https://reviewable.io/reviews/memkind/memkind/681#-McszjS92YjQsIOcRiuC:-McxV7We-R1zsr3R5IJP:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L222)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> environment variable where all allocations will come from PMEM memory with filesystem created on top of it and default PMEM
> file size:
> ```
PMEM file size in one line

But I would rather say here that PMEM memory is limited only by the file system specified in the /mnt/pmem0 path something like this - IMHO it gives you more information than default PMEM file size
</blockquote></details>

Done.
___
*[man/memtier.7, line 232 at r1](https://reviewable.io/reviews/memkind/memkind/681#-Mct-KMVDsCK5khigM7j:-McxWG_50LerFz9yDtKV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L232)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> KMEM_DAX nodes
> ```
Persistent Memory Numa Node(s) ? not sure about this
</blockquote></details>

Done.
___
*[man/memtier.7, line 236 at r1](https://reviewable.io/reviews/memkind/memkind/681#-Mct-agVAnyKH6WFYyVb:-McxWOE4997Gb49sNE8b:b-bwezz7) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L236)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> this threshold value
> ```
"this" is needed here?
</blockquote></details>

Changed to **the**
___
*[man/memtier.7, line 199 at r2](https://reviewable.io/reviews/memkind/memkind/681#-MctL8KfA93VD2jqHEOr:-McxHuojEPgKwJCPy0X8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/6432315e2bf2dce50582babe40bc6c86fcb6afde/man/memtier.7#L199)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> The following
> ```
following example ?
</blockquote></details>

Done.
___
*[man/memtier.7, line 209 at r2](https://reviewable.io/reviews/memkind/memkind/681#-MctLSv5DyiKExhmC-2s:-McxPV4s5ZZ5n3nrd3JI:b7t3kxp) ([raw file](https://github.com/memkind/memkind/blob/6432315e2bf2dce50582babe40bc6c86fcb6afde/man/memtier.7#L209)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> .B MEMKIND_MEM_TIERS="KIND:FS_DAX,PATH:/mnt/pmem0,PMEM_SIZE_LIMIT:10G,RATIO:1;KIND:DRAM,RATIO:4;POLICY:STATIC_RATIO"
> ```
What is first here the LD_PRELOAD or the description:

> ```
> The example value of
> .BR MEMKIND_MEM_TIERS
> environment variable where 20% of the allocated memory will come from PMEM memory and 80% will come from DRAM (
> .I FS_DAX:DRAM
> ratio is 1:4):
> ```

</blockquote></details>

Merged.
___
*[man/memtier.7, line 222 at r2](https://reviewable.io/reviews/memkind/memkind/681#-MctLwvA91uuLDPTaw4-:-McxVt13COo2E_ZL5c68:bpkcmbp) ([raw file](https://github.com/memkind/memkind/blob/6432315e2bf2dce50582babe40bc6c86fcb6afde/man/memtier.7#L222)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> come from
> ```
come only from ?
</blockquote></details>

I think that stating **all allocations** is sufficient here.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[man/memtier.7, line 232 at r1](https://reviewable.io/reviews/memkind/memkind/681#-Mct-KMVDsCK5khigM7j:-McxY_Z074QcbvC8w8jg:bb70gtc) ([raw file](https://github.com/memkind/memkind/blob/d6688bc95fa3303a1931f86d4e71a43a582d0c17/man/memtier.7#L232)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

NUMA

**Review by michalbiesek — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681#-:-McxYxPR7DcpxvTKLkII:bb6ywmx)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
```https://github.com/memkind/memkind/blob/feat-memory-tiering/COPYING is a copy of BSD-3-Clause or I am missing something?```
Yes, we've got BSD-3 clause for the whole memkind project because of some of the jemalloc test files that have this clause. All of the memkind library files, however, are written under BSD-2 clause.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681#-:-McxYTP39WtvEDHY6D9p:b-tphx1y)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
```
Maybe I have unsupported environment but on my CentOS 8.2 I got something like this:

$ make html-local 
groff -mandoc -Thtml man/hbwmalloc.3 > man/hbwmalloc.html
groff -mandoc -Thtml man/memkind.3 > man/memkind.html
groff -mandoc -Thtml man/memkindallocator.3 > man/memkindallocator.html
groff -mandoc -Thtml man/pmemallocator.3 > man/pmemallocator.html
groff -mandoc -Thtml man/memtier.7 > man/memtier.html
./man/memtier.7:191: warning [p 2, 5.9i]: can't break line
./man/memtier.7:198: warning [p 2, 6.7i]: cannot adjust line
./man/memtier.7:215: warning [p 2, 8.2i]: cannot adjust line
./man/memtier.7:191: warning [p 1, 22.0i]: can't break line
./man/memtier.7:198: warning [p 1, 23.0i]: can't break line
./man/memtier.7:215: warning [p 1, 24.8i]: can't break line
```

Yes, I don't want to break lines containing examples of environment variables for better readability. These are the lines that give this warning. The manual itself is generated fine with these warnings, so I left it as is. The only thing that comes to my mind is to exclude this manual from generating html version.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681#-:-McxZLIwAtMyhwvllbht:b-tsh118)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
```
tbh, I was a little confused when I read this for the first time - "to enable in memkind" and you can run this with any command... ;)

maybe a little longer explanation here and why would I like to use it...?
```

I've extended the DESCRIPTION section.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681#-:-McxZXnx-y7wn-iwEjqv:bcbyfx5)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
```
TBH having in the same variable all the tier configurations and the policy is unnecessary saving. I have spent too much time thinking through how to fix this description. In my opinion, the policy should be provided as a separate required environment variable e.g. MEMKIND_POLICY where the description would be almost exactly copy-paste from the POLICY parameter below:

determines the algorithm used to distribute allocations between provided memory kinds. Currently, there are two available policies: STATIC_RATIO and DYNAMIC_THRESHOLD. Under the STATIC_RATIO policy, all allocations conserve the static ratio between memory kinds. Whereas under the DYNAMIC_THRESHOLD policy, the ratio between adjacent memory tiers is kept with a help of a threshold between kinds which value changes in time.
```

Thanks for the proposition. This will be addressed in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681#-:-McxgEBr4fy7LvF757u3:b-kq3fla)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
```
(I'd use a different word to describe STATIC_RATIO)
```

We will discuss the naming with the team next week. If changed, it will be done in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681#-:-Mcxl2n95-2GreMqx_rs:b-wvdv83)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/681)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
