### PR TITLE
Change policy handling in memtier memory

### PR DESCRIPTION
**Pull request by michalbiesek**
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/625)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/625)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek and @PatKamin)

___
*[src/memkind_memtier.c, line 91 at r3](https://reviewable.io/reviews/memkind/memkind/625#-MZC2kAeDWhmbsp7xkm3:-MZC2kAeDWhmbsp7xkm4:b-e6yr18) ([raw file](https://github.com/memkind/memkind/blob/0f4dbda3fcb8d8bf921f6219fe794caed804fc35/src/memkind_memtier.c#L91)):*
> ```C
>     unsigned size; // Number of memory kinds
>     memkind_t (*get_kind)(struct memtier_memory *memory, size_t size);
>     void (*update_cfg)(struct memtier_memory *memory);
> ```

Could you move function pointers definitions to the top or bottom of this struct? To not mix them with other fields?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/625)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 91 at r3](https://reviewable.io/reviews/memkind/memkind/625#-MZC2kAeDWhmbsp7xkm3:-MZCRrgiD7EEE9fN7yRy:b-u18qo9) ([raw file](https://github.com/memkind/memkind/blob/0f4dbda3fcb8d8bf921f6219fe794caed804fc35/src/memkind_memtier.c#L91)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Could you move function pointers definitions to the top or bottom of this struct? To not mix them with other fields?
</blockquote></details>

Done moved in the end.

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/625#-:-MZCScpT7KNPcORxpcOl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/625#-:-MZCuetX7_8tFpphH-vm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
