### PR TITLE
use SPDX tags instead of license boilerplate

### PR DESCRIPTION
**Pull request by kilobyte**
This way:
* engineers avoid tons of legal text
* license compliance is a lot easier to verify

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/332)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Comment by kilobyte** [comment]
Rebased, updated copyright dates, and included new files.

**Comment by kilobyte** [comment]
Rebased again.

**Comment by michalbiesek** [comment]
@kilobyte 
Sorry for late answer, any chance to rebase again and update the dates to 2020 ?

**Pull request merged**
