### PR TITLE
Add MEMKIND_HIGHEST_CAPACITY_PREFERRED variant

### PR DESCRIPTION
**Pull request by michalbiesek**
- only one NUMA Node could be used by this kind since MPOL_PREFERRED limitation:
"If nodemask specifies more than one node ID, the first node in the mask will be selected as the preferred node"

Depends from #427

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/426)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/426)* status: all files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

___
*[man/memkindallocator.3, line 51 at r1](https://reviewable.io/reviews/memkind/memkind/426#-MOX_usWErqjncwX4ooR:-MOX_usXByzMF8V22oTS:bfgzl1e) ([raw file](https://github.com/memkind/memkind/blob/ef9721658421e57dda887bbfecd91e6435410cdb/man/memkindallocator.3#L51)):*
> ```Roff
> .PP
> .B libmemkind::kinds::MEMKIND_HIGHEST_CAPACITY_PREFERRED
> except that if there is not enough memory in the NUMA node that has the highest capacity
> ```

Did you mean "same as... except..."?
___
*[src/memkind.c, line 188 at r1](https://reviewable.io/reviews/memkind/memkind/426#-MOXa8H_6mlq4__cFY_c:-MOXa8H_6mlq4__cFY_d:bstkefc) ([raw file](https://github.com/memkind/memkind/blob/ef9721658421e57dda887bbfecd91e6435410cdb/src/memkind.c#L188)):*
> ```C
> };
> 
> static struct memkind MEMKIND_DAX_KMEM_INTERLEAVE_STATIC = {
> ```

Should this code go into this PR or it is a merge problem?
___
*[src/memkind_hmat.c, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/426#-MOXaaLt92yedr9c1tew:-MOXaaLt92yedr9c1tex:bh98oce) ([raw file](https://github.com/memkind/memkind/blob/ef9721658421e57dda887bbfecd91e6435410cdb/src/memkind_hmat.c#L58)):*
> ```C
>         return;
>     }
>     if (node_variant == NODE_VARIANT_SINGLE &&
> ```

I'm not sure what is a coding style here but could you add a new line before this if?
___
*[test/memkind_highcapacity_tests.cpp, line 90 at r1](https://reviewable.io/reviews/memkind/memkind/426#-MOXbHIp3t3V67z1NoHH:-MOXbHIp3t3V67z1NoHI:bm4tftl) ([raw file](https://github.com/memkind/memkind/blob/ef9721658421e57dda887bbfecd91e6435410cdb/test/memkind_highcapacity_tests.cpp#L90)):*
> ```cpp
>     const int n_swap_alloc = 20;
> 
>     while (0.99 * sum_of_free_space > alloc_size * allocations.size()) {
> ```

maybe (sum_of_free_space - 1) or similar expression will be better?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/426)* status: 0 of 21 files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[src/memkind.c, line 188 at r1](https://reviewable.io/reviews/memkind/memkind/426#-MOXa8H_6mlq4__cFY_c:-MO_0NfTAotd3U3TCA0m:b-rg1xtx) ([raw file](https://github.com/memkind/memkind/blob/ef9721658421e57dda887bbfecd91e6435410cdb/src/memkind.c#L188)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Should this code go into this PR or it is a merge problem?
</blockquote></details>

Merge problem I split this change with separate commit.
___
*[src/memkind_hmat.c, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/426#-MOXaaLt92yedr9c1tew:-MO_0Tqi9lJDlfk7h4B6:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ef9721658421e57dda887bbfecd91e6435410cdb/src/memkind_hmat.c#L58)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I'm not sure what is a coding style here but could you add a new line before this if?
</blockquote></details>

Done.
___
*[test/memkind_highcapacity_tests.cpp, line 90 at r1](https://reviewable.io/reviews/memkind/memkind/426#-MOXbHIp3t3V67z1NoHH:-MO_0Vl44A-JbPSHMun6:b-r537gk) ([raw file](https://github.com/memkind/memkind/blob/ef9721658421e57dda887bbfecd91e6435410cdb/test/memkind_highcapacity_tests.cpp#L90)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

maybe (sum_of_free_space - 1) or similar expression will be better?
</blockquote></details>

Done (removed 0.99)

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 6 of 21 files at r2, 15 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/426)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 7 of 15 files at r4, 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/426)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[man/memkind.3, line 693 at r5](https://reviewable.io/reviews/memkind/memkind/426#-MOg46FXEaQA1wRv7L92:-MOg46FXEaQA1wRv7L93:ba3z817) ([raw file](https://github.com/memkind/memkind/blob/3af2b6483ed295a2b6e9f69d4855e29f319002dc/man/memkind.3#L693)):*
> ```Roff
> .B MEMKIND_HIGHEST_CAPACITY
> except that if there is not enough memory in the NUMA node that has the highest capacity
> the request, the allocation will fall back on other memory NUMA nodes.
> ```

remove `the request,`
___
*[man/memkindallocator.3, line 54 at r5](https://reviewable.io/reviews/memkind/memkind/426#-MOg4TXU1ZQkKCFUH9PU:-MOg4TXU1ZQkKCFUH9PV:ba3z817) ([raw file](https://github.com/memkind/memkind/blob/3af2b6483ed295a2b6e9f69d4855e29f319002dc/man/memkindallocator.3#L54)):*
> ```Roff
> .B MEMKIND_HIGHEST_CAPACITY
> except that if there is not enough memory in the NUMA node that has the highest capacity
> the request, the allocation will fall back on other memory NUMA nodes.
> ```

remove `the request,`

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/426)* status: 5 of 11 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[man/memkind.3, line 693 at r5](https://reviewable.io/reviews/memkind/memkind/426#-MOg46FXEaQA1wRv7L92:-MOjYvXrDnZWg-dqOkXV:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3af2b6483ed295a2b6e9f69d4855e29f319002dc/man/memkind.3#L693)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

remove `the request,`
</blockquote></details>

Done.
___
*[man/memkindallocator.3, line 51 at r1](https://reviewable.io/reviews/memkind/memkind/426#-MOX_usWErqjncwX4ooR:-MOjYwwh0J8M9WK_VOVB:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ef9721658421e57dda887bbfecd91e6435410cdb/man/memkindallocator.3#L51)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Did you mean "same as... except..."?
</blockquote></details>

Done.
___
*[man/memkindallocator.3, line 54 at r5](https://reviewable.io/reviews/memkind/memkind/426#-MOg4TXU1ZQkKCFUH9PU:-MOjYxHDBKUuOj_tcmbs:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3af2b6483ed295a2b6e9f69d4855e29f319002dc/man/memkindallocator.3#L54)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

remove `the request,`
</blockquote></details>

Done.

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 5 files at r5, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/426#-:-MOjhusdCp--zSHjNFXc:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 5 files at r5, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/426)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[man/memkindallocator.3, line 54 at r5](https://reviewable.io/reviews/memkind/memkind/426#-MOg4TXU1ZQkKCFUH9PU:-MOj_wgR0DekoZy50A9K:bpjiyg7) ([raw file](https://github.com/memkind/memkind/blob/3af2b6483ed295a2b6e9f69d4855e29f319002dc/man/memkindallocator.3#L54)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove double colon.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/426)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[man/memkindallocator.3, line 54 at r5](https://reviewable.io/reviews/memkind/memkind/426#-MOg4TXU1ZQkKCFUH9PU:-MOjlcmW5py7brgXzggg:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/3af2b6483ed295a2b6e9f69d4855e29f319002dc/man/memkindallocator.3#L54)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove double colon.
</blockquote></details>

Done

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r5, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/426#-:-MOjo8xnAvfgKVt1Pr8k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
