### PR TITLE
Adding handling of possible exceptions to examples

### PR DESCRIPTION
**Pull request by szadam**
It is related to issue: [Missing information about exceptions #878](https://github.com/memkind/memkind/issues/878)

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

- - -
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/880)

### CODE REVIEW

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/880)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @PatKamin, @szadam, and @wlemkows)

*[a discussion](https://reviewable.io/reviews/memkind/memkind/880#-NNkzH8C1RAqamHRY7mk:-NNkzH8C1RAqamHRY7ml:b-ka34bz) (no related file):*
This PR does not fix mentioned issue - it only relates to that issue

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNkzA2F3F3REiSqVLoE):*
this is not adding information, it's only adding handling of possible exceptions to examples
___
*[`examples/fixed_cpp_allocator.cpp` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNkz97G2sX5rj6rNzfs:-NNkz97G2sX5rj6rNzft:big93yg) ([raw file](https://github.com/memkind/memkind/blob/698226675c451581d982752311d72e38a78ec49b/examples/fixed_cpp_allocator.cpp#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright (C) 2021 Intel Corporation. */
> ```

pls update dates (in all files)
___
*[`examples/fixed_cpp_allocator.cpp` line 34 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNkzNJU1kOGb9dg9aPY:-NNkzNJU1kOGb9dg9aPZ:bqm5e7t) ([raw file](https://github.com/memkind/memkind/blob/698226675c451581d982752311d72e38a78ec49b/examples/fixed_cpp_allocator.cpp#L34)):*
> ```cpp
>     {
>         std::cout << "FORWARD LIST OPEN" << std::endl;
>         try
> ```

pls fix formatting (see GHA failing job for more info)
___
*[`examples/fixed_cpp_allocator.cpp` line 37 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNkzVYM83hsvzVUQ2Pq:-NNkzVYM83hsvzVUQ2Pr:bfm8lfg) ([raw file](https://github.com/memkind/memkind/blob/698226675c451581d982752311d72e38a78ec49b/examples/fixed_cpp_allocator.cpp#L37)):*
> ```cpp
>         {
>             libmemkind::fixed::allocator<int> alc{addr, FIXED_MAP_SIZE};
> ```

why the extra empty line?
___
*[`examples/fixed_cpp_allocator.cpp` line 56 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNl1Hx10BJ21YMR5ngT:-NNl1Hx10BJ21YMR5ngU:bghlbni) ([raw file](https://github.com/memkind/memkind/blob/698226675c451581d982752311d72e38a78ec49b/examples/fixed_cpp_allocator.cpp#L56)):*
> ```cpp
>         catch(const std::exception &e)
>         {
>             std::cout << "Something wrong happen:" << std::endl << e.what() << std::endl;
> ```

1. if anything `happened` is the correct form
2. I'm not a fan of this sentence. Perhaps add at least info it's most likely a memory allocation failure, or something...
___
*[`examples/fixed_cpp_allocator.cpp` line 82 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNl11443sTAkgaUmvnE:-NNl11443sTAkgaUmvnF:b-cfc5sw) ([raw file](https://github.com/memkind/memkind/blob/698226675c451581d982752311d72e38a78ec49b/examples/fixed_cpp_allocator.cpp#L82)):*
> ```cpp
>             assert(deque.size() == 0);
>         }
>         catch(const std::exception& e)
> ```

rather ` &e` than `& e`

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/880)* status: all files reviewed, 8 unresolved discussions (waiting on @lukaszstolarczuk, @szadam, and @wlemkows)

___
*[`examples/fixed_cpp_allocator.cpp` line 56 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNl1Hx10BJ21YMR5ngT:-NNl5yXACF1nm4KUYu99:bin5dm9) ([raw file](https://github.com/memkind/memkind/blob/698226675c451581d982752311d72e38a78ec49b/examples/fixed_cpp_allocator.cpp#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. if anything `happened` is the correct form
2. I'm not a fan of this sentence. Perhaps add at least info it's most likely a memory allocation failure, or something...
</blockquote></details>

+1, be precise.
___
*[`examples/memkind_cpp_allocator.cpp` line 78 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNl61u6Ch9q-rXSfaHO:-NNl61u6Ch9q-rXSfaHP:by9gkqs) ([raw file](https://github.com/memkind/memkind/blob/698226675c451581d982752311d72e38a78ec49b/examples/memkind_cpp_allocator.cpp#L78)):*
> ```cpp
>         std::cout << "Something wrong happen:" << std::endl << e.what() << std::endl;
>     }
>     
> ```

Remove this tab.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/880)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @PatKamin, @szadam, and @wlemkows)

___
*[`examples/fixed_cpp_allocator.cpp` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNkz97G2sX5rj6rNzfs:-NNlWBg1AReXocb0ooVT:baojclm) ([raw file](https://github.com/memkind/memkind/blob/698226675c451581d982752311d72e38a78ec49b/examples/fixed_cpp_allocator.cpp#L2)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

heh, not quite :wink: we rather use format <original_creation_date>-<current_date> - pls fix like `2021-2023`
___
*[`examples/fixed_cpp_allocator.cpp` line 34 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNkzNJU1kOGb9dg9aPY:-NNlWVgyAcGFdqp2_MQG:b-vi6yha) ([raw file](https://github.com/memkind/memkind/blob/698226675c451581d982752311d72e38a78ec49b/examples/fixed_cpp_allocator.cpp#L34)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx, remember to re-run the clang-format command, after applying any changes
___
*[`examples/fixed_cpp_allocator.cpp` line 56 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNl1Hx10BJ21YMR5ngT:-NNlV2jS39MrV6IE6Rs1:b-kkwjnv) ([raw file](https://github.com/memkind/memkind/blob/698226675c451581d982752311d72e38a78ec49b/examples/fixed_cpp_allocator.cpp#L56)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

Maybe something like that
</blockquote></details>

hmm it looks better, but perhaps I'd write it a little shorter, e.g.:
```
"Something went wrong (it's most likely a memory allocation failure): "
```

I believe this should be enough + we have more details in the `what` part :wink: 
___
*[`examples/pmem_cpp_allocator.cpp` line 63 at r2](https://reviewable.io/reviews/memkind/memkind/880#-NNlWr7VBwz_OMuC0Tg8:-NNlWr7VBwz_OMuC0Tg9:b-kjxvb1) ([raw file](https://github.com/memkind/memkind/blob/f1a8a0bd6e0e1c9ed68c8b05ffa1489c27437934/examples/pmem_cpp_allocator.cpp#L63)):*
> ```cpp
>             }
>         } catch (const std::exception &e) {
>             std::cout << "Something wrong happen: " << e.what() << std::endl;
> ```

why a shorter message here?

**Review by PatKamin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/880#-:-NNlbsAmCzm-GhJ7wbtV:bnfp4nl)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @szadam and @wlemkows)

**Review by szadam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/880)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk, @PatKamin, and @wlemkows)

___
*[`examples/fixed_cpp_allocator.cpp` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/880#-NNkz97G2sX5rj6rNzfs:-NNpJohMEbuP9U4M5TDe:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/698226675c451581d982752311d72e38a78ec49b/examples/fixed_cpp_allocator.cpp#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, not quite :wink: we rather use format <original_creation_date>-<current_date> - pls fix like `2021-2023`
</blockquote></details>

Done.
___
*[`examples/pmem_cpp_allocator.cpp` line 63 at r2](https://reviewable.io/reviews/memkind/memkind/880#-NNlWr7VBwz_OMuC0Tg8:-NNpJuu-0sp84T5mmkXT:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f1a8a0bd6e0e1c9ed68c8b05ffa1489c27437934/examples/pmem_cpp_allocator.cpp#L63)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why a shorter message here?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/880)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @PatKamin, @szadam, and @wlemkows)

___
*[`examples/pmem_cpp_allocator.cpp` line 40 at r3](https://reviewable.io/reviews/memkind/memkind/880#-NNpSjjH6bWdGXOuuXNm:-NNpSjjH6bWdGXOuuXNn:bxve39u) ([raw file](https://github.com/memkind/memkind/blob/80c364abdf4eee0b2424ce9c422e89c16f17817e/examples/pmem_cpp_allocator.cpp#L40)):*
> ```cpp
>             }
>         } catch (const std::exception &e) {
>             std::cout << "Something went wrong (it's most likely a memory allocation failure): " << e.what() << std::endl;
> ```

pls re-apply formatting (see failing CI job)

**Review by szadam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/880)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk, @PatKamin, and @wlemkows)

___
*[`examples/pmem_cpp_allocator.cpp` line 40 at r3](https://reviewable.io/reviews/memkind/memkind/880#-NNpSjjH6bWdGXOuuXNm:-NNpXZnY8l69IJPtA9yo:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/80c364abdf4eee0b2424ce9c422e89c16f17817e/examples/pmem_cpp_allocator.cpp#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls re-apply formatting (see failing CI job)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/880#-:-NNpzoMp3h2hu3b5paUv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wlemkows)

**Review by lukaszstolarczuk — APPROVED** [review]

**Pull request merged**
