### PR TITLE
Move initialization of DRAM and KMEM_DAX to mtt_allocator_create

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/801)

### CODE REVIEW

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/801)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[src/mtt_allocator.c, line 72 at r1](https://reviewable.io/reviews/memkind/memkind/801#-N-ZEK7M5H5DS6R9FRXB:-N-ZEK7M5H5DS6R9FRXC:b-sgg7sg) ([raw file](https://github.com/memkind/memkind/blob/11d3cae32bb95406939165a1cab3f061c5c4f49e/src/mtt_allocator.c#L72)):*
> ```C
> // static function definitions ------------------------------------------------
> 
> static void init_dram_nodemask_once()
> ```

Why do we move the whole code here? Maybe the code could stay where it was and the init function could be called from ranking init ? 

Ranking should be initialized before bg thread....

**Review by PatKamin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/801)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[src/mtt_allocator.c, line 72 at r1](https://reviewable.io/reviews/memkind/memkind/801#-N-ZEK7M5H5DS6R9FRXB:-N-anEFj0_Ty5pnKA_mQ:b32v57) ([raw file](https://github.com/memkind/memkind/blob/11d3cae32bb95406939165a1cab3f061c5c4f49e/src/mtt_allocator.c#L72)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Why do we move the whole code here? Maybe the code could stay where it was and the init function could be called from ranking init ? 

Ranking should be initialized before bg thread....
</blockquote></details>

+1

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/801)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[src/mtt_allocator.c, line 72 at r1](https://reviewable.io/reviews/memkind/memkind/801#-N-ZEK7M5H5DS6R9FRXB:-N-b4_yD6Y-PIFQnutCT:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/11d3cae32bb95406939165a1cab3f061c5c4f49e/src/mtt_allocator.c#L72)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by maciekpac — APPROVED** [review]
I approve, but have a small sugestion about an additional assert.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/801#-:-N-brtrt72dcNdyjFSDQ:b-5x099y)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/ranking_utils.c, line 100 at r2](https://reviewable.io/reviews/memkind/memkind/801#-N-brhgbANWS05Q3Sgj3:-N-brhgbANWS05Q3Sgj4:b-d1wjk3) ([raw file](https://github.com/memkind/memkind/blob/d9a3369ca4c51d698faee8ea321710eea2c7d275/src/ranking_utils.c#L100)):*
> ```C
>     }
> 
>     pthread_once(&nodemask_inits[memory_type], init_routines[memory_type]);
> ```

nit: Could we add some assert that the masks are initialized instead of pthread_once ?

**Pull request merged**
