### PR TITLE
Add touch on malloc

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/834)

### CODE REVIEW

**Review by maciekpac — COMMENTED** [review]
I haven't checked if it works yet, just coded without compiling.

I'm leaving the code for reference, I will check it tomorrow (I'm sure there's something to correct).

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/834)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @maciekpac)

___
*[`src/multithreaded_touch_queue.c` line 47 at r1](https://reviewable.io/reviews/memkind/memkind/834#-N6MfQfaBDXmE2eH8c5t:-N6MfQfaBDXmE2eH8c5u:byz4s8d) ([raw file](https://github.com/memkind/memkind/blob/8ac2bb29341d265cdc44a85245b32f138870807e/src/multithreaded_touch_queue.c#L47)):*
> ```C
>     node->next = queue->head;
>     while (!atomic_compare_exchange_weak(&queue->head, &node->next, node))
>         ;
> ```

Why in a loop? Please, add a comment.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/834)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/834)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[`src/multithreaded_touch_queue.c` line 47 at r1](https://reviewable.io/reviews/memkind/memkind/834#-N6MfQfaBDXmE2eH8c5t:-N6hHi1J1gbBfwrd7N2g:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8ac2bb29341d265cdc44a85245b32f138870807e/src/multithreaded_touch_queue.c#L47)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Why in a loop? Please, add a comment.
</blockquote></details>

Done.

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/834)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[`src/multithreaded_touch_queue.c` line 47 at r1](https://reviewable.io/reviews/memkind/memkind/834#-N6MfQfaBDXmE2eH8c5t:-N6hPLFvCTsubmF2kEZT:b-34ati7) ([raw file](https://github.com/memkind/memkind/blob/8ac2bb29341d265cdc44a85245b32f138870807e/src/multithreaded_touch_queue.c#L47)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Thanks. As I understand, now there could be a situation where queue->head will be changed by other thread. As a result node->next will never be equal to queue->next (as this is set only once before entering this loop), hence never setiing queue->head to node.
</blockquote></details>

not really, compare_exchange_weak sets the value of node->next to queue->head on failure:
    // if any other thread overwrites queue->head (there is a race),
    // the function loads the new `head` value to node->next
    // and retries setting the new head

I think I've mentioned it here, but maybe I should make it even more explicit ?

This is how compare_exchange function works by default...

**Review by PatKamin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/834)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
