### PR TITLE
Rename STATIC_THRESHOLD policy to STATIC_RATIO policy

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/661)

### CODE REVIEW

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/661)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 203 at r1](https://reviewable.io/reviews/memkind/memkind/661#-Mb_zuZ9BEXacqZcZgVS:-Mb_zuZ9BEXacqZcZgVT:b-em6lnj) ([raw file](https://github.com/memkind/memkind/blob/c41d4398ed58fcf6a47ceb9ad69947dc984a0f94/utils/memtier_counter_bench/memtier_counter_bench.cpp#L203)):*
> ```
> static threshold.
> ```
static ratio.

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/661)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/661)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

___
*[src/memkind_memtier.c, line 183 at r2](https://reviewable.io/reviews/memkind/memkind/661#-MbaAD4qEu7NP0trLufv:-MbaAD4qEu7NP0trLufw:b-ec8v41) ([raw file](https://github.com/memkind/memkind/blob/20db778b05ce10f78600e6e3c2f73aac53995bff/src/memkind_memtier.c#L183)):*
> ```C
> 
> static memkind_t
> memtier_policy_static_threshold_get_kind(struct memtier_memory *memory,
> ```

static_ratio
___
*[src/memkind_memtier.c, line 275 at r2](https://reviewable.io/reviews/memkind/memkind/661#-MbaAFvs0rtC0HIX943j:-MbaAFvs0rtC0HIX943k:b-ec8v41) ([raw file](https://github.com/memkind/memkind/blob/20db778b05ce10f78600e6e3c2f73aac53995bff/src/memkind_memtier.c#L275)):*
> ```C
> 
> static void
> memtier_policy_static_threshold_update_config(struct memtier_memory *memory)
> ```

static_ratio

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/661)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[src/memkind_memtier.c, line 183 at r2](https://reviewable.io/reviews/memkind/memkind/661#-MbaAD4qEu7NP0trLufv:-MbaByrN7Fd2u-BqUyrC:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/20db778b05ce10f78600e6e3c2f73aac53995bff/src/memkind_memtier.c#L183)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

static_ratio
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 275 at r2](https://reviewable.io/reviews/memkind/memkind/661#-MbaAFvs0rtC0HIX943j:-MbaBzP67ZznpTH3HXQY:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/20db778b05ce10f78600e6e3c2f73aac53995bff/src/memkind_memtier.c#L275)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

static_ratio
</blockquote></details>

Done.
___
*[utils/memtier_counter_bench/memtier_counter_bench.cpp, line 203 at r1](https://reviewable.io/reviews/memkind/memkind/661#-Mb_zuZ9BEXacqZcZgVS:-MbaC-pEEnkMAJpQ7Sn6:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c41d4398ed58fcf6a47ceb9ad69947dc984a0f94/utils/memtier_counter_bench/memtier_counter_bench.cpp#L203)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> static threshold.
> ```
static ratio.
</blockquote></details>

Done.

**Review by PatKamin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/661#-:-MbaCRO4Cqrxy-SOJ_Gb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Pull request merged**
