### PR TITLE
Parse a copy of env vars instead of original vars

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/648)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/648)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[tiering/ctl.c, line 369 at r1](https://reviewable.io/reviews/memkind/memkind/648#-M_yddh98D_vEhceM7Nd:-M_yddh98D_vEhceM7Ne:b-jti7mg) ([raw file](https://github.com/memkind/memkind/blob/afe09086d1e58e4ddfb0a87c28121dd584566134/tiering/ctl.c#L369)):*
> ```C
>     }
> 
>     while (param_str != NULL) {
> ```

Extend the commit message, with information on why, is this needed
___
*[tiering/ctl.c, line 399 at r1](https://reviewable.io/reviews/memkind/memkind/648#-M_ydo9sBZhnDrXRYN0x:-M_ydo9sBZhnDrXRYN0y:b-753ber) ([raw file](https://github.com/memkind/memkind/blob/afe09086d1e58e4ddfb0a87c28121dd584566134/tiering/ctl.c#L399)):*
> ```
> env_var_copy
> ```
env_var_local
___
*[tiering/ctl.c, line 480 at r1](https://reviewable.io/reviews/memkind/memkind/648#-M_yduFR5EENOTH0CP0e:-M_yduFR5EENOTH0CP0f:bh0vq9t) ([raw file](https://github.com/memkind/memkind/blob/afe09086d1e58e4ddfb0a87c28121dd584566134/tiering/ctl.c#L480)):*
> ```
> thresholds_var_copy
> ```
thresholds_var_local

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/648#-:-M_yrv0252Dn03GGwBT4:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/648)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[tiering/ctl.c, line 369 at r1](https://reviewable.io/reviews/memkind/memkind/648#-M_yddh98D_vEhceM7Nd:-M_yqPRa-xhw8ATOV882:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/afe09086d1e58e4ddfb0a87c28121dd584566134/tiering/ctl.c#L369)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Extend the commit message, with information on why, is this needed
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 399 at r1](https://reviewable.io/reviews/memkind/memkind/648#-M_ydo9sBZhnDrXRYN0x:-M_yqPqT69WVAcmjj91K:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/afe09086d1e58e4ddfb0a87c28121dd584566134/tiering/ctl.c#L399)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> env_var_copy
> ```
env_var_local
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 480 at r1](https://reviewable.io/reviews/memkind/memkind/648#-M_yduFR5EENOTH0CP0e:-M_yqQOvDAzY2zRwpklB:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/afe09086d1e58e4ddfb0a87c28121dd584566134/tiering/ctl.c#L480)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> thresholds_var_copy
> ```
thresholds_var_local
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/648)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[tiering/ctl.c, line 369 at r1](https://reviewable.io/reviews/memkind/memkind/648#-M_yddh98D_vEhceM7Nd:-M_yvW6u-pRXay2N9-Ez:b-6vho2i) ([raw file](https://github.com/memkind/memkind/blob/afe09086d1e58e4ddfb0a87c28121dd584566134/tiering/ctl.c#L369)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

funcion -> function

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/648)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

**Pull request merged**
