### PR TITLE
Add MEKIND_LOWEST_LATENCY_LOCAL variants

### PR DESCRIPTION
**Pull request by michalbiesek**
- [x] #466
- [x] #470
- [x] Topologies for HMAT 
- [x] Tests

I highly recommend reviewing this commit by commit

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/471)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/471#-:-MRZcDv_6AcOzNYeSFbM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/471#-:-MRZmhUY-v_AmXIe2sMa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Comment by michalbiesek** [comment]
Small update with typo in first commit.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/471#-:-MRZqSrS0A-O86AwfKnl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
