### PR TITLE
Update fedora dockerimage from 31 to 32

### PR DESCRIPTION
**Pull request by TomekIdczak97**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [x] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [x] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/387)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/387)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @TomekIdczak97)

___
*[utils/docker/Dockerfile.fedora-32, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/387#-MJfifi28RuD3g2c_ApU:-MJfifi28RuD3g2c_ApV:b-x19uu1) ([raw file](https://github.com/memkind/memkind/blob/27332ef01984a8155a77366e49a8c8be382ffdf2/utils/docker/Dockerfile.fedora-32#L1)):*
> ```
> # SPDX-License-Identifier: BSD-2-Clause
> ```

"1jenkins authored and TomekIdczak97 committed" just TomekIdczak97, please
___
*[utils/docker/Dockerfile.fedora-32, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/387#-MJfiuc16GLBvApk-lZz:-MJfiuc16GLBvApk-l_-:b7m3ozi) ([raw file](https://github.com/memkind/memkind/blob/27332ef01984a8155a77366e49a8c8be382ffdf2/utils/docker/Dockerfile.fedora-32#L1)):*
> ```
> # SPDX-License-Identifier: BSD-2-Clause
> ```

use git move to rename this
___
*[utils/docker/Dockerfile.fedora-32, line 12 at r1](https://reviewable.io/reviews/memkind/memkind/387#-MJfiYKr1ZqzocOm1z38:-MJfiYKsEV8qZc6R8-BD:biaoqv3) ([raw file](https://github.com/memkind/memkind/blob/27332ef01984a8155a77366e49a8c8be382ffdf2/utils/docker/Dockerfile.fedora-32#L12)):*
> ```
>     mkpasswd \
> 
>     daxctl-devel \
> ```
Alphabetical order of the packages please

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/387)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[utils/docker/Dockerfile.fedora-32, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/387#-MJfiuc16GLBvApk-lZz:-MJfq3gX2jGHubDdkWoU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/27332ef01984a8155a77366e49a8c8be382ffdf2/utils/docker/Dockerfile.fedora-32#L1)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

use git move to rename this
</blockquote></details>

Done.
___
*[utils/docker/Dockerfile.fedora-32, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/387#-MJfifi28RuD3g2c_ApU:-MJfq3vl0PwHXjGUmuSG:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/27332ef01984a8155a77366e49a8c8be382ffdf2/utils/docker/Dockerfile.fedora-32#L1)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

"1jenkins authored and TomekIdczak97 committed" just TomekIdczak97, please
</blockquote></details>

Done.
___
*[utils/docker/Dockerfile.fedora-32, line 12 at r1](https://reviewable.io/reviews/memkind/memkind/387#-MJfiYKr1ZqzocOm1z38:-MJfq38K1feQBGnWtLvJ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/27332ef01984a8155a77366e49a8c8be382ffdf2/utils/docker/Dockerfile.fedora-32#L12)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     mkpasswd \
> 
>     daxctl-devel \
> ```
Alphabetical order of the packages please
</blockquote></details>

Done.

**Comment by michalbiesek** [comment]
@pmem-bot-ae
test this please

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/387#-:-MJfuBG23g2HO7PyJqUw:bnfp4nl)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/387)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)

___
*[utils/docker/Dockerfile.fedora-32, line 21 at r2](https://reviewable.io/reviews/memkind/memkind/387#-MJfy1D53L_eGgiPvAx7:-MJfy1D53L_eGgiPvAx8:bk9slyp) ([raw file](https://github.com/memkind/memkind/blob/9f58c5aa99fc317e31f0efa9a758de5b200f9750/utils/docker/Dockerfile.fedora-32#L21)):*
> ```
>     json-c-devel \
>     keyutils-libs-devel \
>     kmod-devel \
> ```

Please change newline format: CRLF to LF see https://en.wikipedia.org/wiki/Newline for details

After change you could check format validation using git diff --check  HEAD~1

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/387)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[utils/docker/Dockerfile.fedora-32, line 21 at r2](https://reviewable.io/reviews/memkind/memkind/387#-MJfy1D53L_eGgiPvAx7:-MJgBdib2EUxljUEXpfS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9f58c5aa99fc317e31f0efa9a758de5b200f9750/utils/docker/Dockerfile.fedora-32#L21)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please change newline format: CRLF to LF see https://en.wikipedia.org/wiki/Newline for details

After change you could check format validation using git diff --check  HEAD~1
</blockquote></details>

Done.

**Comment by michalbiesek** [comment]
@pmem-bot-ae
test this please

**Pull request merged**
