### PR TITLE
[feat-memory-tiering] synchronize with main branch with rpm build fix

### PR DESCRIPTION
**Pull request by michalbiesek**
The intention is to avoid merge conflicts later (#577)
- merge with changes from the main branch
- fix rpm build
- extend cleanup target for tiering

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/578)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/578#-:-MW4oWkqCQGz3Yb_9wRI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Comment by PatKamin** [comment]
Add ea5016 ?

**Comment by michalbiesek** [comment]
> Add ea5016 ?

Nope, the "ctl.c" file isn't even exist on the destination branch - https://github.com/memkind/memkind/tree/feat-memory-tiering/tiering

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/578#-:-MW8Seh27hVvsjGwuelt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
