### PR TITLE
Add support for QEMU in memkind tests

### PR DESCRIPTION
**Pull request by michalbiesek**
Provide convenient scripts to install libvirt and QEMU 
Provide support for running tests in the QEMU environment
Provide support to run QEMU tests in docker container

Depends from #408 

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/411)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/411)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[utils/docker/README.md, line 31 at r1](https://reviewable.io/reviews/memkind/memkind/411#-MOGeXi7EEAwKpKVDqzy:-MOGeXi8AuqmH39DUDms:bpqj9wg) ([raw file](https://github.com/memkind/memkind/blob/b90db7a27097b0dcd64c12362b026c60d76da30e/utils/docker/README.md#L31)):*
> ```Markdown
> memkind to not release memory to OS in anticipation of memory reuse soon. For PMEM memory will be released only after calling memkind_destroy_kind()
> 
> * **QEMU_TEST** - Setting **QEMU_TEST** result to execute tests designated for QEMU environment.
> ```

Did you mean "results in execution of tests"?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/411)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[utils/docker/README.md, line 31 at r1](https://reviewable.io/reviews/memkind/memkind/411#-MOGeXi7EEAwKpKVDqzy:-MOH31c3BFAxHNrsswcZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b90db7a27097b0dcd64c12362b026c60d76da30e/utils/docker/README.md#L31)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Did you mean "results in execution of tests"?
</blockquote></details>

Done.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/411)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[utils/docker/Dockerfile.ubuntu-20.04, line 39 at r2](https://reviewable.io/reviews/memkind/memkind/411#-MOHbH2T3ebCkw2hqM5D:-MOIIhyS1dHsdyzKF8TZ:b-k8m7j2) ([raw file](https://github.com/memkind/memkind/blob/498df5cb4d5be503d097951fcfe0e1ac3df7c77e/utils/docker/Dockerfile.ubuntu-20.04#L39)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Package not required for installing libvirt.
</blockquote></details>

Actually, I need python-docutils for libvirt (rst2html5) and python3.8-dev for psutil

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/411)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @michalbiesek)

___
*[utils/docker/Dockerfile.ubuntu-20.04, line 39 at r2](https://reviewable.io/reviews/memkind/memkind/411#-MOHbH2T3ebCkw2hqM5D:-MOIKzioA8UD7zMl0Gro:b-lzorp4) ([raw file](https://github.com/memkind/memkind/blob/498df5cb4d5be503d097951fcfe0e1ac3df7c77e/utils/docker/Dockerfile.ubuntu-20.04#L39)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Actually, I need python-docutils for libvirt (rst2html5) and python3.8-dev for psutil
</blockquote></details>

Move this python3.8-dev package to the commit where you introduce psutils then, please.

**Comment by michalbiesek** [comment]
> > _[Reviewable](https://reviewable.io/reviews/memkind/memkind/411)_ status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @michalbiesek)
> 
> _[utils/docker/Dockerfile.ubuntu-20.04, line 39 at r2](https://reviewable.io/reviews/memkind/memkind/411#-MOHbH2T3ebCkw2hqM5D:-MOIKzioA8UD7zMl0Gro:b-lzorp4) ([raw file](https://github.com/memkind/memkind/blob/498df5cb4d5be503d097951fcfe0e1ac3df7c77e/utils/docker/Dockerfile.ubuntu-20.04#L39)):_
> 
> Previously, michalbiesek wrote…
> Move this python3.8-dev package to the commit where you introduce psutils then, please.

Done

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/411#-:-MOV2omWCTWx-UMXHeKD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
