### PR TITLE
Fix case where threshold in DYNAMIC_THRESHOLD policy stucks at min level

### PR DESCRIPTION
**Pull request by bratpiorka**
- make sure that mimumum change of threshold in DYNAMIC_THRESHOLD policy
  will be at least 1

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/664)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/664)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 314 at r1](https://reviewable.io/reviews/memkind/memkind/664#-MbaK3rr47AMHSj3y--b:-MbaK3rr47AMHSj3y--c:bi78w31) ([raw file](https://github.com/memkind/memkind/blob/49a1891400554fe4c22239790ff0b4ff7c71be55/src/memkind_memtier.c#L314)):*
> ```
> size_t threshold = thres[i].val * memory->thres_degree + 1;
> ```
The threshold is equal to zero because of the result of thres[i].val * memory->thres_degree could be less than 1? So I assume thres[i].val something like ~ 4 bytes? With this change, you always modify the threshold case right?

If you move this code as in the snippet below, would this fix works for your case? without adding one at first place

From:
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>         size_t threshold = thres[i].val * memory->thres_degree + 1;
>         if ((prev_alloc_size == 0) || (current_ratio > thres[i].norm_ratio)) {
>             size_t higher_threshold = thres[i].val + threshold;
>             if (higher_threshold <= thres[i].max) {
>                 thres[i].val = higher_threshold;
>             }
>         } else {
>             size_t lower_threshold = thres[i].val - threshold;
>             if (lower_threshold >= thres[i].min) {
>                 thres[i].val = lower_threshold;
>             }
> ```
</details>


To:
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>         if ((prev_alloc_size == 0) || (current_ratio > thres[i].norm_ratio)) {
>             size_t higher_threshold = thres[i].val(1+memory->thres_degree);
>             if (higher_threshold <= thres[i].max) {
>                 thres[i].val = higher_threshold;
>             }
>         } else {
>             size_t lower_threshold = thres[i].val(1-memory->thres_degree);
>             if (lower_threshold >= thres[i].min) {
>                 thres[i].val = lower_threshold;
>             }
> ```
</details>

___
*[src/memkind_memtier.c, line 314 at r1](https://reviewable.io/reviews/memkind/memkind/664#-MbaQF7a7Eqdov9bGCDP:-MbaQF7a7Eqdov9bGCDQ:bw6lxg2) ([raw file](https://github.com/memkind/memkind/blob/49a1891400554fe4c22239790ff0b4ff7c71be55/src/memkind_memtier.c#L314)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>         size_t threshold = thres[i].val * memory->thres_degree + 1;
>         if ((prev_alloc_size == 0) || (current_ratio > thres[i].norm_ratio)) {
>             size_t higher_threshold = thres[i].val + threshold;
>             if (higher_threshold <= thres[i].max) {
>                 thres[i].val = higher_threshold;
>             }
>         } else {
>             size_t lower_threshold = thres[i].val - threshold;
>             if (lower_threshold >= thres[i].min) {
>                 thres[i].val = lower_threshold;
>             }
> ```
</details>

___
*[src/memkind_memtier.c, line 315 at r1](https://reviewable.io/reviews/memkind/memkind/664#-MbaJuyY9xkRq3pb9SCc:-MbaJuyY9xkRq3pb9SCd:b-fdbzkq) ([raw file](https://github.com/memkind/memkind/blob/49a1891400554fe4c22239790ff0b4ff7c71be55/src/memkind_memtier.c#L315)):*
> ```C
>         // (min, max) range
>         size_t threshold = thres[i].val * memory->thres_degree + 1;
>         if ((prev_alloc_size == 0) || (current_ratio > thres[i].norm_ratio)) {
> ```

Fix commit message - > mimumum

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/664)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[src/memkind_memtier.c, line 314 at r1](https://reviewable.io/reviews/memkind/memkind/664#-MbaK3rr47AMHSj3y--b:-MbaTktE61KHNUASAbiI:bueyxj) ([raw file](https://github.com/memkind/memkind/blob/ac022d7fd9fb3bb42d2b4c219359c63f6ff8ac9d/src/memkind_memtier.c#L314)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> size_t threshold = thres[i].val * memory->thres_degree + 1;
> ```
The threshold is equal to zero because of the result of thres[i].val * memory->thres_degree could be less than 1? So I assume thres[i].val something like ~ 4 bytes? With this change, you always modify the threshold case right?

If you move this code as in the snippet below, would this fix works for your case? without adding one at first place

From:
> ```
>         size_t threshold = thres[i].val * memory->thres_degree + 1;
>         if ((prev_alloc_size == 0) || (current_ratio > thres[i].norm_ratio)) {
>             size_t higher_threshold = thres[i].val + threshold;
>             if (higher_threshold <= thres[i].max) {
>                 thres[i].val = higher_threshold;
>             }
>         } else {
>             size_t lower_threshold = thres[i].val - threshold;
>             if (lower_threshold >= thres[i].min) {
>                 thres[i].val = lower_threshold;
>             }
> ```

To:
> ```
>         if ((prev_alloc_size == 0) || (current_ratio > thres[i].norm_ratio)) {
>             size_t higher_threshold = thres[i].val(1+memory->thres_degree);
>             if (higher_threshold <= thres[i].max) {
>                 thres[i].val = higher_threshold;
>             }
>         } else {
>             size_t lower_threshold = thres[i].val(1-memory->thres_degree);
>             if (lower_threshold >= thres[i].min) {
>                 thres[i].val = lower_threshold;
>             }
> ```

</blockquote></details>

Consider case where thres[i].val = 1, and memory->thres_degree = 0.25, then higher_threshold will also be 1. So this doesn't solve the problem as threshold value will stuck in 1 forever. Or maybe you meant 

 size_t higher_threshold = (thres[i].val + 1) * memory->thres_degree;

?
___
*[src/memkind_memtier.c, line 315 at r1](https://reviewable.io/reviews/memkind/memkind/664#-MbaJuyY9xkRq3pb9SCc:-MbaX85yCP0JryibRUcB:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ac022d7fd9fb3bb42d2b4c219359c63f6ff8ac9d/src/memkind_memtier.c#L315)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Fix commit message - > mimumum 
</blockquote></details>

Done.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/664)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @PatKamin)

___
*[src/memkind_memtier.c, line 314 at r1](https://reviewable.io/reviews/memkind/memkind/664#-MbaK3rr47AMHSj3y--b:-MbajT5j3cd6BDJ4eLn-:b-pdzn5a) ([raw file](https://github.com/memkind/memkind/blob/ac022d7fd9fb3bb42d2b4c219359c63f6ff8ac9d/src/memkind_memtier.c#L314)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Consider case where thres[i].val = 1, and memory->thres_degree = 0.25, then higher_threshold will also be 1. So this doesn't solve the problem as threshold value will stuck in 1 forever. Or maybe you meant 

 size_t higher_threshold = (thres[i].val + 1) * memory->thres_degree;

?
</blockquote></details>

Ok, so you actually want to ceil this:

size_t threshold = size_t(ceil(thres[i].val * memory->thres_degree));

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/664)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @PatKamin)

___
*[src/memkind_memtier.c, line 314 at r1](https://reviewable.io/reviews/memkind/memkind/664#-MbaK3rr47AMHSj3y--b:-MbaqnTmDgms2sTnLYFr:bu0ugyl) ([raw file](https://github.com/memkind/memkind/blob/ac022d7fd9fb3bb42d2b4c219359c63f6ff8ac9d/src/memkind_memtier.c#L314)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Ok, so you actually want to ceil this:

size_t threshold = size_t(ceil(thres[i].val * memory->thres_degree));
</blockquote></details>

yes, this will work perfectly

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/664)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @PatKamin)

___
*[src/memkind_memtier.c, line 314 at r1](https://reviewable.io/reviews/memkind/memkind/664#-MbaK3rr47AMHSj3y--b:-Mbatdbb7Iyq7uzN5vOM:brsz48m) ([raw file](https://github.com/memkind/memkind/blob/ac022d7fd9fb3bb42d2b4c219359c63f6ff8ac9d/src/memkind_memtier.c#L314)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

yes, this will work perfectly
</blockquote></details>

My bad: ceil -> ceilf.
I am not sure if "(float)" is necessary for the function itself.

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/664)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @PatKamin)

___
*[src/memkind_memtier.c, line 314 at r1](https://reviewable.io/reviews/memkind/memkind/664#-MbaK3rr47AMHSj3y--b:-MbaxReZDhib0gRXIYJG:b-rxbb03) ([raw file](https://github.com/memkind/memkind/blob/ac022d7fd9fb3bb42d2b4c219359c63f6ff8ac9d/src/memkind_memtier.c#L314)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

My bad: ceil -> ceilf.
I am not sure if "(float)" is necessary for the function itself.
</blockquote></details>

it works without casting

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/664)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_memtier.c, line 314 at r1](https://reviewable.io/reviews/memkind/memkind/664#-MbaK3rr47AMHSj3y--b:-MbbIXcY0W8JBIcoS5Rb:bnqdks8) ([raw file](https://github.com/memkind/memkind/blob/ac022d7fd9fb3bb42d2b4c219359c63f6ff8ac9d/src/memkind_memtier.c#L314)):*
Add to configure.ac:

> ```
> AC_SEARCH_LIBS([ceilf], [m])
> ```

This should satisfy clang linker

Please do it in the same PR but as a separate commit.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/664)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/664#-:-MbeBOXv2wqprTsvO1FV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/664)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
