### PR TITLE
Page movement

### PR DESCRIPTION
**Pull request by PatKamin**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/758)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/758)* status: all files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[include/memkind/internal/ranking_utils.h, line 19 at r1](https://reviewable.io/reviews/memkind/memkind/758#-MwVtAVxDRYZHUKEYYoK:-MwVtAVxDRYZHUKEYYoL:b-d0wxhj) ([raw file](https://github.com/memkind/memkind/blob/95e9a481d1c8a00ce6348a467ab63697435a853b/include/memkind/internal/ranking_utils.h#L19)):*
> ```objc
> #ifdef __cplusplus
> }
> #endif
> ```

new line
___
*[src/ranking_utils.c, line 19 at r1](https://reviewable.io/reviews/memkind/memkind/758#-MwVtxAs01gggFy-PSzA:-MwVtxAs01gggFy-PSzB:b9xry3q) ([raw file](https://github.com/memkind/memkind/blob/95e9a481d1c8a00ce6348a467ab63697435a853b/src/ranking_utils.c#L19)):*
> ```C
> static nodemask_t get_dram_nodemask()
> {
>     nodemask_t nodemask;
> ```

you could use here memkind_regular_all_get_mbind_nodemask(). In fact you don't need these extra functions - you can call them directly
___
*[src/ranking_utils.c, line 85 at r1](https://reviewable.io/reviews/memkind/memkind/758#-MwVueZw9_sovnKykNrT:-MwVueZw9_sovnKykNrU:bw6rjv2) ([raw file](https://github.com/memkind/memkind/blob/95e9a481d1c8a00ce6348a467ab63697435a853b/src/ranking_utils.c#L85)):*
> ```C
>     const size_t page_size = sysconf(_SC_PAGESIZE);
>     const size_t page_mask = ~(page_size - 1);
>     os_page_addr = (void *)((uintptr_t)page_metadata_addr & page_mask);
> ```

I think this address should be already valid to use, right? 
You could add asserts here to check this.

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/758)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

___
*[include/memkind/internal/ranking_utils.h, line 19 at r1](https://reviewable.io/reviews/memkind/memkind/758#-MwVtAVxDRYZHUKEYYoK:-Mwkw7Em6U4lFV1b-8JT:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/95e9a481d1c8a00ce6348a467ab63697435a853b/include/memkind/internal/ranking_utils.h#L19)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.
___
*[src/ranking_utils.c, line 19 at r1](https://reviewable.io/reviews/memkind/memkind/758#-MwVtxAs01gggFy-PSzA:-Mwkw9xl8Y7Fg2fXYPdR:bugbuva) ([raw file](https://github.com/memkind/memkind/blob/95e9a481d1c8a00ce6348a467ab63697435a853b/src/ranking_utils.c#L19)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

you could use here memkind_regular_all_get_mbind_nodemask(). In fact you don't need these extra functions - you can call them directly
</blockquote></details>

I decided not to use this function as I would have to initialize MEMKIND_REGULAR kind. It might be done this way, but I don't see a reason of involving MEMKIND_REGULAR kind here. Using the functionality of the memkind_regular_all_get_mbind_nodemask() explicitly in the code here is IMHO much easier to digest than seeing dummy allocs of MEMKIND_REGULAR kind.
___
*[src/ranking_utils.c, line 85 at r1](https://reviewable.io/reviews/memkind/memkind/758#-MwVueZw9_sovnKykNrT:-Mwl4ws44wxEk5w3Y5iW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/95e9a481d1c8a00ce6348a467ab63697435a853b/src/ranking_utils.c#L85)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I think this address should be already valid to use, right? 
You could add asserts here to check this.
</blockquote></details>

Done.

**Review by maciekpac — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/758)* status: 2 of 6 files reviewed, 8 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/ranking_utils.c, line 54 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzYPecBU8a_HsivdPS:-MwzYPecBU8a_HsivdPT:b-lcmnkx) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L54)):*
> ```C
> }
> 
> MEMKIND_EXPORT int move_page_metadata(void *page_metadata_addr, size_t size,
> ```

There is TRACED_PAGE_SIZE macro in pagesizes.h, this will always be the same (and should be a multiple of )
___
*[src/ranking_utils.c, line 65 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzXZKo1U2sgt8ivqjX:-MwzXZKo1U2sgt8ivqjY:b8m2r5y) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L65)):*
> ```C
> #ifndef use_mbind
>     int max_node = numa_max_node();
>     int *status = memkind_malloc(MEMKIND_DEFAULT, sizeof(int));
> ```

would it be possible to do it in some init or in some other function?

It would be great to minimize overhead of moving pages. It is not a part of critical path, but we will probably be doing it quite often. 
___
*[src/ranking_utils.c, line 80 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzXC_KBAvh3r-QBZRe:-MwzXC_KBAvh3r-QBZRf:br44qx5) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L80)):*
> ```C
>     numa_bitmask_clearall(&nodemask_dax_kmem);
> #endif
>     if ((uintptr_t)page_metadata_addr % sysconf(_SC_PAGESIZE) != 0) {
> ```

There is a wrapper for this function in pagesizes.h (traced_pagesize_get_sysytem_pagesize())
___
*[src/ranking_utils.c, line 86 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzY-gE-zfNMlIO4AKa:-MwzY-gF1fD5Cs97g_z6:b-fn8vix) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L86)):*
> ```C
> 
>     if (memory_type == DRAM) {
>         nodemask = get_dram_nodemask();
> ```

This calculates the whole nodemask instead of just returning it's value... Would it be possible to initialize it once and just return it later?
___
*[src/ranking_utils.c, line 96 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzYAvN3sfDbD3O92sy:-MwzYAvN3sfDbD3O92sz:b-89a4l7) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L96)):*
> ```C
>         }
>     } else {
>         nodemask = get_dax_kmem_nodemask();
> ```

Ditto

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/758)* status: all files reviewed, 5 unresolved discussions (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/758)* status: all files reviewed, 5 unresolved discussions (waiting on @maciekpac)

___
*[src/ranking_utils.c, line 54 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzYPecBU8a_HsivdPS:-Mx-abeuBzzbjA_nzTNk:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L54)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

There is TRACED_PAGE_SIZE macro in pagesizes.h, this will always be the same (and should be a multiple of )
</blockquote></details>

Done.
___
*[src/ranking_utils.c, line 65 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzXZKo1U2sgt8ivqjX:-Mx-ahfQ-VjhxCNN2dQr:b-9o9npm) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L65)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

would it be possible to do it in some init or in some other function?

It would be great to minimize overhead of moving pages. It is not a part of critical path, but we will probably be doing it quite often. 
</blockquote></details>

Dropping the usage of move_pages().
___
*[src/ranking_utils.c, line 80 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzXC_KBAvh3r-QBZRe:-Mx-bWhk0GlAypcO2vJu:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L80)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

There is a wrapper for this function in pagesizes.h (traced_pagesize_get_sysytem_pagesize())
</blockquote></details>

Done.
___
*[src/ranking_utils.c, line 86 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzY-gE-zfNMlIO4AKa:-Mx4T0Z48ORnS0MEbbE2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L86)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

This calculates the whole nodemask instead of just returning it's value... Would it be possible to initialize it once and just return it later?
</blockquote></details>

Done.
___
*[src/ranking_utils.c, line 96 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzYAvN3sfDbD3O92sy:-Mx4T0IFDt78FD4uJ_mM:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L96)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

**Review by maciekpac — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r5, 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/758)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[src/ranking_utils.c, line 65 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzXZKo1U2sgt8ivqjX:-Mx5T1tfD6XEdejzv2lt:bzdvgx) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L65)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Dropping the usage of move_pages().
</blockquote></details>

I think TRACED_PAGESIZE macro should be used instead...
___
*[src/ranking_utils.c, line 80 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzXC_KBAvh3r-QBZRe:-Mx5TKJ74P36qQ5Dteex:b-ve79ap) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L80)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually, we move the same amount as we trace - TRACED_PAGESIZE should be used instead...

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/758)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[src/ranking_utils.c, line 65 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzXZKo1U2sgt8ivqjX:-Mx8St8N5Td-QAchHFs5:b-tkoof1) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L65)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think TRACED_PAGESIZE macro should be used instead...
</blockquote></details>

Changed to aligning the pointer passed in the mbind() call with the system page size. All the mbind() cares about is where the system page size starts. There is no need to align with an arbitrary value like the TRACED_PAGESIZE.
___
*[src/ranking_utils.c, line 80 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzXC_KBAvh3r-QBZRe:-Mx8T5rm4121L6VbA4e1:b-tkoof1) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L80)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Actually, we move the same amount as we trace - TRACED_PAGESIZE should be used instead...
</blockquote></details>

Changed to aligning the pointer passed in the mbind() call with the system page size. All the mbind() cares about is where the system page size starts. There is no need to align with an arbitrary value like the TRACED_PAGESIZE.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 3 of 3 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/758)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)

**Review by maciekpac — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r12, 4 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/758)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[src/ranking_utils.c, line 65 at r3](https://reviewable.io/reviews/memkind/memkind/758#-MwzXZKo1U2sgt8ivqjX:-MxEeuPY3edIR1KHM5px:b-kkw90g) ([raw file](https://github.com/memkind/memkind/blob/ac3ef725946ccdf3c376983b88031a5b4c8d4569/src/ranking_utils.c#L65)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Changed to aligning the pointer passed in the mbind() call with the system page size. All the mbind() cares about is where the system page size starts. There is no need to align with an arbitrary value like the TRACED_PAGESIZE.
</blockquote></details>

We are tracking not system size pages, but TRACED_PAGESIZE.

Please check this sample case:

SYSTEM_PAGESIZE 1
TRACED_PAGESIZE 2

|                traced page             |
| system page | system_page |

Before demotion:

|dram ranking |
| dram | dram|

after demotion - what we would have with this code:

|pmem ranking |
| pmem | dram|

after demotion - what we would like to have:

|pmem ranking |
| pmem | pmem|


We can set SYSTEM_PAGESIZE to TRACED_PAGESIZE but, for various reasons, we might want to track bigger chunks of memory (memory overhead, tracking accuracy, etc)

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/758)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @bratpiorka and @maciekpac)

**Pull request merged**
