### PR TITLE
Add dax kmem kind

### PR DESCRIPTION
**Pull request by PatKamin**
[x] Test this on the machine with DAX_KMEM
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/630)

### CODE REVIEW

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @PatKamin)

___
*[test/memkind_memtier_dax_kmem_test.cpp, line 21 at r1](https://reviewable.io/reviews/memkind/memkind/630#-MZW_naK6tBfSvsniZGP:-MZW_naL58nNH9ErBNAb:b-kl3h6r) ([raw file](https://github.com/memkind/memkind/blob/ab3660d3296963e0ec3690e87fcad7727b77fae8/test/memkind_memtier_dax_kmem_test.cpp#L21)):*
> ```
> ········
> ```
remove white spaces
___
*[test/memkind_memtier_dax_kmem_test.cpp, line 61 at r1](https://reviewable.io/reviews/memkind/memkind/630#-MZW_pl_7KV1Xa967_n-:-MZW_pl_7KV1Xa967_n0:b-ic19nh) ([raw file](https://github.com/memkind/memkind/blob/ab3660d3296963e0ec3690e87fcad7727b77fae8/test/memkind_memtier_dax_kmem_test.cpp#L61)):*
> ```cpp
>     // ASSERT_EQ(memory_kind, memkind_detect_kind(ptr));
>     // memtier_free(ptr);
> }
> ```

add newline in the en
___
*[tiering/ctl.c, line 214 at r1](https://reviewable.io/reviews/memkind/memkind/630#-MZWa7cZ2Qug0qSeUXmX:-MZWa7cZ2Qug0qSeUXmY:b-pdtj5l) ([raw file](https://github.com/memkind/memkind/blob/ab3660d3296963e0ec3690e87fcad7727b77fae8/tiering/ctl.c#L214)):*
> ```
>     } else if (!strcmp(kind_name, "DAX_KMEM")) {
>         *kind = MEMKIND_DAX_KMEM;
> ```
please update https://github.com/memkind/memkind/blob/bd5b0b0ea0bbbb9b90b5f051b4f925dbb50252c2/man/memtier.7#L23
It would be great to have an additional example string here https://github.com/memkind/memkind/blob/bd5b0b0ea0bbbb9b90b5f051b4f925dbb50252c2/man/memtier.7#L88
___
*[tiering/ctl.c, line 215 at r1](https://reviewable.io/reviews/memkind/memkind/630#-MZWb9LuAXwA2HRoZMOp:-MZWb9LuAXwA2HRoZMOq:b-ebnntb) ([raw file](https://github.com/memkind/memkind/blob/ab3660d3296963e0ec3690e87fcad7727b77fae8/tiering/ctl.c#L215)):*
> ```
> kind = MEMKIND_DAX_KMEM;
> ```
I believe you must do something like dummy allocation malloc/free here, let me explain:

On the first allocation with MEMKIND_DAX_KMEM, you do some init_once action like searching for properly NUMA Nodes, e.g. https://github.com/memkind/memkind/blob/249493e2a82bb7faff952acd795c16200da68255/src/memkind_dax_kmem.c#L46
And in this part of the code, the underneath functions like numa_bitmask_alloc will call malloc.

Without this dummy allocation, you don't perform this one-time action **before** creating a memtier memory object, and assuming it will be created here successfully, on the first allocation which will be using MEMKIND_DAX_KMEM you perform this one-time actions, see what happened here:
https://github.com/memkind/memkind/blob/bd5b0b0ea0bbbb9b90b5f051b4f925dbb50252c2/tiering/memtier.c#L28
I believe there will be a recursive call to malloc,  but please check it.

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[tiering/ctl.c, line 203 at r2](https://reviewable.io/reviews/memkind/memkind/630#-MZXmYfyAX8EhvEzoZKM:-MZXmYfyAX8EhvEzoZKN:bmhq5ge) ([raw file](https://github.com/memkind/memkind/blob/f3ec2363728fc5cf834c66e15f7beb7330410792/tiering/ctl.c#L203)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     } else if (!strcmp(kind_name, "DAX_KMEM_ALL")) {
>         *kind = MEMKIND_DAX_KMEM_ALL;
>     } else if (!strcmp(kind_name, "DAX_KMEM_PREFERRED")) {
>         *kind = MEMKIND_DAX_KMEM_PREFERRED;
>     } else if (!strcmp(kind_name, "DAX_KMEM_INTERLEAVE")) {
>         *kind = MEMKIND_DAX_KMEM_INTERLEAVE;
> ```
</details>

I think  MEMKIND_DAX_KMEM kind should be sufficient here at least for this iteration

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 3 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: all files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[test/tiering_tests.py, line 240 at r4](https://reviewable.io/reviews/memkind/memkind/630#-MZXrDsD6CCKlhalvr6y:-MZXrDsD6CCKlhalvr6z:b-6hy0v) ([raw file](https://github.com/memkind/memkind/blob/5cc0ff41c37e487b9ca62be1560e7b424129bdc8/test/tiering_tests.py#L240)):*
> ```Python
> 
>     @pytest.mark.parametrize("policy", ["POLICY_STATIC_THRESHOLD",
>                                         "POLICY_DYNAMIC_THRESHOLD"])
> ```

for DYNAMIC_THRESHOLD you have to have at least 2 tiers defined

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[tiering/ctl.c, line 203 at r2](https://reviewable.io/reviews/memkind/memkind/630#-MZXmYfyAX8EhvEzoZKM:-MZXpU2lB21thoz8vDxi:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/f3ec2363728fc5cf834c66e15f7beb7330410792/tiering/ctl.c#L203)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     } else if (!strcmp(kind_name, "DAX_KMEM_ALL")) {
>         *kind = MEMKIND_DAX_KMEM_ALL;
>     } else if (!strcmp(kind_name, "DAX_KMEM_PREFERRED")) {
>         *kind = MEMKIND_DAX_KMEM_PREFERRED;
>     } else if (!strcmp(kind_name, "DAX_KMEM_INTERLEAVE")) {
>         *kind = MEMKIND_DAX_KMEM_INTERLEAVE;
> ```
I think  MEMKIND_DAX_KMEM kind should be sufficient here at least for this iteration
</blockquote></details>

Done.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[test/tiering_tests.py, line 240 at r4](https://reviewable.io/reviews/memkind/memkind/630#-MZXrDsD6CCKlhalvr6y:-MZXyfPJ9cFqLQoWsrES:b-cccbci) ([raw file](https://github.com/memkind/memkind/blob/5cc0ff41c37e487b9ca62be1560e7b424129bdc8/test/tiering_tests.py#L240)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

for DYNAMIC_THRESHOLD you have to have at least 2 tiers defined
</blockquote></details>

@patkamin FYI: https://github.com/memkind/memkind/pull/631 for the usage of memtier_memory with only 1 tier

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[test/tiering_tests.py, line 240 at r4](https://reviewable.io/reviews/memkind/memkind/630#-MZXrDsD6CCKlhalvr6y:-MZXyOkX7cp8NAOqaSqh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5cc0ff41c37e487b9ca62be1560e7b424129bdc8/test/tiering_tests.py#L240)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

for DYNAMIC_THRESHOLD you have to have at least 2 tiers defined
</blockquote></details>

Done.
___
*[tiering/ctl.c, line 215 at r1](https://reviewable.io/reviews/memkind/memkind/630#-MZWb9LuAXwA2HRoZMOp:-MZYBGQR51LH7XYz0sn0:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ab3660d3296963e0ec3690e87fcad7727b77fae8/tiering/ctl.c#L215)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

There is one more thing regarding this. You could do this dummy allocation to have information if DAX_KMEM is configured see that we do the same thing in case of memkind_create_pmem(pmem_path, pmem_size, kind) operation
</blockquote></details>

Done.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[tiering/ctl.c, line 203 at r6](https://reviewable.io/reviews/memkind/memkind/630#-MZvAuTw5VYGtn6MEQwY:-MZvAuTw5VYGtn6MEQwZ:b-p46wyx) ([raw file](https://github.com/memkind/memkind/blob/65a92304ed7dc03ceca4d65d61c41d09b7d68ff3/tiering/ctl.c#L203)):*
> ```
> memkind_malloc(*kind, 32);
> ```
1. check if memory allocated by this call is succeeded if not then return -1
2. memkind_free this

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[tiering/ctl.c, line 201 at r6](https://reviewable.io/reviews/memkind/memkind/630#-M_-beor7CvtrnJ4HaRI:-M_-beor7CvtrnJ4HaRJ:b2m7wxh) ([raw file](https://github.com/memkind/memkind/blob/65a92304ed7dc03ceca4d65d61c41d09b7d68ff3/tiering/ctl.c#L201)):*
> ```
> DAX_KMEM
> ```
not sure about naming maybe KMEM_DAX as opposite to "FS_DAX"

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[man/memtier.7, line 93 at r6](https://reviewable.io/reviews/memkind/memkind/630#-M_0GG0PCg61gTrOdBon:-M_0GG0PCg61gTrOdBoo:basx9m9) ([raw file](https://github.com/memkind/memkind/blob/65a92304ed7dc03ceca4d65d61c41d09b7d68ff3/man/memtier.7#L93)):*
> ```
> FS_DAX:/tmp/:10G:1,DRAM:1,DAX_KMEM:3,POLICY_STATIC_THRESHOLD
> ```
I would rather go with a simple example of a scenario using DRAM and KMEM_DAX only (two kinds)
Not sure if it is now possible to handle this by the library but please add here TODO for example with dynamic_thrshold

**Review by bratpiorka — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630#-:-M_QSCUc0qXM3E_e5RMz:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/630)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
