### PR TITLE
Feat memtier interface

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/554)

### CODE REVIEW

**Review by michalbiesek — COMMENTED** [review]
LGTM, please include changes from #553 

> Reviewed 8 of 8 files at r1, 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/554#-:-MUxC5ZX2XIb3t8fC3c9:bbyilo8)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 8 files at r1, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/554#-:-MUxKbDY87y-DdbfCuw_:bnfp4nl)* status: 4 of 11 files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/554)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[Makefile.am, line 559 at r4](https://reviewable.io/reviews/memkind/memkind/554#-MUxRXUz2-InmZuGr8yo:-MUxRXUz2-InmZuGr8yp:b-vwll8x) ([raw file](https://github.com/memkind/memkind/blob/99ac0febc049e00f064d00d06b554cf744b0c003/Makefile.am#L559)):*
> ```Makefile
> 	test/test_dax_kmem.sh
> 
> unit_tests_tiering: tiering/libmemtier.la checkprogs
> ```

is there a way to avoid building all tests from checkprogs?
___
*[src/memkind_memtier.c, line 30 at r4](https://reviewable.io/reviews/memkind/memkind/554#-MUxRITeCAKEc6M6A0XT:-MUxEGK89H7AGM9dqJdU:b-di6rbz) ([raw file](https://github.com/memkind/memkind/blob/99ac0febc049e00f064d00d06b554cf744b0c003/src/memkind_memtier.c#L30)):*
> ```C
>         if (pthread_mutex_unlock(&memtier_registry_g.lock) != 0)
>             assert(0 && "failed to release mutex");
>         return NULL;
> ```

should we add here some log_debug message like "cannot create multiple tiers based on the same kind"?
___
*[man/memkind_memtier.3, line 21 at r4](https://reviewable.io/reviews/memkind/memkind/554#-MUxR64z6Rfw7aWL7E8w:-MUxR64z6Rfw7aWL7E8x:b-gqfp78) ([raw file](https://github.com/memkind/memkind/blob/99ac0febc049e00f064d00d06b554cf744b0c003/man/memkind_memtier.3#L21)):*
> ```Roff
> .BI "struct memtier_tier *memtier_tier_new(memkind_t " "kind");
> .br
> .BI "void memtier_tier_delete(struct memtier_tier  " "*tier" );
> ```

here we have "memtier_tier_delete" but then we have "memtier_delete_kind" - should I unify this?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/554)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[Makefile.am, line 559 at r4](https://reviewable.io/reviews/memkind/memkind/554#-MUxRXUz2-InmZuGr8yo:-MUxSFsbCZ8wniNpQbjU:b32w12) ([raw file](https://github.com/memkind/memkind/blob/99ac0febc049e00f064d00d06b554cf744b0c003/Makefile.am#L559)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

is there a way to avoid building all tests from checkprogs?
</blockquote></details>

No
___
*[src/memkind_memtier.c, line 30 at r4](https://reviewable.io/reviews/memkind/memkind/554#-MUxRITeCAKEc6M6A0XT:-MUxSMrZC5gv7sc48PxL:bd63iu7) ([raw file](https://github.com/memkind/memkind/blob/99ac0febc049e00f064d00d06b554cf744b0c003/src/memkind_memtier.c#L30)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

should we add here some log_debug message like "cannot create multiple tiers based on the same kind"?
</blockquote></details>

IMHO not needed, this will be described in manual.
___
*[man/memkind_memtier.3, line 21 at r4](https://reviewable.io/reviews/memkind/memkind/554#-MUxR64z6Rfw7aWL7E8w:-MUxSIje8Q9TYzwieAIG:byuseg4) ([raw file](https://github.com/memkind/memkind/blob/99ac0febc049e00f064d00d06b554cf744b0c003/man/memkind_memtier.3#L21)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

here we have "memtier_tier_delete" but then we have "memtier_delete_kind" - should I unify this?
</blockquote></details>

https://github.com/memkind/memkind/pull/551#pullrequestreview-603131880

**Review by PatKamin — COMMENTED** [review]
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/554)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

**Comment by michalbiesek** [comment]
> 
> should we add here some log_debug message like "cannot create multiple tiers based on the same kind"?
> 
Ref: https://github.com/memkind/memkind/pull/555

**Comment by michalbiesek** [comment]
> > should we add here some log_debug message like "cannot create multiple tiers based on the same kind"?
> 
> Ref: #555

Please, include commit from #555 in this PR

**Review by michalbiesek — COMMENTED** [review]
Please squash 6ff99c3 into 0e95f53

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/554#-:-MV0VVMuB3829eb-45Bc:b-50d0bn)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @michalbiesek and @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 8 of 8 files at r5, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/554)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
