### PR TITLE
Add tbb::concurrent_hash_map example with memkind

### PR DESCRIPTION
**Pull request by igchor**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [x] Other

### Checklist

- [x] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [x] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments
I don't know how to best handle tbb detection so I'm open for suggestions. Right now, I just added a flag which can be used to enable/disable the example. If tbb is installed in some non-standard location then the user would also have to provide correct paths to CXXFLAGS (-I and -L). Do you have any better ideas?

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/468)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/468)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @igchor)

___
*[configure.ac, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/468#-MRL8orX5phgAxzBYEkV:-MRL8orY-LHwLOukjni2:brjl1kd) ([raw file](https://github.com/memkind/memkind/blob/1fa151190002cc46a522feecb67a1eeb518691ab/configure.ac#L2)):*
> ```
> 2020
> ```
bump please
___
*[configure.ac, line 255 at r1](https://reviewable.io/reviews/memkind/memkind/468#-MRL9-NHEbq7eUrOQMiP:-MRL9-NHEbq7eUrOQMiQ:b-pfmli4) ([raw file](https://github.com/memkind/memkind/blob/1fa151190002cc46a522feecb67a1eeb518691ab/configure.ac#L255)):*
> ```
> enable_tbb_examples="1"
> ```
do you know maybe on which TBB this should work - in other words, can we use AC_CHECK_LIB or check the version?
___
*[examples/Makefile.mk, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/468#-MRL9G-C7PfpSEgpy_BA:-MRL9G-C7PfpSEgpy_BB:bf70fwn) ([raw file](https://github.com/memkind/memkind/blob/1fa151190002cc46a522feecb67a1eeb518691ab/examples/Makefile.mk#L2)):*
> ```
> 2020
> ```
.
___
*[examples/Makefile.mk, line 29 at r1](https://reviewable.io/reviews/memkind/memkind/468#-MRL9C9jDTQbirTsROFV:-MRL9C9jDTQbirTsROFW:b-z3na2h) ([raw file](https://github.com/memkind/memkind/blob/1fa151190002cc46a522feecb67a1eeb518691ab/examples/Makefile.mk#L29)):*
> ```
> memkind_cpp_concurrent_hash_map
> ```
extend .gitgnore file please
___
*[examples/memkind_cpp_concurrent_hash_map.cpp, line 20 at r1](https://reviewable.io/reviews/memkind/memkind/468#-MRL9JHV495oVdUtvGvK:-MRL9JHV495oVdUtvGvL:byx9o0p) ([raw file](https://github.com/memkind/memkind/blob/1fa151190002cc46a522feecb67a1eeb518691ab/examples/memkind_cpp_concurrent_hash_map.cpp#L20)):*
> ```cpp
> 
>     dram_mutex() {
> 		mtx = std::unique_ptr<tbb::spin_rw_mutex>(new tbb::spin_rw_mutex);
> ```

run astyle.sh

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/468)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[configure.ac, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/468#-MRL8orX5phgAxzBYEkV:-MRUg4cU3a32n_JT5RSw:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1fa151190002cc46a522feecb67a1eeb518691ab/configure.ac#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
bump please
</blockquote></details>

Done.
___
*[configure.ac, line 255 at r1](https://reviewable.io/reviews/memkind/memkind/468#-MRL9-NHEbq7eUrOQMiP:-MRUjGK9C2LR_6sBSOWy:bog4ysl) ([raw file](https://github.com/memkind/memkind/blob/1fa151190002cc46a522feecb67a1eeb518691ab/configure.ac#L255)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> enable_tbb_examples="1"
> ```
do you know maybe on which TBB this should work - in other words, can we use AC_CHECK_LIB or check the version?
</blockquote></details>

I've added check for tbb in general, but I don't really know how to check a version using AC_CHECK_LIB since tbb does not export any unmangled symbols (I think).
___
*[examples/Makefile.mk, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/468#-MRL9G-C7PfpSEgpy_BA:-MRUjbMz6nXiVOXG4Ddj:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1fa151190002cc46a522feecb67a1eeb518691ab/examples/Makefile.mk#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
.
</blockquote></details>

Done.
___
*[examples/Makefile.mk, line 29 at r1](https://reviewable.io/reviews/memkind/memkind/468#-MRL9C9jDTQbirTsROFV:-MRUjbun1FZBxvunwDYm:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1fa151190002cc46a522feecb67a1eeb518691ab/examples/Makefile.mk#L29)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> memkind_cpp_concurrent_hash_map
> ```
extend .gitgnore file please
</blockquote></details>

Done.
___
*[examples/memkind_cpp_concurrent_hash_map.cpp, line 20 at r1](https://reviewable.io/reviews/memkind/memkind/468#-MRL9JHV495oVdUtvGvK:-MRUjjhY5ZC8OpjCWZ2L:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1fa151190002cc46a522feecb67a1eeb518691ab/examples/memkind_cpp_concurrent_hash_map.cpp#L20)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

run astyle.sh
</blockquote></details>

Done.

**Review by michalbiesek — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/468)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[examples/Makefile.mk, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/468#-MRL9G-C7PfpSEgpy_BA:-MRUltME0gopzE0VOB_S:b-8k8854) ([raw file](https://github.com/memkind/memkind/blob/1fa151190002cc46a522feecb67a1eeb518691ab/examples/Makefile.mk#L2)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

2021
___
*[test/Makefile.mk, line 241 at r2](https://reviewable.io/reviews/memkind/memkind/468#-MRUmEI_3myMUCQUPYQW:-MRUmEI_3myMUCQUPYQX:b-x5fcnf) ([raw file](https://github.com/memkind/memkind/blob/db2fd3b1e26008b08aea913d016e069fc90b65fc/test/Makefile.mk#L241)):*
> ```
> # Examples as tests
> ```
can we extend also this case ? see 6480fb1 for the files which should be updated.
Additonally the gitignore and spec file -> see https://github.com/memkind/memkind/blob/956c63358bbc4dec85a3235236f4c6758407dff6/memkind.spec.mk#L191

**Comment by lukaszstolarczuk** [comment]
Finishing this PR is not a high priority for us - to be continued.

Ref: https://github.com/memkind/memkind/issues/872

**Pull request closed without merging**
