### PR TITLE
Experiment MEMKIND_DAX_KMEM_BALANCED

### PR DESCRIPTION
**Pull request by michalbiesek**
- test experiment NUMA balancing
- support for MEMKIND_DAX_KMEM_BALANCED can be verified using ./memkind-balance-verify binary

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/688)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/688)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek and @PatKamin)

___
*[src/memkind_default.c, line 24 at r1](https://reviewable.io/reviews/memkind/memkind/688#-MdvWR2ZCO8aWCg5LDsd:-MdvWR2ZCO8aWCg5LDse:b-3wqvb1) ([raw file](https://github.com/memkind/memkind/blob/c2f2f2a04a2cef58f66bb375e45d66cf3378f425/src/memkind_default.c#L24)):*
> ```C
> #endif
> 
> #ifndef MPOL_PREFERRED_MANY
> ```

shouldn't this be defined in some header of external library?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/688)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[src/memkind_default.c, line 24 at r1](https://reviewable.io/reviews/memkind/memkind/688#-MdvWR2ZCO8aWCg5LDsd:-MdvXY3j-XDX_bFcc2xr:bg7zlda) ([raw file](https://github.com/memkind/memkind/blob/c2f2f2a04a2cef58f66bb375e45d66cf3378f425/src/memkind_default.c#L24)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

shouldn't this be defined in some header of external library?
</blockquote></details>

Nope - same situation as in case:
https://github.com/memkind/memkind/blame/master/src/memkind_default.c#L20-L22
https://github.com/memkind/memkind/blob/0b57ed5ab6aa3b484b5515f3f51bdc42994c810b/src/memkind_pmem.c#L19-L25

**Review by bratpiorka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/688)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/688)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 19 of 22 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/688)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[man/memkind.3, line 923 at r2](https://reviewable.io/reviews/memkind/memkind/688#-Me-vkng3CpJ0P1Tfw8D:-Me-vkng3CpJ0P1Tfw8E:bvg85ng) ([raw file](https://github.com/memkind/memkind/blob/c1d2a265d90ea16338f92e8aa9e4343daeb516fc/man/memkind.3#L923)):*
> ```Roff
> .B MEMKIND_DAX_KMEM_BALANCED (EXPERIMENTAL)
> Allocate from the closest persistent memory NUMA node at the time
> of allocation. The page placement can be later optimized (moved to DRAM) by kernel to react e.g. the accessing pattern changing.
> ```

to react to

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/688)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[man/memkind.3, line 923 at r2](https://reviewable.io/reviews/memkind/memkind/688#-Me-vkng3CpJ0P1Tfw8D:-Me5MhFE8tJkw9OgrPJW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c1d2a265d90ea16338f92e8aa9e4343daeb516fc/man/memkind.3#L923)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

to react to
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/688#-:-Me5P-KS2DPfPsySaWev:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/688)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Pull request merged**
