### PR TITLE
Cleanup logging mechanism

### PR DESCRIPTION
**Pull request by michalbiesek**
- remove reference to memkind_private
- remove obsolete NULL check

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/594)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/594)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek and @PatKamin)

___
*[tiering/ctl.c, line 298 at r1](https://reviewable.io/reviews/memkind/memkind/594#-MWZ1-wR5Hwl1sgd4ubJ:-MWZ0yqlDx1osdAghoNj:bjyau6x) ([raw file](https://github.com/memkind/memkind/blob/db709264abdba06ba2721a58583b33e224ea1aaa/tiering/ctl.c#L298)):*
> ```C
> 
>     current_tier = memtier_tier_new(kind);
>     if (current_tier == NULL) {
> ```


I think this check is also obsolete - memtier_builder_add_tier() checks if tier is null

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/594#-:-MWZ1Srr0HfSKvdUXa2y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/594)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[tiering/ctl.c, line 298 at r1](https://reviewable.io/reviews/memkind/memkind/594#-MWZ1-wR5Hwl1sgd4ubJ:-MWZ31G_762Ny7ja599k:bpiq16u) ([raw file](https://github.com/memkind/memkind/blob/db709264abdba06ba2721a58583b33e224ea1aaa/tiering/ctl.c#L298)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I think this check is also obsolete - memtier_builder_add_tier() checks if tier is null
</blockquote></details>

Not related with this PR, but done

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/594#-:-MWZ65XZDHsWtU_wJQkC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
