### PR TITLE
Fix message printing issue

### PR DESCRIPTION
**Pull request by PatKamin**
Fix wrong print messages introduced in commit #2d0279d

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/668)

### CODE REVIEW

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/668)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[test/dax_kmem_env_var_test.py, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/668#-MbmFNGw8OrEax_pzx9A:-MbmFNGw8OrEax_pzx9B:b-cppajk) ([raw file](https://github.com/memkind/memkind/blob/d41f3bf6d16f4293afadce24da72fadb89a39483/test/dax_kmem_env_var_test.py#L45)):*
> ```Python
>                 "is not the same as nodemask "
>                 "dax_kmem_nodemask_env_variable ({1})".format(
>                     dax_kmem_nodemask_default,
> ```

LGTM,
If you want to refer to commit, format your message like in e.g.: https://github.com/memkind/memkind/commit/8c5870cea711810fafb90fc04739bc3c3f5b7fa6

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/668#-:-MboXmSS7jPFivccghfF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/668)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[test/dax_kmem_env_var_test.py, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/668#-MbmFNGw8OrEax_pzx9A:-MbpnDK11_X99H5vKCEK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/8b68ddf739199ea09f533c842a47efb507b71188/test/dax_kmem_env_var_test.py#L45)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

LGTM,
If you want to refer to commit, format your message like in e.g.: https://github.com/memkind/memkind/commit/8c5870cea711810fafb90fc04739bc3c3f5b7fa6
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/668)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Pull request merged**
