### PR TITLE
Add zipf distribution tiering benchmark

### PR DESCRIPTION
**Pull request by PatKamin**
Co-authored-by: Maciej Paczocha <maciej.paczocha@intel.com>

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/729)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/729)* status: all files reviewed, 4 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 136 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPcSyJ9LTqO3TguWOl:-MuPcSyJ9LTqO3TguWOm:b8n8gy5) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L136)):*
> ```cpp
>                             0, data_size_u64);
>                         size_t index = distr(generator);
>                         // RFC: Make this malloc() twice as large than for
> ```

Could you change source of copy to a random location? It common that cache prefetcher reads more data than needed (eg. cacheline with requested data and one next)
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 151 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPccZtAGvQRNINONGb:-MuPccZtAGvQRNINONGc:blgdy9) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L151)):*
> ```cpp
>                         // read-modify-write?
>                         static_cast<volatile uint64_t *>(data.get())[i] =
>                             static_cast<volatile uint64_t *>(
> ```

in this scenario you can read data from one half of buffer and write it to the second half
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 344 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPbewt4vd5V2Ky2sJS:-MuPbewt4vd5V2Ky2sJT:b6b69sj) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L344)):*
> ```cpp
> 
> // what needs to be done:
> // 3. re-allocate loaders - dropping this idea?
> ```

I don't understand this comment
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 412 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPnJ6n7vSkUfAwKJQo:-MuPnJ6oEjGoMcjS9NvU:b7e70wl) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L412)):*
> ```cpp
> int main(int argc, char *argv[])
> {
>     size_t PMEM_DRAM_RATIO = 8;
> ```

could you also parametrize pmem_dram_ratio?

**Review by maciekpac — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/729)* status: all files reviewed, 7 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 13 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPlShy6219XiXEyBBP:-MuPlShy6219XiXEyBBQ:bb852f0) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L13)):*
> ```cpp
> #include <thread>
> 
> typedef enum tc_test_case_t
> ```

This is a c++ file, can we use something like:
```c++
enum class TestCase {
    RANDOM_INC,
     .....
};
```

and then use them as TestCase::RANDOM_INC ?

Does "tc" stand for "test case" ? In such case, I would avoid repetition if possible.
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 111 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPlEm-2OixRIKdWJgv:-MuPlEm-2OixRIKdWJgw:bpci2br) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L111)):*
> ```cpp
>         switch (test_case) {
>             case (TC_RANDOM_INC):
>                 for (size_t it = 0; it < iterations; ++it) {
> ```

It's good that the code is repeated, under switch-case, so that the switch statement is evaluated only once :)
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 133 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPoC619Gi2fvF76gvt:-MuPoC619Gi2fvF76gvu:bg5as5i) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L133)):*
> ```cpp
>                     for (size_t i = 0; i < data_size_u64 - CACHE_LINE_SIZE_U64;
>                          i += CACHE_LINE_SIZE_U64) {
>                         std::uniform_int_distribution<uint64_t> distr(
> ```

Can't this be created before the loops, only once ?
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 136 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPcSyJ9LTqO3TguWOl:-MuPoLBgEJQmkr30fR0j:b6cxfi5) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L136)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Could you change source of copy to a random location? It common that cache prefetcher reads more data than needed (eg. cacheline with requested data and one next)
</blockquote></details>

You want to say that we should generate two numbers, not one?

About the cache size - maybe we would try to use 2*CACHE_LINE_SIZE_U64 or 5*CACHE_LINE_SIZE_U64, also in other places (e.g. SEQ_INC) ?

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/729)* status: all files reviewed, 7 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 136 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPcSyJ9LTqO3TguWOl:-MuPq-OQBRI44XoEvxOU:bjumfx) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L136)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

You want to say that we should generate two numbers, not one?

About the cache size - maybe we would try to use 2*CACHE_LINE_SIZE_U64 or 5*CACHE_LINE_SIZE_U64, also in other places (e.g. SEQ_INC) ?
</blockquote></details>

Yes, two numbers. About SEQ_INC - this is a sequential test so I would leave it as it is.

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/729)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 13 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPlShy6219XiXEyBBP:-MuQ3UHg4GPqtjAG2FMS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L13)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

This is a c++ file, can we use something like:
```c++
enum class TestCase {
    RANDOM_INC,
     .....
};
```

and then use them as TestCase::RANDOM_INC ?

Does "tc" stand for "test case" ? In such case, I would avoid repetition if possible.
</blockquote></details>

Done.
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 111 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPlEm-2OixRIKdWJgv:-MuQ42Ft0SgB9uUkswSx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L111)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

It's good that the code is repeated, under switch-case, so that the switch statement is evaluated only once :)
</blockquote></details>

Done.
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 133 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPoC619Gi2fvF76gvt:-MuQ4NsH1cRcNmx6iVyS:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L133)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Can't this be created before the loops, only once ?
</blockquote></details>

Done.
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 136 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPcSyJ9LTqO3TguWOl:-MuQGopj8fTMAOmh1SXt:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L136)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Yes, two numbers. About SEQ_INC - this is a sequential test so I would leave it as it is.
</blockquote></details>

Done.
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 151 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPccZtAGvQRNINONGb:-MuQJky36nD34RniWlLt:b-ee4yff) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L151)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

in this scenario you can read data from one half of buffer and write it to the second half
</blockquote></details>

I would have two times less reads than in other scenarios then. I think that current modification would be better, with larger leaps between data being written and read.
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 344 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPbewt4vd5V2Ky2sJS:-MuQK6wG5J401vAFEkmo:b-7tg66k) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L344)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I don't understand this comment
</blockquote></details>

I understand it as doing reallocations after initial mallocs - but I don't see a point in doing this - @maciekpac ?
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 412 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPnJ6n7vSkUfAwKJQo:-MuQa99x6a7aVm7YIJ_v:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L412)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

could you also parametrize pmem_dram_ratio?
</blockquote></details>

Done.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/729)* status: all files reviewed, 4 unresolved discussions (waiting on @maciekpac)

___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 151 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPccZtAGvQRNINONGb:-MuQuM1S8LN8tBDf154f:b32wtd) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L151)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I would have two times less reads than in other scenarios then. I think that current modification would be better, with larger leaps between data being written and read.
</blockquote></details>

ok

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/729)* status: all files reviewed, 4 unresolved discussions (waiting on @maciekpac)

**Review by maciekpac — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/729)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 344 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPbewt4vd5V2Ky2sJS:-MuVstuz7AzX8-tcnRDR:b-y4ps89) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L344)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I understand it as doing reallocations after initial mallocs - but I don't see a point in doing this - @maciekpac ?
</blockquote></details>

I think it can be removed, it was added long time ago and is no longer valid
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 143 at r3](https://reviewable.io/reviews/memkind/memkind/729#-MuVsbJm-D7sUaoXsVuH:-MuVsbJm-D7sUaoXsVuI:blrhqd5) ([raw file](https://github.com/memkind/memkind/blob/c52110f1d4532a1641379f74167412208ab0a434/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L143)):*
> ```cpp
>                 for (size_t it = 0; it < iterations; ++it) {
>                     for (size_t i = 0;
>                          i < data_size_u64 - 5 * CACHE_LINE_SIZE_U64;
> ```

a macro/constant would be better than "5" - easier to modify and check effects on the number of cache misses

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/729)* status: all files reviewed, 3 unresolved discussions (waiting on @PatKamin)

___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 132 at r3](https://reviewable.io/reviews/memkind/memkind/729#-MuVyJ4f3_l3_GvFJobD:-MuVyJ4f3_l3_GvFJobE:b-knefej) ([raw file](https://github.com/memkind/memkind/blob/c52110f1d4532a1641379f74167412208ab0a434/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L132)):*
> ```cpp
>                     for (size_t i = 0; i < data_size_u64;
>                          i += CACHE_LINE_SIZE_U64) {
>                         size_t index_from = distr(generator);
> ```

please add a TODO here "consider using a table with prepared random values in case of CPU-bottleneck"

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/729)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 344 at r1](https://reviewable.io/reviews/memkind/memkind/729#-MuPbewt4vd5V2Ky2sJS:-MujGcl26vFlDuuhCNna:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/0abe528258d923ce956b5fce5f6fa8af424cfa9c/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L344)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I think it can be removed, it was added long time ago and is no longer valid
</blockquote></details>

Done.
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 132 at r3](https://reviewable.io/reviews/memkind/memkind/729#-MuVyJ4f3_l3_GvFJobD:-MujGJh09EmZesRgGchh:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c52110f1d4532a1641379f74167412208ab0a434/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L132)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please add a TODO here "consider using a table with prepared random values in case of CPU-bottleneck"
</blockquote></details>

Done.
___
*[utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp, line 143 at r3](https://reviewable.io/reviews/memkind/memkind/729#-MuVsbJm-D7sUaoXsVuH:-MujGZCJ0Gf3ETJFJf6U:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c52110f1d4532a1641379f74167412208ab0a434/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L143)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

a macro/constant would be better than "5" - easier to modify and check effects on the number of cache misses
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/729)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

**Review by maciekpac — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/729)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
