### PR TITLE
Modify TopologyFactory

### PR DESCRIPTION
**Pull request by michalbiesek**
- move kind into class
- provide is_kind_HighBandwidth,is_kind_required_HMAT,is_HMAT_supported functions

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/506)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/506)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[test/TestPrereq.hpp, line 338 at r1](https://reviewable.io/reviews/memkind/memkind/506#-MSSUeAQ45_6pWCzUYM8:-MSSUeAQ45_6pWCzUYM9:b-bwogjx) ([raw file](https://github.com/memkind/memkind/blob/97ce7480f65fe0509fe88c39a73fe6dff59c55a9/test/TestPrereq.hpp#L338)):*
> ```cpp
>         return (kind == MEMKIND_LOWEST_LATENCY_LOCAL ||
>                 kind == MEMKIND_LOWEST_LATENCY_LOCAL_PREFERRED ||
>                 is_kind_HighBandwidth(kind));
> ```

MEMKIND_HBW requires HMAT?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/506)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[test/TestPrereq.hpp, line 338 at r1](https://reviewable.io/reviews/memkind/memkind/506#-MSSUeAQ45_6pWCzUYM8:-MSSV-pF0gutawrTy4bW:b-siu1al) ([raw file](https://github.com/memkind/memkind/blob/97ce7480f65fe0509fe88c39a73fe6dff59c55a9/test/TestPrereq.hpp#L338)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

MEMKIND_HBW requires HMAT?
</blockquote></details>

For CPU different than KN yes - but regarding changes this PR I update this commit

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/506#-:-MSSsASB0uXDUjKj-ZZH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/506#-:-MSWv1O_0ByuEsl1FXxU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
