### PR TITLE
Return valid ptr for size zero passed to malloc-like functions

### PR DESCRIPTION
**Pull request by PatKamin**
Make memkind return from malloc-like functions either NULL or a valid ptr,
depending on what is returned by the system's standard library in such
situations.

This change affects the existing API in a sense that the corner case return value is changed.
This is in response to the issue #853.

### Types of changes

- [x] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

- - -
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/856)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r1, 6 of 7 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: all files reviewed, 4 unresolved discussions (waiting on @kilobyte, @PatKamin, and @pbalcer)

___
*[`configure.ac` line 30 at r1](https://reviewable.io/reviews/memkind/memkind/856#-NDlQ0Dk3mPT5KEo5gSB:-NDlQ0Dk3mPT5KEo5gSC:b-q74txj) ([raw file](https://github.com/memkind/memkind/blob/a681a03717b621dba8c71dd1934b72eca3b73694/configure.ac#L30)):*
> ```M4Sugar
> 
> #================================malloc(0)=====================================
> AC_CACHE_CHECK([check standard library malloc(0) return ptr], [malloc_cv_zero_bytes],
> ```

great!
___
*[`doc/memkind.3.md` line 144 at r3](https://reviewable.io/reviews/memkind/memkind/856#-NE07Dmx-eZqj8WfUq0O:-NE07Dmx-eZqj8WfUq0P:b-myk7nb) ([raw file](https://github.com/memkind/memkind/blob/2ff4a74c204fa13e8cc700c442870bb5c80357e1/doc/memkind.3.md#L144)):*
> ```Markdown
>     of *num* * *size*, with the exception that the allocated memory is explicitly initialized
>     to zero bytes.
>     If *nmemb* or *size* is zero, then `memkind_calloc()` returns either NULL or a valid ptr,
> ```

nmemb?



_Code quote:_
```Markdown
nmemb
```
___
*[`doc/memkind.3.md` line 175 at r3](https://reviewable.io/reviews/memkind/memkind/856#-NE07HIBBTpYjpmq6fiA:-NE07HIBBTpYjpmq6fiB:b-ep6baw) ([raw file](https://github.com/memkind/memkind/blob/2ff4a74c204fa13e8cc700c442870bb5c80357e1/doc/memkind.3.md#L175)):*
> ```Markdown
>     pointed to by *memptr*. The requested *alignment* must be a power of 2 at least as large
>     as *sizeof(void*)*.
>     If *size* is 0 and the system's standard library returns NULL on malloc(0) call,
> ```

you changed 0 -> "zero" in few places but not here



_Code quote:_
```Markdown
0
```
___
*[`man/memkind.3` line 126 at r3](https://reviewable.io/reviews/memkind/memkind/856#-NE07XO2CEL9W_iisCQJ:-NE07XO2CEL9W_iisCQK:b-7m4j0q) ([raw file](https://github.com/memkind/memkind/blob/2ff4a74c204fa13e8cc700c442870bb5c80357e1/man/memkind.3#L126)):*
> ```Roff
> argument of \f[I]num\f[R] * \f[I]size\f[R], with the exception that the
> allocated memory is explicitly initialized to zero bytes.
> If \f[I]nmemb\f[R] or \f[I]size\f[R] is zero, then
> ```

nmemb



_Code quote:_
```Roff
nmemb
```

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: 18 of 21 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @pbalcer)

___
*[`doc/memkind.3.md` line 144 at r3](https://reviewable.io/reviews/memkind/memkind/856#-NE07Dmx-eZqj8WfUq0O:-NE0AevP6zcOkx4v1b_O:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2ff4a74c204fa13e8cc700c442870bb5c80357e1/doc/memkind.3.md#L144)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

nmemb?
</blockquote></details>

Done.
___
*[`doc/memkind.3.md` line 175 at r3](https://reviewable.io/reviews/memkind/memkind/856#-NE07HIBBTpYjpmq6fiA:-NE0GRqaC0HzwEUvdLFa:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2ff4a74c204fa13e8cc700c442870bb5c80357e1/doc/memkind.3.md#L175)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

you changed 0 -> "zero" in few places but not here
</blockquote></details>

Done.
___
*[`man/memkind.3` line 126 at r3](https://reviewable.io/reviews/memkind/memkind/856#-NE07XO2CEL9W_iisCQJ:-NE0Cl27ElE5AJo93yit:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2ff4a74c204fa13e8cc700c442870bb5c80357e1/man/memkind.3#L126)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

nmemb
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte and @pbalcer)

**Review by pbalcer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: 15 of 22 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[`configure.ac` line 30 at r7](https://reviewable.io/reviews/memkind/memkind/856#-NEeO3Lz-ADuEYOgp6Qc:-NEeO3Lz-ADuEYOgp6Qd:b-h4ktt1) ([raw file](https://github.com/memkind/memkind/blob/9eeadfebaa9c79ebd36b6015d272dc174824ce59/configure.ac#L30)):*
> ```M4Sugar
> 
> #================================malloc(0)=====================================
> AC_CACHE_CHECK([standard library malloc(0) return ptr], [malloc_cv_zero_bytes],
> ```

the system memkind runs on is not necessarily the one that it was compiled on. This check should be done when initializing libmemtier, and the flag to control the behavior be a runtime one, not a compile-time ifdef.

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: 15 of 22 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @kilobyte, and @pbalcer)

___
*[`configure.ac` line 30 at r7](https://reviewable.io/reviews/memkind/memkind/856#-NEeO3Lz-ADuEYOgp6Qc:-NEju6GP-0yIXrccJVfo:b3psajm) ([raw file](https://github.com/memkind/memkind/blob/9eeadfebaa9c79ebd36b6015d272dc174824ce59/configure.ac#L30)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

the system memkind runs on is not necessarily the one that it was compiled on. This check should be done when initializing libmemtier, and the flag to control the behavior be a runtime one, not a compile-time ifdef.
</blockquote></details>

This would resolve the issue when running libmemtier, but not when using memkind API from libmemkind. Maybe providing an extra parameter to set malloc(0) behavior explicitly by user would be a better idea? With a default behavior of returning a valid ptr? In such a case automatic detection wouldn't be provided.

**Review by pbalcer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: 15 of 22 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[`configure.ac` line 30 at r7](https://reviewable.io/reviews/memkind/memkind/856#-NEeO3Lz-ADuEYOgp6Qc:-NEk0ZIL9wGGHnZ2z0Cz:blo8yjv) ([raw file](https://github.com/memkind/memkind/blob/9eeadfebaa9c79ebd36b6015d272dc174824ce59/configure.ac#L30)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This would resolve the issue when running libmemtier, but not when using memkind API from libmemkind. Maybe providing an extra parameter to set malloc(0) behavior explicitly by user would be a better idea? With a default behavior of returning a valid ptr? In such a case automatic detection wouldn't be provided.
</blockquote></details>

Yes, there will need to be a public API that configures this behavior in libmemkind so that you can use in libmemtier.

The default behavior of memkind should be whatever it is right now so that we don't break backward compatibility.

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: 15 of 22 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @kilobyte, and @pbalcer)

___
*[`configure.ac` line 30 at r7](https://reviewable.io/reviews/memkind/memkind/856#-NEeO3Lz-ADuEYOgp6Qc:-NEkGd9CD-oztko6q2tU:b-m0qnv) ([raw file](https://github.com/memkind/memkind/blob/9eeadfebaa9c79ebd36b6015d272dc174824ce59/configure.ac#L30)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Yes, there will need to be a public API that configures this behavior in libmemkind so that you can use in libmemtier.

The default behavior of memkind should be whatever it is right now so that we don't break backward compatibility.
</blockquote></details>

OK, I will add a configure parameter for setting malloc(0) behavior of returning non-null ptr and leave as a default the current state of code (returning NULL in this case).

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @kilobyte, and @pbalcer)

___
*[`configure.ac` line 30 at r7](https://reviewable.io/reviews/memkind/memkind/856#-NEeO3Lz-ADuEYOgp6Qc:-NEu2f-v10q8nxtOdlPw:b52bonw) ([raw file](https://github.com/memkind/memkind/blob/9eeadfebaa9c79ebd36b6015d272dc174824ce59/configure.ac#L30)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

OK, I will add a configure parameter for setting malloc(0) behavior of returning non-null ptr and leave as a default the current state of code (returning NULL in this case).
</blockquote></details>

Reworked, please review.

**Review by pbalcer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[`configure.ac` line 30 at r7](https://reviewable.io/reviews/memkind/memkind/856#-NEeO3Lz-ADuEYOgp6Qc:-NF8SHTW5yeKEVaa1pAV:b-wlpi9s) ([raw file](https://github.com/memkind/memkind/blob/9eeadfebaa9c79ebd36b6015d272dc174824ce59/configure.ac#L30)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Reworked, please review.
</blockquote></details>

But this is still a compile-time option. You need to add a new API function that configures this behavior at runtime for kinds. For example:

`void memkind_set_allow_zero_allocs(memkind_t kind, bool allow_zero_allocs);`

**Review by pbalcer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[`configure.ac` line 30 at r7](https://reviewable.io/reviews/memkind/memkind/856#-NEeO3Lz-ADuEYOgp6Qc:-NF8SyJ86E36iXJYEnZ0:b-p3dn9u) ([raw file](https://github.com/memkind/memkind/blob/9eeadfebaa9c79ebd36b6015d272dc174824ce59/configure.ac#L30)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

But this is still a compile-time option. You need to add a new API function that configures this behavior at runtime for kinds. For example:

`void memkind_set_allow_zero_allocs(memkind_t kind, bool allow_zero_allocs);`

</blockquote></details>

(and then use that inside of libmemtier, when that library is being initialized, based on the behavior of the system malloc).

**Review by pbalcer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: 0 of 41 files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @PatKamin)

___
*[`configure.ac` line 33 at r9](https://reviewable.io/reviews/memkind/memkind/856#-NFi5SqR5M3juV7guZ5m:-NFi5SqSDZk5_plAUAUF:bpdxhlf) ([raw file](https://github.com/memkind/memkind/blob/e44f80f5aaf3dfbb357f44f1c81c8febd582f6e2/configure.ac#L33)):*
> ```M4Sugar
>   [AS_HELP_STRING([--enable-malloc-nonnull], [Memkind malloc-like functions return a valid pointer for size = 0])],
> [if test "x$enable_malloc_nonnull" = "xyes" ; then
>   enable_malloc_nonnull="1"
> ```

I think you can now entirely remove this compile-time check and the `MEMKIND_NONNULL_CHECK` ifdef.
___
*[`src/memkind_arena.c` line 660 at r9](https://reviewable.io/reviews/memkind/memkind/856#-NFi3ve05UoGU1nL3t-P:-NFi3ve05UoGU1nL3t-Q:b-pki1uz) ([raw file](https://github.com/memkind/memkind/blob/e44f80f5aaf3dfbb357f44f1c81c8febd582f6e2/src/memkind_arena.c#L660)):*
> ```C
>     unsigned arena;
> 
>     if (!kind->allow_zero_allocs && (MEMKIND_UNLIKELY(!size || !num))) {
> ```

Shouldn't this be `(!allow_zero_allocs && !size) || !num` ?
___
*[`src/memkind_arena.c` line 761 at r9](https://reviewable.io/reviews/memkind/memkind/856#-NFi4EcdCqEN3vbqoZrO:-NFi4EcdCqEN3vbqoZrP:b-etpgeh) ([raw file](https://github.com/memkind/memkind/blob/a94597e4660ac95dedec3743aa619cf2dd5b0df6/src/memkind_arena.c#L761)):*
> ```C
> static void *jemk_mallocx_check(size_t size, int flags)
> {
>     if (MEMKIND_LIKELY(size)) {
> ```

Why did you change this single check for multiple checks later down in the code?

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856)* status: 0 of 41 files reviewed, 4 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @pbalcer)

___
*[`src/memkind_arena.c` line 660 at r9](https://reviewable.io/reviews/memkind/memkind/856#-NFi3ve05UoGU1nL3t-P:-NFrghF4-TXZ97TPUw4l:b-ykm4gc) ([raw file](https://github.com/memkind/memkind/blob/e44f80f5aaf3dfbb357f44f1c81c8febd582f6e2/src/memkind_arena.c#L660)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Shouldn't this be `(!allow_zero_allocs && !size) || !num` ?
</blockquote></details>

I've included `num` check, because this `calloc` internally passes `size` and `num` parameters as `malloc(size * num)`. So to have the behavior of `malloc(0)` preserved, I check for `!num` also. See here: https://github.com/memkind/memkind/blob/master/src/memkind_arena.c#L654 .
___
*[`src/memkind_arena.c` line 761 at r9](https://reviewable.io/reviews/memkind/memkind/856#-NFi4EcdCqEN3vbqoZrO:-NFrgBGPEvlNpAIO9n-0:bg4iqrs) ([raw file](https://github.com/memkind/memkind/blob/a94597e4660ac95dedec3743aa619cf2dd5b0df6/src/memkind_arena.c#L761)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

Why did you change this single check for multiple checks later down in the code?
</blockquote></details>

Thanks, no need for that, can't remember the reasons. Adding an additional parameter to handle it in this function's scope.
___
*[`configure.ac` line 30 at r7](https://reviewable.io/reviews/memkind/memkind/856#-NEeO3Lz-ADuEYOgp6Qc:-NFrLfkiEeilgyHdCZrr:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9eeadfebaa9c79ebd36b6015d272dc174824ce59/configure.ac#L30)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

(and then use that inside of libmemtier, when that library is being initialized, based on the behavior of the system malloc).
</blockquote></details>

Done.
___
*[`configure.ac` line 33 at r9](https://reviewable.io/reviews/memkind/memkind/856#-NFi5SqR5M3juV7guZ5m:-NFrLifsDjqmaiqu9BOy:bs7wumx) ([raw file](https://github.com/memkind/memkind/blob/e44f80f5aaf3dfbb357f44f1c81c8febd582f6e2/configure.ac#L33)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I think you can now entirely remove this compile-time check and the `MEMKIND_NONNULL_CHECK` ifdef.
</blockquote></details>

Done.

**Review by pbalcer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 38 files at r10.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/856#-:-NGQf6ZB1_VKvr_HmMJd:bnfp4nl)* status: 1 of 41 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @kilobyte)

**Pull request merged**
