### PR TITLE
fix memkind_malloc_usable_size() definition

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/716)

### CODE REVIEW

**Review by kilobyte — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/716)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[include/memkind.h, line 12 at r1](https://reviewable.io/reviews/memkind/memkind/716#-Mr1OigO-7oBsLVo7TqS:-Mr1OigP4WCnD0ushVRT:b45qbjn) ([raw file](https://github.com/memkind/memkind/blob/02dd9d9c6d08c1aae362cf22bf969aa82f33006a/include/memkind.h#L12)):*
> ```objc
> #include <sys/types.h>
> 
> #ifndef MEMKIND_MALLOC_USABLE_SIZE_CONST_DEFINED
> ```

Why not just `#ifndef MEMKIND_MALLOC_USABLE_SIZE_CONST` ?  No matter if it's "const" or "", the define exists.

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/716)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[include/memkind.h, line 12 at r1](https://reviewable.io/reviews/memkind/memkind/716#-Mr1OigO-7oBsLVo7TqS:-Mr1U1XT1y1J7Yf5Clln:b-xcnspv) ([raw file](https://github.com/memkind/memkind/blob/02dd9d9c6d08c1aae362cf22bf969aa82f33006a/include/memkind.h#L12)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Why not just `#ifndef MEMKIND_MALLOC_USABLE_SIZE_CONST` ?  No matter if it's "const" or "", the define exists.
</blockquote></details>

good point :)

**Review by kilobyte — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/716)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac and @PatKamin)

**Review by PatKamin — APPROVED** [review]

**Review by maciekpac — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/716)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
