### PR TITLE
Implement verbose option

### PR DESCRIPTION
**Pull request by michalbiesek**
- silent unnecessary information from build
- leave print of tests and mout directory

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/480)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/480)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[utils/qemu/main.py, line 74 at r1](https://reviewable.io/reviews/memkind/memkind/480#-MRYwoyg0r2bRvJsDqC8:-MRYwoyg0r2bRvJsDqC9:b-eybh9v) ([raw file](https://github.com/memkind/memkind/blob/3b659fe5aee74bf1952d3afffae0de7e1b9d2c59/utils/qemu/main.py#L74)):*
> ```Python
> 
>     @property
>     def _echo_option(self) -> dict:
> ```

nit: _verbosity_option ?
___
*[utils/qemu/main.py, line 78 at r1](https://reviewable.io/reviews/memkind/memkind/480#-MRYvtNp7HUWQm-HO0IZ:-MRYvtNqB0NGb1wwx8x0:b-kouvtr) ([raw file](https://github.com/memkind/memkind/blob/3b659fe5aee74bf1952d3afffae0de7e1b9d2c59/utils/qemu/main.py#L78)):*
> ```Python
>         Echo cmd options
>         """
>         return {'echo':True} if self.verbose else {'hide':True}
> ```

Add whitespaces before values in dicts.

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/480#-:-MRYySO-6xjsUx3pIeS7:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/480)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[utils/qemu/main.py, line 78 at r1](https://reviewable.io/reviews/memkind/memkind/480#-MRYvtNp7HUWQm-HO0IZ:-MRZ-Iw13WsCaghyKHwe:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3b659fe5aee74bf1952d3afffae0de7e1b9d2c59/utils/qemu/main.py#L78)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add whitespaces before values in dicts.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/480)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[utils/qemu/main.py, line 78 at r2](https://reviewable.io/reviews/memkind/memkind/480#-MRZ-wH-87vuu_UIzuRG:-MRZ-wH-87vuu_UIzuRH:b-kn5qzo) ([raw file](https://github.com/memkind/memkind/blob/95fa2b02c0736c1a3eadce8c5b03cdf146a1820f/utils/qemu/main.py#L78)):*
> ```Python
>         Verbosity option
>         """
>         return {'echo' : True} if self.verbose else {'hide' : True}
> ```

nit: Remove whitespaces after keys in dictionaries :)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/480#-:-MRZ7apN5rSZVXUZhk7f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
