### PR TITLE
Complete memtier api manual

### PR DESCRIPTION
**Pull request by PatKamin**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [x] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/827)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/827)* status: all files reviewed, 3 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[`man/memkind_memtier.3` line 4 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N50QihvAwHZjfV_DZBD:-N50QihvAwHZjfV_DZBE:b-vcjost) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L4)):*
> ```Roff
> .\" Copyright (C) 2021-2022 Intel Corporation.
> .\"
> .TH "MEMKIND_MEMTIER" 3 "2021-03-01" "Intel Corporation" "MEMKIND_MEMTIER" \" -*- nroff -*-
> ```

I think you should also update the date here
___
*[`man/memkind_memtier.3` line 103 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N50PdkGD7rDiKy5cB1I:-N50PdkGD7rDiKy5cB1J:b-9unw59) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L103)):*
> ```Roff
> .PP
> .BR memtier_builder_delete ()
> removes the
> ```

deletes
___
*[`man/memkind_memtier.3` line 139 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N50Ps6N3rrVFGdvNPsp:-N50Ps6N3rrVFGdvNPsq:b-9unw59) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L139)):*
> ```Roff
> .PP
> .BR memtier_delete_memtier_memory ()
> removes the
> ```

deletes

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/827)* status: all files reviewed, 8 unresolved discussions (waiting on @kilobyte and @PatKamin)

___
*[`man/memkind_memtier.3` line 16 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N54Ed2q1FMCuEI8vc9w:-N54Ed2q1FMCuEI8vc9x:b-8caodw) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L16)):*
> ```Roff
> .B Link with -lmemkind
> .sp
> Instead of the API directly,
> ```

Sounds strange... Maybe we could just list the options, e.g. "the API can be used either directly from C code, or via environment variables ...."

Also, the functionality is slightly different - single, self-contained binary vs a binary that requires environment variables...
___
*[`man/memkind_memtier.3` line 78 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N54FFwy2G9y-_1IuwQu:-N54FFwz1zw5P5lqZqMb:bvxxog8) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L78)):*
> ```Roff
> .BI "int memtier_ctl_set(struct memtier_builder " "*builder" ", const char " "*name" ", const void " "*val" );
> .SH "DESCRIPTION"
> This library enables memory tiering mechanism. It allows to make allocations with the usage of multiple kinds keeping a
> ```

nit: 
This library enables explicit allocation-time memory tiering.

I don't think *mechanism* is necessary here; also, we currently support tiering at allocation time (no movement), the allocation from C++ code is explicit (in a way that the code has to be modified); most transparent solutions focus on movement, it would be great to note that this is not the case here.
___
*[`man/memkind_memtier.3` line 79 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N54Fmrq4jL7lBTiindO:-N54Fmrq4jL7lBTiindP:b-7depxj) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L79)):*
> ```Roff
> .SH "DESCRIPTION"
> This library enables memory tiering mechanism. It allows to make allocations with the usage of multiple kinds keeping a
> specified ratio between them. This ratio determines how much of total allocated memory should be allocated with each kind.
> ```

*Allocated to* is the most common preposition, this sounds strange...

https://www.freecollocation.com/search?word=allocate

I also think "allocated from" might be acceptable, but I'm not sure
___
*[`man/memkind_memtier.3` line 127 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N54HhuJ5UfLrh5zUkqT:-N54HhuJ5UfLrh5zUkqU:bp9nn0c) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L127)):*
> ```Roff
> The higher it is relative to other tiers'
> .IR kind_ratio ,
> the higher the share of allocated memory on that tier.
> ```

Maybe some practical example ? E.g.

ratio: DRAM:DAX_KMEM 1:4
sample allocation size: 20 GB total, 4 GB DRAM, 16 GB DAX_KMEM
___
*[`man/memkind_memtier.3` line 163 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N54IcFuEqvXatv8ALgC:-N54IcFuEqvXatv8ALgD:brp3k3u) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L163)):*
> ```Roff
> bytes of memory on one of memory tiers defined by the
> .IR memory .
> See TODO for further details on memory tiers.
> ```

TODO ???

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/827)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @maciekpac)

___
*[`man/memkind_memtier.3` line 4 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N50QihvAwHZjfV_DZBD:-N54vLaq4EGPwOoU_Pz2:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L4)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

I think you should also update the date here
</blockquote></details>

Done.
___
*[`man/memkind_memtier.3` line 16 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N54Ed2q1FMCuEI8vc9w:-N54wCb42pu3IDSojjY7:by02ml1) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L16)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Sounds strange... Maybe we could just list the options, e.g. "the API can be used either directly from C code, or via environment variables ...."

Also, the functionality is slightly different - single, self-contained binary vs a binary that requires environment variables...
</blockquote></details>

Rephrased, is it any better?
___
*[`man/memkind_memtier.3` line 79 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N54Fmrq4jL7lBTiindO:-N54yZLz0Zl2w2oVKySL:bw9y7de) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L79)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

*Allocated to* is the most common preposition, this sounds strange...

https://www.freecollocation.com/search?word=allocate

I also think "allocated from" might be acceptable, but I'm not sure
</blockquote></details>

Rephrased. Please, verify.
___
*[`man/memkind_memtier.3` line 103 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N50PdkGD7rDiKy5cB1I:-N54yg7N2WDcv1QPa-_8:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L103)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

deletes
</blockquote></details>

Done.
___
*[`man/memkind_memtier.3` line 127 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N54HhuJ5UfLrh5zUkqT:-N555KuI34CosVE5Bo15:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L127)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Maybe some practical example ? E.g.

ratio: DRAM:DAX_KMEM 1:4
sample allocation size: 20 GB total, 4 GB DRAM, 16 GB DAX_KMEM
</blockquote></details>

Done.
___
*[`man/memkind_memtier.3` line 139 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N50Ps6N3rrVFGdvNPsp:-N54yjbp-MtPMEuJTvUG:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L139)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

deletes
</blockquote></details>

Done.
___
*[`man/memkind_memtier.3` line 163 at r1](https://reviewable.io/reviews/memkind/memkind/827#-N54IcFuEqvXatv8ALgC:-N555M3u2m3oRGd9rGTx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/724221b69be654ed2b538a173c11a2954afe6c87/man/memkind_memtier.3#L163)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

TODO ???
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/827)* status: all files reviewed, 4 unresolved discussions (waiting on @kilobyte and @maciekpac)

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 5 of 5 files at r11, 2 of 2 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Pull request merged**
