### PR TITLE
Modify Readme Device DAX part

### PR DESCRIPTION
**Pull request by michalbiesek**
- provide information about kernel patches for DAX KMEM
- refer to pmem.io blog post regarding configuration part

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/376)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/376)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[README, line 198 at r1](https://reviewable.io/reviews/memkind/memkind/376#-MHz1O6xA6mOOoS0q6es:-MHz1O6xA6mOOoS0q6et:bun2p22) ([raw file](https://github.com/memkind/memkind/blob/c5afb071cad018b02e1d328e96bdf36f24990824/README#L198)):*
> ```
> * [patch4](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c221c0b0308fd01d9fb33a16f64d2fd95f8830a4)
> * [patch5](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=31e4ca92a7dd4cdebd7fe1456b3b0b6ace9a816f)
> * [patch6](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9f960da72b25054163cf555e622dcdc3b8ccc488)
> ```

Do we really need to list these patches?

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/376)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[README, line 200 at r1](https://reviewable.io/reviews/memkind/memkind/376#-MHz2tTe8Zz1faJKlmKy:-MHz2tTe8Zz1faJKlmKz:b-kt3j9r) ([raw file](https://github.com/memkind/memkind/blob/c5afb071cad018b02e1d328e96bdf36f24990824/README#L200)):*
> ```
> * [patch6](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9f960da72b25054163cf555e622dcdc3b8ccc488)
> 
> and created DAX device, see [article](https://pmem.io/2020/01/20/memkind-dax-kmem.html) for details.
> ```

nit: Begin a new sentence here.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/376)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[README, line 198 at r1](https://reviewable.io/reviews/memkind/memkind/376#-MHz1O6xA6mOOoS0q6es:-MHz7sXzDP6ZR073X16E:bb7kbel) ([raw file](https://github.com/memkind/memkind/blob/c5afb071cad018b02e1d328e96bdf36f24990824/README#L198)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Do we really need to list these patches?
</blockquote></details>

Yes - discussed offline.
___
*[README, line 200 at r1](https://reviewable.io/reviews/memkind/memkind/376#-MHz2tTe8Zz1faJKlmKy:-MHz7rPw-dwxikW9Dwcz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c5afb071cad018b02e1d328e96bdf36f24990824/README#L200)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Begin a new sentence here.
</blockquote></details>

Done.

**Review by kasiawasiuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/376)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[README, line 264 at r2](https://reviewable.io/reviews/memkind/memkind/376#-MI-99Oi9BGK3N8JptjY:-MI-99Oi9BGK3N8JptjZ:b456y78) ([raw file](https://github.com/memkind/memkind/blob/28e23d8d8cc4d600d41783bb2dab36ea37a9d811/README#L264)):*
> ```
>       0:  10  21  17
>       1:  21  10  28
>       4:  17  28  10
> ```

Why do you remove the instruction? It was useful for me ;)

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/376)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kasiawasiuta and @PatKamin)

___
*[README, line 264 at r2](https://reviewable.io/reviews/memkind/memkind/376#-MI-99Oi9BGK3N8JptjY:-MI-9lkuAYp0n2S1Hm58:b-wsl3gn) ([raw file](https://github.com/memkind/memkind/blob/28e23d8d8cc4d600d41783bb2dab36ea37a9d811/README#L264)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

Why do you remove the instruction? It was useful for me ;)
</blockquote></details>

The article https://pmem.io/2020/01/20/memkind-dax-kmem.html - referred  in this PR IMHO covers all information that I remove from here.

**Review by kasiawasiuta — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/376)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by kasiawasiuta — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/376)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
