### PR TITLE
Enable fsdax tests

### PR DESCRIPTION
**Pull request by PatKamin**
Requires:
- [x] #594 
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/595)

### CODE REVIEW

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/595)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[test/tiering_tests.py, line 218 at r2](https://reviewable.io/reviews/memkind/memkind/595#-MWZ7kF5CIJgD9vGRRWI:-MWZ7kF613mzaOAcn9QW:bvy8vbh) ([raw file](https://github.com/memkind/memkind/blob/2810d554e32fad0a3dc8a98026a67e78a7f95713/test/tiering_tests.py#L218)):*
> ```
>     # TODO enable this check after implementing full FS_DAX support in
>     # libmemtier
> ```
remove this

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/595)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @michalbiesek)

___
*[test/tiering_tests.py, line 218 at r2](https://reviewable.io/reviews/memkind/memkind/595#-MWZ7kF5CIJgD9vGRRWI:-MWZ8wo73RBWJfvYdDZn:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/2810d554e32fad0a3dc8a98026a67e78a7f95713/test/tiering_tests.py#L218)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     # TODO enable this check after implementing full FS_DAX support in
>     # libmemtier
> ```
remove this
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/595)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/595#-:-MWZ9ri78kGUar1yYCR_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
