### PR TITLE
Handle data movement logic

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/759)

### CODE REVIEW

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/759)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @maciekpac)

___
*[test/memkind_memtier_data_movement_test.cpp, line 497 at r2](https://reviewable.io/reviews/memkind/memkind/759#-Mw_cMEN7VmY1DqVaCcB:-Mw_cMEP6tMLY45AP2uS:bvvqzi1) ([raw file](https://github.com/memkind/memkind/blob/36cf59df65389a765f6ca7c376441110e32c2cbe/test/memkind_memtier_data_movement_test.cpp#L497)):*
> ```cpp
> 
>     ASSERT_LE(dram_size, limits.lowLimit);
>     ASSERT_LE(dram_size, 16 * 1024 * 1024u);
> ```

These two checks have exactly the same right hand comparison value. Remove the second one, same below.

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 4 of 15 files at r1, 2 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/759)* status: all files reviewed, 4 unresolved discussions (waiting on @maciekpac)

___
*[src/mtt_internals.c, line 90 at r2](https://reviewable.io/reviews/memkind/memkind/759#-Mw_nyNT5wPz_9J1AJHO:-Mw_nyNT5wPz_9J1AJHP:b-itb320) ([raw file](https://github.com/memkind/memkind/blob/36cf59df65389a765f6ca7c376441110e32c2cbe/src/mtt_internals.c#L90)):*
> ```C
> {
>     metadata_handle handle;
>     ranking_metadata_create(&handle);
> ```

this function will allocate an object every call - can we reuse it?
___
*[test/memkind_memtier_data_movement_test.cpp, line 438 at r2](https://reviewable.io/reviews/memkind/memkind/759#-Mw_oYBR7GT56RfqPIR9:-Mw_oYBR7GT56RfqPIRA:b-n32mde) ([raw file](https://github.com/memkind/memkind/blob/36cf59df65389a765f6ca7c376441110e32c2cbe/test/memkind_memtier_data_movement_test.cpp#L438)):*
> ```cpp
>     ASSERT_GT(hotness, 0.0);
> 
>     // check that there are no pages on pmem
> ```

please add an explanation why
___
*[test/memkind_memtier_data_movement_test.cpp, line 449 at r2](https://reviewable.io/reviews/memkind/memkind/759#-Mw_owwW4833ta9zz44f:-Mw_owwW4833ta9zz44g:b-bfqj85) ([raw file](https://github.com/memkind/memkind/blob/36cf59df65389a765f6ca7c376441110e32c2cbe/test/memkind_memtier_data_movement_test.cpp#L449)):*
> ```cpp
> }
> 
> TEST_F(PEBSTest, MovementLogic)
> ```

please rename this test to "soft limit" or similar

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/759)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/mtt_internals.c, line 90 at r2](https://reviewable.io/reviews/memkind/memkind/759#-Mw_nyNT5wPz_9J1AJHO:-MwaEWh86FJk2TkbzxoQ:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/36cf59df65389a765f6ca7c376441110e32c2cbe/src/mtt_internals.c#L90)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this function will allocate an object every call - can we reuse it?
</blockquote></details>

Done
___
*[test/memkind_memtier_data_movement_test.cpp, line 438 at r2](https://reviewable.io/reviews/memkind/memkind/759#-Mw_oYBR7GT56RfqPIR9:-MwaHMR_721VfPkdvJHI:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/36cf59df65389a765f6ca7c376441110e32c2cbe/test/memkind_memtier_data_movement_test.cpp#L438)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please add an explanation why
</blockquote></details>

Done.
___
*[test/memkind_memtier_data_movement_test.cpp, line 449 at r2](https://reviewable.io/reviews/memkind/memkind/759#-Mw_owwW4833ta9zz44f:-MwaHWjADN-FvHYp5A8k:bx8mrdg) ([raw file](https://github.com/memkind/memkind/blob/36cf59df65389a765f6ca7c376441110e32c2cbe/test/memkind_memtier_data_movement_test.cpp#L449)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please rename this test to "soft limit" or similar
</blockquote></details>

Renamed to:
SoftLimitMovementLogic

I think this test might be extended in the future to check real numa policy once actual movement is implemented; for now, we are checking if the correct number of pages were migrated between rankings.
___
*[test/memkind_memtier_data_movement_test.cpp, line 497 at r2](https://reviewable.io/reviews/memkind/memkind/759#-Mw_cMEN7VmY1DqVaCcB:-MwaHpoK5UhiKD1U1GJ-:b-8vmxhl) ([raw file](https://github.com/memkind/memkind/blob/36cf59df65389a765f6ca7c376441110e32c2cbe/test/memkind_memtier_data_movement_test.cpp#L497)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

These two checks have exactly the same right hand comparison value. Remove the second one, same below.
</blockquote></details>

I wanted to be double or triple sure about the outcome, just to make sure that *limits* were not modified anywhere. 

I know that it does not look good, but this is a crucial check and I introduced redundancy on purpose, to make the tests more resilient. I would strongly prefer to leave it this way; if you insist, I can remove the first one and leave the value supplied by hand, not the other way around.

**Review by PatKamin — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/759)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/759)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
