### PR TITLE
Add multi-vma allocator - reference to check vma overhead

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/843)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/843)* status: all files reviewed, 9 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 186 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8TetYS3-bRL5mNJbnG:-N8TetYS3-bRL5mNJbnH:bei1hau) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L186)):*
> ```cpp
>     std::mutex freelistMutex;
>     void *areaStart;
>     void *areaCstart;
> ```

what is Cstart? please add a comment 
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 194 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tf-EB8Zuf19PXTrhM:-N8Tf-EB8Zuf19PXTrhN:b-clhpw2) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L194)):*
> ```cpp
>     size_t vmaCounter=0ul;
> 
>     bool temp_deleted_something=false;
> ```

this should be an atomic?
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 240 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tfa-s18uY2tAU9bZh:-N8Tfa-s18uY2tAU9bZi:b7wxax3) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L240)):*
> ```cpp
>         // Add page gap, check new page
>         size_t to_add = pageSizeLeft;
> #define MULTI_VMA_ALLOCATOR
> ```

move this define to the top of this file
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 270 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tf3cdDfGfEXHK_ham:-N8Tf3cdDfGfEXHK_han:bz72jcv) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L270)):*
> ```cpp
>            reinterpret_cast<uint8_t *>(areaStart) + TOTAL_SIZE);
>         vmaCounter = 0ul;
>         // to_add += pageSize;
> ```

this is commented - please remove it
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 276 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tf1t23x1OIJ9unwx_:-N8Tf1t23x1OIJ9unwxa:bh3o6fy) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L276)):*
> ```cpp
>         assert(ret != MAP_FAILED && ret == tmmap_start);
> ```

remove empty line
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 301 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Te_7MEvMNg_0ADzcY:-N8Te_7MEvMNg_0ADzcZ:b-9tpqlx) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L301)):*
> ```cpp
>         return ret;
>     }
>     void free(void *ptr)
> ```

add empty line
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 646 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tfg6-6CvJ5hsCRf8J:-N8Tfg6-6CvJ5hsCRf8K:b-9xj6zb) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L646)):*
> ```cpp
>     uint64_t malloc_time = clock_bench_time_ms() - start_mallocs_timestamp;
> 
>     // TODO update internal repetitions - should be configurable grom command line
> ```

grom->from
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 649 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8TfeWh3APyfhf2fhCU:-N8TfeWh3APyfhf2fhCV:bh3o6fy) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L649)):*
> ```cpp
>     std::vector<std::pair<uint64_t, uint64_t>> ret;
>     ret.reserve(internal_repetitions);
> ```

remove empty line
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 925 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tfqyu-Fa3FFKyuBKJ:-N8Tfqyu-Fa3FFKyuBKK:bp339r6) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L925)):*
> ```cpp
>         case KEY_NOMALLOC_ITERATIONS:
>         {
>             assert(arg && "argument for vma interval not supplied");
> ```

change assert text to "internal repetitions"

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/843)* status: all files reviewed, 9 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 186 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8TetYS3-bRL5mNJbnG:-N8Tknis37l8P7oAihiy:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L186)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

what is Cstart? please add a comment 
</blockquote></details>

Done.
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 194 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tf-EB8Zuf19PXTrhM:-N8TkzyW9Kakdw7Oo9P8:b-wratmp) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L194)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this should be an atomic?
</blockquote></details>

moved behind mutex
btw, added explanation
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 240 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tfa-s18uY2tAU9bZh:-N8TlSlVDra19Ya4TDSt:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L240)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

move this define to the top of this file
</blockquote></details>

Done.
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 270 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tf3cdDfGfEXHK_ham:-N8TlXm74cRZw31lPvPK:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L270)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this is commented - please remove it
</blockquote></details>

Done.
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 276 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tf1t23x1OIJ9unwx_:-N8Tl_2O1kVBhSPEGOH1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L276)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 301 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Te_7MEvMNg_0ADzcY:-N8Tlc4p8VdhcIWWsZvi:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L301)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

add empty line
</blockquote></details>

Done.
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 646 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tfg6-6CvJ5hsCRf8J:-N8TlfmwDfOZq79duPoZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L646)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

grom->from
</blockquote></details>

Done.
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 649 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8TfeWh3APyfhf2fhCU:-N8TloaVBw14nlymZkJw:brc69f8) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L649)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

I think it's really more readable with one line space between this reserve and the for loop
___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 925 at r1](https://reviewable.io/reviews/memkind/memkind/843#-N8Tfqyu-Fa3FFKyuBKJ:-N8TmAE5CeFBeR-2B_z6:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/face45240cf5567b3464b139fb1a519e6bcd38be/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L925)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

change assert text to "internal repetitions"
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/843)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/843)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[`utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp` line 188 at r2](https://reviewable.io/reviews/memkind/memkind/843#-N8XjhQ65BT2TcFia5n8:-N8XjhQ65BT2TcFia5n9:bfhz4rk) ([raw file](https://github.com/memkind/memkind/blob/293b740f416288601f5e9ffee0806501fba838c5/utils/memtier_zipf_bench/memtier_zipf_counter_bench.cpp#L188)):*
> ```cpp
>     void *areaStart;
>     /// start of unused area
>     void *areaCstart;
> ```

Maybe it's some common naming convention that I'm not familiar with. However, wouldn't `unusedAreaStart` be more self-explaining?

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/843)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
