### PR TITLE
Refresh untouched hotness

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/813)

### CODE REVIEW

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/813)* status: 6 of 11 files reviewed, 5 unresolved discussions (waiting on @bratpiorka, @maciekpac, and @PatKamin)

___
*[`src/ranking_internals.cpp` line 217 at r3](https://reviewable.io/reviews/memkind/memkind/813#-N1cLs-wDYCxwrzLb3Pv:-N1cLs-wDYCxwrzLb3Pw:b-2tj012) ([raw file](https://github.com/memkind/memkind/blob/5fdbe33cf340b6a78ad72434a39a735ca6f4ed6b/src/ranking_internals.cpp#L217)):*
> ```cpp
>             }
>         } else {
>             this->leastRecentlyUsed.insert(std::make_pair(timestamp, pages));
> ```

I think that this is more probable scenario. I suggest inverting the if else clause.
___
*[`src/ranking_internals.cpp` line 222 at r3](https://reviewable.io/reviews/memkind/memkind/813#-N1cMOZeB-9kIw8EJ4ud:-N1cMOZf9uAS_vst42FZ:b-xw42fp) ([raw file](https://github.com/memkind/memkind/blob/5fdbe33cf340b6a78ad72434a39a735ca6f4ed6b/src/ranking_internals.cpp#L222)):*
> ```cpp
> }
> 
> MEMKIND_EXPORT void Ranking::AddHotnessToPages_(PageMetadata *page)
> ```

nit: For clarity, this could be moved to a separate commit. This change is not related to the LRU.
___
*[`src/ranking_internals.cpp` line 230 at r3](https://reviewable.io/reviews/memkind/memkind/813#-N1cPcXKExzUUzaZ4W_C:-N1cPcXKExzUUzaZ4W_D:b-xw42fp) ([raw file](https://github.com/memkind/memkind/blob/5fdbe33cf340b6a78ad72434a39a735ca6f4ed6b/src/ranking_internals.cpp#L230)):*
> ```cpp
> 
> MEMKIND_EXPORT void
> Ranking::AddHotnessToPages_(std::set<PageMetadata *> &&pages)
> ```

nit: For clarity, this could be moved to a separate commit. This change is not related to the LRU.
___
*[`src/ranking_internals.cpp` line 239 at r3](https://reviewable.io/reviews/memkind/memkind/813#-N1cPedyEn4AfXno5B17:-N1cPedyEn4AfXno5B18:b-2tj012) ([raw file](https://github.com/memkind/memkind/blob/5fdbe33cf340b6a78ad72434a39a735ca6f4ed6b/src/ranking_internals.cpp#L239)):*
> ```cpp
>                 current_hotness_it->second.insert(page);
>             }
>         } else {
> ```

I think that this is more probable scenario. I suggest inverting the if else clause.
___
*[`src/ranking_internals.cpp` line 315 at r3](https://reviewable.io/reviews/memkind/memkind/813#-N1cVU5F0wg0Jxy4puT7:-N1cVU5F0wg0Jxy4puT8:b-lzno3t) ([raw file](https://github.com/memkind/memkind/blob/5fdbe33cf340b6a78ad72434a39a735ca6f4ed6b/src/ranking_internals.cpp#L315)):*
> ```cpp
> MEMKIND_EXPORT bool Ranking::Touch(uintptr_t addr)
> {
>     bool touched = false;
> ```

Return true or false directly in-place. No need for storing this variable, the code is concise and will be clear with such a change.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/813)* status: all files reviewed, 5 unresolved discussions (waiting on @bratpiorka and @maciekpac)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/813)* status: 6 of 12 files reviewed, 5 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[`src/ranking_internals.cpp` line 217 at r3](https://reviewable.io/reviews/memkind/memkind/813#-N1cLs-wDYCxwrzLb3Pv:-N1hOl5C2Kb86pB0KSFY:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5fdbe33cf340b6a78ad72434a39a735ca6f4ed6b/src/ranking_internals.cpp#L217)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I think that this is more probable scenario. I suggest inverting the if else clause.
</blockquote></details>

Done.
___
*[`src/ranking_internals.cpp` line 222 at r3](https://reviewable.io/reviews/memkind/memkind/813#-N1cMOZeB-9kIw8EJ4ud:-N1hJC7W4n257hoo1uNI:bnhucdy) ([raw file](https://github.com/memkind/memkind/blob/5fdbe33cf340b6a78ad72434a39a735ca6f4ed6b/src/ranking_internals.cpp#L222)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: For clarity, this could be moved to a separate commit. This change is not related to the LRU.
</blockquote></details>

I think splitting is not that critical in our case
___
*[`src/ranking_internals.cpp` line 230 at r3](https://reviewable.io/reviews/memkind/memkind/813#-N1cPcXKExzUUzaZ4W_C:-N1hJH7d57ISSLtISTI4:bnhucdy) ([raw file](https://github.com/memkind/memkind/blob/5fdbe33cf340b6a78ad72434a39a735ca6f4ed6b/src/ranking_internals.cpp#L230)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: For clarity, this could be moved to a separate commit. This change is not related to the LRU.
</blockquote></details>

I think splitting is not that critical in our case
___
*[`src/ranking_internals.cpp` line 239 at r3](https://reviewable.io/reviews/memkind/memkind/813#-N1cPedyEn4AfXno5B17:-N1hOnT77xcQvONpxiTx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5fdbe33cf340b6a78ad72434a39a735ca6f4ed6b/src/ranking_internals.cpp#L239)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I think that this is more probable scenario. I suggest inverting the if else clause.
</blockquote></details>

Done.
___
*[`src/ranking_internals.cpp` line 315 at r3](https://reviewable.io/reviews/memkind/memkind/813#-N1cVU5F0wg0Jxy4puT7:-N1hJhZz0NndUbnE1ZX6:bkjxs5g) ([raw file](https://github.com/memkind/memkind/blob/5fdbe33cf340b6a78ad72434a39a735ca6f4ed6b/src/ranking_internals.cpp#L315)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Return true or false directly in-place. No need for storing this variable, the code is concise and will be clear with such a change.
</blockquote></details>

I know that we don't need to follow MISRA-C rules, but it states that "a function should have only a single point of return" ([source](https://rules.sonarsource.com/c/RSPEC-1005)). Do we have a set of rules that states that the inverse method should be used ? Otherwise, it's just an opinion...

I think that keeping the variable named shows the meaning of the returned value clearer...

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 5 files at r5, 1 of 5 files at r7, 5 of 5 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/813)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
