### PR TITLE
Add DATA_MOVEMENT policy

### PR DESCRIPTION
**Pull request by PatKamin**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/725)

### CODE REVIEW

**Review by bratpiorka — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/725)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/725)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[src/memkind_memtier.c, line 629 at r2](https://reviewable.io/reviews/memkind/memkind/725#-MtDYlq534pB4eISSukQ:-MtDQx274vSMPTU53Wjd:bsgrtc7) ([raw file](https://github.com/memkind/memkind/blob/b28b78e821c9aa9546af074a927aae4a61bd517c/src/memkind_memtier.c#L629)):*
> ```C
>     }
> 
>     for (i = 1; i < memory->cfg_size; ++i) {
> ```

this code could be moved to a function

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/725)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/memkind_memtier.c, line 629 at r2](https://reviewable.io/reviews/memkind/memkind/725#-MtDYlq534pB4eISSukQ:-Mtc8s_s97JWZlgODKh-:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b28b78e821c9aa9546af074a927aae4a61bd517c/src/memkind_memtier.c#L629)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this code could be moved to a function
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 8 of 8 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/725)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 8 of 8 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/725)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
