### PR TITLE
Move NODE_VARIANT_* definitions to memkind_private.h

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/459)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/459)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @bratpiorka)

___
*[include/memkind/internal/memkind_private.h, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/459#-MQv_KKD4776z3nXiqau:-MQv_KKD4776z3nXiqav:bu5ch16) ([raw file](https://github.com/memkind/memkind/blob/dc763c33acf96b7026b14922e5b0b608bcd665a5/include/memkind/internal/memkind_private.h#L2)):*
> ```
> 2020
> ```
bump dates in files
___
*[include/memkind/internal/memkind_private.h, line 100 at r1](https://reviewable.io/reviews/memkind/memkind/459#-MQvZyQ7BwKoGcSY9vRf:-MQvZyQ7BwKoGcSY9vRg:b-4qvim) ([raw file](https://github.com/memkind/memkind/blob/dc763c33acf96b7026b14922e5b0b608bcd665a5/include/memkind/internal/memkind_private.h#L100)):*
> ```
> #define NODE_VARIANT_MULTIPLE 0
> #define NODE_VARIANT_SINGLE   1
> #define NODE_VARIANT_MAX      2
> ```
Please replace macro with an enum - and use it in memkind_dax_kmem.c and memkind_hbw.c

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/459)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[include/memkind/internal/memkind_private.h, line 2 at r1](https://reviewable.io/reviews/memkind/memkind/459#-MQv_KKD4776z3nXiqau:-MQvcCYM0H5fMoeFpkHx:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/dc763c33acf96b7026b14922e5b0b608bcd665a5/include/memkind/internal/memkind_private.h#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
bump dates in files
</blockquote></details>

Done.
___
*[include/memkind/internal/memkind_private.h, line 100 at r1](https://reviewable.io/reviews/memkind/memkind/459#-MQvZyQ7BwKoGcSY9vRf:-MQvcD_ODDvZpircgtM7:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/dc763c33acf96b7026b14922e5b0b608bcd665a5/include/memkind/internal/memkind_private.h#L100)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #define NODE_VARIANT_MULTIPLE 0
> #define NODE_VARIANT_SINGLE   1
> #define NODE_VARIANT_MAX      2
> ```
Please replace macro with an enum - and use it in memkind_dax_kmem.c and memkind_hbw.c
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/459)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @bratpiorka)

___
*[include/memkind/internal/memkind_bitmask.h, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/459#-MQvezgtAywQcAhC3lAh:-MQvezgtAywQcAhC3lAi:b-c42xa4) ([raw file](https://github.com/memkind/memkind/blob/c48624a890d3ecb75c1a305c4e41687cd036975e/include/memkind/internal/memkind_bitmask.h#L2)):*
> ```
> 2020
> ```
2021
___
*[src/memkind_bitmask.c, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/459#-MQvf3VF6Z859OvS88JG:-MQvf3VF6Z859OvS88JH:b-c42xa4) ([raw file](https://github.com/memkind/memkind/blob/c48624a890d3ecb75c1a305c4e41687cd036975e/src/memkind_bitmask.c#L2)):*
> ```
> 2020
> ```
2021
___
*[src/memkind_bitmask.c, line 9 at r2](https://reviewable.io/reviews/memkind/memkind/459#-MQvf5La5CZab84dWAje:-MQvf5La5CZab84dWAjf:b-uxqto5) ([raw file](https://github.com/memkind/memkind/blob/c48624a890d3ecb75c1a305c4e41687cd036975e/src/memkind_bitmask.c#L9)):*
> ```
> #include <memkind/internal/memkind_private.h>
> ```
remove
___
*[src/memkind_dax_kmem.c, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/459#-MQvfAWb4sa7Yok2Ph9h:-MQvfAWb4sa7Yok2Ph9i:b-c42xa4) ([raw file](https://github.com/memkind/memkind/blob/c48624a890d3ecb75c1a305c4e41687cd036975e/src/memkind_dax_kmem.c#L2)):*
> ```
> 2020
> ```
2021
___
*[src/memkind_dax_kmem.c, line 171 at r2](https://reviewable.io/reviews/memkind/memkind/459#-MQvfTAXCQ0yWnS_FVhK:-MQvfTAXCQ0yWnS_FVhL:b-6iocpy) ([raw file](https://github.com/memkind/memkind/blob/c48624a890d3ecb75c1a305c4e41687cd036975e/src/memkind_dax_kmem.c#L171)):*
> ```
> set_closest_numanode
> ```
https://github.com/memkind/memkind/blob/865173b4633037145a58cc875984a7449896d3e3/src/memkind_hbw.c#L356 please update and bump date in memkind_HBW

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/459)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[include/memkind/internal/memkind_bitmask.h, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/459#-MQvezgtAywQcAhC3lAh:-MQvh2NAAJcDn6z33umE:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c48624a890d3ecb75c1a305c4e41687cd036975e/include/memkind/internal/memkind_bitmask.h#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
2021
</blockquote></details>

Done.
___
*[src/memkind_bitmask.c, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/459#-MQvf3VF6Z859OvS88JG:-MQvhDlj88JelkKFIOk1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c48624a890d3ecb75c1a305c4e41687cd036975e/src/memkind_bitmask.c#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
2021
</blockquote></details>

Done.
___
*[src/memkind_bitmask.c, line 9 at r2](https://reviewable.io/reviews/memkind/memkind/459#-MQvf5La5CZab84dWAje:-MQvh3qZDOskuPbNeKEA:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c48624a890d3ecb75c1a305c4e41687cd036975e/src/memkind_bitmask.c#L9)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include <memkind/internal/memkind_private.h>
> ```
remove
</blockquote></details>

Done.
___
*[src/memkind_dax_kmem.c, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/459#-MQvfAWb4sa7Yok2Ph9h:-MQvh5Fw3F69l10RUsnv:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c48624a890d3ecb75c1a305c4e41687cd036975e/src/memkind_dax_kmem.c#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 2020
> ```
2021
</blockquote></details>

Done.
___
*[src/memkind_dax_kmem.c, line 171 at r2](https://reviewable.io/reviews/memkind/memkind/459#-MQvfTAXCQ0yWnS_FVhK:-MQvh6T9CZAaOBt2gKmw:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c48624a890d3ecb75c1a305c4e41687cd036975e/src/memkind_dax_kmem.c#L171)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> set_closest_numanode
> ```
https://github.com/memkind/memkind/blob/865173b4633037145a58cc875984a7449896d3e3/src/memkind_hbw.c#L356 please update and bump date in memkind_HBW
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/459)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/memkind_dax_kmem.c, line 171 at r2](https://reviewable.io/reviews/memkind/memkind/459#-MQvfTAXCQ0yWnS_FVhK:-MQviOi87yUyIkCUmaHj:bxu4mdu) ([raw file](https://github.com/memkind/memkind/blob/c48624a890d3ecb75c1a305c4e41687cd036975e/src/memkind_dax_kmem.c#L171)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please update set_closest_numanode in memkind_hbw.c (link mentioned in previous comment)

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/459#-:-MQvzP4h7vqV2QXAzP4o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
