### PR TITLE
Update documentation of memtier API

### PR DESCRIPTION
**Pull request by PatKamin**
[x] Requires #827 
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/830)

### CODE REVIEW

**Review by maciekpac — COMMENTED** [review]
I think git did not detect file rename, it shows one file was deleted and another one added... maybe the PR could be split into two commits:

1. Rename
2. Edit

?

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/830#-:-N5EROv0DFnZqOgyeRbN:b-x9w6tn)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by PatKamin — COMMENTED** [review]
Splitted into two commits.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/830#-:-N5EVOWk1wj1YTk27W-H:bry0t7o)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by maciekpac — CHANGES_REQUESTED** [review]
This is just a 1:1 copy of libmemtier.3 ?

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/830#-:-N5Eg0Mn0e7x2yorUOAI:b-n9nr96)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[`man_pages/memtier.html` line 374 at r2](https://reviewable.io/reviews/memkind/memkind/830#-N5EeIGk2Ci554n22I-r:-N5EeIGk2Ci554n22I-s:b-2jnvpu) ([raw file](https://github.com/memkind/memkind/blob/e44bb4753fb9124bafb044dc50168f51c6baabbd/man_pages/memtier.html#L374)):*
> ```HTML
> 
> <p style="margin-left:11%; margin-top: 1em">See
> <b>libmemtier</b>(7) for details on the usage of memkind
> ```

This is ok for a man page, but how can we access this page via browses there an html version ?

**Review by maciekpac — COMMENTED** [review]
Sorry, I did not mean to block this request

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/830#-:-N5Eg7zO3GhuZt18E3EF:bcoe7iz)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/830)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @maciekpac)

___
*[`man_pages/memtier.html` line 374 at r2](https://reviewable.io/reviews/memkind/memkind/830#-N5EeIGk2Ci554n22I-r:-N5F0eeF8QjdDrCBT9vu:b6lbcwi) ([raw file](https://github.com/memkind/memkind/blob/e44bb4753fb9124bafb044dc50168f51c6baabbd/man_pages/memtier.html#L374)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

This is ok for a man page, but how can we access this page via browses there an html version ?
</blockquote></details>

Added second man page.

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/830)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/830)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[`man_pages/libmemtier7.html` line 16 at r6](https://reviewable.io/reviews/memkind/memkind/830#-N5F67qs5WKvnDCZ6elp:-N5FP46RCAzBLZSJecNF:b9r8ckz) ([raw file](https://github.com/memkind/memkind/blob/739dabe22a25413523e85780099db25082ee31fd/man_pages/libmemtier7.html#L16)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

In fact, shouldn't this manpage be (at least partially) adapted ?

libmemtier3 uses the MEMKIND_MEMTIER title
</blockquote></details>

Changes in #832     
___
*[`man_pages/libmemtier7.html` line 54 at r6](https://reviewable.io/reviews/memkind/memkind/830#-N5F78IwBBS2y03SK9N_:-N5FPDRHEiCp-k2YxBWp:b-ob9o1u) ([raw file](https://github.com/memkind/memkind/blob/739dabe22a25413523e85780099db25082ee31fd/man_pages/libmemtier7.html#L54)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

In order to use the memkind memory tiering *with pre-built binaries* ?
</blockquote></details>

Changed in #832  
___
*[`man_pages/libmemtier7.html` line 363 at r6](https://reviewable.io/reviews/memkind/memkind/830#-N5F7xrg-H5vB9Cw4wyA:-N5FPFxF6KCRl1hBQ79o:bxl2t7m) ([raw file](https://github.com/memkind/memkind/blob/739dabe22a25413523e85780099db25082ee31fd/man_pages/libmemtier7.html#L363)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Is the date ok ?
</blockquote></details>

Changed in #832

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/830)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
