### PR TITLE
Introduce C++ allocator for PMEM

### PR DESCRIPTION
**Pull request by Epromee**
We have created STL-like C++ allocator for PMEM kind.
This allocator could be used with any STL-like data structures.
We created set of test and examples for STL data structures.
Also, we tested this allocator privately with Intel TBB data structures.

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/67)

### CODE REVIEW

**Comment by Epromee** [comment]
We have fixed the build issues, but Travis CI build has failed due to a server error. Need someone to restart the build, please.

**Comment by KFilipek** [comment]
retest this please

**Comment by michalbiesek** [comment]
Hi sorry for delayed response. Thanks for Your contribution.
Please rebase to master branch - current in our development process astyle configuration was updated. Please clean up Your commit history ( squash the changes related to PMEM C++ allocator into one) - it will be easier to review.

Please update following places with references to files which You added:
https://github.com/memkind/memkind/blob/d19888318707d2c88fbd8f737f9099a124301c68/MANIFEST

https://github.com/memkind/memkind/blob/d19888318707d2c88fbd8f737f9099a124301c68/copying_headers/MANIFEST.freeBSD

**Comment by Epromee** [comment]
Thanks for the reply, we have implemented the last-mentioned changes.

**Comment by michalbiesek** [comment]
___
*[MANIFEST, line 31 at r8](https://reviewable.io/reviews/memkind/memkind/67#-LJTAhet1CZO0u56a_Ei:-LJTAhet1CZO0u56a_Ej:bq5d2w8) ([raw file](https://github.com/memkind/memkind/blob/8b28359963d2beeb8b9e8e41dd5b452f9b5cb16c/MANIFEST#L31)):*
> ```
> examples/pmem_example.c
> install_astyle.sh
> examples/pmem_cpp_allocator.cpp
> ```

Please move this line to line above. It should be after line: examples/pmem_example.c

**Comment by michalbiesek** [comment]
@nvml-bot
test this please

**Comment by michalbiesek** [comment]
Sorry for late response.

**Comment by michalbiesek** [comment]
___
*[examples/pmem_cpp_allocator.cpp, line 54 at r9](https://reviewable.io/reviews/memkind/memkind/67#-LM1BlmA7NmKXZQAzKtw:-LM1BlmA7NmKXZQAzKtx:bhcjiaq) ([raw file](https://github.com/memkind/memkind/blob/94716f874c5728f42a52a566cf5de9606136936b/examples/pmem_cpp_allocator.cpp#L54)):*
> ```cpp
> 
>     /*
>      * Because of the issue #57 we cannot create multiple PMEM kinds.
> ```

The issue with destroy was solved - I think this comment should be removed and source code should be updated ( regarding information in this comment)

**Comment by michalbiesek** [comment]
___
*[include/pmem_allocator.h, line 39 at r9](https://reviewable.io/reviews/memkind/memkind/67#-LM1CuNS5W58-Qlm3gU2:-LM1CuNS5W58-Qlm3gU3:b73411p) ([raw file](https://github.com/memkind/memkind/blob/94716f874c5728f42a52a566cf5de9606136936b/include/pmem_allocator.h#L39)):*
> ```objc
> namespace pmem
> {
>     template<typename T>
> ```

Corresponding manual (man file to this include) will be great asset and help for future
see for example hbwallocator.3

**Comment by michalbiesek** [comment]
___
*[include/pmem_allocator.h, line 104 at r9](https://reviewable.io/reviews/memkind/memkind/67#-LM1DhSQD30ZoRcKm-lI:-LM1DhSQD30ZoRcKm-lJ:bhcan8y) ([raw file](https://github.com/memkind/memkind/blob/94716f874c5728f42a52a566cf5de9606136936b/include/pmem_allocator.h#L104)):*
> ```
> ;
> ```
remove

**Comment by michalbiesek** [comment]
___
*[include/pmem_allocator.h, line 180 at r9](https://reviewable.io/reviews/memkind/memkind/67#-LM1EWUv1HJnQ6zOYWWn:-LM1EWUwCj-ts3xouhET:b-d1m5gi) ([raw file](https://github.com/memkind/memkind/blob/94716f874c5728f42a52a566cf5de9606136936b/include/pmem_allocator.h#L180)):*
> ```
> (void *)p
> ```
I think this could be replaced by static_cast<void *>

**Comment by michalbiesek** [comment]
@nvml-bot
test this please

**Comment by michalbiesek** [comment]
___
*[test/pmem_allocator_tests.cpp, line 43 at r9](https://reviewable.io/reviews/memkind/memkind/67#-LM7sKx6735QmE2fZI4_:-LM7sKx79OWFCX7DUVG3:bfqlpk9) ([raw file](https://github.com/memkind/memkind/blob/94716f874c5728f42a52a566cf5de9606136936b/test/pmem_allocator_tests.cpp#L43)):*
> ```
>  static constexpr const char* PMEM_DIR = "/tmp/";
> ```
Please make it if possible as:
 extern const char*  PMEM_DIR; ( before class definition )
This is regarding commit https://github.com/memkind/memkind/commit/10eba774ae3568f99769dad4b431b4c4bce2da8b

**Comment by michalbiesek** [comment]
Closing. This will be finish in https://github.com/memkind/memkind/pull/85

**Pull request closed without merging**
