### PR TITLE
fix issue#405

### PR DESCRIPTION
**Pull request by bratpiorka**
fix issue#405

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/406)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/406)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

___
*[configure.ac, line 84 at r1](https://reviewable.io/reviews/memkind/memkind/406#-MMQwwuO6LYPQ-lBwZ4D:-MMQwwuO6LYPQ-lBwZ4E:b-j3my0j) ([raw file](https://github.com/memkind/memkind/blob/e6747901e9b09e35dd56b020203de35b07f6e1ca/configure.ac#L84)):*
> ```M4Sugar
> [enable_debug="0"]
> )
> if test "x$enable_debug" = "x1" ; then
> ```

Please change the commit message. I prefer to have more information in the git log than just reference for issues on Github.
Something like:

Extend the configure with --enable-debug-jemalloc option
- instruments jemalloc code for debug
___
*[Makefile.am, line 480 at r1](https://reviewable.io/reviews/memkind/memkind/406#-MMQwQLgBdZOLkyKP64N:-MMQwQLgBdZOLkyKP64O:bv4fxdp) ([raw file](https://github.com/memkind/memkind/blob/e6747901e9b09e35dd56b020203de35b07f6e1ca/Makefile.am#L480)):*
> ```Makefile
> 	bash -c "ar -M < <(echo -e '$(ar_prog)')"
> 	cp libmemkind.a .libs/
> 	rm libmemkind.a
> ```

Please set up your email to correct email.
Currently is present in this commit as:
Author: Rafal Rudnicki <rrudnick@localhost.localdomain>
___
*[Makefile.am, line 483 at r1](https://reviewable.io/reviews/memkind/memkind/406#-MMQvKKO4R3tfAESA78d:-MMQvKKP4ubQ2FpoAy77:b-t95dn5) ([raw file](https://github.com/memkind/memkind/blob/e6747901e9b09e35dd56b020203de35b07f6e1ca/Makefile.am#L483)):*
> ```
> JEMALLOC_DEBUG_FLAGS = --enable-debug
> ```
I believe this could be done in configure.ac layer see min_lg_align_opt. Then you could get rid of this if here.
I prefer to keep the original order of arguments in JEMALLOC_CONFIG

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/406)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka)

___
*[Makefile.am, line 483 at r1](https://reviewable.io/reviews/memkind/memkind/406#-MMR--aeB1ID_9urhRje:-MMR--aeB1ID_9urhRjf:b-r6qivi) ([raw file](https://github.com/memkind/memkind/blob/e6747901e9b09e35dd56b020203de35b07f6e1ca/Makefile.am#L483)):*
> ```
> JEMALLOC_DEBUG_FLAGS
> ```
Maybe we could rename this to something like:
JEMALLOC_BUILD_TYPE_FLAGS

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/406)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[config.h.in~, line 1 at r2](https://reviewable.io/reviews/memkind/memkind/406#-MMV2iWH2sR_x8p_FCTt:-MMV2iWH2sR_x8p_FCTu:b-ts4s96) ([raw file](https://github.com/memkind/memkind/blob/dcab807c6df50b2aa604bd1f9e7ed6847a620b4b/config.h.in~#L1)):*
> ```
> /* config.h.in.  Generated from configure.ac by autoheader.  */
> ```

If this file is autogenerated during build, then it shouldn't be in commit.

**Pull request closed without merging**
