### PR TITLE
Change behavior of local variant

### PR DESCRIPTION
**Pull request by michalbiesek**
- [x] Tests
- Ref: #518 

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/520)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520)* status: all files reviewed, 2 unresolved discussions (waiting on @jschmieg, @michalbiesek, and @PatKamin)

___
*[man/memkind.3, line 708 at r1](https://reviewable.io/reviews/memkind/memkind/520#-MTFrsTdBUX9q7xbuIx2:-MTFrsTdBUX9q7xbuIx3:brq2rq5) ([raw file](https://github.com/memkind/memkind/blob/b82f6d322ea6d4fd862856fb300866fafe0d5853/man/memkind.3#L708)):*
> ```Roff
> .BR Note:
> If there are multiple NUMA nodes in the same local domain that have the highest
> capacity - NUMA Node will be the one with worse latency and bandwidth attribute.
> ```

"and" or "or"?
___
*[src/memkind_mem_attributes.c, line 116 at r1](https://reviewable.io/reviews/memkind/memkind/520#-MTFs2VEEBHIZSgX8-Pc:-MTFs2VEEBHIZSgX8-Pd:b9z895i) ([raw file](https://github.com/memkind/memkind/blob/b82f6d322ea6d4fd862856fb300866fafe0d5853/src/memkind_mem_attributes.c#L116)):*
> ```C
>                         unpreferred_val = numa_distance(init_node->os_index, local_nodes[i]->os_index);
>                         hwloc_bitmap_only(attr_loc_mask, local_nodes[i]->os_index);
>                         // preffer capacity over latency
> ```

in man you wrote "latency and bandwidth" and here you test distance - why not hwloc attributes?

**Review by PatKamin — COMMENTED** [review]
> Reviewed 9 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520)* status: all files reviewed, 3 unresolved discussions (waiting on @jschmieg and @michalbiesek)

___
*[man/memkind.3, line 708 at r1](https://reviewable.io/reviews/memkind/memkind/520#-MTFvjPg7BJtkI1Ac__D:-MTFvjPh6VMgo0iic4eZ:bgnglpp) ([raw file](https://github.com/memkind/memkind/blob/b82f6d322ea6d4fd862856fb300866fafe0d5853/man/memkind.3#L708)):*
> ```Roff
> .BR Note:
> If there are multiple NUMA nodes in the same local domain that have the highest
> capacity - NUMA Node will be the one with worse latency and bandwidth attribute.
> ```

- allocate from NUMA node with worse latency and (or?) bandwidth attribute

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @jschmieg, and @PatKamin)

___
*[man/memkind.3, line 708 at r1](https://reviewable.io/reviews/memkind/memkind/520#-MTFrsTdBUX9q7xbuIx2:-MTFvxlAA6su_EOYWxSG:b-a2ujfl) ([raw file](https://github.com/memkind/memkind/blob/b82f6d322ea6d4fd862856fb300866fafe0d5853/man/memkind.3#L708)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

"and" or "or"?
</blockquote></details>

Changed.
___
*[man/memkind.3, line 708 at r1](https://reviewable.io/reviews/memkind/memkind/520#-MTFvjPg7BJtkI1Ac__D:-MTG-KJ40BGLiKD7kzKZ:b-s6pe5s) ([raw file](https://github.com/memkind/memkind/blob/b82f6d322ea6d4fd862856fb300866fafe0d5853/man/memkind.3#L708)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

- allocate from NUMA node with worse latency and (or?) bandwidth attribute
</blockquote></details>

Done - Changed.
FYI From the low-level perspective, the information comes from NUMA distance, SLIT table is based on latency attribute.
___
*[src/memkind_mem_attributes.c, line 116 at r1](https://reviewable.io/reviews/memkind/memkind/520#-MTFs2VEEBHIZSgX8-Pc:-MTFt_dk-5TrBbdvHqi5:bf14ir6) ([raw file](https://github.com/memkind/memkind/blob/b82f6d322ea6d4fd862856fb300866fafe0d5853/src/memkind_mem_attributes.c#L116)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

in man you wrote "latency and bandwidth" and here you test distance - why not hwloc attributes?
</blockquote></details>

This is by purpose - see that I don't want to limit the usage of memory kind(s) related to "local capacity attribute" by HMAT support. 
See the README table, where the requirements of memory kind are listed - I utilize information about latency from numa_distance.

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520#-:-MTGB5lU66nScwEk-veC:bnfp4nl)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @jschmieg, and @PatKamin)

___
*[src/memkind_mem_attributes.c, line 116 at r1](https://reviewable.io/reviews/memkind/memkind/520#-MTFs2VEEBHIZSgX8-Pc:-MTGAzFf6ElUUU6Somtt:b32w0x) ([raw file](https://github.com/memkind/memkind/blob/b82f6d322ea6d4fd862856fb300866fafe0d5853/src/memkind_mem_attributes.c#L116)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

This is by purpose - see that I don't want to limit the usage of memory kind(s) related to "local capacity attribute" by HMAT support. 
See the README table, where the requirements of memory kind are listed - I utilize information about latency from numa_distance.
</blockquote></details>

OK

**Review by PatKamin — COMMENTED** [review]
> Reviewed 3 of 12 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschmieg)

___
*[man/memkind.3, line 708 at r1](https://reviewable.io/reviews/memkind/memkind/520#-MTFvjPg7BJtkI1Ac__D:-MTGJ-Hr3K9a3-6TIN_k:b-2mn5ph) ([raw file](https://github.com/memkind/memkind/blob/b82f6d322ea6d4fd862856fb300866fafe0d5853/man/memkind.3#L708)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Done - Changed.
FYI From the low-level perspective, the information comes from NUMA distance, SLIT table is based on latency attribute.
</blockquote></details>

OK. Please, rephrase to sth like: "capacity - allocation will be done from NUMA node with worse latency attribute. ".

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @bratpiorka, @jschmieg, and @PatKamin)

___
*[man/memkind.3, line 708 at r1](https://reviewable.io/reviews/memkind/memkind/520#-MTFvjPg7BJtkI1Ac__D:-MTGPCNt0LJAV3XAHBsf:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b82f6d322ea6d4fd862856fb300866fafe0d5853/man/memkind.3#L708)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

OK. Please, rephrase to sth like: "capacity - allocation will be done from NUMA node with worse latency attribute. ".
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520#-:-MTK1VPFAdLpzWvM8Eka:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschmieg)

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520)* status: all files reviewed, 1 unresolved discussion (waiting on @jschmieg and @michalbiesek)

___
*[src/memkind_mem_attributes.c, line 120 at r3](https://reviewable.io/reviews/memkind/memkind/520#-MTKc-Bc79HpjJLH9URf:-MTKc-Bc79HpjJLH9URg:b-psyrc2) ([raw file](https://github.com/memkind/memkind/blob/a9787455388f17ad0e75e934080f8c7b17e198c3/src/memkind_mem_attributes.c#L120)):*
> ```C
>                                (numa_distance(init_node->os_index,
>                                               local_nodes[i]->os_index) > unpreferred_val)) {
>                         hwloc_bitmap_only(attr_loc_mask, local_nodes[i]->os_index);
> ```

`unpreferred_val = ...;` ?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520)* status: all files reviewed, 1 unresolved discussion (waiting on @jschmieg and @pbalcer)

___
*[src/memkind_mem_attributes.c, line 120 at r3](https://reviewable.io/reviews/memkind/memkind/520#-MTKc-Bc79HpjJLH9URf:-MTL3sHU85f5nlFfr1-0:b19mckh) ([raw file](https://github.com/memkind/memkind/blob/a9787455388f17ad0e75e934080f8c7b17e198c3/src/memkind_mem_attributes.c#L120)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

`unpreferred_val = ...;` ?
</blockquote></details>

unpreferred_val in this case provides information about latency. Internally the information comes from the "numa_distance" function.
The higher the NUMA distance - the worse latency is expected.

The logic here compares:
- the NUMA distance calculated from the previously founded Highest Capacity Node 
- the NUMA distance calculated for (second) founded Highest Capacity Node - the NUMA Node which got same capacity compared to the previous one

If the second Highest Capacity Node offers worse latency than the previous one - then it became the new destination NUMA Node.

See that I retrieve information about latency from numa_distance instead of hwloc by purpose.
If I would want to use libhwloc I would need HMAT support - and this is an unnecessary limitation for using this memory kind. Imagine that I have only DRAM and PMEM  on the platform without HMAT support just like described in https://github.com/memkind/memkind/issues/518.

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520)* status: all files reviewed, 1 unresolved discussion (waiting on @jschmieg and @michalbiesek)

___
*[src/memkind_mem_attributes.c, line 120 at r3](https://reviewable.io/reviews/memkind/memkind/520#-MTKc-Bc79HpjJLH9URf:-MTLzLz_CJiy7ZNhwXty:ba45e63) ([raw file](https://github.com/memkind/memkind/blob/a9787455388f17ad0e75e934080f8c7b17e198c3/src/memkind_mem_attributes.c#L120)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

unpreferred_val in this case provides information about latency. Internally the information comes from the "numa_distance" function.
The higher the NUMA distance - the worse latency is expected.

The logic here compares:
- the NUMA distance calculated from the previously founded Highest Capacity Node 
- the NUMA distance calculated for (second) founded Highest Capacity Node - the NUMA Node which got same capacity compared to the previous one

If the second Highest Capacity Node offers worse latency than the previous one - then it became the new destination NUMA Node.

See that I retrieve information about latency from numa_distance instead of hwloc by purpose.
If I would want to use libhwloc I would need HMAT support - and this is an unnecessary limitation for using this memory kind. Imagine that I have only DRAM and PMEM  on the platform without HMAT support just like described in https://github.com/memkind/memkind/issues/518. 
</blockquote></details>

right, I get all that.

But this is a loop over numa nodes, and you use this variable to store the latency of the currently selected node. In the next iteration of this loop, do you intentionally want to compare against the latency of the first numa node with the same capacity?
For example:

id   capacity   latency
1        10            100
2        10            150
3        10            110

For this set of numa nodes, the current algorithm would pick node 3, but we want node 2. Right?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @jschmieg, @PatKamin, and @pbalcer)

___
*[src/memkind_mem_attributes.c, line 120 at r3](https://reviewable.io/reviews/memkind/memkind/520#-MTKc-Bc79HpjJLH9URf:-MTZp8kYC45plKORIeql:b8cqo0f) ([raw file](https://github.com/memkind/memkind/blob/a9787455388f17ad0e75e934080f8c7b17e198c3/src/memkind_mem_attributes.c#L120)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

right, I get all that.

But this is a loop over numa nodes, and you use this variable to store the latency of the currently selected node. In the next iteration of this loop, do you intentionally want to compare against the latency of the first numa node with the same capacity?
For example:

id   capacity   latency
1        10            100
2        10            150
3        10            110

For this set of numa nodes, the current algorithm would pick node 3, but we want node 2. Right?

</blockquote></details>

Yes, you are right, sorry didn't get it from the first comment, my bad.

I update the test scenario to cover your example (in bandwidth domain) - QEMU has some limitations, regarding simulation same capacity so recreate this in bandwidth domain.

Regarding comment - Done :) - Thanks for pointing this.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520)* status: all files reviewed, 1 unresolved discussion (waiting on @jschmieg and @pbalcer)

**Review by pbalcer — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/520#-:-MT_KaQ718LRunP-Nx4C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschmieg)

**Pull request merged**
