### PR TITLE
Do not juggle pages with hotness diff hotness below 10%

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/824)

### CODE REVIEW

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/824)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/824#-N3OQv2cBNrDB5JIgjg9):*
with hotness diff



_Code quote:_
```
with hotness diff hotness
```
___
*[`src/mtt_internals.c` line 27 at r1](https://reviewable.io/reviews/memkind/memkind/824#-N3OR13kApab5xfPOVz6:-N3OR13kApab5xfPOVz7:b-k3nwei) ([raw file](https://github.com/memkind/memkind/blob/9c7658d9037e2d8c5b4b6e3dfcf58237e4bdff7f/src/mtt_internals.c#L27)):*
> ```C
> // with 4kB traced page, 512kB per cycle
> #define MAX_TO_JUGGLE (128ul)
> // do not juggle pages with hotness diff hotness below 10%
> ```

with hotness diff



_Code quote:_
```C
with hotness diff hotness
```

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/824)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/824#-N3OQv2cBNrDB5JIgjg9):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

with hotness diff
</blockquote></details>

Done.
___
*[`src/mtt_internals.c` line 27 at r1](https://reviewable.io/reviews/memkind/memkind/824#-N3OR13kApab5xfPOVz6:-N3OSBIi82zDokq0IEoD:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9c7658d9037e2d8c5b4b6e3dfcf58237e4bdff7f/src/mtt_internals.c#L27)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

with hotness diff
</blockquote></details>

Done.

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/824)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Review by maciekpac — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/824)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
