### PR TITLE
Update ubuntu dockerfile to version 20.04

### PR DESCRIPTION
**Pull request by TomekIdczak97**
### Description

Update Ubuntu dockerfile from 18.04 to 20.04 version.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [x] Other

### Checklist

- [x] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/366)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @TomekIdczak97)

___
*[utils/docker/Dockerfile.ubuntu-20.04, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFk4BHEAWMb2uFfjoZR:-MFk4BHEAWMb2uFfjoZS:bb6ht35) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L1)):*
> ```
> #  Copyright (C) 2019 Intel Corporation.
> ```

2020
___
*[utils/docker/Dockerfile.ubuntu-20.04, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFk4KQt-ZFBxHLLJUNh:-MFk4KQt-ZFBxHLLJUNi:brzrmr2) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L26)):*
> ```
> FROM ubuntu:20.04
> 
> LABEL maintainer="katarzyna.wasiuta@intel.com"
> ```

tomasz.idczak ?

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @PatKamin and @TomekIdczak97)

___
*[utils/docker/Dockerfile.ubuntu-20.04, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFk4BHEAWMb2uFfjoZR:-MFkT6_10EHC-dC4Ukiz:b-ixkxov) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L1)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

2020
</blockquote></details>

And please use SPDX-License format
___
*[utils/docker/Dockerfile.ubuntu-20.04, line 24 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFkTLzICfXRQPoAAVhC:-MFkTLzICfXRQPoAAVhD:b2o9ho5) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L24)):*
> ```
> FROM ubuntu:20.04
> ```
Regarding this please also update this reference:
https://github.com/memkind/memkind/blame/master/utils/docker/README.md#L5
___
*[utils/docker/Dockerfile.ubuntu-20.04, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFk4KQt-ZFBxHLLJUNh:-MFkTAKK5GmbXvyV6GRa:bw0vfwc) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L26)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

tomasz.idczak ?
</blockquote></details>

I prefer Katarzyna to be maintainer of this file.

**Comment by michalbiesek** [comment]
@pmem-bot-ae
test this please

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @PatKamin and @TomekIdczak97)

___
*[utils/docker/Dockerfile.ubuntu-20.04, line 47 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFkWsWI5h-kGz7hTN5Z:-MFkWsWI5h-kGz7hTN5_:b44lza3) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L47)):*
> ```
>     pkg-config \
>     python3-pip \
>     sudo \
> ```

Please change newline format: CRLF to LF  see https://en.wikipedia.org/wiki/Newline for details
___
*[utils/docker/Dockerfile.ubuntu-20.04, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFkVX3v38QYxoTUUgHZ:-MFkVX3v38QYxoTUUgH_:b-mz599y) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L58)):*
> ```
> 
> # Add user
> ENV USER memkinduser
> ```

Please change the commit author name and email to yourself
and commit message from: " Update ubuntu dockerfile to version 20.04" to
 Update Ubuntu Dockerfile to version 20.04

**Review by kasiawasiuta — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: all files reviewed, 5 unresolved discussions (waiting on @PatKamin and @TomekIdczak97)

___
*[utils/docker/Dockerfile.ubuntu-20.04, line 55 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFo_2KM2KYMJLja14DF:-MFo_2KM2KYMJLja14DG:b1qudwi) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L55)):*
> ```
> # Install pytest
> RUN pip3 install pytest==3.9.2
> RUN pip3 install setuptools==3.4.1
> ```

Probably the problem is with this version

**Comment by michalbiesek** [comment]
> > Reviewed 1 of 4 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)_ status: all files reviewed, 5 unresolved discussions (waiting on @PatKamin and @TomekIdczak97)
> 
> _[utils/docker/Dockerfile.ubuntu-20.04, line 55 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFo_2KM2KYMJLja14DF:-MFo_2KM2KYMJLja14DG:b1qudwi) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L55)):_
> 
> > ```
> > # Install pytest
> > RUN pip3 install pytest==3.9.2
> > RUN pip3 install setuptools==3.4.1
> > ```
> 
> Probably the problem is with this version

If you have a problem with python and setuptools please in this PR just bump the Ubuntu version in Dockerfile and in other switch to python3

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @kasiawasiuta, @michalbiesek, and @PatKamin)

___
*[utils/docker/Dockerfile.ubuntu-20.04, line 1 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFk4BHEAWMb2uFfjoZR:-MGIJ4ZL6Qs29IiXWAbD:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L1)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

And please use SPDX-License format
</blockquote></details>

Done.
___
*[utils/docker/Dockerfile.ubuntu-20.04, line 24 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFkTLzICfXRQPoAAVhC:-MGIKaNp2i3OUbkh7wDL:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L24)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> FROM ubuntu:20.04
> ```
Regarding this please also update this reference:
https://github.com/memkind/memkind/blame/master/utils/docker/README.md#L5
</blockquote></details>

Done.
___
*[utils/docker/Dockerfile.ubuntu-20.04, line 47 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFkWsWI5h-kGz7hTN5Z:-MGIJFwW6YOX9FxWoFdT:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L47)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please change newline format: CRLF to LF  see https://en.wikipedia.org/wiki/Newline for details
</blockquote></details>

Done.
___
*[utils/docker/Dockerfile.ubuntu-20.04, line 55 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFo_2KM2KYMJLja14DF:-MGIJHZf7OnI3l5Njdc7:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L55)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

If you have a problem with python and setuptools please in this PR just bump the Ubuntu version in Dockerfile and in other switch to python3 
</blockquote></details>

Done.
___
*[utils/docker/Dockerfile.ubuntu-20.04, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFkVX3v38QYxoTUUgHZ:-MGIJHoq5S5cHnbsq8l7:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L58)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please change the commit author name and email to yourself
and commit message from: " Update ubuntu dockerfile to version 20.04" to
 Update Ubuntu Dockerfile to version 20.04
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @kasiawasiuta, @PatKamin, and @TomekIdczak97)

___
*[utils/docker/Dockerfile.ubuntu-20.04, line 58 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFkVX3v38QYxoTUUgHZ:-MGIMC310Wqu4FmSBBZs:b-1eelc7) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L58)):*
<details><summary><i>Previously, TomekIdczak97 (tomekidczak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope. "TomekIdczak97 authored and 1jenkins committed".
TomekIdczak97  should be the author and the one who committed this change.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @kasiawasiuta, @PatKamin, and @TomekIdczak97)

___
*[utils/docker/README.md, line 49 at r2](https://reviewable.io/reviews/memkind/memkind/366#-MGIMjKQ716Z14epbo5k:-MGIMjKQ716Z14epbo5l:b-7jugcq) ([raw file](https://github.com/memkind/memkind/blob/13ea2d05becfc5a1d8cf4ad508112092e86e057b/utils/docker/README.md#L49)):*
> ```
> 18.04
> ```
20.04

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @kasiawasiuta, @michalbiesek, and @PatKamin)

___
*[utils/docker/README.md, line 49 at r2](https://reviewable.io/reviews/memkind/memkind/366#-MGIMjKQ716Z14epbo5k:-MGIPaY32gGj6J7EBxrw:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/13ea2d05becfc5a1d8cf4ad508112092e86e057b/utils/docker/README.md#L49)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 18.04
> ```
20.04
</blockquote></details>

Done.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @kasiawasiuta, @michalbiesek, and @PatKamin)

___
*[utils/docker/Dockerfile.ubuntu-20.04, line 55 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFo_2KM2KYMJLja14DF:-MGJIYDmEPucf-6R2Pfw:ba4ffnv) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L55)):*
<details><summary><i>Previously, TomekIdczak97 (tomekidczak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not exactly, the test gives false-positive results. the version of pytest is important here. 
You could see it by yourself see: test/test.sh.log file and after your test and you will see something like:

### Processing pytest file 'test/autohbw_test.py' ###

### Processing pytest file 'test/trace_mechanism_test.py' ###

and in old version of this Dockerfile you could see


### Processing pytest file '/test/autohbw_test.py' ###
Test_autohbw.test_TC_MEMKIND_autohbw_malloc_and_free,PASSED
Test_autohbw.test_TC_MEMKIND_autohbw_calloc_and_free,PASSED
Test_autohbw.test_TC_MEMKIND_autohbw_realloc_and_free,PASSED
Test_autohbw.test_TC_MEMKIND_autohbw_posix_memalign_and_free,PASSED

### Processing pytest file 'test/trace_mechanism_test.py' ###
Test_trace_mechanism.test_TC_MEMKIND_logging_MEMKIND_HBW,PASSED
Test_trace_mechanism.test_TC_MEMKIND_2MBPages_logging_MEMKIND_HUGETLB,PASSED
Test_trace_mechanism.test_TC_MEMKIND_logging_negative_MEMKIND_DEBUG_env,PASSED

I believe you need somehow analyze https://github.com/memkind/memkind/blob/32e1ba90a12111cf0020de94a1cddf13a934bf95/test/test.sh#L345-L361

Please check if in this PR you could only bump the OS version and analyze the python incompatibility in separate issue

**Review by kasiawasiuta — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[utils/docker/Dockerfile.ubuntu-20.04, line 55 at r1](https://reviewable.io/reviews/memkind/memkind/366#-MFo_2KM2KYMJLja14DF:-MGd-hLu-Cy_-5eqpX9Q:b-6qu3mi) ([raw file](https://github.com/memkind/memkind/blob/1e1fe49429977dd14ded4bb2a941a3f28949bc4b/utils/docker/Dockerfile.ubuntu-20.04#L55)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Not exactly, the test gives false-positive results. the version of pytest is important here. 
You could see it by yourself see: test/test.sh.log file and after your test and you will see something like:

### Processing pytest file 'test/autohbw_test.py' ###

### Processing pytest file 'test/trace_mechanism_test.py' ###

and in old version of this Dockerfile you could see


### Processing pytest file '/test/autohbw_test.py' ###
Test_autohbw.test_TC_MEMKIND_autohbw_malloc_and_free,PASSED
Test_autohbw.test_TC_MEMKIND_autohbw_calloc_and_free,PASSED
Test_autohbw.test_TC_MEMKIND_autohbw_realloc_and_free,PASSED
Test_autohbw.test_TC_MEMKIND_autohbw_posix_memalign_and_free,PASSED

### Processing pytest file 'test/trace_mechanism_test.py' ###
Test_trace_mechanism.test_TC_MEMKIND_logging_MEMKIND_HBW,PASSED
Test_trace_mechanism.test_TC_MEMKIND_2MBPages_logging_MEMKIND_HUGETLB,PASSED
Test_trace_mechanism.test_TC_MEMKIND_logging_negative_MEMKIND_DEBUG_env,PASSED

I believe you need somehow analyze https://github.com/memkind/memkind/blob/32e1ba90a12111cf0020de94a1cddf13a934bf95/test/test.sh#L345-L361

Please check if in this PR you could only bump the OS version and analyze the python incompatibility in separate issue
</blockquote></details>

That's interesting. version 3.9.2 for ubuntu 20.04 wasn't working as the image wasn't building. As Michał says, fixing the script is a better way than looking for the specific pytest version that can handle it. Unless some pytest versions have a bug.

**Comment by michalbiesek** [comment]
@pmem-bot-ae
test this please

**Review by kasiawasiuta — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek and @PatKamin)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366#-:-MIZFh1t9MDbrQ38J_ln:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

**Comment by michalbiesek** [comment]
As we spoke offline, please consider to update the following places regarding Python 3 and https://www.python.org/dev/peps/pep-3105/:

https://github.com/memkind/memkind/blob/7759dcc69e02f9812324e195f6a53702881cbc8f/test/trace_mechanism_test.py#L20
https://github.com/memkind/memkind/blob/7759dcc69e02f9812324e195f6a53702881cbc8f/test/trace_mechanism_test.py#L29
https://github.com/memkind/memkind/blob/7759dcc69e02f9812324e195f6a53702881cbc8f/test/trace_mechanism_test.py#L38
https://github.com/memkind/memkind/blob/7759dcc69e02f9812324e195f6a53702881cbc8f/test/autohbw_test.py#L28
https://github.com/memkind/memkind/blob/7759dcc69e02f9812324e195f6a53702881cbc8f/test/autohbw_test.py#L37
https://github.com/memkind/memkind/blob/7759dcc69e02f9812324e195f6a53702881cbc8f/test/autohbw_test.py#L46
https://github.com/memkind/memkind/blob/7759dcc69e02f9812324e195f6a53702881cbc8f/test/autohbw_test.py#L55

**Comment by michalbiesek** [comment]
@pmem-bot-ae
test this please

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/366)* status: all files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta)

**Pull request merged**
