### PR TITLE
Add ranking

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/741)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/741)* status: all files reviewed, 8 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[include/memkind/internal/ranking_internals.hpp, line 110 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvOfJjA2GunC-vdg4uY:-MvOfJjA2GunC-vdg4uZ:b-ttlwlc) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/include/memkind/internal/ranking_internals.hpp#L110)):*
> ```cpp
>     ///     bool: true if not empty (hotness valid)
>     ///     double: hotness
>     std::pair<bool, double> GetHotestHotness();
> ```

maybe just simple "GetHotest" and "GetColdest"?
___
*[src/ranking_internals.cpp, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTEZp-E_OvMU70107G:-MvTEZp-E_OvMU70107H:b-bv46xz) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L45)):*
> ```cpp
>         this->value_ += add;
>     else
>         this->value_ += std::numeric_limits<double>::max();
> ```

"+="? not simple "=" ?
___
*[src/ranking_internals.cpp, line 94 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTGaHI53ITvrj85CDM:-MvTGaHI53ITvrj85CDN:b-25gldq) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L94)):*
> ```cpp
>     // TODO check SIMD optimisations
>     double ret = 0;
>     for (size_t i = 0; i < EXPONENTIAL_COEFFS_NUMBER; ++i)
> ```

please use { } here
___
*[src/ranking_internals.cpp, line 153 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTH6Sl2i_ZSvmRdjXs:-MvTH6Sl2i_ZSvmRdjXt:bk5boik) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L153)):*
> ```cpp
> MEMKIND_EXPORT void Ranking::Touch(uintptr_t addr)
> {
>     addr = (addr / PAGE_SIZE) * PAGE_SIZE;
> ```

add comment "get base address of page" or sth like that
___
*[src/ranking_internals.cpp, line 160 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTHDHJAB-qjefrhL0k:-MvTHDHJAB-qjefrhL0l:b-7r316n) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L160)):*
> ```cpp
>             this->pagesToUpdate.push_back(temp);
>         }
>     }
> ```

else?
___
*[src/ranking_internals.cpp, line 170 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTHWY87feOWBhrPFRp:-MvTHWY87feOWBhrPFRq:biymx1j) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L170)):*
> ```cpp
>         auto pages_entry = this->hotnessToPages.find(hotness);
>         // find correct entry in multimap
>         for (; pages_entry != this->hotnessToPages.end() &&
> ```

could you change this to "while() {} "? 
___
*[src/ranking_internals.cpp, line 214 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTHsr46-gC07Ftq1G_:-MvTHsr46-gC07Ftq1Ga:b-hee1sy) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L214)):*
> ```cpp
> MEMKIND_EXPORT Page Ranking::PopHottest()
> {
>     auto hottest = this->hotnessToPages.rbegin();
> ```

hottest pages are in reverse order? so from coldest to hottest? add a comment here
___
*[test/memkind_memtier_data_movement_test.cpp, line 378 at r2](https://reviewable.io/reviews/memkind/memkind/741#-MvOfysh4C1KMS13apYl:-MvOfysh4C1KMS13apYm:b-875qvj) ([raw file](https://github.com/memkind/memkind/blob/9237bbd598dd2c201dd471276421045574f6f345/test/memkind_memtier_data_movement_test.cpp#L378)):*
> ```cpp
> TEST_F(RankingBindingsTest, Basic)
> {
>     ranking_add_pages(handle, 0x2530FFAA, 5, 1 * SECOND);
> ```

what is tested here? there are no asserts in this tests

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/741)* status: all files reviewed, 11 unresolved discussions (waiting on @maciekpac)

___
*[src/ranking_internals.cpp, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvXfK6L3D5oSj_1CL9R:-MvXfK6L3D5oSj_1CL9S:b-s56r53) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L26)):*
> ```cpp
> double compensationCoeff_;
> 
> MEMKIND_EXPORT HotnessCoeff::HotnessCoeff(double init_hotness,
> ```

What is the purpose of exposing ranking internals?
___
*[src/ranking_internals.cpp, line 231 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvXdLh61vQppyoX7p1_:-MvXdLh61vQppyoX7p1a:buf3mrl) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L231)):*
> ```cpp
>     this->pageAddrToPage.emplace(std::make_pair(page.GetStartAddr(), page));
>     auto page_it = this->pageAddrToPage.find(page.GetStartAddr());
>     assert(page_it != this->pageAddrToPage.end() && "page not constructed!");
> ```

Is there any difference if you checked the return value of a bool from the emplace() function? This way there would be no need for obtaining the iterator via find(). Same thing would apply to `Ranking::AddPages`.

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/741)* status: 0 of 10 files reviewed, 13 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[include/memkind/internal/ranking_internals.hpp, line 110 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvOfJjA2GunC-vdg4uY:-MvXxVWy9X8RmQVWZyS4:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/include/memkind/internal/ranking_internals.hpp#L110)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

maybe just simple "GetHotest" and "GetColdest"?
</blockquote></details>

Done.
___
*[src/ranking_internals.cpp, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvXfK6L3D5oSj_1CL9R:-MvXyhkY7ufu4ajge40u:b-z0swwt) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L26)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

What is the purpose of exposing ranking internals?
</blockquote></details>

for test purposes

we might need a separate MEMKIND_EXPORT and MEMKIND_TEST macros in the future, or sth like that
___
*[src/ranking_internals.cpp, line 45 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTEZp-E_OvMU70107G:-MvXyxP51uPFOpb4RlC9:b-tcyy93) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L45)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

"+="? not simple "=" ?
</blockquote></details>

you're right, thank you
___
*[src/ranking_internals.cpp, line 94 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTGaHI53ITvrj85CDM:-MvXzHCs7Y6nuuzlGW2Q:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L94)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please use { } here
</blockquote></details>

Done.
___
*[src/ranking_internals.cpp, line 153 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTH6Sl2i_ZSvmRdjXs:-MvXz_87E7_I6nX3ErKI:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L153)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

add comment "get base address of page" or sth like that
</blockquote></details>

Done.
___
*[src/ranking_internals.cpp, line 160 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTHDHJAB-qjefrhL0k:-MvXzj1G2wNzYZFfE-u9:bmqegov) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L160)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

else?
</blockquote></details>

address not tracked, comment added
___
*[src/ranking_internals.cpp, line 170 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTHWY87feOWBhrPFRp:-MvY-QlN5aZML74LWk7n:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L170)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

could you change this to "while() {} "? 
</blockquote></details>

Done.
___
*[src/ranking_internals.cpp, line 214 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvTHsr46-gC07Ftq1G_:-MvY-g1DBiT_TRaJyvCZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L214)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

hottest pages are in reverse order? so from coldest to hottest? add a comment here
</blockquote></details>

Done.
___
*[src/ranking_internals.cpp, line 231 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvXdLh61vQppyoX7p1_:-MvY6bHe30YRPJhfWyJV:b-mvj1q0) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L231)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Is there any difference if you checked the return value of a bool from the emplace() function? This way there would be no need for obtaining the iterator via find(). Same thing would apply to `Ranking::AddPages`.
</blockquote></details>

your solution should be better, thanks for pointing that out
___
*[src/ranking_internals.cpp, line 106 at r2](https://reviewable.io/reviews/memkind/memkind/741#-MvTtSz-10ar6TX_fS_I:-MvXzICqEwZJoNCB3DSX:bhe0qoe) ([raw file](https://github.com/memkind/memkind/blob/9237bbd598dd2c201dd471276421045574f6f345/src/ranking_internals.cpp#L106)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Consider renaming this as it could be confused with OS-managed pages.
</blockquote></details>

Done, renamed to PageMetadata
___
*[test/memkind_memtier_data_movement_test.cpp, line 378 at r2](https://reviewable.io/reviews/memkind/memkind/741#-MvOfysh4C1KMS13apYl:-MvYfCBqDvGEVRXoFckR:b-bu91xm) ([raw file](https://github.com/memkind/memkind/blob/9237bbd598dd2c201dd471276421045574f6f345/test/memkind_memtier_data_movement_test.cpp#L378)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

what is tested here? there are no asserts in this tests
</blockquote></details>

Updated
___
*[test/memkind_memtier_data_movement_test.cpp, line 491 at r2](https://reviewable.io/reviews/memkind/memkind/741#-MvXrXSRDJm_Cwb-HD2M:-MvYVu3c3X8Q2pI-_0VU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/9237bbd598dd2c201dd471276421045574f6f345/test/memkind_memtier_data_movement_test.cpp#L491)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Could you add tests for using `HotnessCoeff::Update()` with non-zero `hotness_to_add`? Also using some really big numbers would be interesting (check for a double overflow).
</blockquote></details>

Done.
___
*[test/memkind_memtier_data_movement_test.cpp, line 535 at r2](https://reviewable.io/reviews/memkind/memkind/741#-MvXv3tR0UXXE_iZlSUO:-MvYR03M27jVGPBAhEd9:bc04o8k) ([raw file](https://github.com/memkind/memkind/blob/9237bbd598dd2c201dd471276421045574f6f345/test/memkind_memtier_data_movement_test.cpp#L535)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This test would be much more readable if you created a new struct with some meaningful field names instead of using std::pair. Now one have to dive into GetColdestHotness/GetHotestHotness functions to get the meaning of `first` and `second`. Even better would be to return just one value (as the name of the function suggests - hotness). And the boolean value could be returned as a ptr argument.
</blockquote></details>

Modified to return true on success, false on failure; hotness as an argument

**Review by bratpiorka — APPROVED** [review]
> Reviewed 4 of 6 files at r4, 6 of 6 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/741)* status: all files reviewed, 5 unresolved discussions (waiting on @PatKamin)

___
*[src/ranking_internals.cpp, line 26 at r1](https://reviewable.io/reviews/memkind/memkind/741#-MvXfK6L3D5oSj_1CL9R:-MvYhS6RDCep8REKwTXA:b-ey41w1) ([raw file](https://github.com/memkind/memkind/blob/3d6f2e2e22b17351262cd67b5bddff46085f8e4f/src/ranking_internals.cpp#L26)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

for test purposes

we might need a separate MEMKIND_EXPORT and MEMKIND_TEST macros in the future, or sth like that
</blockquote></details>

great idea

**Review by PatKamin — APPROVED** [review]
> Reviewed 4 of 10 files at r3, 5 of 6 files at r4, 1 of 6 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/741)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 7 of 7 files at r8, 6 of 6 files at r9, 1 of 1 files at r10, 6 of 6 files at r11, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/741)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
