### PR TITLE
Add mtt mmap

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [x] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/797)

### CODE REVIEW

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/797)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[include/mtt_allocator.h, line 44 at r1](https://reviewable.io/reviews/memkind/memkind/797#-N-Wcyog5jBGTTSLA8kD:-N-Wz5Gi9FIY_h2o3aX5:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ae5c9064afa1e421bdf3086b233c575e3678836b/include/mtt_allocator.h#L44)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Declaration doubled, remove one.
</blockquote></details>

Done.
___
*[src/mtt_allocator.c, line 479 at r1](https://reviewable.io/reviews/memkind/memkind/797#-N-WkGM-8jkf4F6A1NXi:-N-Wzp3W3-ymijntyp_o:bb6un1j) ([raw file](https://github.com/memkind/memkind/blob/ae5c9064afa1e421bdf3086b233c575e3678836b/src/mtt_allocator.c#L479)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: "Single allocation greater than or equal to hard limit is not implemented"
</blockquote></details>

Done

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 7 of 7 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/797)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[src/bigary.c, line 130 at r4](https://reviewable.io/reviews/memkind/memkind/797#-N-X23RBEiiadgbdw7mZ:-N-X23RBEiiadgbdw7m_:b-irlfmc) ([raw file](https://github.com/memkind/memkind/blob/6eaef2f359aea84133fa355e866a54f0bd47b290/src/bigary.c#L130)):*
> ```C
>     if (mmap(m_bigary->area + m_bigary->top, top - m_bigary->top,
>              PROT_READ | PROT_WRITE, MAP_FIXED | m_bigary->flags, m_bigary->fd,
>              0ul) == MAP_FAILED) {
> ```

why 0?

**Review by PatKamin — APPROVED** [review]
> Reviewed 7 of 7 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/797)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/797)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/bigary.c, line 130 at r4](https://reviewable.io/reviews/memkind/memkind/797#-N-X23RBEiiadgbdw7mZ:-N-X9CUk-z1c5jihBA4r:b25qzor) ([raw file](https://github.com/memkind/memkind/blob/6eaef2f359aea84133fa355e866a54f0bd47b290/src/bigary.c#L130)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

why 0?
</blockquote></details>

https://man7.org/linux/man-pages/man2/mmap.2.html

MAP_ANONYMOUS
              The mapping is not backed by any file; its contents are
              initialized to zero.  The fd argument is ignored; however,
              some implementations require fd to be -1 if MAP_ANONYMOUS
              (or MAP_ANON) is specified, and portable applications
              should ensure this.  The offset argument should be zero.
              The use of MAP_ANONYMOUS in conjunction with MAP_SHARED is
              supported on Linux only since kernel 2.4.

**Review by bratpiorka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/797)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
