### PR TITLE
Improve validation of MEMKIND_HBW_THRESHOLD env variable

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/509)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/509)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[src/memkind_mem_attributes.c, line 232 at r1](https://reviewable.io/reviews/memkind/memkind/509#-MSXRZhV4390uDGNGi7P:-MSXRZhV4390uDGNGi7Q:bh4p27o) ([raw file](https://github.com/memkind/memkind/blob/eeda1903f2564e1c699b158b58d6e8297e11f806/src/memkind_mem_attributes.c#L232)):*
> ```C
>         log_info("Environment variable MEMKIND_HBW_THRESHOLD detected: %s.",
>                  hbw_threshold_env);
>         char *end;
> ```

LGTM, but please also add note in memkind.3 that MEMKIND_HBW_THRESHOLD must be greater than or equal to 0.

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/509)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[src/memkind_mem_attributes.c, line 232 at r1](https://reviewable.io/reviews/memkind/memkind/509#-MSXRZhV4390uDGNGi7P:-MSXYCAKA0hka_D0OTmX:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/eeda1903f2564e1c699b158b58d6e8297e11f806/src/memkind_mem_attributes.c#L232)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

LGTM, but please also add note in memkind.3 that MEMKIND_HBW_THRESHOLD must be greater than or equal to 0.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/509)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @michalbiesek)

___
*[src/memkind_mem_attributes.c, line 237 at r2](https://reviewable.io/reviews/memkind/memkind/509#-MSXZgv51rjwyq_y2Jkq:-MSXZgv51rjwyq_y2Jkr:bjhzpa5) ([raw file](https://github.com/memkind/memkind/blob/a62205a48498837eb95ffa837d95bff86f5e1449/src/memkind_mem_attributes.c#L237)):*
> ```C
>         if (hbw_threshold > UINT_MAX || *end != '\0' || errno != 0) {
>             log_err("Environment variable MEMKIND_HBW_THRESHOLD is invalid value.");
>             return MEMKIND_ERROR_ENVIRON;
> ```

log_fatal() followed by abort()

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/509)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[src/memkind_mem_attributes.c, line 237 at r2](https://reviewable.io/reviews/memkind/memkind/509#-MSXZgv51rjwyq_y2Jkq:-MSX_HAp4DqrxDHagLUA:b-syymgz) ([raw file](https://github.com/memkind/memkind/blob/a62205a48498837eb95ffa837d95bff86f5e1449/src/memkind_mem_attributes.c#L237)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

log_fatal() followed by abort()
</blockquote></details>

@michalbiesek - do you agree with Patryk?

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/509)* status: all files reviewed, 2 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[src/memkind_mem_attributes.c, line 237 at r2](https://reviewable.io/reviews/memkind/memkind/509#-MSXZgv51rjwyq_y2Jkq:-MSXaRfo2X-Mid6m0J-e:b-sfylzw) ([raw file](https://github.com/memkind/memkind/blob/a62205a48498837eb95ffa837d95bff86f5e1449/src/memkind_mem_attributes.c#L237)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

@michalbiesek - do you agree with Patryk?
</blockquote></details>

No - this form is OK - don't change this. - in the previous case with thread value see that happened during __construc__t - here we have the perfect situation to handle this with MEMKIND_ERROR_ENVIRON.

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/509)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/509#-:-MSXbgTSDpEnrFPqtmKE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
