### PR TITLE
[WIP] Add memory kind for current running CPU

### PR DESCRIPTION
**Pull request by michalbiesek**
- allocate memory only for running CPU
- this could avoid numactl binding on the whole application

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/469)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/469)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[man/memkindallocator.3, line 100 at r1](https://reviewable.io/reviews/memkind/memkind/469#-MRPBnQH3W7-_9z7u43p:-MRPBnQH3W7-_9z7u43q:b3wqj0u) ([raw file](https://github.com/memkind/memkind/blob/7beb5c66232f5309697535875515bfccd51663c8/man/memkindallocator.3#L100)):*
> ```Roff
> Allocate from regular memory using the default page size. Regular means general purpose memory from the NUMA nodes containing CPUs.
> .PP
> .B libmemkind::kinds::LOCAL
> ```

CPU_LOCAL ?
___
*[include/memkind/internal/memkind_cpu.h, line 12 at r1](https://reviewable.io/reviews/memkind/memkind/469#-MRPBtRH7zBILn9swrZC:-MRPBtRI9Q3yRY8ijJw4:b5cf8qb) ([raw file](https://github.com/memkind/memkind/blob/7beb5c66232f5309697535875515bfccd51663c8/include/memkind/internal/memkind_cpu.h#L12)):*
> ```objc
> 
> /*
>  * Header file for the CPU memory memkind operations.
> ```

CPU local memory

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/469)* status: all files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

___
*[src/memkind_cpu.c, line 41 at r1](https://reviewable.io/reviews/memkind/memkind/469#-MRPFiB15bItv1UkTxK2:-MRPFiB20MesTgchn2rs:bb1ji38) ([raw file](https://github.com/memkind/memkind/blob/7beb5c66232f5309697535875515bfccd51663c8/src/memkind_cpu.c#L41)):*
> ```C
> static void cpu_local_nodes_init(void)
> {
>     unsigned cpu_max = numa_num_configured_cpus();
> ```

It's not a max cpu number as the var name suggests. Rename to ie. cpus_num to be consistent with nodes_num var name or change both to sth like nodes_count/cpus_count.
___
*[src/memkind_cpu.c, line 62 at r1](https://reviewable.io/reviews/memkind/memkind/469#-MRPZyX93VqQBMHqgyxx:-MRPZyXACXXXcD5HVyAb:bu0l09s) ([raw file](https://github.com/memkind/memkind/blob/7beb5c66232f5309697535875515bfccd51663c8/src/memkind_cpu.c#L62)):*
> ```C
>         if (numa_node_to_cpus(node_id, node_cpu_mask) != 0)
>             continue;
>         if (numa_bitmask_weight(node_cpu_mask) && numa_node_size64(node_id,NULL) >0) {
> ```

Add whitespace before 0.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/469)* status: 3 of 14 files reviewed, 4 unresolved discussions (waiting on @PatKamin)

___
*[man/memkindallocator.3, line 100 at r1](https://reviewable.io/reviews/memkind/memkind/469#-MRPBnQH3W7-_9z7u43p:-MSYBlIU7gKxzwBoyo-D:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7beb5c66232f5309697535875515bfccd51663c8/man/memkindallocator.3#L100)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

CPU_LOCAL ?
</blockquote></details>

Done.
___
*[src/memkind_cpu.c, line 41 at r1](https://reviewable.io/reviews/memkind/memkind/469#-MRPFiB15bItv1UkTxK2:-MSYBm9k2TztHupXo4Mg:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7beb5c66232f5309697535875515bfccd51663c8/src/memkind_cpu.c#L41)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It's not a max cpu number as the var name suggests. Rename to ie. cpus_num to be consistent with nodes_num var name or change both to sth like nodes_count/cpus_count.
</blockquote></details>

Done.
___
*[src/memkind_cpu.c, line 62 at r1](https://reviewable.io/reviews/memkind/memkind/469#-MRPZyX93VqQBMHqgyxx:-MSYBmubB48E3fHXG7xU:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7beb5c66232f5309697535875515bfccd51663c8/src/memkind_cpu.c#L62)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add whitespace before 0.
</blockquote></details>

Done.
___
*[include/memkind/internal/memkind_cpu.h, line 12 at r1](https://reviewable.io/reviews/memkind/memkind/469#-MRPBtRH7zBILn9swrZC:-MSYBgV57zlXks1Oa4PH:b5d8nxs) ([raw file](https://github.com/memkind/memkind/blob/7beb5c66232f5309697535875515bfccd51663c8/include/memkind/internal/memkind_cpu.h#L12)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

CPU local memory
</blockquote></details>

Prefer CPU memory since it considers API for MEMKIND_REGULAR

**Review by PatKamin — COMMENTED** [review]
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/469)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/469)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lukaszstolarczuk** [comment]
This change is a WIP and is stale for a while, so I'm allowing myself to close it. It will be tracked in issue: https://github.com/memkind/memkind/issues/876

**Pull request closed without merging**
