### PR TITLE
Fix DAX_KMEM_PREFERRED test failure

### PR DESCRIPTION
**Pull request by PatKamin**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/755)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/755)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[test/memkind_dax_kmem_test.cpp, line 406 at r1](https://reviewable.io/reviews/memkind/memkind/755#-Mw6e0-zEpRzyLyXSVnv:-Mw6e0-zEpRzyLyXSVnw:boqnnlp) ([raw file](https://github.com/memkind/memkind/blob/d305d810b9352150814094aeeb0de148c2004359/test/memkind_dax_kmem_test.cpp#L406)):*
> ```cpp
>     ASSERT_GT(numa_size, 0U);
> 
>     while ((size_t)numa_free_size - alloc_size >
> ```

maybe a for loop with expected num of iterations (allocations) would be better here?

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/755)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/755)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

___
*[test/memkind_dax_kmem_test.cpp, line 406 at r1](https://reviewable.io/reviews/memkind/memkind/755#-Mw6e0-zEpRzyLyXSVnv:-MwAykqe6b_J91Mx7YBC:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/d305d810b9352150814094aeeb0de148c2004359/test/memkind_dax_kmem_test.cpp#L406)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

maybe a for loop with expected num of iterations (allocations) would be better here?
</blockquote></details>

Done.

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/755)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[test/memkind_dax_kmem_test.cpp, line 407 at r4](https://reviewable.io/reviews/memkind/memkind/755#-MwBEOC5AyYyV7lSyGBN:-MwBEOC5AyYyV7lSyGBO:bcshwk) ([raw file](https://github.com/memkind/memkind/blob/c3ab9d62ed3ee605acd23a8c8606f23bf8ba69f7/test/memkind_dax_kmem_test.cpp#L407)):*
> ```cpp
>     size_t free_size_limit = 0.99 * (size_t)numa_free_size;
>     const int allocs_no = free_size_limit / alloc_size;
>     const int extra_allocs_no =
> ```

please add a comment why allocs_no is calculated this way (with info that allocs_no + extra_allocs_no allocations size is greater that numa free size)
___
*[test/memkind_dax_kmem_test.cpp, line 427 at r4](https://reviewable.io/reviews/memkind/memkind/755#-MwBEVgc2mswTZeMIqYF:-MwBEVgc2mswTZeMIqYG:b6gdif2) ([raw file](https://github.com/memkind/memkind/blob/c3ab9d62ed3ee605acd23a8c8606f23bf8ba69f7/test/memkind_dax_kmem_test.cpp#L427)):*
> ```cpp
>     }
> 
>     get_mempolicy(&numa_id, nullptr, 0, ptr, MPOL_F_NODE | MPOL_F_ADDR);
> ```

please add a comment that only last allocation is checked here

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/755)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka)

___
*[test/memkind_dax_kmem_test.cpp, line 407 at r4](https://reviewable.io/reviews/memkind/memkind/755#-MwBEOC5AyYyV7lSyGBN:-MwB_YJt8g6KbpKeTT-r:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c3ab9d62ed3ee605acd23a8c8606f23bf8ba69f7/test/memkind_dax_kmem_test.cpp#L407)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please add a comment why allocs_no is calculated this way (with info that allocs_no + extra_allocs_no allocations size is greater that numa free size)
</blockquote></details>

Done.
___
*[test/memkind_dax_kmem_test.cpp, line 427 at r4](https://reviewable.io/reviews/memkind/memkind/755#-MwBEVgc2mswTZeMIqYF:-MwB_YsF4h_3rWHXDu8n:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/c3ab9d62ed3ee605acd23a8c8606f23bf8ba69f7/test/memkind_dax_kmem_test.cpp#L427)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please add a comment that only last allocation is checked here
</blockquote></details>

Done.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/755)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

**Review by bratpiorka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/755)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
