### PR TITLE
Clean up memkind_bandwidth module

### PR DESCRIPTION
**Pull request by michalbiesek**
- Rename module to memkind_bitmask
- Simplify logic of mapping initiator of allocation and destination of allocation
- First identify set to expected Nodes (HBW, PMEM)
- Second, iterate over all CPU Nodes to find the closest one of unique nodes from the first step

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/422)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/422)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @kasiawasiuta, @michalbiesek, and @PatKamin)

___
*[src/memkind_bitmask.c, line 66 at r4](https://reviewable.io/reviews/memkind/memkind/422#-MOWPxFhBvahphK0KuY_:-MOWPxFhBvahphK0KuYa:b-xa3d5k) ([raw file](https://github.com/memkind/memkind/blob/be29997d087687d7576f6deed9f13d9e695b0dc7/src/memkind_bitmask.c#L66)):*
> ```
> d_errno = errno;
> ```
what is this for?
___
*[src/memkind_bitmask.c, line 105 at r4](https://reviewable.io/reviews/memkind/memkind/422#-MOWROCABK4WATHIgWRB:-MOWQOCG7tueVXofklU4:bdmi0op) ([raw file](https://github.com/memkind/memkind/blob/be29997d087687d7576f6deed9f13d9e695b0dc7/src/memkind_bitmask.c#L105)):*
> ```C
> free_node_arr:
>     free(node_arr);
> ```

This is not straightforward what is going on here... could you add some comments to this GOTO's? in this line you could e.g. write "if everything is ok then... "

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/422)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @kasiawasiuta, and @PatKamin)

___
*[src/memkind_bitmask.c, line 66 at r4](https://reviewable.io/reviews/memkind/memkind/422#-MOWPxFhBvahphK0KuY_:-MOWTGZY7FvGLNz61Wya:b-2p24fj) ([raw file](https://github.com/memkind/memkind/blob/be29997d087687d7576f6deed9f13d9e695b0dc7/src/memkind_bitmask.c#L66)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

> ```
> d_errno = errno;
> ```
what is this for?
</blockquote></details>

Ref: 4f9fe21
___
*[src/memkind_bitmask.c, line 105 at r4](https://reviewable.io/reviews/memkind/memkind/422#-MOWROCABK4WATHIgWRB:-MOWUw0S3NVOAdDo_dwG:biacw62) ([raw file](https://github.com/memkind/memkind/blob/be29997d087687d7576f6deed9f13d9e695b0dc7/src/memkind_bitmask.c#L105)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

This is not straightforward what is going on here... could you add some comments to this GOTO's? in this line you could e.g. write "if everything is ok then... "
</blockquote></details>

I added some comments in each section - see if it is clear now

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 6 files at r3, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/422)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kasiawasiuta and @PatKamin)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/422#-:-MOWVjPB5LgpbKsfX1CA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kasiawasiuta and @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/422)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @kasiawasiuta, and @michalbiesek)

___
*[src/memkind_dax_kmem.c, line 59 at r3](https://reviewable.io/reviews/memkind/memkind/422#-MOWB4vn5Si0I6ay1Qk9:-MOWB4vo-W0b0gV2wCa6:b-ljav9i) ([raw file](https://github.com/memkind/memkind/blob/afc3b30719539d8b6a902312557bd67535cd2499/src/memkind_dax_kmem.c#L59)):*
> ```C
>     struct daxctl_dev *dev, *_dev;
>     struct daxctl_ctx *ctx;
>     // NUMA Nodes could not be always in arithmetic progression
> ```

could be not in arithmetic progression
___
*[src/memkind_hbw.c, line 302 at r3](https://reviewable.io/reviews/memkind/memkind/422#-MOWLmnm4mxnDmHBR-hX:-MOWLmnn5qrbO1cLleIg:bp0xl3h) ([raw file](https://github.com/memkind/memkind/blob/afc3b30719539d8b6a902312557bd67535cd2499/src/memkind_hbw.c#L302)):*
> ```C
>         node_cpumask = numa_allocate_cpumask();
>         if (!node_cpumask) {
>             log_err("malloc() failed.");
> ```

`numa_allocate_cpumask() failed` would be better.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/422)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @bratpiorka, @kasiawasiuta, and @PatKamin)

___
*[src/memkind_dax_kmem.c, line 59 at r3](https://reviewable.io/reviews/memkind/memkind/422#-MOWB4vn5Si0I6ay1Qk9:-MOWYDJJ2kVjRoOaiaA4:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/afc3b30719539d8b6a902312557bd67535cd2499/src/memkind_dax_kmem.c#L59)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

could be not in arithmetic progression
</blockquote></details>

Done.
___
*[src/memkind_hbw.c, line 302 at r3](https://reviewable.io/reviews/memkind/memkind/422#-MOWLmnm4mxnDmHBR-hX:-MOWYCvw0wG-3WpDsqtp:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/afc3b30719539d8b6a902312557bd67535cd2499/src/memkind_hbw.c#L302)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`numa_allocate_cpumask() failed` would be better.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/422#-:-MOWgneQ81jfl_6ZHjY_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kasiawasiuta)

**Pull request merged**
