### PR TITLE
Fix building when malloc_usable_size() requires a "const void*" argument

### PR DESCRIPTION
**Pull request by bratpiorka**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/713)

### CODE REVIEW

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/713)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @kilobyte, and @maciekpac)

___
*[src/memkind.c, line 833 at r1](https://reviewable.io/reviews/memkind/memkind/713#-MpknY8A5V5wgLm9FZ67:-MpknY8A5V5wgLm9FZ68:bp3vj0y) ([raw file](https://github.com/memkind/memkind/blob/faa295ebca5e5378a75d6590301c13e564d607ea/src/memkind.c#L833)):*
> ```C
> }
> 
> MEMKIND_EXPORT size_t memkind_malloc_usable_size(
> ```

Use `// clang-format off/on`

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/713)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[src/memkind.c, line 833 at r1](https://reviewable.io/reviews/memkind/memkind/713#-MpknY8A5V5wgLm9FZ67:-MpkqS1uDnVkm18sNahc:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/faa295ebca5e5378a75d6590301c13e564d607ea/src/memkind.c#L833)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Use `// clang-format off/on`
</blockquote></details>

Done.

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/713)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte and @maciekpac)

**Review by PatKamin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/713#-:-MqJp1mB3qsm1rmBTwNc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte and @maciekpac)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/713)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

___
*[src/memkind.c, line 833 at r1](https://reviewable.io/reviews/memkind/memkind/713#-MpknY8A5V5wgLm9FZ67:-Mpl8qUA3Y40gGQyqu75:b-gis2rt) ([raw file](https://github.com/memkind/memkind/blob/faa295ebca5e5378a75d6590301c13e564d607ea/src/memkind.c#L833)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why can't we format it the way clang would?

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/713)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @kilobyte)

___
*[configure.ac, line 359 at r2](https://reviewable.io/reviews/memkind/memkind/713#-MqKCRH24vHcK_Y8pb4W:-MqKCRH24vHcK_Y8pb4X:bjx3hin) ([raw file](https://github.com/memkind/memkind/blob/de934d0bd523ad9cd776e3c738204ad9671d0932/configure.ac#L359)):*
> ```M4Sugar
> fi
> 
> #===============================malloc_usable_size=============================
> ```

I think this ties our code to autotools even further - I remember there was a talk about moving to a different build system, but I'm not sure about the timeframe and if this would actulally be done.

I think that having an additional comment here would be great, but I'm ok with the current version.
___
*[configure.ac, line 366 at r2](https://reviewable.io/reviews/memkind/memkind/713#-MqKCxb-16hz-AY--0Tt:-MqKCxb-16hz-AY--0Tu:b-wpite1) ([raw file](https://github.com/memkind/memkind/blob/de934d0bd523ad9cd776e3c738204ad9671d0932/configure.ac#L366)):*
> ```M4Sugar
> ]],[[
> size_t malloc_usable_size(const void *ptr);
> ]])], [memkind_malloc_usable_size_const="1"], [memkind_malloc_usable_size_const="0"])
> ```

Isn't it possible to consolidate this line with the next one? This is not a blocker, but I would be happy to know

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/713)* status: all files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @kilobyte)

___
*[configure.ac, line 366 at r2](https://reviewable.io/reviews/memkind/memkind/713#-MqKCxb-16hz-AY--0Tt:-MqKITQ43usGjOX5m4P2:b-81n5gv) ([raw file](https://github.com/memkind/memkind/blob/de934d0bd523ad9cd776e3c738204ad9671d0932/configure.ac#L366)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Isn't it possible to consolidate this line with the next one? This is not a blocker, but I would be happy to know
</blockquote></details>

Settled in-person

**Pull request merged**
