### PR TITLE
[Main branch] Update for 1.13.0

### PR DESCRIPTION
**Pull request by PatKamin**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/721)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721)* status: all files reviewed, 1 unresolved discussion (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[ChangeLog, line 3 at r1](https://reviewable.io/reviews/memkind/memkind/721#-MrXGCp3EUDa0ox3Bzig:-MrXGCp3EUDa0ox3Bzih:b-b0rmp) ([raw file](https://github.com/memkind/memkind/blob/eebfdf1dbbb286c67a590025213724e283b9d7cd/ChangeLog#L3)):*
> ```
> * Wed Dec 22 2021 Patryk Kaminski <patryk.kaminski@intel.com> v1.13.0
> - Added fixed kind for static maps (along with the C++ allocator)
> - Added memkind_get_capacity() function for getting the memory capacity of nodes available to a given kind
> ```

looking at older messages "Provided a function.. " will be more consistent

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @kilobyte, and @maciekpac)

___
*[ChangeLog, line 3 at r1](https://reviewable.io/reviews/memkind/memkind/721#-MrXGCp3EUDa0ox3Bzig:-MrXIc9lDnIif9j9iK30:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/eebfdf1dbbb286c67a590025213724e283b9d7cd/ChangeLog#L3)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

looking at older messages "Provided a function.. " will be more consistent
</blockquote></details>

Done.

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721)* status: all files reviewed, 1 unresolved discussion (waiting on @kilobyte and @PatKamin)

___
*[ChangeLog, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/721#-MrXJ27Y4tThudhC5Zm2:-MrXJ27Y4tThudhC5Zm3:bld5f2i) ([raw file](https://github.com/memkind/memkind/blob/44991d246d5fd28cdc3e2830a6fa6873abf5e340/ChangeLog#L2)):*
> ```
> * Wed Dec 22 2021 Patryk Kaminski <patryk.kaminski@intel.com> v1.13.0
> - Added fixed kind for static maps (along with the C++ allocator)
> ```

"static maps" ?

user-supplied memory area ?

1. The area can be mmapped, but does not have to be; what do you mean by a "static map" exactly?

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @bratpiorka, @kilobyte, and @maciekpac)

___
*[ChangeLog, line 2 at r2](https://reviewable.io/reviews/memkind/memkind/721#-MrXJ27Y4tThudhC5Zm2:-MrXJwS46fUnq_63CRCf:b-qwmwih) ([raw file](https://github.com/memkind/memkind/blob/44991d246d5fd28cdc3e2830a6fa6873abf5e340/ChangeLog#L2)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

"static maps" ?

user-supplied memory area ?

1. The area can be mmapped, but does not have to be; what do you mean by a "static map" exactly?
</blockquote></details>

Right, it's too narrow. I've taken this phrase from the commit message of 38ae1e3cfe2d15e7ab9fda5fbd603c5000a658b4. Done.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721)* status: all files reviewed, 1 unresolved discussion (waiting on @kilobyte and @maciekpac)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721)* status: all files reviewed, 2 unresolved discussions (waiting on @kilobyte, @maciekpac, and @PatKamin)

___
*[ChangeLog, line 9 at r3](https://reviewable.io/reviews/memkind/memkind/721#-MrXLGwREjuQ-HMx7VsR:-MrXLGwREjuQ-HMx7VsS:b-q2hkou) ([raw file](https://github.com/memkind/memkind/blob/b1cbd53974149550f5c25acbfeff7357130f7f2e/ChangeLog#L9)):*
> ```
> - Updated ax_pthread.m4 to a new version from autoconf-archive
> - Fixed wrong NUMA nodes masks for some of static kinds
> - Fixed building when malloc_usable_size() requires a "const void*" argument
> ```

Nit: Fixed building on platforms where malloc_usable_size() requires a "const void*" argument

maybe would be a little bit better?



_Code quote:_
```
Fixed building when malloc_usable_size() requires a "const void*" argument
```

**Review by kilobyte — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[ChangeLog, line 7 at r3](https://reviewable.io/reviews/memkind/memkind/721#-MrXMOotC8k6ROsPuLFT:-MrXMOotC8k6ROsPuLFU:bpzy5ah) ([raw file](https://github.com/memkind/memkind/blob/b1cbd53974149550f5c25acbfeff7357130f7f2e/ChangeLog#L7)):*
> ```
> - Optimized PMEM kind (allocating metadata from main memory)
> - Added logging to file mechanism (enabled with an --enable-logging-to-file configure parameter)
> - Updated ax_pthread.m4 to a new version from autoconf-archive
> ```

Do we want such details in the changelog?  There's the git log for changes that don't affect the user.
___
*[ChangeLog, line 9 at r3](https://reviewable.io/reviews/memkind/memkind/721#-MrXLGwREjuQ-HMx7VsR:-MrXMIG_AMuF1lD-af5w:b-90plzx) ([raw file](https://github.com/memkind/memkind/blob/b1cbd53974149550f5c25acbfeff7357130f7f2e/ChangeLog#L9)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Nit: Fixed building on platforms where malloc_usable_size() requires a "const void*" argument

maybe would be a little bit better?
</blockquote></details>

Perhaps we instead could say what platforms are affected?  The details are not as interesting.

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @bratpiorka, @kilobyte, and @maciekpac)

___
*[ChangeLog, line 7 at r3](https://reviewable.io/reviews/memkind/memkind/721#-MrXMOotC8k6ROsPuLFT:-MrXQdZ78KU4XWtwHhmu:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b1cbd53974149550f5c25acbfeff7357130f7f2e/ChangeLog#L7)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Do we want such details in the changelog?  There's the git log for changes that don't affect the user.
</blockquote></details>

Done.
___
*[ChangeLog, line 9 at r3](https://reviewable.io/reviews/memkind/memkind/721#-MrXLGwREjuQ-HMx7VsR:-MrXSqtC9Xb-7jFsWToc:b-uvfbot) ([raw file](https://github.com/memkind/memkind/blob/b1cbd53974149550f5c25acbfeff7357130f7f2e/ChangeLog#L9)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Perhaps we instead could say what platforms are affected?  The details are not as interesting.
</blockquote></details>

Is that any better?

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @maciekpac)

___
*[ChangeLog, line 9 at r3](https://reviewable.io/reviews/memkind/memkind/721#-MrXLGwREjuQ-HMx7VsR:-MrXTOcm3DiHubDwFmWt:b-sfe2pd) ([raw file](https://github.com/memkind/memkind/blob/b1cbd53974149550f5c25acbfeff7357130f7f2e/ChangeLog#L9)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Is that any better?
</blockquote></details>

Not what I meant but meh...

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by kilobyte — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/721#-:-MrXXP3w6iJP8mEt7d6h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
