### PR TITLE
Extend API with memkind_get_capacity() function

### PR DESCRIPTION
**Pull request by PatKamin**
- this function returns total size of the PMEM file for PMEM kind
  or, for the other kinds, the sum of memory for all NUMA nodes
  where a given kind could allocate

### Types of changes

- [x] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [x] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/704)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/704)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/memkind/memkind/704#-Miz3JYg70LoVBA-jku9):*
the sum of total memory
___
*[include/memkind.h, line 521 at r1](https://reviewable.io/reviews/memkind/memkind/704#-Miz3PpZD9zQj8_skpkU:-Miz3PpZD9zQj8_skpkV:b-s4o9p9) ([raw file](https://github.com/memkind/memkind/blob/03f4e87cb8c9ecc82de7d4697640d873fd5fbd31/include/memkind.h#L521)):*
> ```objc
> /// \note STANDARD API
> /// \param kind specified memory kind
> /// \return Total memory on nodes from which a given kind can allocate in bytes on success, -1 on failure
> ```

could?

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/704)* status: all files reviewed, 5 unresolved discussions (waiting on @PatKamin)

___
*[test/get_total_memory_test.cpp, line 52 at r4](https://reviewable.io/reviews/memkind/memkind/704#-MjdVi67AKCR3efIFmof:-MjdVi67AKCR3efIFmog:b-bt814q) ([raw file](https://github.com/memkind/memkind/blob/b3ac3b8aa2528ad8c4f697781d14eeb636d0ae10/test/get_total_memory_test.cpp#L52)):*
> ```cpp
>         total_memory += curr_node_size;
>     }
>     ASSERT_EQ(total_memory, memkind_get_total_memory(MEMKIND_DEFAULT));
> ```

As we spoke offline, please return error on MEMKIND_DEFAULT, HUGETLB, INTERLEAVE etc. and create test that expect error on these cases.
___
*[test/get_total_memory_test.cpp, line 72 at r4](https://reviewable.io/reviews/memkind/memkind/704#-MjdW64s67sAYkKzhOnz:-MjdW64s67sAYkKzhOo-:b-wcrhuz) ([raw file](https://github.com/memkind/memkind/blob/b3ac3b8aa2528ad8c4f697781d14eeb636d0ae10/test/get_total_memory_test.cpp#L72)):*
> ```cpp
>     long long total_memory = 0;
> 
>     for (auto node : numa_nodes) {
> ```

you could create a helper function in TestPrereq that takes numa_nodes and returns total size
___
*[test/Makefile.mk, line 30 at r4](https://reviewable.io/reviews/memkind/memkind/704#-MjdG3sgEgxNTFezd5sw:-MjdG3shC0wh0aqdCq_5:b-2nfwwu) ([raw file](https://github.com/memkind/memkind/blob/b3ac3b8aa2528ad8c4f697781d14eeb636d0ae10/test/Makefile.mk#L30)):*
> ```Makefile
>                   test/environ_err_hbw_threshold_test \
>                   test/defrag_reallocate \
> 				  test/get_total_memory_test \
> ```

convert tabs to spaces

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/704)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @bratpiorka)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/memkind/memkind/704#-Miz3JYg70LoVBA-jku9):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

the sum of total memory
</blockquote></details>

Total memory sounds best.
___
*[include/memkind.h, line 521 at r1](https://reviewable.io/reviews/memkind/memkind/704#-Miz3PpZD9zQj8_skpkU:-MjdcE4sCCPONzMV4TzX:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/03f4e87cb8c9ecc82de7d4697640d873fd5fbd31/include/memkind.h#L521)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

could?
</blockquote></details>

Done.
___
*[test/get_total_memory_test.cpp, line 52 at r4](https://reviewable.io/reviews/memkind/memkind/704#-MjdVi67AKCR3efIFmof:-MjdlRgN89VLxFmEPBDh:b5je2tf) ([raw file](https://github.com/memkind/memkind/blob/b3ac3b8aa2528ad8c4f697781d14eeb636d0ae10/test/get_total_memory_test.cpp#L52)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

As we spoke offline, please return error on MEMKIND_DEFAULT, HUGETLB, INTERLEAVE etc. and create test that expect error on these cases.
</blockquote></details>

Error for PREFERRED kinds for now.
___
*[test/get_total_memory_test.cpp, line 72 at r4](https://reviewable.io/reviews/memkind/memkind/704#-MjdW64s67sAYkKzhOnz:-MjdlQ9I3-ECzM3cItit:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b3ac3b8aa2528ad8c4f697781d14eeb636d0ae10/test/get_total_memory_test.cpp#L72)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

you could create a helper function in TestPrereq that takes numa_nodes and returns total size
</blockquote></details>

Done.
___
*[test/Makefile.mk, line 30 at r4](https://reviewable.io/reviews/memkind/memkind/704#-MjdG3sgEgxNTFezd5sw:-MjdmFY14tGjfvX_nWYa:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/b3ac3b8aa2528ad8c4f697781d14eeb636d0ae10/test/Makefile.mk#L30)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

convert tabs to spaces
</blockquote></details>

Done.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 9 of 10 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/704)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 17 of 17 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, 9 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/704)* status: all files reviewed, 6 unresolved discussions (waiting on @PatKamin)

___
*[-- commits, line 12 at r8](https://reviewable.io/reviews/memkind/memkind/704#-Mjo2GEBBVp3R4T-GYR5):*
Fixes case, where ...
___
*[src/memkind_hbw.c, line 309 at r7](https://reviewable.io/reviews/memkind/memkind/704#-Mjo0np-4yuPxSq7fCtw:-Mjo0np-4yuPxSq7fCtx:b-o3m2yg) ([raw file](https://github.com/memkind/memkind/blob/ea2c7e6dc7d74344c800720702531bbf90d71b54/src/memkind_hbw.c#L309)):*
> ```C
> 
>     // Check if NUMA configuration is supported.
>     int nodes_num = numa_max_node() + 1;
> ```

here you should stay with original numa_num_configured_nodes();
___
*[src/memkind_hbw.c, line 330 at r7](https://reviewable.io/reviews/memkind/memkind/704#-Mjo10DDCOBfkGy-qVNX:-Mjo10DDCOBfkGy-qVNY:be2sfa9) ([raw file](https://github.com/memkind/memkind/blob/ea2c7e6dc7d74344c800720702531bbf90d71b54/src/memkind_hbw.c#L330)):*
> ```C
>     }
>     assert(node_cpumask->size >= nodes_num);
>     for (i = 0; i < nodes_num; ++i) {
> ```

this is the place that needs to be fixed
___
*[test/get_capacity_test.cpp, line 130 at r10](https://reviewable.io/reviews/memkind/memkind/704#-Mjo3Uva7OLAX1oMOop1:-Mjo3Uvb1P71V4i3YXHW:b-k3xhvf) ([raw file](https://github.com/memkind/memkind/blob/00ecf2fc6eef8aa8151ad23accd644411f365e28/test/get_capacity_test.cpp#L130)):*
> ```cpp
>     int process_cpu = sched_getcpu();
>     int process_node = numa_node_of_cpu(process_cpu);
>     ASSERT_EQ(status, 0);
> ```

this secondary check for status value is unnecessary
___
*[test/get_capacity_test.cpp, line 174 at r10](https://reviewable.io/reviews/memkind/memkind/704#-Mjo3rz-DFYS-MMM2qiT:-Mjo3rz-DFYS-MMM2qiU:bxxzac8) ([raw file](https://github.com/memkind/memkind/blob/00ecf2fc6eef8aa8151ad23accd644411f365e28/test/get_capacity_test.cpp#L174)):*
> ```cpp
>     ASSERT_EQ(status, 0);
> 
>     ASSERT_EQ(-1, memkind_get_capacity(memory_kind));
> ```

please add comment why we're expecting -1 here
___
*[test/get_capacity_test.cpp, line 175 at r10](https://reviewable.io/reviews/memkind/memkind/704#-Mjo404f6IXzLWXDKESi:-Mjo404f6IXzLWXDKESj:b-d0wxhj) ([raw file](https://github.com/memkind/memkind/blob/00ecf2fc6eef8aa8151ad23accd644411f365e28/test/get_capacity_test.cpp#L175)):*
> ```cpp
> 
>     ASSERT_EQ(-1, memkind_get_capacity(memory_kind));
> }
> ```

new line

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 13 of 13 files at r11, 1 of 1 files at r12, 3 of 3 files at r13, 8 of 8 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/704)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by bratpiorka — APPROVED** [review]

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/704)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

___
*[-- commits, line 12 at r8](https://reviewable.io/reviews/memkind/memkind/704#-Mjo2GEBBVp3R4T-GYR5):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Fixes case, where ...
</blockquote></details>

Done.
___
*[src/memkind_hbw.c, line 309 at r7](https://reviewable.io/reviews/memkind/memkind/704#-Mjo0np-4yuPxSq7fCtw:-Mk12nI26kXYaUX1Cyx3:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ea2c7e6dc7d74344c800720702531bbf90d71b54/src/memkind_hbw.c#L309)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

here you should stay with original numa_num_configured_nodes();
</blockquote></details>

Done.
___
*[src/memkind_hbw.c, line 330 at r7](https://reviewable.io/reviews/memkind/memkind/704#-Mjo10DDCOBfkGy-qVNX:-Mk15-wx2CNe-UrVwuJb:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ea2c7e6dc7d74344c800720702531bbf90d71b54/src/memkind_hbw.c#L330)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this is the place that needs to be fixed
</blockquote></details>

Done.
___
*[test/get_capacity_test.cpp, line 130 at r10](https://reviewable.io/reviews/memkind/memkind/704#-Mjo3Uva7OLAX1oMOop1:-Mk16lVK8P9LtmARwAb9:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/00ecf2fc6eef8aa8151ad23accd644411f365e28/test/get_capacity_test.cpp#L130)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

this secondary check for status value is unnecessary
</blockquote></details>

Done.
___
*[test/get_capacity_test.cpp, line 174 at r10](https://reviewable.io/reviews/memkind/memkind/704#-Mjo3rz-DFYS-MMM2qiT:-Mk189bq2q69YUpYZix1:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/00ecf2fc6eef8aa8151ad23accd644411f365e28/test/get_capacity_test.cpp#L174)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

please add comment why we're expecting -1 here
</blockquote></details>

Done.
___
*[test/get_capacity_test.cpp, line 175 at r10](https://reviewable.io/reviews/memkind/memkind/704#-Mjo404f6IXzLWXDKESi:-Mk16pKh3-wC8XmhNyrs:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/00ecf2fc6eef8aa8151ad23accd644411f365e28/test/get_capacity_test.cpp#L175)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/704)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by bratpiorka — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r16, 10 of 10 files at r17, 16 of 17 files at r18, 1 of 2 files at r19, 5 of 6 files at r20, 12 of 12 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/704#-:-MkfNWG94EbG2a5_tD90:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
