### PR TITLE
Fix integer overflow & optimize integer operations

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [x] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [x] All newly added files have proprietary license (if necessary)
- [x] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/760)

### CODE REVIEW

**Review by bratpiorka — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/760)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/760)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[test/memkind_memtier_data_movement_test.cpp, line 382 at r1](https://reviewable.io/reviews/memkind/memkind/760#-Mwa4nZx2oe7DosTKtg4:-Mwa4nZx2oe7DosTKtg5:be3jj35) ([raw file](https://github.com/memkind/memkind/blob/5640d855cd927518152d8a16e89932392570a658/test/memkind_memtier_data_movement_test.cpp#L382)):*
> ```cpp
>               big_alloc_size + sizeof(freelist_node_meta_t));
> 
>     pool_allocator_free(temp);
> ```

Freeing only the second malloc(). The first one needs to be freed as well.

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/760)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[test/memkind_memtier_data_movement_test.cpp, line 382 at r1](https://reviewable.io/reviews/memkind/memkind/760#-Mwa4nZx2oe7DosTKtg4:-MwaE7-U9TMRbF-jAfKw:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5640d855cd927518152d8a16e89932392570a658/test/memkind_memtier_data_movement_test.cpp#L382)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Freeing only the second malloc(). The first one needs to be freed as well.
</blockquote></details>

Done.

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/760)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
