### PR TITLE
Add mockup for memkind_memtier

### PR DESCRIPTION
**Pull request by michalbiesek**
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/530)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/530)* status: 5 of 8 files reviewed, 6 unresolved discussions (waiting on @michalbiesek)

___
*[MANIFEST, line 406 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOOK1T6Dt1_yoeKk81:-MUOOK1U1QGpu4edzyMM:b-arjwo0) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/MANIFEST#L406)):*
> ```
> man/memkind_pmem.3
> man/memkindallocator.3
> man/memtier.3
> ```

memkind_memtier.3 ?
___
*[include/memkind_memtier.h, line 7 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOOeXG1SNT_2fyfwtd:-MUOOeXG1SNT_2fyfwte:b-sae8bf) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/include/memkind_memtier.h#L7)):*
> ```objc
> #ifdef __cplusplus
> extern "C" {
> #endif
> ```

Please, add an empty line below.
___
*[include/memkind_memtier.h, line 9 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOOlcUDMsOrAQA2ING:-MUOOlcUDMsOrAQA2INH:brhumzt) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/include/memkind_memtier.h#L9)):*
> ```objc
> #endif
> #include <memkind.h>
> #include <stdlib.h>
> ```

Same here.
___
*[include/memkind_memtier.h, line 34 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOPe479hLo8qL8DJv1:-MUOPe479hLo8qL8DJv2:b-8vhf8x) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/include/memkind_memtier.h#L34)):*
> ```objc
> /// \brief Create a memtier tier
> /// \note STANDARD API
> /// \return tiering tier, NULL on failure
> ```

memtier tier?
___
*[include/memkind_memtier.h, line 99 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUORCyIDsl2nhGTc9HP:-MUORCyJ4pDxArzF7rGL:bdrd716) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/include/memkind_memtier.h#L99)):*
> ```objc
> /// \param builder memtier builder
> /// \param kind pointer to memtier kind which will be created
> /// \return Operation status, MEMKIND_SUCCESS on success, other values on
> ```

Please, use either MEMKIND_SUCCESS or 0 in all of these functions.
___
*[include/memkind_memtier.h, line 224 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOVcKB-7edSfHmjLbt:-MUOVcKB-7edSfHmjLbu:b33wft5) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/include/memkind_memtier.h#L224)):*
> ```objc
> #ifdef __cplusplus
> }
> #endif
> ```

End with a newline.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/530)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @michalbiesek)

___
*[src/memkind_memtier.c, line 62 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOWdLJ54WLkd2gQrl1:-MUOWdLJ54WLkd2gQrl2:bs31e3o) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/src/memkind_memtier.c#L62)):*
> ```C
> MEMKIND_EXPORT void memtier_delete_kind(struct memtier_kind *kind)
> {
>     jemk_free(kind);
> ```

Check for NULL?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/530)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @PatKamin)

___
*[MANIFEST, line 406 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOOK1T6Dt1_yoeKk81:-MUOiGDiC1YDX0_RLH-g:b-wp98ly) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/MANIFEST#L406)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

memkind_memtier.3 ?
</blockquote></details>

Not sure, see that my intention was to have an official interface without the underscore, but I need to think about it .
___
*[include/memkind_memtier.h, line 7 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOOeXG1SNT_2fyfwtd:-MUOie2-7aq0x7EA2M7i:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/include/memkind_memtier.h#L7)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, add an empty line below.
</blockquote></details>

Done.
___
*[include/memkind_memtier.h, line 9 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOOlcUDMsOrAQA2ING:-MUOidqP3S-e85u-Gj84:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/include/memkind_memtier.h#L9)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[include/memkind_memtier.h, line 34 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOPe479hLo8qL8DJv1:-MUOiXKC1n_Sb6lzVcYW:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/include/memkind_memtier.h#L34)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

memtier tier?
</blockquote></details>

Done.
___
*[include/memkind_memtier.h, line 99 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUORCyIDsl2nhGTc9HP:-MUOifm3DL9xR3tNq0zO:b-j0poe4) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/include/memkind_memtier.h#L99)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, use either MEMKIND_SUCCESS or 0 in all of these functions.
</blockquote></details>

Done (with 0)
___
*[include/memkind_memtier.h, line 224 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOVcKB-7edSfHmjLbt:-MUOiqI0-TbSxK2WUmqm:bt9nq26) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/include/memkind_memtier.h#L224)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

End with a newline.
</blockquote></details>

There is a newline.
___
*[src/memkind_memtier.c, line 62 at r1](https://reviewable.io/reviews/memkind/memkind/530#-MUOWdLJ54WLkd2gQrl1:-MUOiszEAP3fRrA-g4cC:b5olpzx) ([raw file](https://github.com/memkind/memkind/blob/5a99b7f84a39299705c21624c03eace9cd64c871/src/memkind_memtier.c#L62)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Check for NULL?
</blockquote></details>

Not needed - see that this is a "free" operation from standard API and according to documentation: "If ptr is NULL, no action occurs."

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/530)* status: 7 of 8 files reviewed, all discussions resolved

**Pull request merged**
