### PR TITLE
Add python linter to GitHub Actions

### PR DESCRIPTION
**Pull request by PatKamin**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/577)

### CODE REVIEW

**Review by michalbiesek — COMMENTED** [review]
LGTM but please add TODO with information that all the python files should be supported by this linter

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/577#-:-MW4kO9h52-PZksq1x1O:burbpzo)* status: 0 of 1 files reviewed, all discussions resolved

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/577)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/577#-:-MW4l7hQ76tbE1nEUZNl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/577)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/577)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
