### PR TITLE
Add description of how to generate a RPM package

### PR DESCRIPTION
**Pull request by szadam**
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/859)

### CODE REVIEW

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/859)* status: all files reviewed, 5 unresolved discussions (waiting on @szadam)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/859#-NHT7UdqBIBzSQoPgpAL):*
nit: an RPM
___
*[`README` line 96 at r1](https://reviewable.io/reviews/memkind/memkind/859#-NHT6LFu1n9xgX5Hyh60:-NHT6LFu1n9xgX5Hyh61:b2jz6ss) ([raw file](https://github.com/memkind/memkind/blob/73f4e83f8e48c7ca3a5131182486388954478f04/README#L96)):*
> ```
> `make man-local` will generate man files in the man/ directory.
> 
> ## RPM
> ```

Generating RPM package
___
*[`README` line 98 at r1](https://reviewable.io/reviews/memkind/memkind/859#-NHT6XFM4FDy66EHqt2Q:-NHT6XFM4FDy66EHqt2R:bah6hj9) ([raw file](https://github.com/memkind/memkind/blob/73f4e83f8e48c7ca3a5131182486388954478f04/README#L98)):*
> ```
> ## RPM
> 
> For generating RPM package you will need to install:
> ```

Please, add an information that this can be done on Fedora OS.
___
*[`README` line 98 at r1](https://reviewable.io/reviews/memkind/memkind/859#-NHT7Pa4-crqIii8Nq0_:-NHT7Pa57F4yWSRsr-Pq:bw3odi9) ([raw file](https://github.com/memkind/memkind/blob/73f4e83f8e48c7ca3a5131182486388954478f04/README#L98)):*
> ```
> ## RPM
> 
> For generating RPM package you will need to install:
> ```

**an** RPM
___
*[`README` line 104 at r1](https://reviewable.io/reviews/memkind/memkind/859#-NHT6zYp7dppK7jBVrkg:-NHT6zYp7dppK7jBVrkh:bdh5r5) ([raw file](https://github.com/memkind/memkind/blob/73f4e83f8e48c7ca3a5131182486388954478f04/README#L104)):*
> ```
> * **hwloc-devel**
> 
> `make rpm` will generate RPM package.
> ```

**the** RPM package

**Review by szadam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/859)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @PatKamin)

___
*[`README` line 96 at r1](https://reviewable.io/reviews/memkind/memkind/859#-NHT6LFu1n9xgX5Hyh60:-NHd34wz74R6NWArf2sz:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/73f4e83f8e48c7ca3a5131182486388954478f04/README#L96)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Generating RPM package
</blockquote></details>

Done.
___
*[`README` line 98 at r1](https://reviewable.io/reviews/memkind/memkind/859#-NHT6XFM4FDy66EHqt2Q:-NHd38D4Am7Y7EpRhgJd:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/73f4e83f8e48c7ca3a5131182486388954478f04/README#L98)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, add an information that this can be done on Fedora OS.
</blockquote></details>

Done.
___
*[`README` line 98 at r1](https://reviewable.io/reviews/memkind/memkind/859#-NHT7Pa4-crqIii8Nq0_:-NHd391u-6oLdNf8LGU9:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/73f4e83f8e48c7ca3a5131182486388954478f04/README#L98)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

**an** RPM
</blockquote></details>

Done.
___
*[`README` line 104 at r1](https://reviewable.io/reviews/memkind/memkind/859#-NHT6zYp7dppK7jBVrkg:-NHd39QRAwXBc8KJmkBZ:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/73f4e83f8e48c7ca3a5131182486388954478f04/README#L104)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

**the** RPM package
</blockquote></details>

Done.

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/859)* status: all files reviewed, 1 unresolved discussion (waiting on @szadam)

___
*[`README` line 104 at r2](https://reviewable.io/reviews/memkind/memkind/859#-NHd5t1B8h4cgVXopeCU:-NHd5t1B8h4cgVXopeCV:bg15p6g) ([raw file](https://github.com/memkind/memkind/blob/7188305fa81aef2e910263d9e9a48f96088d78be/README#L104)):*
> ```
> * **hwloc-devel** (despite the fact that it is normally an optional package)
> 
> `make rpm` generating the RPM package.
> ```

generating -> generates

**Review by szadam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/859)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[`README` line 104 at r2](https://reviewable.io/reviews/memkind/memkind/859#-NHd5t1B8h4cgVXopeCU:-NHdPPJv8DqIKBAweqmp:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/7188305fa81aef2e910263d9e9a48f96088d78be/README#L104)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

generating -> generates
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/859)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/859)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)

**Pull request merged**
