### PR TITLE
Run DAX_KMEM tests regardless of the CPU model

### PR DESCRIPTION
**Pull request by PatKamin**
For running DAX_KMEM tests having DAX_KMEM NUMA nodes set up should be
enough. No need for restricting these tests to certain CPU models.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/833)

### CODE REVIEW

**Review by maciekpac — COMMENTED** [review]
As I understand it, there is also another check that tests if the DAX_KMEM node is present?

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/833#-:-N5Z8GDG2_mlnLRzRUTA:b-roh5c1)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by PatKamin — COMMENTED** [review]
Yes, further parts of check_support() function.

> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/833#-:-N6IzWuv3j0jsAYJv5uL:bjnttug)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/833)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by bratpiorka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/833)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
