### PR TITLE
Add support for HBW on Arm64

### PR DESCRIPTION
**Pull request by keiya-nobuta**
This patch enables HBW on Arm64 if it can be configured as HBW NUMA node like Xeon-Phi.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/373)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/373)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @keiya-nobuta)

___
*[src/memkind_hbw.c, line 265 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZBqLAUWlBxvaHehD:-MHKZBqMD_yizppyeEab:b-vudua0) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L265)):*
> ```C
> #define CPU_FAMILY_INTEL        (0x06)
> 
> #ifdef __x86_64__
> ```

@keiya-nobuta 
Could you give me more details about the reason for this patch, for example, what ARM processor could be used with HBW - I want to ensure that it is presented to Operating System in the same way as in the case of KNL.  Besides the question you are aware that you could use MEMKIND_HBW_NODES to list the NUMA nodes that are treated as high bandwidth
___
*[src/memkind_hbw.c, line 290 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZ8IT0tAlzRiQpBdR:-MHKZ8IU8FrDeUKf83s9:bgte8f1) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L290)):*
> ```
> #endif// __x86_64__
> ```
spaces instead of tabs please
___
*[src/memkind_hbw.c, line 299 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKYvgm1MZTEvmsx1fY:-MHKYvgn4MOFlHjwNl8b:b-fg2bap) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L299)):*
> ```
>__ARM_ARCH >= 8
> ```
__aarch64__ ?
___
*[src/memkind_hbw.c, line 349 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZ1shB1lFJFdTjDq6:-MHKZ1shB1lFJFdTjDq7:b-ql24d3) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L349)):*
> ```
> __ARM_ARCH >= 8
> ```
__aarch64__ ?
___
*[src/memkind_hbw.c, line 353 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKYx9B166vVlbsRzts:-MHKYx9B166vVlbsRztt:b840uex) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L353)):*
> ```C
> 
>     if(ret == 0) {
> 	log_info("Detected High Bandwidth Memory.");
> ```

spaces instead of tabs, please

**Review by keiya-nobuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/373)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[src/memkind_hbw.c, line 265 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZBqLAUWlBxvaHehD:-MHLVsyRB0TdDK8mjve_:b6a79k4) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L265)):*
>Could you give me more details about the reason for this patch, for example, what ARM processor could be used with HBW - I want to ensure that it is presented to Operating System in the same way as in the case of KNL.

aarch 64 server already has HBM2 such as FUJITSU FX700. HBM2 and DIMM mixed servers are not available yet, but I think they will be coming no distant future. This is a patch that supports it.

> Besides the question you are aware that you could use MEMKIND_HBW_NODES to list the NUMA nodes that are treated as high bandwidth

I know MEMKIND_HBW_NODES, but can memkind not support other than KNL?
___
*[src/memkind_hbw.c, line 290 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZ8IT0tAlzRiQpBdR:-MHLXfijCzdHd_yEvSi5:b32w0x) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L290)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #endif// __x86_64__
> ```
spaces instead of tabs please
</blockquote></details>

OK
___
*[src/memkind_hbw.c, line 299 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKYvgm1MZTEvmsx1fY:-MHLY0W9ALlCygbx9qox:b-psh8qt) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L299)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>__ARM_ARCH >= 8
> ```
__aarch64__ ?
</blockquote></details>

Is `__aarch64__` more commonly used? So I rewrote it.
___
*[src/memkind_hbw.c, line 349 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZ1shB1lFJFdTjDq6:-MHLZgsYCfNLGgLFQfrD:b-4tdk9g) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L349)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> __ARM_ARCH >= 8
> ```
__aarch64__ ?
</blockquote></details>

I rewrote to `__aarch64__`.
___
*[src/memkind_hbw.c, line 353 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKYx9B166vVlbsRzts:-MHLYBmdBobBqTMC0cys:b32w0x) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L353)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

spaces instead of tabs, please
</blockquote></details>

OK

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/373)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @keiya-nobuta)

___
*[src/memkind_hbw.c, line 265 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZBqLAUWlBxvaHehD:-MHLb9d_8CGOCP_ppbyP:b-t9x89) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L265)):*
<details><summary><i>Previously, keiya-nobuta wrote…</i></summary><blockquote>

>Could you give me more details about the reason for this patch, for example, what ARM processor could be used with HBW - I want to ensure that it is presented to Operating System in the same way as in the case of KNL.

aarch 64 server already has HBM2 such as FUJITSU FX700. HBM2 and DIMM mixed servers are not available yet, but I think they will be coming no distant future. This is a patch that supports it.

> Besides the question you are aware that you could use MEMKIND_HBW_NODES to list the NUMA nodes that are treated as high bandwidth

I know MEMKIND_HBW_NODES, but can memkind not support other than KNL?
</blockquote></details>

@keiya-nobuta 
Is HBM2 is presented on the Operating System level as Numa Node without CPU?

**Review by keiya-nobuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/373)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[src/memkind_hbw.c, line 265 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZBqLAUWlBxvaHehD:-MHLy5cs6EZddR5g1GUq:bevzuyn) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L265)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

@keiya-nobuta 
Is HBM2 is presented on the Operating System level as Numa Node without CPU?

</blockquote></details>

No, on the FX700.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/373)* status: 0 of 1 files reviewed, all discussions resolved

___
*[src/memkind_hbw.c, line 265 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZBqLAUWlBxvaHehD:-MHLz5uVANMpspE6H4ia:b-61kx5) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L265)):*
<details><summary><i>Previously, keiya-nobuta wrote…</i></summary><blockquote>

No, on the FX700.
</blockquote></details>

Ok, so if you look into code, you will see that for currently supported configuration: HBW memory is detected as:
https://github.com/memkind/memkind/blob/f1c4ac9efd17e45b5bd669023a018e8b47bda398/src/memkind_hbw.c#L303

Regarding HBM2 on the FX700, to support it, we must find a way to identify the correct HBM NUMA Node. We plan to address the issue of clear identification of different memory (DRAM, HBW..) on different memory configurations in the future. If you have any feedback regarding this, I would be happy to hear it.

**Review by keiya-nobuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/373)* status: 0 of 1 files reviewed, all discussions resolved

___
*[src/memkind_hbw.c, line 265 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZBqLAUWlBxvaHehD:-MHM0e3-EpEAo_A8bbKD:bir3iq) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L265)):*
> Regarding HBM2 on the FX700, to support it, we must find a way to identify the correct HBM NUMA Node. 

FX700 has HBM2 only, hense there is no HBM NUMA Node without CPU. I am targeting future products with DIMM/HBM2 mixed.  If these band-width and latency characteristics are similar to KNL, it is reasonable to configure DIMMs as local memory on NUMA nodes.

> We plan to address the issue of clear identification of different memory (DRAM, HBW..) on different memory configurations in the future. If you have any feedback regarding this, I would be happy to hear it.

I have no idea right now. For example, do we use HMAT (that was used in the previous version)?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/373)* status: 0 of 1 files reviewed, all discussions resolved

___
*[src/memkind_hbw.c, line 265 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZBqLAUWlBxvaHehD:-MHMA6lt828Zwfekkt81:b-j4toa6) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L265)):*
<details><summary><i>Previously, keiya-nobuta wrote…</i></summary><blockquote>

> Regarding HBM2 on the FX700, to support it, we must find a way to identify the correct HBM NUMA Node. 

FX700 has HBM2 only, hense there is no HBM NUMA Node without CPU. I am targeting future products with DIMM/HBM2 mixed.  If these band-width and latency characteristics are similar to KNL, it is reasonable to configure DIMMs as local memory on NUMA nodes.

> We plan to address the issue of clear identification of different memory (DRAM, HBW..) on different memory configurations in the future. If you have any feedback regarding this, I would be happy to hear it.

I have no idea right now. For example, do we use HMAT (that was used in the previous version)?
</blockquote></details>

Yes, we already have an idea to utilize the information from the HMAT table and get more details about actual memory characteristics.
If you are "targeting future products with DIMM/HBM2 mixed," then changes from this PR will not handle the HBM2 correctly, see that for our **current** implementation, we assume that HBM Numa Nodes are Nodes without CPU - this is the premise to identify it as High Bandwidth Memory Numa Node

**Review by keiya-nobuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/373)* status: 0 of 1 files reviewed, all discussions resolved

___
*[src/memkind_hbw.c, line 265 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZBqLAUWlBxvaHehD:-MHVrN2S5qiAxnY6tbid:b-dorau1) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L265)):*
> Yes, we already have an idea to utilize the information from the HMAT table and get more details about actual memory characteristics.

I would like to read it if it is already discussed. Can I see it somewhere?

Linux already supports HMAT on v5.5 or later, so we can see sysfs attributes such as /sys/devices/system/node/node0/access0/initiators/read_bandwidth if ACPI presents HMAT. I think we can implement that idea using this attribute. However, it necessary to enable CONFIG_ACPI_HMAT  (major distributions disable this config as far as I know). So I think HMAT implementations will not be common for some time.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/373)* status: 0 of 1 files reviewed, all discussions resolved

___
*[src/memkind_hbw.c, line 265 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZBqLAUWlBxvaHehD:-MI3GgeO9J391ETgHIeU:b2440u) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L265)):*
<details><summary><i>Previously, keiya-nobuta wrote…</i></summary><blockquote>

> Yes, we already have an idea to utilize the information from the HMAT table and get more details about actual memory characteristics.

I would like to read it if it is already discussed. Can I see it somewhere?

Linux already supports HMAT on v5.5 or later, so we can see sysfs attributes such as /sys/devices/system/node/node0/access0/initiators/read_bandwidth if ACPI presents HMAT. I think it can be implemented using this. However, it necessary to enable CONFIG_ACPI_HMAT  (major distributions disable this config as far as I know). So I think HMAT implementations will not be common for some time.
</blockquote></details>

Sorry for the late answer. We don't have documentation related to this yet. Yes, we are aware of HMAT availability in the kernel.
Regarding this Pull Request and extend memkind to work with different architectures - this Pull Request is invalid as we already spoke: HBW NUMA Node on FX700 is presented differently than on current supported architectures. For a scenario **when a user could identify NUMA Nodes** which could be treated as HBW memory, you could use MEMKIND_HBW_NODES environmental variable and MEMKIND_HBW* kind from memkind.h. For DRAM memory, you could look into https://github.com/memkind/memkind/pull/308, and potential usage of a new environment variable introduced there - let me know what you think about PR from a link - could it be useful in your case.
In the long-term perspective, we will handle the HMAT table's information to recognize properties internally by memkind. We will take your concern into consideration regarding the situation when HMAT will not be available in the OS - thanks for pointing that.

**Review by keiya-nobuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/373)* status: 0 of 1 files reviewed, all discussions resolved

___
*[src/memkind_hbw.c, line 265 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZBqLAUWlBxvaHehD:-MIOMKQ-B9aGmnmVyQt9:b-wfo7lt) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L265)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Sorry for the late answer. We don't have documentation related to this yet. Yes, we are aware of HMAT availability in the kernel.
Regarding this Pull Request and extend memkind to work with different architectures - this Pull Request is invalid as we already spoke: HBW NUMA Node on FX700 is presented differently than on current supported architectures. For a scenario **when a user could identify NUMA Nodes** which could be treated as HBW memory, you could use MEMKIND_HBW_NODES environmental variable and MEMKIND_HBW* kind from memkind.h. For DRAM memory, you could look into https://github.com/memkind/memkind/pull/308, and potential usage of a new environment variable introduced there - let me know what you think about PR from a link - could it be useful in your case.
In the long-term perspective, we will handle the HMAT table's information to recognize properties internally by memkind. We will take your concern into consideration regarding the situation when HMAT will not be available in the OS - thanks for pointing that.
</blockquote></details>

Those environment variables is useful, and it should work on FX700. But if a user couldn't identify HBW NUMA nodes, an automatic identification mechanism is necessary. I understand that this Pull Request not work on FX700, but even if I could extend mechanism for identifying DRAM and HBW memory for various architectures, FX700 is not a heterogeneous memory configuration hence requires special handling. Is it correct?

I'm interested in using HMAT, so can I discuss it in another issue?

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/373)* status: 0 of 1 files reviewed, all discussions resolved

___
*[src/memkind_hbw.c, line 265 at r1](https://reviewable.io/reviews/memkind/memkind/373#-MHKZBqLAUWlBxvaHehD:-MIOPXri0aZHhPpOpqUz:byi7hsq) ([raw file](https://github.com/memkind/memkind/blob/3f697d9aab0b8b88410a6ce4c2637d7227f5f064/src/memkind_hbw.c#L265)):*
<details><summary><i>Previously, keiya-nobuta wrote…</i></summary><blockquote>

Those environment variables is useful, and it should work on FX700. But if a user couldn't identify HBW NUMA nodes, an automatic identification mechanism is necessary. I understand that this Pull Request not work on FX700, but even if I could extend mechanism for identifying DRAM and HBW memory for various architectures, FX700 is not a heterogeneous memory configuration hence requires special handling. Is it correct?

I'm interested in using HMAT, so can I discuss it in another issue?
</blockquote></details>

Let me be clear here - those environment variables are the alternative approach to the primary goal. The primary objective in memkind is to recognize specific memory automatically, without user involvement. Regarding FX700 support and environment variables - I intended to present what you could do today to handle different types of memories.
Suppose you could distinguish DRAM/HBW by yourself before using libmemkind. In that case, you could inform memkind about it to take the point - but this was just an alternative(when this cannot be automatically detected).

Yes, we can continue to discuss HMAT in a separate issue.

**Comment by michalbiesek** [comment]
@keiya-nobuta 
I believe we could close this PR (regarding #401), or if you have more comments for this PR, please post it here.

**Comment by keiya-nobuta** [comment]
OK, I'm closing this PR.

**Pull request closed without merging**
