### PR TITLE
Fix syntax error in MEM_THRESHOLDS env var usage example

### PR DESCRIPTION
**Pull request by szadam**
### Types of changes

- [x] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/823)

### CODE REVIEW

**Comment by szadam** [comment]
MEMKIND_MEM_THRESHOLDS manual ('=' -> ':' in example)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/823)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac and @PatKamin)

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/823)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac and @szadam)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/823#-N3NYGjSC88pqakxQkd0):*
nit: Perhaps 'Fix MEM_THRESHOLDS env var usage example' would describe better what changes are introduced with this commit.

**Review by maciekpac — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/823)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/823#-N3NYGjSC88pqakxQkd0):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: Perhaps 'Fix MEM_THRESHOLDS env var usage example' would describe better what changes are introduced with this commit.
</blockquote></details>

up

Or sth like:
Fix syntax error in MEM_THRESHOLDS env var usage example

you provided a fix for incorrect code sample and the commit message does not reflect it

**Comment by szadam** [comment]
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/823#-N3NYGjSC88pqakxQkd0):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

up

Or sth like:
Fix syntax error in MEM_THRESHOLDS env var usage example

you provided a fix for incorrect code sample and the commit message does not reflect it
</blockquote></details>

thanks, I have changed it

**Review by szadam — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/823)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)

**Comment by szadam** [comment]
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/memkind/memkind/823#-N3NYGjSC88pqakxQkd0):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Have you pushed the changes ? I still see the old version
</blockquote></details>

done

**Review by PatKamin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/823)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)

**Pull request merged**
