### PR TITLE
Add validation of qemu image path

### PR DESCRIPTION
**Pull request by michalbiesek**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/memkind/memkind/443)

### CODE REVIEW

**Review by bratpiorka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/443#-:-MOq3jlwBrvzWNuvheeA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/443)* status: all files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[utils/qemu/main.py, line 382 at r1](https://reviewable.io/reviews/memkind/memkind/443#-MOqTsXs4ggt5EtRSHQd:-MOqTsXs4ggt5EtRSHQe:b7dl5fe) ([raw file](https://github.com/memkind/memkind/blob/ff51d73adaf252982802f609b8426c57ed7ee488/utils/qemu/main.py#L382)):*
> ```Python
> 
> 
> def parse_image_path(image_path: str) -> str:
> ```

`validate_image_path` would describe better what is going on here.

**Review by michalbiesek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/443)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[utils/qemu/main.py, line 382 at r1](https://reviewable.io/reviews/memkind/memkind/443#-MOqTsXs4ggt5EtRSHQd:-MOqaUttE2lqahARcuC4:b-896fix) ([raw file](https://github.com/memkind/memkind/blob/ff51d73adaf252982802f609b8426c57ed7ee488/utils/qemu/main.py#L382)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

`validate_image_path` would describe better what is going on here.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkind/memkind/443)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
